### PR TITLE
Fix example code of the CRUDController

### PR DESCRIPTION
**Pull request by Kolyunya**
Fixed example code which otherwise threw 

> Type error: Argument 2 passed to AppBundle\Controller\CRUDController::batchActionMerge() must be an instance of AppBundle\Controller\Request or null, instance of Symfony\Component\HttpFoundation\Request given

### CODE REVIEW

**Comment by Kolyunya** [comment]
Wrong branch.

**Comment by greg0ire** [comment]
Not a problem

**Comment by greg0ire** [comment]
Please rebase on 3.x, then force push.

**Comment by greg0ire** [comment]
1. Fetch all new commits: `git fetch --all`. ⬇️ 
2. Rebase on what you fetched interactively: ✂️ 
    1. `git rebase -i origin/3.x`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin repository.
    2. A window will show up with many lines, remove every line but the last one, which should correspond to your commit.
   2. If you run into a conflict: 💥 
        1. fix it with `git mergetool`. 😷 
        1. continue on your merry way with `git rebase --continue`. ⏩ 
3. Force push to overwrite all this : `git push --force`. ⬆️

**Comment by Kolyunya** [comment]
I just made a brand new PR for the  `3.x` branch: https://github.com/sonata-project/SonataAdminBundle/pull/4375

**Comment by greg0ire** [comment]
1. Fetch all new commits: `git fetch --all`. ⬇️ 
2. Rebase on what you fetched interactively: ✂️ 
    1. `git rebase -i origin/3.x`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin repository.
    2. A window will show up with many lines, remove every line but the last one, which should correspond to your commit.
   2. If you run into a conflict: 💥 
        1. fix it with `git mergetool`. 😷 
        1. continue on your merry way with `git rebase --continue`. ⏩ 
3. Force push to overwrite all this : `git push --force`. ⬆️

**Comment by Kolyunya** [comment]
Duplicate of the https://github.com/sonata-project/SonataAdminBundle/pull/4375

**Pull request closed without merging**
