### PR TITLE
Set twig globals after first admin instanciation

### LINKED ISSUE #8120: Submitting a form with ->render instead of ->renderWithExtraParams does not work
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
Direct dependencies required in composer.json:
sonata-project/admin-bundle              4.28.0 4.28.0 The missing Symfony Admin Generator
sonata-project/doctrine-orm-admin-bundle 4.13.0 4.14.0 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/intl-bundle               3.1.0  3.1.0  Symfony SonataIntlBundle
sonata-project/media-bundle              4.10.4 4.10.4 Symfony SonataMediaBundle
sonata-project/twig-extensions           2.3.0  2.3.0  Sonata twig extensions
sonata-project/user-bundle               5.10.0 5.10.0 Symfony SonataUserBundle

Transitive dependencies not required in composer.json:
sonata-project/block-bundle              5.0.1  5.0.1  Symfony SonataBlockBundle
sonata-project/doctrine-extensions       2.3.0  2.3.0  Doctrine2 behavioral extensions
sonata-project/exporter                  3.2.0  3.3.0  Lightweight Exporter library
sonata-project/form-extensions           2.1.0  2.1.0  Symfony form extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
Direct dependencies required in composer.json:
symfony/console                    v6.3.4  v6.3.4  Eases the creation of beautiful and testable command line interfaces
symfony/debug-bundle               v6.3.2  v6.3.2  Provides a tight integration of the Symfony VarDumper component a...
symfony/doctrine-messenger         v6.3.6  v6.3.6  Symfony Doctrine Messenger Bridge
symfony/dotenv                     v6.3.0  v6.3.0  Registers environment variables from a .env file
symfony/filesystem                 v6.3.1  v6.3.1  Provides basic utilities for the filesystem
symfony/flex                       v2.4.0  v2.4.0  Composer plugin for Symfony
symfony/framework-bundle           v6.3.6  v6.3.6  Provides a tight integration between Symfony components and the S...
symfony/mailer                     v6.3.5  v6.3.5  Helps sending emails
symfony/messenger                  v6.3.6  v6.3.6  Helps applications send and receive messages to/from other applic...
symfony/monolog-bundle             v3.8.0  v3.8.0  Symfony MonologBundle
symfony/rate-limiter               v6.3.6  v6.3.6  Provides a Token Bucket implementation to rate limit input and ou...
symfony/runtime                    v6.3.2  v6.3.2  Enables decoupling PHP applications from global state
symfony/serializer                 v6.3.6  v6.3.6  Handles serializing and deserializing data structures, including ...
symfony/stopwatch                  v6.3.0  v6.3.0  Provides a way to profile code
symfony/twig-bundle                v6.3.0  v6.3.0  Provides a tight integration of Twig into the Symfony full-stack ...
symfony/web-profiler-bundle        v6.3.6  v6.3.6  Provides a development tool that gives detailed information about...
symfony/webpack-encore-bundle      v1.17.2 v2.1.1  Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v6.3.3  v6.3.3  Loads and dumps YAML files

Transitive dependencies not required in composer.json:
symfony/asset                      v6.3.0  v6.3.0  Manages URL generation and versioning of web assets such as CSS s...
symfony/cache                      v6.3.6  v6.3.6  Provides extended PSR-6, PSR-16 (and tags) implementations
symfony/cache-contracts            v3.3.0  v3.3.0  Generic abstractions related to caching
symfony/clock                      v6.3.4  v6.3.4  Decouples applications from the system clock
symfony/config                     v6.3.2  v6.3.2  Helps you find, load, combine, autofill and validate configuratio...
symfony/dependency-injection       v6.3.5  v6.3.5  Allows you to standardize and centralize the way objects are cons...
symfony/deprecation-contracts      v3.3.0  v3.3.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v6.3.6  v6.3.6  Provides integration for Doctrine with various Symfony components
symfony/error-handler              v6.3.5  v6.3.5  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v6.3.2  v6.3.2  Provides tools that allow your application components to communic...
symfony/event-dispatcher-contracts v3.3.0  v3.3.0  Generic abstractions related to dispatching event
symfony/expression-language        v6.3.0  v6.3.0  Provides an engine that can compile and evaluate expressions
symfony/finder                     v6.3.5  v6.3.5  Finds files and directories via an intuitive fluent interface
symfony/form                       v6.3.6  v6.3.6  Allows to easily create, process and reuse HTML forms
symfony/http-client                v6.3.6  v6.3.6  Provides powerful methods to fetch HTTP resources synchronously o...
symfony/http-client-contracts      v3.3.0  v3.3.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v6.3.6  v6.3.6  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v6.3.6  v6.3.6  Provides a structured process for converting a Request into a Res...
symfony/intl                       v6.3.2  v6.3.2  Provides access to the localization data of the ICU library
symfony/mime                       v6.3.5  v6.3.5  Allows manipulating MIME messages
symfony/monolog-bridge             v6.3.1  v6.3.1  Provides integration for Monolog with various Symfony components
symfony/options-resolver           v6.3.0  v6.3.0  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v6.3.5  v6.3.5  Provides password hashing utilities
symfony/polyfill-intl-grapheme     v1.28.0 v1.28.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.28.0 v1.28.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.28.0 v1.28.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.28.0 v1.28.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.28.0 v1.28.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.28.0 v1.28.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP ...
symfony/polyfill-php73             v1.28.0 v1.28.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP ...
symfony/polyfill-php80             v1.28.0 v1.28.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP ...
symfony/polyfill-php83             v1.28.0 v1.28.0 Symfony polyfill backporting some PHP 8.3+ features to lower PHP ...
symfony/process                    v6.3.4  v6.3.4  Executes commands in sub-processes
symfony/property-access            v6.3.2  v6.3.2  Provides functions to read and write from/to an object or array u...
symfony/property-info              v6.3.0  v6.3.0  Extracts information about PHP class' properties using metadata o...
symfony/routing                    v6.3.5  v6.3.5  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.3.2  v3.3.2  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v6.3.6  v6.3.6  Provides a tight integration of the Security component into the S...
symfony/security-core              v6.3.5  v6.3.5  Symfony Security Component - Core Library
symfony/security-csrf              v6.3.2  v6.3.2  Symfony Security Component - CSRF Library
symfony/security-http              v6.3.6  v6.3.6  Symfony Security Component - HTTP Integration
symfony/service-contracts          v3.3.0  v3.3.0  Generic abstractions related to writing services
symfony/string                     v6.3.5  v6.3.5  Provides an object-oriented API to strings and deals with bytes, ...
symfony/translation                v6.3.6  v6.3.6  Provides tools to internationalize your application
symfony/translation-contracts      v3.3.0  v3.3.0  Generic abstractions related to translation
symfony/twig-bridge                v6.3.5  v6.3.5  Provides integration for Twig with various Symfony components
symfony/validator                  v6.3.6  v6.3.6  Provides tools to validate values
symfony/var-dumper                 v6.3.6  v6.3.6  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v6.3.6  v6.3.6  Allows exporting any serializable PHP data structure to plain PHP...
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 8.2.8 (cli) (built: Jul  8 2023 07:09:59) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.8, Copyright (c), by Zend Technologies
    with blackfire v1.86.4~linux-x64-non_zts82, https://blackfire.io, by Blackfire
```

## Subject

The pull request #8116 auto-injects admin in twig so that CRUDController::renderWithExtraParams can be replaced by ::render instead. However, in a form edition or creation, the injected admin uniqId parameter and other parameters linked to the form are null. Thus, when we submit the form without uniqid, the form is not recognized as submitted.

## Steps to reproduce

Create a basic admin form, replace renderWithExtraParams by render in CRUDController::editAction and CRUDController::createAction, then try to create or edit an object.

## Expected results

Submitting the form once works.

## Actual results

Submitting the form once does not work, we have to submit it another time. In fact, one submit out of two does not work because when we are redirected to a form, the uniqId parameter is null.
Result of `{{ dump(admin) }}` in the form template, with render : https://i.imgur.com/ZbeVvcv.png
Result of `{{ dump(admin) }}` in the form template, with renderWithExtraParams : https://i.imgur.com/aNXxHXG.png

### PR DESCRIPTION
**Pull request by AntoineRoue**
Fixes #8120

## Changelog
```markdown
### Fixed
- Needing to submit form twice when using CRUDController::render()
```

### CODE REVIEW

**Comment by AntoineRoue** [comment]
I should have converted it to draft but did not find the button. It's done now.

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks !

**Comment by core23** [comment]
Sorry for the late feedback. This solution does only work if your Controller extends the `CRUDController`. 

If you want to create small (batch) action controller, there is no need to extend that controller and this solution does not work.

**Comment by AntoineRoue** [comment]
If you don't extend CRUDController, then do you really need 'admin' and 'base_template' variables in twig ?

Before these globals were set, if extended CRUDController then we had to use CRUDController::renderWithExtraParams to render the template. Without extending CRUDController, if we wanted these variable in twig, we had to add them ourself when rendering the template. In the end, it would work like before no ?

**Comment by Warxcell** [comment]
Unfortunately this breaks when inside long-running process like roadrunner. It throws exception that `admin` already exists as global, because it was set by previous admin.

**Comment by VincentLanglet** [comment]
> Unfortunately this breaks when inside long-running process like roadrunner. It throws exception that `admin` already exists as global, because it was set by previous admin.

Hi, can you try the 4.29.1 version ?

**Comment by Warxcell** [comment]
> > Unfortunately this breaks when inside long-running process like roadrunner. It throws exception that `admin` already exists as global, because it was set by previous admin.
> 
> Hi, can you try the 4.29.1 version ?

I saw the fix, but isn't that just hiding the error? Seems like the global twig variable `admin` will stay forever as initially set, and all furhter reads will read the first admin instance.

**Comment by VincentLanglet** [comment]
> I saw the fix, but isn't that just hiding the error? Seems like the global twig variable `admin` will stay forever as initially set, and all furhter reads will read the first admin instance.

I'm not sure about this since the code allows to update globals:
```
/**
     * Registers a Global.
     *
     * New globals can be added before compiling or rendering a template;
     * but after, you can only update existing globals.
     *
     * @param mixed $value The global value
     */
    public function addGlobal(string $name, $value)
    {
        if ($this->extensionSet->isInitialized() && !\array_key_exists($name, $this->getGlobals())) {
            throw new \LogicException(sprintf('Unable to add global "%s" as the runtime or the extensions have already been initialized.', $name));
        }

        if (null !== $this->resolvedGlobals) {
            $this->resolvedGlobals[$name] = $value;
        } else {
            $this->globals[$name] = $value;
        }
    }
```

**Comment by Warxcell** [comment]
> > I saw the fix, but isn't that just hiding the error? Seems like the global twig variable `admin` will stay forever as initially set, and all furhter reads will read the first admin instance.
> 
> I'm not sure about this since the code allows to update globals:
> 
> ```
> /**
>      * Registers a Global.
>      *
>      * New globals can be added before compiling or rendering a template;
>      * but after, you can only update existing globals.
>      *
>      * @param mixed $value The global value
>      */
>     public function addGlobal(string $name, $value)
>     {
>         if ($this->extensionSet->isInitialized() && !\array_key_exists($name, $this->getGlobals())) {
>             throw new \LogicException(sprintf('Unable to add global "%s" as the runtime or the extensions have already been initialized.', $name));
>         }
> 
>         if (null !== $this->resolvedGlobals) {
>             $this->resolvedGlobals[$name] = $value;
>         } else {
>             $this->globals[$name] = $value;
>         }
>     }
> ```

Yes, but only if no exception is thrown? In our case - exception IS thrown.

**Comment by VincentLanglet** [comment]
> Yes, but only if no exception is thrown? In our case - exception IS thrown.

According to `if ($this->extensionSet->isInitialized() && !\array_key_exists($name, $this->getGlobals())) {`

Exception is thrown only if the global doesn't exists and the extension is initialized.
So no exception is thrown in your example.

Let's end this theoretically discussion here and wait for a well-reported bug instead if it exists.

**Pull request merged**
