### PR TITLE
DefaultRouteGenerator must use route to child admin if route name contains a dot

### PR DESCRIPTION
**Pull request by sergiostrampelli**
Patch and unit test

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Can you please squash your commit and set a more clear message?

BTW, could you explain what is this update? What is the goal?

Tests need to be fixed too.

Note: Please don't open another PR to respond with your modification, just update this one.

Thanks.

**Comment by sergiostrampelli** [comment]
Sorry, I have lost the comment in previous PR.

This fix #2505

**Comment by Soullivaneuh** [comment]
@sergiostrampelli please consider:

> Can you please squash your commit and set a more clear message?

For the message, I'm talking about the commit itself.

**Comment by Soullivaneuh** [comment]
Why closing this one? Please do not open a PR on each modification, just rebase your git history.

**Comment by sergiostrampelli** [comment]
Il 30/06/2015 18:57, Sullivan SENECHAL ha scritto:
> Why closing this one? Please do not open a PR on each modification, just
> rebase your git history.

I don't know how to rebase on github.

I think would be faster if you get my changes, than you explain to me 
how to do.

**Comment by Soullivaneuh** [comment]
@sergiostrampelli Please take a look at this documentation for squashing commits: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

When you'll get a single commit, you can rewrite comment with git amend: https://fr.atlassian.com/git/tutorials/rewriting-history/git-commit--amend/

Note: You will have to force your push to rewrite remote history and update PR: `git push --force`.

**Comment by sergiostrampelli** [comment]
Thnaks a lot for your help.
I have tried without success: now I have 5 commit ...
I prefere to delete this repository.

**Comment by Soullivaneuh** [comment]
@sergiostrampelli Those commits was here before my comment. Have you tried with the doc I gave you?

Please do not make new PR anytime we request modification, this is painful to manage.

Just follow the doc. You have now 5 commits to squash, so you have to start with a `git rebase -i HEAD~5` and follow the documentation

**Comment by Soullivaneuh** [comment]
Well, closing this one...

**Comment by sergiostrampelli** [comment]
I used yesterday that guide, but I worked in github (web) and on a repository forked a lot of time ago.  Too complicated for 6 rows of code.  I preferred to scrape all better than squashing.

**Comment by Soullivaneuh** [comment]
> Too complicated for 6 rows of code.

It's especially not complicated to rebase and squash commit with little modification.

Please understand that your method is largely more painful for us to manage PR and history.

**Pull request closed without merging**
