### PR TITLE
skeletons are now valid for @Symfony ruleset by PHP-CS-Fixer

### PR DESCRIPTION
**Pull request by OskarStark**
I am targeting this branch, because this is BC.

## Subject

Otherwise this would be fixed by PHP-CS-Fixer all the time afterwards

### CODE REVIEW

**Comment by OskarStark** [comment]
@greg0ire should we change this, too? `_action`

**Comment by greg0ire** [comment]
I don't understand your question, can you please elaborate?

**Comment by OskarStark** [comment]
> I don't understand your question, can you please elaborate?

I mean, we changed something from `_action` to `actions` or sth else in another PR a few weeks ago, can you remember? My question is, if we should adjust this in the skeleton for further admins, too

**Comment by OskarStark** [comment]
fixed the tests

**Comment by greg0ire** [comment]
It's like that in [the docs](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/5a6819928f947cb7e5a8d288ad83f8131bab4875/Resources/doc/reference/list_field_definition.rst#example) so... maybe? I don't think it is mandatory. @andrewmy can you advise?

**Comment by andrewmy** [comment]
`_action` name wasn't changed, only the type from `action` to `actions` to make it work like described in the docs.

**Comment by OskarStark** [comment]
Thanks, you are right, so we're good to go!

**Comment by greg0ire** [comment]
Thanks @OskarStark !

**Pull request merged**
