### PR TITLE
Remove "e" letter after delete checkbox in SonataAdmin/Collection tab…

### PR DESCRIPTION
**Pull request by Benjoulbambou**
I tried to write a lot about this PR but I hope you will believe me that juste remove a letter in the code won't break it. 

Thanks !

### CODE REVIEW

**Comment by OskarStark** [comment]
Good catch, can you pease associate your commits email with your github account?

**Comment by Benjoulbambou** [comment]
> Good catch, can you pease associate your commits email with your github account?

Done !

**Comment by kunicmarko20** [comment]
Thank you @Benjoulbambou

**Comment by greg0ire** [comment]
Why was it labeled as pedantic? Is it not worthy of a release?

**Pull request merged**
