### PR TITLE
Import assets from CoreBundle

### PR DESCRIPTION
**Pull request by franmomu**
## Subject

This was part of https://github.com/sonata-project/SonataAdminBundle/pull/5833, but this is just importing assets and modifying the routes.

I am targeting this branch, because this is part of https://github.com/sonata-project/SonataAdminBundle/pull/5833.

## Changelog

```markdown
### Added
- Import assets from SonataCoreBundle
```

### CODE REVIEW

**Comment by franmomu** [comment]
> Including 3rd party assets looks like a bad idea to me.

I don't like it either, but they should be somewhere, let's see how https://github.com/sonata-project/SonataAdminBundle/pull/5461 goes.

**Comment by VincentLanglet** [comment]
@franmomu @core23 Can we do something about this PR ? 
The dev-master branch is not working since 4 months.

If we don't import assert and wait for webpack we should revert partially or totally https://github.com/sonata-project/SonataAdminBundle/pull/5833

**Comment by wbloszyk** [comment]
@VincentLanglet This problem will be fix while drop CoreBundle in Sonata 3.

https://github.com/sonata-project/SonataAdminBundle/pull/6096

This PR will drop dependencies from CoreBundle and also fix assets. I add EventListener for assets:install command. While assets will be install then listener will add core files when CoreBundle are not register. 

In sonata 4 we should allow use old and new templates (bootstrap 3 and bootstrap 4) versions. In Sonata 5 bootstrap 3 should be drop. This will allow BC and masę upgrade proces more friendly.

**Comment by VincentLanglet** [comment]
> @VincentLanglet This problem will be fix while drop CoreBundle in Sonata 3.

I know you're working a lot on this, big thanks.

Currently your PR is still a draft with failing tests, and I can't say how much time you'll need to finish it. So I think we should find a quickest solution for the dev-master branch.

If the new plan is to make sonataCore optional on Sonata 3 thanks to your work, then the started work made by https://github.com/sonata-project/SonataAdminBundle/pull/5833 is not necessary and we should revert the CoreBundle-drop part https://github.com/sonata-project/SonataAdminBundle/pull/5833/commits/26b11541793c8b7285c8ef94a81f96ef8a4ec7e7.

1. Dev-master will require again CoreBundle
2. When we'll merge your PR CoreBundle will be optional on 3.x
3. When we'll merge 3.x into master CoreBundle will be optional on dev-master
4. Then we fully remove CoreBundle on dev-master (?)

WDYT @wbloszyk ?

**Comment by wbloszyk** [comment]
Look at https://github.com/sonata-project/dev-kit/issues/697

I can push STEP 2 PRs after merge STEP 1 and release this change. Test will work then. Like i wrote there, i done it but some PR must be push one by one.

1. It can be revert. But for me it waste time. Better check my PR instead. 

This PR should not be merge, i do it in 3.x branch.

sonatacore assets should be keep until Sonata5 to keep templetes BC.

**Comment by VincentLanglet** [comment]
Closing in favor of https://github.com/sonata-project/SonataAdminBundle/pull/6096

**Pull request closed without merging**
