### PR TITLE
Add Picker Option to Form Filter to change default field_type

### PR DESCRIPTION
**Pull request by Hanmac**
## Subject

I am targeting this branch, because it should be BC.

It is needed to make this one cleaner: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1662 

## Changelog

```markdown
### Added
- Added picker option to Form Filter to change default field_type.

### Changed

### Deprecated

### Removed

### Fixed
- Filter DateTimeType used wrong date_format

### Security
```

### CODE REVIEW

**Review by VincentLanglet — CHANGES_REQUESTED** [review]
This should not be a form option.
This add extra hidden complexity without real gain.

If you want to add such things it's better to introduce a new config option here:
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/DependencyInjection/Configuration.php#L181

Then, passing the value in the constructor of all those Type.

**Comment by VincentLanglet** [comment]
There is already https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/DependencyInjection/Configuration.php#L313-L316
We might introduce `use_date_picker` ; false by default.

**Comment by jordisala1991** [comment]
> There is already https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/DependencyInjection/Configuration.php#L313-L316 We might introduce `use_date_picker` ; false by default.

I do not know if that is a good idea. The other uses disable that libraries completely, this new option will only disable / enable on the filters, I will still be able to use a form type for a date picker. 

IMO in fact we could end up deprecating those options, (depends on where do we go with javascript)

**Comment by jordisala1991** [comment]
> This should not be a form option. This add extra hidden complexity without real gain.
> 
> If you want to add such things it's better to introduce a new config option here: https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/DependencyInjection/Configuration.php#L181
> 
> Then, passing the value in the constructor of all those Type.

I agree, if this option is only for avoid writing another option that is already possible, then -1 on my side

**Comment by Hanmac** [comment]
so i change it to use global configuration instead, right?
as for Config Option how about `use_date_picker_in_filter` ?

**Comment by VincentLanglet** [comment]
> I do not know if that is a good idea. The other uses disable that libraries completely, this new option will only disable / enable on the filters, I will still be able to use a form type for a date picker.

@jordisala1991 Do you think the name is not a good idea or do you think the option is not a good idea ?

We might find a better name for the option. But I don't think the global config option is a good idea
This would avoid to override every time the field type like https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1662#issue-1253974304

And I dunno if we should add `in_filter` in the option, since we might consider using this config option for everywhere a DateType is used later  (even if currently it's only in filters).

**Comment by VincentLanglet** [comment]
BTW, as reported https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1662#issuecomment-1143373501 we have a little issue @jordisala1991

The `field_type` default value from the formType https://github.com/sonata-project/SonataAdminBundle/blob/50d851bf588eef86a80f2fe6d39a5f8923bf8540/src/Form/Type/Filter/DateRangeType.php#L43 is ALWAYS overriden by the one in the Filter
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/4.x/src/Filter/AbstractDateFilter.php#L116

Even if no `field_type` is provided, it will default to TextType since there is a default value https://github.com/sonata-project/SonataAdminBundle/blob/50d851bf588eef86a80f2fe6d39a5f8923bf8540/src/Filter/Filter.php#L90

But removing the default value doesn't solve fully the issue, since `null` is not accepted (and won't fallback to the field_type default).

**Comment by VincentLanglet** [comment]
> BTW, as reported [sonata-project/SonataDoctrineORMAdminBundle#1662 (comment)](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1662#issuecomment-1143373501) we have a little issue @jordisala1991
> 
> The `field_type` default value from the formType
> 
> https://github.com/sonata-project/SonataAdminBundle/blob/50d851bf588eef86a80f2fe6d39a5f8923bf8540/src/Form/Type/Filter/DateRangeType.php#L43
> 
> is ALWAYS overriden by the one in the Filter
> https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/4.x/src/Filter/AbstractDateFilter.php#L116
> Even if no `field_type` is provided, it will default to TextType since there is a default value
> 
> https://github.com/sonata-project/SonataAdminBundle/blob/50d851bf588eef86a80f2fe6d39a5f8923bf8540/src/Filter/Filter.php#L90
> 
> But removing the default value doesn't solve fully the issue, since `null` is not accepted (and won't fallback to the field_type default).

Will be solved by https://github.com/sonata-project/SonataAdminBundle/pull/7841

then https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1662 will need to be handled directly on SonataDoctrineORMAdminBundle

**Pull request closed without merging**
