### PR TITLE
Force top: 0 on navbar positioning on mobile

### LINKED ISSUE #4850: Navbar moves when in mobile view with new refreshNavbarStuckClass function
In mobile view the navbar overlaps the top table when scrolling, due to new refresh function that does not take in account non sticky nav bar mode.

Example
sticky nav bar refresh issue

Referring to #4678 
@EmmanuelVella 

Workaround is to remove calling Admin.refreshNavbarStuckClass(topNavbar) on line 539 and 549

### PR DESCRIPTION
**Pull request by jordisala1991**
I am targeting this branch, because this is BC.

Closes #4850 

## Changelog

```markdown
### Fixed
- Navbar positioning on mobile is no longer altered like in desktop
```

## Subject

I don't like to use importants, but on this case, the good solution would be BC break probably, because the perfect scenario would be to not have the fixed class on the body if the header is not fixed.

### CODE REVIEW

**Comment by greg0ire** [comment]
Can't you add more selectors so that this rule has higher priority?

**Comment by jordisala1991** [comment]
Not a big fan of specificity wars, but I will try to win the battle

**Comment by jordisala1991** [comment]
Fixed, I do not like it a lot, but now it has more priority because is more specific. We should probably consider refactoring this to not use fixed class when the header is not fixed, that would solve some issues. But it will require a lot more work. For now, this is a acceptable solution.

**Comment by greg0ire** [comment]
Thanks @jordisala1991 !

**Pull request merged**
