### PR TITLE
Update Select2 plugin to version 4.0.3

### PR DESCRIPTION
**Pull request by adriexnet**
I am targeting this branch, because the [change log] of v2.3.4 say that Select2 plugin was updated to version 4.0.3 but the version not was changed at bower.json.

## Changelog

```markdown
### Changed
- select2 version was changed from  3.4.6 to 4.0.3
```

## Subject

Update Select2 plugin to version 4.0.3

[change log]: <https://github.com/sonata-project/SonataAdminBundle/blob/b33f27ba38c6917eef169cbff59447e3d057eb16/Resources/public/vendor/admin-lte/changelog.md#user-content-change-log>

### CODE REVIEW

**Comment by greg0ire** [comment]
+ 67000 additions vs - 5000 deletions, this does not look right… plus there are docs and tests in there.

**Comment by core23** [comment]
There is a packagist project https://packagist.org/packages/select2/select2. Maybe we could require this instead? Or someone could create a select2-bundle?

**Comment by greg0ire** [comment]
That's another problem, but at the moment we're using a frontend package manager for our frontend dependencies.

**Comment by greg0ire** [comment]
[hey there is bowerphp](https://github.com/Bee-Lab/bowerphp)

**Comment by core23** [comment]
Would you rather check this ~70k lines of code or use a proper dependency? It may be the solution for this problem which up to date libs.

**Comment by greg0ire** [comment]
[Found it here](https://github.com/sonata-project/SonataAdminBundle/issues/2036)

**Comment by greg0ire** [comment]
> Would you rather check this ~70k lines of code or use a proper dependency?

I agree, that's very very ugly… sooo… bowerphp?

**Comment by core23** [comment]
You could give it a try.

Btw. this PR is against an outdated branch

**Comment by greg0ire** [comment]
> Btw. this PR is against an outdated branch

Oh right!

**Comment by greg0ire** [comment]
> You could give it a try.

Maybe I will, but feel free to beat me at it, anyone!

**Comment by adriexnet** [comment]
Hi @greg0ire, I know there are many changes, but all are in Resources/public/vendor/select2/ where bower stores the select2 package and bower packages include all content that is not ignored in the repository, in the case of select2 https://github.com/select2/select2/tree/4.0.3 includes vendors, docs, test and other files useless for a dist  version 

What can I do to achieve this change can be approved?

**Comment by greg0ire** [comment]
> What can I do to achieve this change can be approved?

Nothing, sorry, the 2.x branch is no longer supported (and IMO we should delete it)

**Comment by adriexnet** [comment]
ok, thanks for let me know

**Pull request closed without merging**
