### PR TITLE
Fix display of select filter list with no choice

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because bugfix.

## Changelog

```markdown
### Fixed
- Stop displaying the filter dropdown with no usable filters
```

### CODE REVIEW

**Review by dmaicher — APPROVED** [review]

**Review by franmomu — APPROVED** [review]

**Comment by kirya-dev** [comment]
Great!

**Comment by kirya-dev** [comment]
Great!
But this template has same checks: `admin.datagrid.hasDisplayableFilters`
Its can be refactored?

**Comment by kirya-dev** [comment]
Replace filter closures into Datagrid?

**Comment by kirya-dev** [comment]
Add following methods:
```php
Datagrid::getCanBeDisplayedFilters()
Filter::isDisplayed()
Filter::canBeDisaplayed()

**Pull request merged**
