### PR TITLE
fix compatibility issue when using uuid

### PR DESCRIPTION
**Pull request by sergiostrampelli**
A valid UUID have also dashes

### CODE REVIEW

**Comment by rande** [comment]
Can you update unit test ?

**Comment by sergiostrampelli** [comment]
I think that the check itself is useless: the concrete manager must handle and/or check the id.

**Comment by patrickli** [comment]
@sergiostrampelli I actually agree with you on this. Any arbitrary string should be allowed as id. It is not the responsibility of the admin to assume the format of the id. Here is the unit test for you:

```php
    public function testGetSubject()
    {
        $class = 'Application\Sonata\NewsBundle\Entity\Post';
        $admin = new PostAdmin('sonata.post.admin.post', $class, 'SonataNewsBundle:PostAdmin');

        $modelManager = $this->getMock(
            'Sonata\AdminBundle\Model\ModelManagerInterface'
        );
        $modelManager->expects($this->once())
            ->method('find')
            ->with($class, $this->anything())
            ->will($this->returnValue(new DummySubject()));
        $admin->setModelManager($modelManager);

        $admin->setRequest(new Request(array('id' => 'any-arbitrary-string')));
        $admin->initialize();

        $this->assertNotFalse($admin->getSubject());
    }
```

**Comment by rande** [comment]
The code is also a performance check to avoid hitting the database every time the ``getSubject`` method is called ...

**Comment by patrickli** [comment]
Then we can update it so that if the `find` returns null, set `$this->subject` to `false`.

**Comment by rande** [comment]
@patrickli yep, but you still get a first extra hit.

**Comment by patrickli** [comment]
The bottom line is, I don't think it is a good idea to dictate what format an object's id should be.

**Comment by patrickli** [comment]
I have updated my pull request #2693 to include unit tests and not-found-object caching.

**Pull request closed without merging**
