### PR TITLE
always include delete button in option prototype

### PR DESCRIPTION
**Pull request by greg0ire**
It makes no sense to prevent people from deleting things that are not
yet persisted.

### CODE REVIEW

**Comment by OskarStark** [comment]
sounds reasonable to me

@core23 what do you think?

**Comment by core23** [comment]
Are you sure, that this code only works for not persisted objects?

**Comment by greg0ire** [comment]
`prototype` is defined when building the `data-prototype` html attribute that will be used by a piece of javascript when you click the little "plus" to add an item to a collection. This creates a form for the new item (which are not persisted, because they are new).

**Comment by greg0ire** [comment]
I tried that on a project of mine, BTW.

**Comment by OskarStark** [comment]
@greg0ire can you ensure this by a test?

**Comment by greg0ire** [comment]
I'll give it a try, but it looks hard.

**Comment by greg0ire** [comment]
@OskarStark where should I look for twig tests ? Is there anything yet that does something similar? There are Behat tests in the sandbox, is that what I should look into?

**Comment by OskarStark** [comment]
Yes i think we have some twig tests somewhere, i recommended to another contributer to have a look at the symfony core.

@core23 did you make a test for twig?

**Comment by core23** [comment]
Never made a twig test :/

**Comment by greg0ire** [comment]
Actually, I know how I could test this, but it would require introducing behat and Mink in the project. I would create a very small project in the Test directory, and an Admin within it, and then use the Symfony2 driver for Mink to visit the admin edit page and check that the collection is as expected.

This approach is presented in more detail by @jakzal here : http://zalas.eu/run-behat-scenarios-and-functional-tests-from-symfony-bundle-in-isolation-of-project/

But that's a big decision, too big for this PR I guess… it would imply loading fixtures, so maybe also choosing a fixture system, and setup a database.

On the otherhand, I guess I could write an integration test in the sandbox, but the problem is, you must merge first.

**Comment by jakzal** [comment]
@greg0ire you don't need Behat/Mink for this. You could use Symfony's WebTestCase just as well, or write an integration test.

**Comment by greg0ire** [comment]
I was planning on using the symfony2 driver for mink for this (which is basically like WebTestCase, but a lot more readable). What do you mean by "integration test" though, exactly ?

**Comment by jakzal** [comment]
In this case, an integration test would be something that calls twig to render the template. I don't know sonata well enough to asses which option is the best in this case, sorry :)

**Comment by greg0ire** [comment]
Thanks for the answer. So it would initialize Twig, make it render the template, and see the output… might be a solution indeed, but I'll have to know precisely what variables need to be passed to the template. Not easy I think…

**Comment by OskarStark** [comment]
maybe this helps @greg0ire ?

https://github.com/sonata-project/SonataAdminBundle/commit/c6f3986034501b3124ffe2e2f92ab1a0d033f198

**Comment by greg0ire** [comment]
Yes it does :) I'll try to do something from there…

**Comment by greg0ire** [comment]
Well, that wasn't easy, especially the sf <2.8.0 compatibility part, but I guess this will make testing widgets easier. @core23 @OskarStark This is RTM

**Comment by OskarStark** [comment]
Thank you @greg0ire

**Comment by greg0ire** [comment]
Yay! Thank you for merging @OskarStark !

**Comment by OskarStark** [comment]
you're welcome :+1:

**Pull request merged**
