### PR TITLE
Add type hints

### PR DESCRIPTION
**Pull request by greg0ire**
## Subject

I am targeting this branch, because this is BC.

### CODE REVIEW

**Comment by greg0ire** [comment]
Woops, conflicts!

**Comment by core23** [comment]
This is not pedantic, 'cause you changed the method signature. 

Technically this is a soft BC break
https://3v4l.org/5OrlF

**Comment by core23** [comment]
You implied, that the user will use the same return types that you added in this PR, but he could use some other types.

**Comment by greg0ire** [comment]
The classes I did it on are final.

**Comment by greg0ire** [comment]
Putting back pedantic then, right?

**Comment by OskarStark** [comment]
Please rebase

**Pull request merged**
