### PR TITLE
Implement FormMapper from BlockBundle

### LINKED ISSUE #7349: FormMapper of Sonata 4 is not compatible with blockBundle one
In BlockBundle, a FormMapper interface was introduced:
https://github.com/sonata-project/SonataBlockBundle/pull/513

The Admin FormMapper was supposed to implements this interface.
But this is currently not possible
- `setHelps`/`addHelp` doesn't exist anymore
- `add` doesnt accept a FormBuilderInterface anymore
- the `: self` return type in the interface of the BlockBundle disallow to use `:self` in AdminBundle.
- `get` doesn't have `FormBuilderInterface` as return type

The interface of the BlockBundle need to be updated to 
```
    /**
     * @param class-string<FormTypeInterface>|null $type
     * @param array<string, mixed>                 $options
     */
    public function create(string $name, ?string $type = null, array $options = []): FormBuilderInterface;

    /**
     * @param string[] $keys field names
     *
     * @return static
     */
    public function reorder(array $keys);

    /**
     * @param string               $name
     * @param class-string|null    $type
     * @param array<string, mixed> $options
     *
     * @return static
     */
    public function add(string $name, ?string $type = null, array $options = []);

    /**
     * @return static
     */
    public function remove(string $key);

    /**
     * @return static
     */
    public function has(string $key): bool;

    public function get(string $name): FormBuilderInterface;
```
for SonataAdminBundle to be compatible.

The easiest solution might be a BC-break on BlockBundle 4 cc @sonata-project/contributors ?
Something like https://github.com/sonata-project/SonataBlockBundle/pull/899

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes #7349

### CODE REVIEW

**Review by jordisala1991 — APPROVED** [review]

**Review by dmaicher — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thanks @VincentLanglet

**Comment by core23** [comment]
Not sure if this a good idea. We rely on an interface that has nothing to do with the form mapping. The block component is only used for the page composer of the `PageBundle`.

IMHO we should revert this.

**Comment by core23** [comment]
We want to decouple our components to reduce complexity.

**Comment by VincentLanglet** [comment]
I have a lot of frustration by getting a comment like this after opening an issue #7349 to discuss about it, pinging the contributors on Github and on slack in order to have opinion about this, getting almost no response and being force to decision by my own.

The BlockBundle is already a dependency of AdminBundle, [used multiple times](https://github.com/sonata-project/SonataAdminBundle/search?q=blockbundle) ; I'm not sure how using it one more time is a problem here.

The [DatagridBundle](https://github.com/sonata-project/SonataDatagridBundle) was already a try to decouple components in order to reduce complexity. Now, it's just a monster with a lot of duplicated code from SonataAdminBundle which
- Doesn't have all the bug-fix of the admin or persistence bundle
- Have slightly different interfaces
It should be a dependency of the AdminBundle, but won't never be because of the too many differences. And some project is now using both datagrid and admin bundles with no benefits.

I don't want to reproduce this with the block bundle. We almost done by keeping some useless method like `setHelps` or `getHelps` because they were coming from the AdminBundle and when we deprecated them from the AdminBundle, nobody knows they had to do the same in the BlockBundle. By implementing the interface, we'll know next time.

Also implementing the interface avoid to create the same adapter every time we need one. The `FormMapper` is not related to the PageBundle. It's already used in both [PageBundle](https://github.com/sonata-project/SonataPageBundle/blob/fed26c06856de8d6b1161d0f23001db7b8377e2b/src/Mapper/PageFormMapper.php) and the [DashboardBundle](https://github.com/sonata-project/SonataDashboardBundle/blob/72d12e081c8edf08159bd88c26641c408129b25e/src/Mapper/DashboardFormMapper.php). And those implementations was not valid anymore since some method signature of the Admin FormMapper changed.

To me, the `FormMapper` is only related to the [EditableService](https://github.com/sonata-project/SonataBlockBundle/blob/b161b8273366bec8d878e8e5a5c91a270eba3aa2/src/Block/Service/EditableBlockService.php) and people should be able to create an editable block service when using SonataAdminBundle, since we provide a FormMapper fully compatible.

**Comment by VincentLanglet** [comment]
Looking at the `BlockBundle\FormMapper` interface, it's really similar to [FormBuilderInterface](https://github.com/symfony/form/blob/5.3/FormBuilderInterface.php) one.

IMHO, we could deprecate this interface in BlockBundle 4.x and use the FormBuilderInterface to the EditableBlockService interface instead. WDYT ? (cc @sonata-project/contributors)

**Comment by core23** [comment]
> I have a lot of frustration by getting a comment like this after opening an issue #7349 to discuss about it, pinging the contributors on Github and on slack in order to have opinion about this, getting almost no response and being force to decision by my own.

Sorry for the inconvenience. I'm doing this whole stuff in my free time and did not receive a single dollar / euro from it. You cannot expect, that every contributor watches every issue 24/7. I know that is sometimes hard to get some feedback, especially when it is vacation time or when there is a lack of interest in this project from time to time.

Back to topic.

I just sam the change when looking at the changelog for the RC release (#7370) which got my attention, because it's a major step we can't revert soon. From an architecture perspective, we should not depend on interfaces that have nothing to do with the current implementation. The `FormMapper` might look similar to the interface, but there are some differenes. The admin bundle does not rely on components that got the interface, the block bundle does.

> Also implementing the interface avoid to create the same adapter every time we need one. The `FormMapper` is not related to the PageBundle. It's already used in both [PageBundle](https://github.com/sonata-project/SonataPageBundle/blob/fed26c06856de8d6b1161d0f23001db7b8377e2b/src/Mapper/PageFormMapper.php) and the [DashboardBundle](https://github.com/sonata-project/SonataDashboardBundle/blob/72d12e081c8edf08159bd88c26641c408129b25e/src/Mapper/DashboardFormMapper.php). And those implementations was not valid anymore since some method signature of the Admin FormMapper changed.

Adding an interface dependency to a component that are soft-related adds complexity might create some issues when creating a new major release of the block bundle. This creates more issues the more we rely on unrelated interface and slows down the release process. It's better use the adapter pattern which allows more flexibility.

> The BlockBundle is already a dependency of AdminBundle, [used multiple times](https://github.com/sonata-project/SonataAdminBundle/search?q=blockbundle) ; I'm not sure how using it one more time is a problem here.

That's right, but the usage is for block components, not general components.

> The [DatagridBundle](https://github.com/sonata-project/SonataDatagridBundle) was already a try to decouple components in order to reduce complexity. Now, it's just a monster with a lot of duplicated code from SonataAdminBundle which

I'm okay with including the datagrid components, because they are similar and heavily used inside the admin bundle.

**Comment by VincentLanglet** [comment]
>  I'm doing this whole stuff in my free time and did not receive a single dollar / euro from it. 

Neither did I.

> The `FormMapper` might look similar to the interface, but there are some differences. The admin bundle does not rely on components that got the interface, the block bundle does.
>
> Adding an interface dependency to a component that are soft-related adds complexity might create some issues when creating a new major release of the block bundle. This creates more issues the more we rely on unrelated interface and slows down the release process. It's better use the adapter pattern which allows more flexibility.

WDYT about [this solution](https://github.com/sonata-project/SonataAdminBundle/pull/7364#issuecomment-894824688) @core23 ?

IMHO:
- Implementing the FormMapper interface is a sufficiently correct solution for Block&Admin 4
- In Block5 changing FormMapper to the FormBuilderInterface will solve the issue.

> I'm okay with including the Datagrid components, because they are similar and heavily used inside the admin bundle.

I just tried multiple times, it just required to much work and to much BC-break because it wasn't done correctly at the first time. The idea was good, not the realization and now we should kill it with fire.

**Comment by jordisala1991** [comment]
I don't think any of us gets paid to do open source, we try our best and we have to deal with this and assume we don't have infinite time or the releases won't be perfect.

About the topic, I only see 3 solutions for the AdminBundle:

1. Go with what we have now, which IMO it is good enough for a 5/6 year old major release.
2. Revert the `implements FormMapper` change and don't worry about if SonataBlockBundle works with SonaPageBundle
3. Delay again the SonataAdmin 4 release to think about perfect solutions.

To me , both 1 and 2 are good. To be honest, I think the 1 is good enough for now, we had plenty of time (not a matter of weeks, but years) to think about a better solution.

But, if we don't want the 1, Im fine with the option 2., because I never used SonataPageBundle and I don't know if its going to be ever compatible with SonataAdmin 4, maybe if there is enough interest on the comunity (not by me).

What I don't think we should do, is delay again this release. It will never be perfect, and it will never be bug free.

**Comment by wbloszyk** [comment]
For me this solution is acceptable. We should not wait for other solution and block major release. 

Anyway it is not good solution. We are using `FormMapper` in many bundles. In one place it is from `AdminBuindle`, in other from `BlockBundle` etc. Simmilar we are using `datagrid`. What is little confusing. 

IMHO We should find some solution like `contracts` or move some functionality to seperate bundle. For example we can move `FormMapper` and whole form structure to `sonata-project/form-extensions`.  Additionaly sonata form (awsome ajax widget or tabs) can be use seperatly then. Allow using sonata tools instead whole sonata will be make it more famous. Mybe we can go to it in 5.0?

**Comment by VincentLanglet** [comment]
> For me this solution is acceptable. We should not wait for other solution and block major release.

Agree, I think I'll release the v4 tomorrow then since the majority consider this as acceptable.

> Anyway it is not good solution. We are using `FormMapper` in many bundles. In one place it is from `AdminBuindle`, in other from `BlockBundle` etc.

Like I said, to me there is no need for a custom "FormMapper" in the BlockBundle. A FormBuilderInterface will do the job.
I'll open an issue for the BlockBundle v5.

> IMHO We should find some solution like `contracts` or move some functionality to seperate bundle.

This could be done in a dream world. But the more bundle we have, the more it's difficult to maintain them.
A mono repository could help, but it requires lot of configuration.

We're currently like 5 actives contributors.
We should focus on what is easy to maintain, and might even abandon some bundles.

**Comment by wbloszyk** [comment]
I mean do something like vue.js structure. Like make some form component, datagrid component... etc. and then layer higher use it in Admin. Another layer higer create Pool. 

In this scructure all of components can be use as seperate tool. It will be easier to maintain too.

**Pull request merged**
