### PR TITLE
Edit wrong example for  command make:sonata:admin

### PR DESCRIPTION
**Pull request by smash-wp**
replace wrong command example for "make:sonata:admin" from "$ bin/console sonata:admin:generate App/Entity/Foo" to "$ bin/console make:sonata:admin App/Entity/Foo"

### CODE REVIEW

**Comment by greg0ire** [comment]
I approved but actually… the command still exists, right? https://github.com/sonata-project/SonataAdminBundle/blob/b23a4ca42f061d682d892bb6142ad4bf2699adac/src/Command/GenerateAdminCommand.php#L43 What's the deal?

**Comment by greg0ire** [comment]
@indiancomet can you help with this? What is the plan? Should we deprecate the old command?

**Comment by OskarStark** [comment]
The old command is still working with older symfony versions. If you are using Sf 2.8 you cannot use the maker command. So both should exists unless we drop the deps support

**Comment by OskarStark** [comment]
But we can of course use the latest infos in the docs so 👍🏻

**Comment by greg0ire** [comment]
Crystal clear, thanks @OskarStark !
@smash-wp congrats on your first contribution!

**Comment by smash-wp** [comment]
@greg0ire thanks :)

**Pull request merged**
