### PR TITLE
Fix - Variable "admin" does not exist.

### PR DESCRIPTION
**Pull request by ggabrovski**
## Subject

After updating to 3.84 I found some Twig runtime error related to missing "admin" variable. Probably one extra check will fix the issue or someone with more experience can suggest better solution.

I am targeting this branch, because of BC.

## Changelog

```markdown
### Fixed
Variable "admin" does not exist in `CRUD/Association/edit_many_script.html.twig`
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Hi @ggabrovski, do you know the PR/commit which introduce the bug ? It would help to understand more about this bug.

**Comment by VincentLanglet** [comment]
Hi @ggabrovski,

`admin.label` should be changed to `associationadmin.label` ; can you update the PR ?

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks !

**Comment by ggabrovski** [comment]
It was in #6614
src/Resources/views/CRUD/Association/edit_many_script.html.twig

I change it to associationadmin.label

VincentLanglet, Thank you very much for the support

**Pull request merged**
