### PR TITLE
Update styles.css

### PR DESCRIPTION
**Pull request by webislife**
Fix image size in table and fix for loooooooooooong words in td

Hey, fix please this changes for the best view table)

### CODE REVIEW

**Comment by velikanov** [comment]
:+1:

**Comment by arthas-eve** [comment]
:+1:

**Comment by rande** [comment]
Can you add a before/after screenshots?

**Comment by webislife** [comment]
yes, see example
![Image]
(http://i.gyazo.com/dd86842e9f10dce177db01b8a6e47ca1.png)

**Pull request merged**
