### PR TITLE
fix sticky navbar scroll lag on safari

### LINKED ISSUE #7192: refreshNavbarStuckClass leads to scroll lag on safari
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              dev-master 23df35c dev-master 23df35c The missing Symfony Admin Generator
sonata-project/block-bundle              4.5.3              4.5.3              Symfony SonataBlockBundle
sonata-project/cache                     2.1.1              2.1.1              Cache library
sonata-project/doctrine-extensions       1.12.0             1.12.0             Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle dev-master b59f9e5 dev-master b59f9e5 Integrate Doctrine ORM into the SonataAdminB...
sonata-project/exporter                  2.6.2              2.6.2              Lightweight Exporter library
sonata-project/form-extensions           1.9.0              1.9.0              Symfony form extensions
sonata-project/twig-extensions           1.5.1              1.5.1              Sonata twig extensions
```

</p>
</details>

## Subject

The `refreshNavbarStuckClass` function in `assets/js/admin.js` leads to nasty scroll lag on Safari whenever the corresponding waypoint is reached. Responsible is this part:

https://github.com/sonata-project/SonataAdminBundle/blob/01677b25381aa3c3d87dfaf7fe8699d9bc4744f3/src/Resources/public/Admin.js#L722

Safari does not seem to handle this kind of runtime injection of global styles very well.
This does not occur on Firefox, on Chrome I had the issue in the past but it resolved itself.
In the past I had Safari issues like this on other machines as well, but it might be machine specific to some degree.

This bug leads to a bad UX on some machines. I will create a PR to fix it.

### PR DESCRIPTION
**Pull request by moostrich**
## Subject

With these changes the css is only updated when there is an actual change in the `topNavbar` height.
So it's basically only done once on page load as opposed to each time you scroll across the waypoint.

I am targeting this branch, because I used ES6 template strings in the Webpack environment.

Closes #7192.

## Changelog

```markdown
### Fixed
Scroll lag on Safari due to refreshNavbarStuckClass call.
```

### CODE REVIEW

**Review by VincentLanglet — DISMISSED** [review]

**Review by jordisala1991 — CHANGES_REQUESTED** [review]
Always remember to compile assets

**Comment by jordisala1991** [comment]
It would be nice to try to not introduce more jQuery lines, and use plain Js instead

**Comment by VincentLanglet** [comment]
> Always remember to compile assets

@jordisala1991 would it be possible to add a check to the ci in order to check if the assets were builded ?

**Comment by moostrich** [comment]
@jordisala1991 Ok sure no problem, I rewrote everything in plain js. I will keep in mind that you want to remove jQuery for future PR's.

Can you clarify regarding compiling assets, I have little experience in contributing. Do you want me to commit the compiled `src/Resources/public/app.js` file? I tested it of course but was not sure if the build should be checked in.

**Comment by jordisala1991** [comment]
> > Always remember to compile assets
> 
> 
> 
> @jordisala1991 would it be possible to add a check to the ci in order to check if the assets were builded ?

I think it should be possible but dont know how. Maybe runing same commands and git diff?

To generate compilation assets run:

yarn install --frozen-lockfile
yarn encore production

(you can read more on the contribution guide, at the root of the project)

**Comment by VincentLanglet** [comment]
> > > Always remember to compile assets
> > 
> > 
> > @jordisala1991 would it be possible to add a check to the ci in order to check if the assets were builded ?
> 
> I think it should be possible but dont know how. Maybe runing same commands and git diff?

Indeed https://github.com/sonata-project/dev-kit/pull/1546

**Comment by moostrich** [comment]
@jordisala1991 Thank your for clarifying :) Everything should be there now.

**Comment by jordisala1991** [comment]
Could you associate your commits with your github account? Probably you are missing the email in your local config (otherwise we cant see who made those commits after the merge)

**Comment by VincentLanglet** [comment]
Hi @moostrich, do you have to rebase ?

**Comment by VincentLanglet** [comment]
Hi @moostrich, are you still interested in this PR ? Can you rebase master ?

**Comment by moostrich** [comment]
@VincentLanglet Hey! Sorry lost track of this, thanks for reminding. Just rebased onto master.

**Review by VincentLanglet — APPROVED** [review]

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thanks @moostrich

**Pull request merged**
