### PR TITLE
Clean NEXT_MAJOR comments of #4542

### PR DESCRIPTION
**Pull request by jlamur**
I cherry picked the commit https://github.com/sonata-project/SonataAdminBundle/commit/26d69b89b3184d12653dffc2fdea65ea37125c6f and then cleaned NEXT_MAJOR comments.

I don't know if this should be closed or merged, but a discussion started here about it: https://github.com/sonata-project/SonataAdminBundle/pull/4542#discussion_r125561202

ping @greg0ire @OskarStark

### CODE REVIEW

**Comment by jlamur** [comment]
Please note that I wrote commented tests that do not pass. :cry: 
I fixed them in the last commit. I only modified some hooked method names, it's not a big deal.

Depending on what happen to this PR (merged or not), I will create a new PR to fix the mentioned tests on `3.x`.

**Comment by greg0ire** [comment]
Now the automatic merge works well, I think it is ok to take care of `NEXT_MAJOR` comments: if there are conflicts, we can now quickly and take care of then one by one instead of ending up with a gazillion merge conflicts.

**Comment by jlamur** [comment]
:+1: 

IMO, we should ideally create PRs to clean `NEXT_MAJOR` comments regularly. WDTY?

**Comment by jlamur** [comment]
Ready to merge if @sonata-project/contributors like the idea to clean `NEXT_MAJOR` comments after a PR is merged and not just when preparing the next major release.

**Comment by jordisala1991** [comment]
We should wait for dev-kit to merge on master no?

**Comment by jlamur** [comment]
It was done this night https://github.com/sonata-project/SonataAdminBundle/commit/2e2098a2568125eadff91803983557d40939a5fb

**Comment by greg0ire** [comment]
@jordisala1991 it did, hence the conflicts

**Comment by core23** [comment]
> Ready to merge if @sonata-project/contributors like the idea to clean `NEXT_MAJOR` comments after a PR is merged and not just when preparing the next major release.

That's the best way to have a long period to test if this will really work.

**Comment by jordisala1991** [comment]
Thank you @jlamur :)

**Comment by jordisala1991** [comment]
We just have to look at this to know that is better this way: 
https://github.com/sonata-project/SonataAdminBundle/pull/4669

**Pull request merged**
