### PR TITLE
Improve hint to exception message

### PR DESCRIPTION
**Pull request by axzx**
I am targeting this branch, because is improve.
ref 56b0201c63c50e61e6bb002c78fdd1991924d347 

## Changelog

```markdown
### Added
- Added `levenshtein` to improve an error message. 
```

## Subject

Now the most-matched phrase is displayed. In addition, a list of all admin services is also displayed.

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Check flintCI please.

**Comment by OskarStark** [comment]
Please add a test case

**Comment by axzx** [comment]
@OskarStark coverage/coveralls checked the old code. Can you reset it?

**Comment by greg0ire** [comment]
I thought you were bothered with the length of the message, and were going to trim it to the X best candidates according to levenshtein…

**Comment by axzx** [comment]
@greg0ire I meant that a large number of names will not help. That's why it's better to display one best matching admin service.

**Comment by axzx** [comment]
@greg0ire Do you have any suggestions on how to improve it?

**Comment by axzx** [comment]
ok guys. wait:)

**Comment by axzx** [comment]
@greg0ire done. I modified the code a bit.

**Comment by kunicmarko20** [comment]
Restarted tests and they are passing, guess this can be merged now.

**Comment by kunicmarko20** [comment]
@OskarStark I think we use that label only for issues? we should probably use minor/patch here

**Comment by OskarStark** [comment]
Argh you are right, sorry, please change it

**Comment by OskarStark** [comment]
Thank you @axzx 👍

**Pull request merged**
