### PR TITLE
Update Admin.php

### PR DESCRIPTION
**Pull request by annaos**
Otherwise /sonata-project/doctrine-orm-admin-bundle/Resources/views/CRUD/edit_orm_one_to_many.html.twig line 66 will not work

### CODE REVIEW

**Comment by pulzarraider** [comment]
ping @i2005year

**Comment by core23** [comment]
ping @annaos

**Comment by core23** [comment]
Are you still working on this? Please squash and rebase or close this PR @annaos

**Comment by core23** [comment]
Closing this for now, because there is no activity of @annaos on GitHub anymore

**Pull request closed without merging**
