### PR TITLE
Fix no subject error on nested collection

### LINKED ISSUE #7532: No subject on add collection element
Hello team,

**Environment**
<details>
<summary>Sonata Package</summary>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              4.0.1  3.79.0 The missing Symfony Admin Generator
sonata-project/block-bundle              4.7.0  3.21.0 Symfony SonataBlockBundle
sonata-project/cache                     2.2.0  2.1.1  Cache library
sonata-project/doctrine-extensions       1.14.0 1.10.1 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 4.0.0  3.24.0 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.8.0  2.4.1  Lightweight Exporter library
sonata-project/form-extensions           1.11.0 1.6.0  Symfony form extensions
sonata-project/twig-extensions           1.9.0  1.4.1  Sonata twig extensions
```

</details>
<details>
<summary>Symfony packages</summary>

```
symfony/asset                      v5.3.4  v5.3.4  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/cache                      v5.3.8  v5.3.8  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.4.0  v2.4.0  Generic abstractions related to caching
symfony/config                     v5.3.4  v5.3.4  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v5.3.7  v5.3.7  Eases the creation of beautiful and testable command line interfaces
symfony/contracts                  v1.1.0  v2.4.0  A set of abstractions extracted out of the Symfony components
symfony/debug-bundle               v5.3.4  v5.3.4  Provides a tight integration of the Symfony Debug component into the Symfony full-stack framework
symfony/dependency-injection       v5.3.8  v5.3.8  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v2.4.0  v2.4.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.3.8  v5.3.8  Provides integration for Doctrine with various Symfony components
symfony/dotenv                     v5.3.8  v5.3.8  Registers environment variables from a .env file
symfony/error-handler              v5.3.7  v5.3.7  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.3.7  v5.3.7  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v2.4.0  v2.4.0  Generic abstractions related to dispatching event
symfony/expression-language        v5.3.7  v5.3.7  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.3.4  v5.3.4  Provides basic utilities for the filesystem
symfony/finder                     v5.3.7  v5.3.7  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.17.0 v1.17.0 Composer plugin for Symfony
symfony/form                       v5.3.8  v5.3.8  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v5.3.8  v5.3.8  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client-contracts      v2.4.0  v2.4.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.3.7  v5.3.7  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.3.9  v5.3.9  Provides a structured process for converting a Request into a Response
symfony/options-resolver           v5.3.7  v5.3.7  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v5.3.8  v5.3.8  Provides password hashing utilities
symfony/polyfill-ctype             v1.23.0 v1.23.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.23.1 v1.23.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.23.0 v1.23.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-normalizer   v1.23.0 v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.23.1 v1.23.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.23.1 v1.23.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/property-access            v5.3.8  v5.3.8  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v5.3.8  v5.3.8  Extracts information about PHP class' properties using metadata of popular sources
symfony/routing                    v5.3.7  v5.3.7  Maps an HTTP request to a set of configuration variables
symfony/runtime                    v5.3.4  v5.3.4  Enables decoupling PHP applications from global state
symfony/security-acl               v3.2.0  v3.2.0  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v5.3.8  v5.3.8  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v5.3.8  v5.3.8  Symfony Security Component - Core Library
symfony/security-csrf              v5.3.4  v5.3.4  Symfony Security Component - CSRF Library
symfony/security-guard             v5.3.7  v5.3.7  Symfony Security Component - Guard
symfony/security-http              v5.3.8  v5.3.8  Symfony Security Component - HTTP Integration
symfony/service-contracts          v2.4.0  v2.4.0  Generic abstractions related to writing services
symfony/stopwatch                  v5.3.4  v5.3.4  Provides a way to profile code
symfony/string                     v5.3.7  v5.3.7  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/templating                 v5.3.7  v5.3.7  Provides all the tools needed to build any kind of template system
symfony/translation                v5.3.9  v5.3.9  Provides tools to internationalize your application
symfony/translation-contracts      v2.4.0  v2.4.0  Generic abstractions related to translation
symfony/twig-bridge                v5.3.7  v5.3.7  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v5.3.4  v5.3.4  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v5.3.8  v5.3.8  Provides tools to validate values
symfony/var-dumper                 v5.3.8  v5.3.8  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.3.8  v5.3.8  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-profiler-bundle        v5.3.8  v5.3.8  Provides a development tool that gives detailed information about the execution of any request
symfony/yaml                       v5.3.6  v5.3.6  Loads and dumps YAML files
```
</details>

```
$ php -v
PHP 7.4.23 (cli) (built: Sep  3 2021 17:58:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

```

I try to implement in an edit page, 3 levels of nested collection.
A -> B[] -> C[]

When i add B element to A, no problem, everything work perfectly.
But when i whant to Add C element to the B i have this error.
Admin "App\Admin\BAdmin" has no subject.

I create a little sandbox with the reproduced error here : https://github.com/Pasttaga/sonata-test

If anyone has any idea what I did wrong.

Thanks in advance

### PR DESCRIPTION
**Pull request by Pasttaga**
## Subject
Nested collection in form not work with more than 2 levels.
This PR fix error 'Admin has no subject'.

I am targeting this branch, because it's probably a bug.

Closes #7532.

## Changelog

```markdown

### Fixed
- Set subject of $associationAdmin when collection is append to childs collections.
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
@Pasttaga or @VincentLanglet do you think this can be tested?

**Comment by Pasttaga** [comment]
> @Pasttaga or @VincentLanglet do you think this can be tested?

I think one more level can be tested in test `Sonata\AdminBundle\Tests\Admin\AdminHelperTest::testAppendFormFieldElementWithCollection()` i try it without success for the moment.

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
> @Pasttaga or @VincentLanglet do you think this can be tested?

It could. But I'm not sure it will be easy.

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thanks @Pasttaga

**Pull request merged**
