### PR TITLE
Allow to use Twig 2.x in Sonata apps

### PR DESCRIPTION
**Pull request by javiereguiluz**
I am targetting this branch, because this is not a deprecation removal or a BC break.

Closes no issue.

## Changelog

```markdown
### Changed
- allow the usage of Twig 2.0
````

## Subject

Twig 2.0 will probably be released this week. I'm trying to test it in a Symfony app that uses Sonata. I can't install it because:

```
$ composer update twig/twig

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sonata-project/admin-bundle 3.10.0 requires twig/twig ^1.26 -> satisfiable by twig/twig[1.x-dev].
    - sonata-project/admin-bundle 3.10.0 requires twig/twig ^1.26 -> satisfiable by twig/twig[1.x-dev].
    - sonata-project/admin-bundle 3.10.0 requires twig/twig ^1.26 -> satisfiable by twig/twig[1.x-dev].
    - Can only install one of: twig/twig[2.x-dev, 1.x-dev].
    - Installation request for twig/twig 2.x-dev -> satisfiable by twig/twig[2.x-dev].
    - Installation request for sonata-project/admin-bundle (locked at 3.10.0, required as ^3.0) -> satisfiable by sonata-project/admin-bundle[3.10.0].
```

### CODE REVIEW

**Comment by greg0ire** [comment]
I think there are [some deprecations to fix](https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/184784616#L3181) before merging things like that : 

> Calling "getrender_array" on template "SonataAdminBundle:CRUD:list_array.html.twig" from template "SonataAdminBundle:CRUD:list_array.html.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0: 2x
    2x in SonataAdminExtensionTest::testRenderListElement from Sonata\AdminBundle\Tests\Twig\Extension
> Calling "getattributes" on template "knp_menu.html.twig" from template "Core/tab_menu_template.html.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0: 4x
    2x in TabMenuTest::testLabelTranslationDomainOverride from Sonata\AdminBundle\Tests\Menu\Integration
    1x in TabMenuTest::testLabelTranslationNominalCase from Sonata\AdminBundle\Tests\Menu\Integration
    1x in TabMenuTest::testLabelTranslationWithParameters from Sonata\AdminBundle\Tests\Menu\Integration

**Comment by greg0ire** [comment]
The first one comes from knp… so I guess we can't upgrade until knp is compatible with Twig 2…

**Comment by greg0ire** [comment]
Related issue : https://github.com/KnpLabs/KnpMenu/issues/250

**Comment by greg0ire** [comment]
@javiereguiluz : in the meantime, if you want to try Twig 2 and see if things fail, I suggest you use an inline alias.

**Comment by OskarStark** [comment]
anything todo here @greg0ire ?

**Comment by greg0ire** [comment]
Fix all the deprecation I listed. We are apparently not fully compatible with Twig 2 yet.

**Comment by greg0ire** [comment]
Also, tests in this PR were not run with Twig 2.0, and won't be until both https://github.com/sonata-project/SonataCoreBundle/pull/371 and https://github.com/sonata-project/SonataIntlBundle/pull/146 are merged. When they are, please trigger a new build by reopening this, it will probably fail.

**Comment by greg0ire** [comment]
@romainneutron fixed a deprecation in #4276

**Comment by greg0ire** [comment]
No problem, but next time just force push and/or change the base branch (you can do that on github since a few weeks)

**Comment by greg0ire** [comment]
Reopening, this should make the build fail, because now Twig 2 can be installed, and the test suite be run with it.

**Comment by greg0ire** [comment]
Restarting the build

**Comment by greg0ire** [comment]
As expected, the build fails now.

**Pull request closed without merging**
