### PR TITLE
change html with a links in no_result_content

### PR DESCRIPTION
**Pull request by axzx**
## Subject

I am targeting this branch, because BC.

## Changelog

```markdown
### Changed
- html with a links in no_result_content
```

The `go_to_the_first_page` link appears when there are more results.
The `button_create` link only appears if it is not AJAX.

obraz
obraz

### CODE REVIEW

**Review by VincentLanglet — CHANGES_REQUESTED** [review]
What's your issue @axzx ?

The goal was
- If there is results, see ONLY the `go_to_first_page` link.
- If there is no result, see the create button.

With your change, if there is results, you see the link AND the button.

You should not be able to see the button when there is results.

**Comment by axzx** [comment]
> What's your issue @axzx ?
> 
> The goal was
> 
>     * If there is results, see ONLY the `go_to_first_page` link.
> 
>     * If there is no result, see the create button.
> 
> 
> With your change, if there is results, you see the link AND the button.
> 
> You should not be able to see the button when there is results.

I improved the html a bit.
You also need to pay attention to the Ajax behavior.
I changed the code so that it was as you wrote.

**Review by VincentLanglet — APPROVED** [review]
Do you have a screenshot of the new render ?

**Review by wbloszyk — APPROVED** [review]
Will be nice to have screen shot before merge.

**Comment by axzx** [comment]
> Do you have a screenshot of the new render ?

I completed the description of the PR.
Nothing has changed in appearance.

**Comment by wbloszyk** [comment]
Thank you @axzx

**Pull request merged**
