### PR TITLE
Revert: Show matching filters in search results

### PR DESCRIPTION
**Pull request by core23**
## Subject

This is a hotfix to make the search useable again if you have cascaded search filters.
```php
    protected function configureDatagridFilters(DatagridMapper $filter): void
    {
        $filter
            ->add('addresses.city')
        ;
    }
```

The following code needs some rework to make the feature useable again:

```twig
 {% set match = name|split('.')|reduce((carry, v) => carry ? attribute(carry, v) : null, result) %}
```

I am targeting this branch, because #7005 break the search result.

## Changelog

```markdown
### Removed
 - Information about the matching filters in the search results, because it does not work for cascaded oneToMany filters.
```

### CODE REVIEW

**Comment by core23** [comment]
cc @phansys

**Review by VincentLanglet — COMMENTED** [review]
Should we add a test to avoid the regression to come back ?

**Comment by phansys** [comment]
https://github.com/sonata-project/SonataAdminBundle/pull/7005#issuecomment-894645956

If the feature is removed for some reason about nested properties in a collection, please make it clear in the description.
When I added these changes, I tested the behavior with nested accessors (like `city.state.country`), but not using collections (like in `addresses.city`).

**Comment by core23** [comment]
> Should we add a test to avoid the regression to come back ?

It's a revert commit, because the feature does not work. Where do you want a regression test?

**Comment by VincentLanglet** [comment]
> It's a revert commit, because the feature does not work. Where do you want a regression test?

You're saying that 
> ```
>     protected function configureDatagridFilters(DatagridMapper $filter): void
>     {
>         $filter
>             ->add('addresses.city')
>         ;
>     }
> ```
is not working anymore on this page. So you're fixing a bug, by removing partially the feature.

When phansys added the feature, he added multiple tests ; no this one.
If someone try to add this feature again later, he could re-add the bug, since there is no test preventing him.

Best would be to add a `testSearchResultPageWorksWithCascadedSearchFilter` test, to avoid someone to re-add the bug.

**Comment by core23** [comment]
> When phansys added the feature, he added multiple tests ; no this one.

I did not see a single test for this feature #7005

> Best would be to add a testSearchResultPageWorksWithCascadedSearchFilter test, to avoid someone to re-add the bug.

That's right, it would be good to have a specific test for this. Unfortunately this is a twig bug and can't be covered with a simple php unit test. I don't have much time to create a functional test for a broken feature that I did not create.

In the past we just reverted changes that are breaking and started from scratch when reimplementing the feature.

**Review by dmaicher — APPROVED** [review]
Simple revert seems good to me here

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Might better to use the v4-implementation way
- https://github.com/sonata-project/SonataAdminBundle/commit/abdf0a47f5a0a55e7818294e749c11ec797bbb3a
- https://github.com/sonata-project/SonataAdminBundle/pull/7347
- https://github.com/sonata-project/SonataAdminBundle/pull/7379
Instead of fully removing the feature

But still ok

**Pull request merged**
