### PR TITLE
Update RoleSecurityHandler.php

### PR DESCRIPTION
**Pull request by cassianotartari**
Just call the isGranted with object first than without it. I'm using "strategy: unanimous" and I was with the same problem reported in this issue: https://github.com/sonata-project/SonataAdminBundle/issues/1458 and PR: https://github.com/sonata-project/SonataAdminBundle/pull/1507 but I'm using "sonata.admin.security.handler.role". I'm coding a custom voter and I was receiving a NULL object without this code modification.

### CODE REVIEW

**Comment by core23** [comment]
I think there is no reason for a BC break @pulzarraider 

He switched the operands of an "or" condition.

**Comment by OskarStark** [comment]
but why the switch? oO

**Comment by core23** [comment]
Can you give some more information @cassianotartari 

Please rebase too

**Comment by core23** [comment]
Are you still working on this? Please squash and rebase or close this PR @cassianotartari

**Comment by cassianotartari** [comment]
Sorry, I've stopped playing with this, it was used in a old project.

**Pull request closed without merging**
