### PR TITLE
Remove custom view doc

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because doc update.

See https://github.com/sonata-project/SonataAdminBundle/issues/6189

The doc is promoting a bad pattern which is not fully working.

Admin without entity is currently not fully working and it will be worst in the next major.
Moreover, if it's just a way to have the page in the sidebar, there are better way to do it than creating a fake admin.

That's why we should IMHO remove this doc.

### CODE REVIEW

**Comment by phansys** [comment]
Thank you @VincentLanglet!

**Comment by john-dufrene-dev** [comment]
Without custom view, what is the simple way to do that in custom controller ?

**Comment by VincentLanglet** [comment]
> @VincentLanglet Without custom view, what is the simple way to do that in custom controller ?

A custom route, with the data you need.
A custom template, with the view you want.
And a little bit of config https://github.com/sonata-project/SonataAdminBundle/issues/6189#issuecomment-657130541

**Comment by john-dufrene-dev** [comment]
@VincentLanglet Do you have a very simple example that I could test?

**Pull request merged**
