### PR TITLE
Remove compatibility layer with old versions of sf

### PR DESCRIPTION
**Pull request by greg0ire**
## Subject
I am targeting this branch, because this is probably BC.

### CODE REVIEW

**Comment by core23** [comment]
> I am targeting this branch, because this is probably BC.

Dropping a class is BC?

**Comment by greg0ire** [comment]
If it cannot be used, probably, right?

**Comment by core23** [comment]
AFAIK we don't need the class anymore, but the user could have some code that relies on it

**Comment by greg0ire** [comment]
You're right, who knows? Let's not take the risk.

**Pull request closed without merging**
