### PR TITLE
Added current translationDomain by default and new format option in CRUD:list_trans.html.twig

### PR DESCRIPTION
**Pull request by ruscon**

### CODE REVIEW

**Comment by ruscon** [comment]
How can i view SonataCi / Sandbox / PHPUnit error ? =/

**Comment by OskarStark** [comment]
@ruscon can we merge this on ``2.3`` ?

**Comment by ruscon** [comment]
@OskarStark yep

**Comment by OskarStark** [comment]
@Soullivaneuh how can i handle this?

**Comment by Soullivaneuh** [comment]
In this case, please open a new PR against `2.3`.

**Comment by Soullivaneuh** [comment]
After reflexion, no. Not 2.3. This is not a bugfix.

**Comment by OskarStark** [comment]
Thank you for your feedback @Soullivaneuh 

I'm gonna merge this PR as it is.

Thank @ruscon :+1:

**Pull request merged**
