### PR TITLE
Deprecate BCLabelTranslatorStrategy

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because {reason}.

Closes #{put_issue_number_here}.

## Changelog

```markdown
### Deprecated
- BCLabelTranslatorStrategy
```

### CODE REVIEW

**Review by jordisala1991 — APPROVED** [review]

**Review by jordisala1991 — CHANGES_REQUESTED** [review]
rector needs to be fixed.

**Comment by VincentLanglet** [comment]
> rector needs to be fixed.

Done

**Review by jordisala1991 — DISMISSED** [review]

**Comment by jordisala1991** [comment]
Maybe adding an upgrade note is necessary? what should the user do if he is using that translator strategy?

**Comment by VincentLanglet** [comment]
> Maybe adding an upgrade note is necessary? what should the user do if he is using that translator strategy?

done

**Review by jordisala1991 — APPROVED** [review]

**Pull request merged**
