### PR TITLE
add on_top to @admin annotation

### PR DESCRIPTION
**Pull request by wodka**
add the on_top option to admin annotation

### CODE REVIEW

**Comment by core23** [comment]
Please use the PR template and say a little more what this `on_top` options is doing.

Also please provide at least a unit test.

**Comment by wodka** [comment]
The on_top is working according to: https://sonata-project.org/bundles/admin/3-x/doc/cookbook/recipe_knp_menu.html

the only thing the pull request does is to add the field to the annotation

**Comment by jordisala1991** [comment]
are you sure you want to target master branch? we are currently using 3.x for the things that are BC compatible. And this should be BC.

**Comment by wodka** [comment]
oh, I'll change that

**Comment by wodka** [comment]
I'll create a new one...

**Comment by wodka** [comment]
created a new pull request in https://github.com/sonata-project/SonataAdminBundle/pull/4411 (also usde the template there)

**Pull request closed without merging**
