### PR TITLE
remove subclass parameter when generating sonata_admin_short_object_information

### LINKED ISSUE #7843: subclass parameter conflict between admin
There is name conflict for the subclass parameter.

If you are in the creating flow (since the on edit or show the subclass parameter don't exits) and one of the form type that need to call another admin (Example ModelListType) that has subclass as well it will failed. The subclass parameter from the current create admin will be pass to the ajax call (to load the information) and the other admin will failed since the class referred by the subclass parameter will not exists.

Solution would be to prefix the parameter name with the admin code (or something the sort) that way the parameter will be only interpreted by the proper admin. 

This would cause issue to people that are generated url with subclass outside of the admin. We could trigger a deprecated if present and use it any way. It would not solve the issue of people using $request->query->get('subclass') directly. 

We could make a configuration that need to be explicitly enable to fix the issue.

This is present in v3 and v4

### PR DESCRIPTION
**Pull request by mpoiriert**
…

I am targeting this branch, because bug is present in this branch.

Closes #7843.

## Changelog
```markdown
### Fixed

Fix the subclass query parameter conflict in the sonata.admin.action.get_short_object_description controller.
```

## To do

- [ ] Update the tests;
- [ ] Update the documentation;
- [ ] Add an upgrade note.

### CODE REVIEW

**Comment by mpoiriert** [comment]
@VincentLanglet This is something that would work and it's really specific to the bug I have found.
Admin may be conflicting somewhere else but I am not sure where and how to reproduce it. Maybe we could fix one at the time ? (Aka per PR).

I would rewrite the url generation of that specific url in a macro since it's getting bigger and noisy.

**Comment by VincentLanglet** [comment]
This seems nice.
Can you
- Add a comment to all the filter to explain the conflict you want to solve (for next developers)
- Try to add a functional test to reproduce the previous error (and avoid a regression)

**Comment by mpoiriert** [comment]
@VincentLanglet I have add another way to solve this. It may be a bit less clean from a coding point of view but it's safer (if someone generate the url from somewhere), easier to test (just need to make a unit test for the action) and maintain (the action is aware of it's behaviour and no one else need to).

I have add back the query parameter just so the request is still intact at the end but this could be optional and just removing the parameter would be enough.

**Comment by mpoiriert** [comment]
@VincentLanglet I have add another way to solve this. It may be a bit less clean from a coding point of view but it's safer (if someone generate the url from somewhere), easier to test (just need to make a unit test for the action) and maintain (the action is aware of it's behaviour and no one else need to).

I have add back the query parameter just so the request is still intact at the end but this could be optional and just removing the parameter would be enough.

I prefer the second option, what do you think ?

**Comment by VincentLanglet** [comment]
So you just need to remove the subclass before 
```
        $object = $admin->getObject($objectId);
        if (null === $object) {
            throw new NotFoundHttpException(sprintf('Could not find subject for id "%s"', $objectId));
        }
```
? (And the filter could be removed ?)

This is not easy to understand and would require some comments I think.
But this could be an easy BC fix.
We might add a NEXT_MAJOR comment to ask for changing some `subclass` parameter to avoid the conflict in Sonata 5

**Comment by mpoiriert** [comment]
> ? (And the filter could be removed ?)

Yes the filter could be removed.

> This is not easy to understand and would require some comments I think.

Or course I'll add comment.

> We might add a NEXT_MAJOR comment to ask for changing some `subclass` parameter to avoid the conflict in Sonata 5

Not sure exactly where. I think the solution I have done with removing the subclass parameter in the action/controller that have conflict with would be the best way to do (and keep it that way). 

This make sure that we don't need to bother how the url get generated. Other wise we would need to add the filter in the first solution every where we need it and we will never be sure someone does not generate the url somewhere else without the filter.

I don't know which controller would need this so I don't know where to remove the subclass and this is probably where the NEXT_MAJOR would be.

**Comment by VincentLanglet** [comment]
Let's go with this solution then

**Comment by mpoiriert** [comment]
@VincentLanglet I added the automation test and some comment near the code for the developer.

Should be ready

**Review by VincentLanglet — APPROVED** [review]

**Review by jordisala1991 — APPROVED** [review]
Good for now. For next major we should try to reduce parameters sent to methods to the minimum needed.

**Comment by VincentLanglet** [comment]
I'll wait for https://github.com/sonata-project/SonataAdminBundle/pull/7819 to release

**Pull request merged**
