### PR TITLE
Fix group menu sub items translation domain

### PR DESCRIPTION
**Pull request by lightglitch**
Related to #4601 and #4614

## Changelog
```markdown
### Fixed
- Fix knp menu extra configuration for domain translations in Group Menu
```

## Subject

The menu extras uses **label_catalogue**, not **translation_domain**.

### CODE REVIEW

**Comment by lightglitch** [comment]
Related to #4601 and #4614

**Comment by OskarStark** [comment]
Can you please provide a test?

**Comment by lightglitch** [comment]
@OskarStark done but the commit https://github.com/sonata-project/SonataAdminBundle/commit/6f52a027174a48121aed5a50052581def5e60a2b needs to be reverted.

**Comment by core23** [comment]
Please leave a note on https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/Menu/sonata_menu.html.twig#L29, so we can remove this hack later.

**Comment by greg0ire** [comment]
Please kindly squash your commits together. If you don't, we'll try to remember to do it for you but it's best if you save us this trouble.

How to do that?

1. `git rebase -i origin/3.x`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin/whatever-you-call-it repository.
2. A window will show up with many lines, replace `pick` with `fixup` on every line but the first one
3. Close your editor, git should do its magic, and you should end up with one commit
4. Use `git push --force` to overwrite what you already pushed. Don't forget the `--force` option otherwise git will try to merge both things together.

**Comment by lightglitch** [comment]
I already squash them, only left the revert.

**Comment by greg0ire** [comment]
Oh right you were not reverting your commit, so that's great.

**Comment by OskarStark** [comment]
Thank you @lightglitch 👍

**Comment by axzx** [comment]
This change caused an error. Again.

https://github.com/sonata-project/SonataAdminBundle/issues/4614

**Comment by greg0ire** [comment]
@axzx please elaborate on this and work together with @lightglitch and @ejkun on a solution that all of you will test before it is merged.

**Comment by greg0ire** [comment]
@sonata-project/contributors when a contributor provides a PR that close issues, we should ask for reviews from all people involved in the linked issues.

**Comment by lightglitch** [comment]
Just tested the dev branch on my project and it's working for me, my configurations:

```

**Comment by axzx** [comment]
@lightglitch sorry, my bad. The team mate did not include changes to the overwritten `sonata_menu.html.twig` file

**Comment by OskarStark** [comment]
@axzx, so this is working as expected?

**Comment by axzx** [comment]
@OskarStark yes. its OK.

**Pull request merged**
