### PR TITLE
Fixed wrong method call in "list__select.html.twig" 

### PR DESCRIPTION
**Pull request by core23**
### Changelog

```markdown
### Fixed
- Fixed wrong method call in `list__select.html.twig`. 
```

### Subject
Fixed bug introduced with #3887. The wrong method was used.

### CODE REVIEW

**Comment by greg0ire** [comment]
The route is good, but the method isn't. The message should read:

```
use object-unaware method

We have no object to pass to generateObjectUrl()
```

**Comment by core23** [comment]
Fixed it @greg0ire

**Comment by Soullivaneuh** [comment]
@core23 Test will fail because of #3899. Please rebase. :+1:

**Comment by OskarStark** [comment]
Thank you @core23 👍

**Pull request merged**
