### PR TITLE
use iCheck sqaure blue instead of flatblue for checkboxes

### LINKED ISSUE #3276: shall we use the AdminLTE checkbox style which looks better (like the inputs)?
now:
bildschirmfoto 2015-09-23 um 11 24 13

possible:
bildschirmfoto_2015-09-23_um_11_24_47

### PR DESCRIPTION
**Pull request by OskarStark**
fixes #3276 

before it looks like this:
bildschirmfoto 2015-09-23 um 11 24 13

now it looks like this:

not checked:
bildschirmfoto 2015-09-23 um 13 25 56

hover:
bildschirmfoto 2015-09-23 um 13 26 11

checked:
bildschirmfoto 2015-09-23 um 13 26 15

a screen from sonata page admin NOW:
bildschirmfoto 2015-09-23 um 13 27 50

before it looks like:
bildschirmfoto 2015-09-23 um 14 46 22

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Can we have the before screenshot of page admin please?

**Comment by OskarStark** [comment]
you see this in the referenced issue #3276

**Comment by Soullivaneuh** [comment]
I was talking about page admin, before your modification.

**Comment by OskarStark** [comment]
hmm this is just the checkbox and you see this on the login page, but if you like i can add another screen

**Comment by OskarStark** [comment]
done @Soullivaneuh

**Comment by OskarStark** [comment]
@Soullivaneuh can you please merge this?

**Comment by Soullivaneuh** [comment]
Would like to have appreciation of other collaborators before.

cc @rande @pulzarraider

**Comment by OskarStark** [comment]
:+1:

**Comment by pulzarraider** [comment]
:+1:

**Comment by OskarStark** [comment]
thank you guys!

**Pull request merged**
