### PR TITLE
Merge branch '3.x' into master

### PR DESCRIPTION
**Pull request by phansys**

### CODE REVIEW

**Comment by phansys** [comment]
While I was preparing the merge, I noticed an issue with a mocked value at tests. If possible, #5610 should be merged before in order to re-create this PR.

**Comment by OskarStark** [comment]
I merged the test fix 👍🏻

**Comment by phansys** [comment]
> I merged the test fix 👍🏻

Great! Thank you so much.
This PR is ready for revision.

**Comment by greg0ire** [comment]
Looks ok! You can push this to origin/master IMO

**Pull request merged**
