### PR TITLE
fixed nested child association in forms

### PR DESCRIPTION
**Pull request by digitalkaoz**
this PR fixes nested associations in forms.

```
 A
  - B
     - C
```

currently its not possible to add a `new C` to `B` if editing from within `A`.

this PR fixes that.

### CODE REVIEW

**Comment by digitalkaoz** [comment]
fixes #2875

**Comment by Soullivaneuh** [comment]
@digitalkaoz Thanks for your contribution.

Could you please give us some use case of your issue and push additional related test on this PR?

Thanks.

**Comment by digitalkaoz** [comment]
ok ill try:

```php
// domain model
class Person {
   /**
    * @ManyToOne(targetEntity="Address")
    */ 
   private $address;
}

class Address {
   /**
    * @ OneToMany(targetEntity="PhoneNumber")
    */ 
   private $phoneNumbers = [];
}

class PhoneNumber {}
```

```php
//admin

class PersonAdmin {
  configureFormFields($formBuilder) {
    $formBuilder->add('address', 'sonata_type_admin');
  }
}

class AddressAdmin {
  configureFormFields($formBuilder) {
    $formBuilder->add('phoneNumbers', 'sonata_type_admin');
  }
}

class PhoneNumberAdmin {
  configureFormFields($formBuilder) {
    ...
  }
}
```

currently im not able to add new Elements to `Address::phoneNumber` from within `PersonAdmin`. This PR fixes that.

probably related issues: https://github.com/sonata-project/SonataAdminBundle/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+embedded+admin+ 

I dont know where to start with Tests. As its JS+PHP Workflow.

**Comment by Soullivaneuh** [comment]
@digitalkaoz Thanks, will take a look.

Can you please rebase your PR to get latest Travis config working?

**Comment by digitalkaoz** [comment]
@Soullivaneuh ok its rebased

**Comment by Soullivaneuh** [comment]
Seems your modifications broke tests.

**Comment by digitalkaoz** [comment]
no its a travis <> github auth/connection issue issue. try to restart the job

**Comment by digitalkaoz** [comment]
ah sorry, we still support php5.3? wait a sec ;)

**Comment by Soullivaneuh** [comment]
Not only.

Take a look also to this one: https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/66789446#L212

To fix, try run `make cs` on your project.

**Comment by digitalkaoz** [comment]
ok now it should pass the CS checks and be 5.3 compatible

**Comment by digitalkaoz** [comment]
@Soullivaneuh most builds passed, the failing once are travis timeouts or allowed failures

**Comment by greg0ire** [comment]
Please rebase again, the Travis issue was fixed recently.

**Comment by greg0ire** [comment]
Also, the first message in this PR could be part of the commit message. It currently reads : 

> fixed nested child association in forms

Commit message that start with "fixed" are usually not good because they often just say that they fix something, and not how it was broken (that is most of the time not obvious), and how they fixed it. Please make a commit message in this form : 

> what you did, precisely
>
> what it fixes and why. This part can actually be very long,
> feel free to embed your nice A, B, C schema in there.
> You should explain here what "not possible" exactly means
> and how your change fixes that

**Comment by digitalkaoz** [comment]
ok rebased and did some cleanup @greg0ire

**Comment by greg0ire** [comment]
Thanks a lot!

**Comment by OskarStark** [comment]
great job @digitalkaoz 

thanks!

**Comment by digitalkaoz** [comment]
a merge would be good so i can remove it locally here

**Comment by Soullivaneuh** [comment]
This merge needs a more serious review with manual tests IMO.

BTW, could you add some unit tests related to your fixed issue?

**Comment by digitalkaoz** [comment]
The `AdminHelper::appendFormFieldElement` is (as it is right now) an untestable beast, maybe thats the reason why 0 tests exists for it ;) ... i tried it the last two hours. it would need a major refactoring, but i dont see that in the scope of this bugfix...nevermind i added a test for the other public methods i changed...

**Comment by Soullivaneuh** [comment]
Test failed because of CS: https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/68830915#L378

You can fix it by running `make cs` command.

**Comment by digitalkaoz** [comment]
mh i did but not with the provided make command, nevermind, removed it

**Comment by robhunt3r** [comment]
@Soullivaneuh Please merge this as we are using it on our project, working perfectly but we want some of the master updates, and we will loose this fix... We would like to use master with this PR!

Thanks. GJ @digitalkaoz

**Comment by Soullivaneuh** [comment]
> but we want some of the master updates, and we will loose this fix... We would like to use master with this PR!

@robhunt3r waiting for this merge, you can, as a workaround: 

* Fork the repo
* Create a branch `master-fixes`
* Merge branches with fixes you want from forks
* Rebase it from master if needed
* Use is as a VCS repository

@digitalkaoz Can you please squash your commit?

I prefer @rande confirmation about working code and BC check before merge it.

**Comment by robhunt3r** [comment]
@Soullivaneuh The problem is, I'm not a git expert, well, not even an advanced user, just pull/merge/push from my own branches, so when I tried to merge @digitalkaoz fork into my form from sonata@master, I messed it up so... I just forget about it :P

Thanks for the fast reply, and let's see if everything pass the checks and we can have this sooner or later ^^

**Comment by greg0ire** [comment]
> so when I tried to merge @digitalkaoz fork into my form from sonata@master, I messed it up so...

too bad, you were probably not that far from a solution. Maybe make sure that your fork is up to date with the latest changes from sonata@master, and try again.

**Comment by digitalkaoz** [comment]
ok squashed and rebased...should be mergable now. i didnt hear anything on this for months, so i thought nobody uses the Sonata-Admin like me.

@robhunt3r you could even use my branch in composer (https://getcomposer.org/doc/05-repositories.md)

**Comment by robhunt3r** [comment]
@greg0ire Yeah I was doing everything wrong. I've tried now and worked at first attempt, maybe I was lazy that day that everything went wrong :P

@digitalkaoz We needed your patch about 15 minutes after creating our project haha, it was a must and found your fork when we were trying to code it ourselves, then we just used VCR with your branch and everything worked, but we needed some new stuff (that now we got) that was on master.

Now that everything is up to date for us, maybe I will do a PR with some things we added to sonata that we thought were necessary.

**Comment by greg0ire** [comment]
> @greg0ire Yeah I was doing everything wrong. I've tried now and worked at first attempt, maybe I was lazy that day that everything went wrong :P

Congrats, your are now officially an "advanced user"

**Comment by OskarStark** [comment]
sounds like the same problem to me:
https://github.com/sonata-project/SonataMediaBundle/blob/e81b9bc228e77d838caf4e6c8e4e61758cc29bce/Admin/GalleryAdmin.php#L132

https://github.com/sonata-project/SonataPageBundle/blob/d9ff145f6d05ee9cc17c4f2b906a102b2e339bc9/Admin/BaseBlockAdmin.php#L120

**Comment by robhunt3r** [comment]
@OskarStark That sounds more like a problem with related entities where adders/setters are not being called correctly. 

One way to fix is doing that on every Admin's preUpdate, but I think the best way is to set cascades correctly and of course using  `'by_reference' => false` on our forms. Another way could be to add the inverse method in our entity

`public function addFoo(Foo $foo) {
      $foo->setBar($this);
      $this->foo[] = $foo;
}`

But this PR fixes other problem, which is rendering nested forms, which wasn't possible in Sonata in more than 1 nesting level.

**Comment by OskarStark** [comment]
Thank you @robhunt3r for the info :+1:

**Comment by fivetide** [comment]
Is there anything holding this PR from being merged? If so i would gladly volunteer to move this forward, as i am in desperate need of this fix..

**Comment by OskarStark** [comment]
@robhunt3r 
> Now that everything is up to date for us, maybe I will do a PR with some things we added to sonata that we thought were necessary.
PR's are welcome :smile: 

@Soullivaneuh @rande IMO there is no reason why we should not merge this PR. We have tests and user feedback that this works.

**Comment by wallacio** [comment]
@digitalkaoz I'm not sure if I've found a case where this doesn't work, or if I've missed something.

I'm using SonataAdminBundle 2.3. Rather than fork and use it as a repo in composer, I've extended SonataAdminBundle (using easy extends) and partly overridden Admin/AdminHelper.php and Utils/FormBuilderIterator.php to include your edits, and redefined sonata.admin.helper service to use this extended class. This works, or at least I know it's using the extended class.

I've got an entity 'Loan', which can have many 'Securities' which in turn can have many 'Security Documents'. A 'Security Document' is a join table for 'Security' and 'Document'. 

loan-security-doc

Excerpts from the Admins for this relation is as follows:

LoanAdmin.php:
`->add('securities', 'sonata_type_collection', ...)`

SecurityAdmin.php:
`->add('securityDocuments','sonata_type_collection', ....)`

SecurityDocumentAdmin.php:
`->add('document','sonata_type_model_list')`

DocumentAdmin.php is a basic name/description/file admin.

This renders the following in the LoanAdmin page:
security-admin

Clicking _Add New_ for Document throws the same error,
"Call to a member function getName() on null"

I added some debug to AdminHelper::appendFormFieldElement to see what's happening here.
```
dump($formBuilder);		
dump($childFormBuilder);
dump($elementId);
```
dump

So, $childFormBuilder is definitely null, but why? Is it
a) because $formBuilder only contains 1st level children (i.e. there are no child objects of 'securities')
b) elementId contains `_0_` (index of the child for many to one, presumably; if there are two 'Security' entities associated with the Loan, the element contains `_1_` )

I appreciate that your PR is against a different branch (master, vs 2.3) but I didn't see any reason why doing what I've done wouldn't work. I've tried to keep this as brief as possible without posting a load of code, but if this isn't enough to get your head round I'll obviously provide more detail!

**Comment by digitalkaoz** [comment]
Have you tried with the Master branch?

wallacio <notifications@github.com> schrieb am Do., 12. Nov. 2015 16:59:

**Comment by wallacio** [comment]
well, no - I'm not that keen on using dev branches in production applications so I'd be keen to avoid that unless absolutely necessary!

**Comment by digitalkaoz** [comment]
Just for testing if your issue remains

wallacio <notifications@github.com> schrieb am Do., 12. Nov. 2015 17:45:

**Comment by wallacio** [comment]
Yeah, I appreciate that - but for me to go to dev-master means about 4 million* major dependency updates including some which just aren't stable (I'm using symfony-cmf bundles too)

*exaggeration

**Comment by wallacio** [comment]
Can I ask someone who is using this solution to help me with a bit of debug? If you have a relationship like this (A - B - C - D, where B and C are collections), can you paste in a dump($formBuilder) to let me see how deep the nesting of 'children' goes? My guess is that it's not working for me because AdminHelper cannot see any children below B (as per dump in my previous post), but a dump of your working environment will confirm this.

**Comment by digitalkaoz** [comment]
i tested it here...and it worked till an infinite level...

**Comment by wallacio** [comment]
ok, thanks - I'm just trying to work out why no children show in the dump of $formBuilder. I am trying to work out where, from receiving the request, the levels are created (and in my case, why no children appear below B) even before the patch you authored can process the tree.

**Comment by wallacio** [comment]
Ok - I've painfully stripped out any dependencies from my application so that I could try out dev-master, and integrate your changes. No difference, unfortunately - but I don't think the issue is with your fix.

For whatever reason, Admin/FormBuilder isn't correctly building the hierarchy (children) correctly - a dump of $formBuilder in appendFormFieldElement shows it's not there - so there's no way the Iterator is going to be able to find the nested entity further down the hierarchy. I've tried to trace this through as best I could, but I'm not clever enough. I do know it's in the form, and it's being passed in the request.

I don't know if my issue is a bug in SonataAdminBundle, misconfiguration or something else but I'd appreciate a bit of help. Happy to open this as a separate issue if appropriate, I just don't know if it's related to this or is something different.

**Comment by fivetide** [comment]
I dont mean to nag, but i would still love to see this merged...

**Comment by OskarStark** [comment]
ping @rande 

@digitalkaoz can you pleases rebase your PR?

**Comment by digitalkaoz** [comment]
ill rebase when somebody is willing to merge

**Comment by fivetide** [comment]
I made a PR (#3457) from a rebased version. So nothing should hold us back now :)

**Comment by Soullivaneuh** [comment]
> I made a PR (#3457) from a rebased version. So nothing should hold us back now :)

@fivetide I would prefer to stay on the main one.

> ill rebase when somebody is willing to merge. i did it multiple times in the past, nobody merged it, so lets wait if somebody is willing to merge and fix this ugly bug

@digitalkaoz I'm sorry for this. We do what we can with our freetime.

Please do a rebase and ping me. I'll try to test it at least this week-end / next-week.

Thanks for your work.

I would like to have @rande opinion for this too.

**Comment by greg0ire** [comment]
> @fivetide I would prefer to stay on the main one.

@fivetide : If you manage to rebase this, you can ask @digitalkaoz to `reset --hard` his branch on your version, by following this steps (if he is willing, of course) : 

1. add your fork as a remote
2. fetch your branches
3. reset on your branch

**Comment by digitalkaoz** [comment]
Thats not a Problem of understanding rebase ;) but i like to hear if it
probably will be merged or not. Otherwise the effort is useless

Grégoire Paris <notifications@github.com> schrieb am Mi., 2. Dez. 2015
10:06:

**Comment by greg0ire** [comment]
> Thats not a Problem of understanding rebase ;)

I didn't imply that. I implied it could be painful and time-consuming, so if other want this badly, they can give their time instead of yours ;)

**Comment by fivetide** [comment]
> @fivetide I would prefer to stay on the main one.

No problem. I am just trying to help here.

**Comment by OskarStark** [comment]
i am :+1: for merging this PR we have tests and it looks ok to me, but i'm not so familar with this topic, so @rande should say :+1: or :-1:

**Comment by digitalkaoz** [comment]
@OskarStark rebased...the failing test on 5.3 (lowest deps) is not triggered by me...so @rande ?

**Comment by nielvrom** [comment]
I'm working on version 2.3, how can I implement this fix in my project?

**Comment by wallacio** [comment]
Is this fixed by #3553 ?

**Comment by cosf87** [comment]
@wallacio I think so. Now nested associations work fine for me.

**Comment by core23** [comment]
Are you still working on this? Please rebase or close this PR @digitalkaoz

**Comment by digitalkaoz** [comment]
I rebased it several times. Nobody wants to merge it but every user wants
it, so i guess its not worth the work...

Christian Gripp <notifications@github.com> schrieb am Fr., 15. Apr. 2016,
18:57:

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Comment by sujayjaju** [comment]
Can this issue be reopened?
This would be extremely handy.

Right now, Adding a new 'C' to 'B' in Form 'A' results in error 
```Call to a member function getAssociationAdmin() on null```

**Comment by digitalkaoz** [comment]
@sujayjaju sadly nobody responsible for SonataAdmin is willing to have bugs fixed...i wont put any afford into this PR again... i would recommend to move away from SonataAdmin!

**Comment by greg0ire** [comment]
> sadly nobody responsible for SonataAdmin is willing to have bugs fixed
WTF? Explain this : https://github.com/sonata-project/SonataAdminBundle/pulse/monthly

**Comment by greg0ire** [comment]
@Soullivaneuh all emotions aside, I think we should just merge, and revert if there is any issue with this.

**Comment by digitalkaoz** [comment]
@greg0ire sorry for my emotions. but i felt very sad. as it was an obvious bug, a lot of people cried for merge, nobody did. i rebased serveral times, did everything to get this merged. nothing happend. so i lost my feelings for SonataAdmin. I thought maybe this was solved in the meantime, appearently not, that doesnt give me the feeling in this project back...feel free to do whatever you want with my PR...

**Comment by greg0ire** [comment]
I re-read it all and I'm starting to understand how you are feeling. We are going to try our best to avoid that kind of situation.

**Comment by greg0ire** [comment]
I think the best course of action would be for @sujayjaju to carry this in a new PR, because this is long to read, unclear, etc. Also, the PR template is missing (not your fault @digitalkaoz , I think that PR it just very old).

**Comment by digitalkaoz** [comment]
i would say its ancient, as the bug still is...

**Comment by Soullivaneuh** [comment]
@digitalkaoz To be clear: I did say the PR need manual test because at this time I see a quite big modification: https://github.com/sonata-project/SonataAdminBundle/pull/3056#issuecomment-116668763

To be even more clear: This is an advice, with a `IMO` BTW. "This need" does not mean "I'll do it"  and clearly at this moment I didn't get the time at all and I'm not paid for that.

Nobody didn't get this manual test either apparently.

So yes I did be able to just click on the merge button. And maybe got some insults because "OMG sonata is broken please fix". So no, I didn't get this responsibility and I didn't have the possibility to test it manually at this time.

To conclude: This PR as been close as many other because of branch refactoring, so this is not a refusal. I think the generic message was enough clear.

So now feel free to carry-on a new PR on the right branch. If you don't want, feel also free too. Maybe another guy will do it, or not. This is how open-source work.

Regards.

**Comment by Soullivaneuh** [comment]
Also : On this PR I asked @rande confirmation just because I was not sure about this.

Again, I prefer waiting month or years merging a PR than introduce even more bug and BC breaking (and this was like that before one sonata...). Do what you want on your side.

Last words: if a @sonata-project/core member is concerned by this issue and OK to do a manual test, it would be great.

**Comment by digitalkaoz** [comment]
@Soullivaneuh me and a lot of other people tested it manually. we have tests and all. the PR was perfectly ready for merge, nobody did, and in the end it was closed due to some branch refactoring...

i gave you a fix, you didnt wanted the fix. so thats ok for me, its open-source...but i wont put any afford into sonata projects again or use them...thats open source too...

as i said, feel free to do whatever you want with the fix

**Comment by Soullivaneuh** [comment]
@digitalkaoz I did understand your concern, don't worry.

As I said, I just did say my advises on this PR, I didn't reject it.

It was in 2015, the PR was sadly closed due to the automatic refactor branch and now we have many mergers.

@sujayjaju or another, feel free to open a new PR if you want to.

**Comment by sujayjaju** [comment]
I will try to give it a shot - but I am not sure since I don't understand the flow well enough.

**Pull request closed without merging**
