### PR TITLE
[WIP] Override list__action templates from config file

### PR DESCRIPTION
**Pull request by Soullivaneuh**
PR related to #2586.

The goal is to permit `list__action.html.twig` and `list__action_*.html.twig` override from config file.

 - [ ] Permit list templates options
 - [ ] Update the documentation

@rande: I'm a little confusing. I passed list_action template on Configuration and compiler pass. How to pass it on `ListBuilder` classes?

Thanks.

### CODE REVIEW

**Comment by rande** [comment]
you can access to those value with ``$admin->getTemplate('template_name')``

**Comment by Soullivaneuh** [comment]
Already tried but no.

Here the template available on my ListBuilder:

```
array (size=22)
  'array' => string 'SonataAdminBundle:CRUD:list_array.html.twig' (length=43)
  'boolean' => string 'SonataAdminBundle:CRUD:list_boolean.html.twig' (length=45)
  'date' => string 'SonataIntlBundle:CRUD:list_date.html.twig' (length=41)
  'time' => string 'SonataAdminBundle:CRUD:list_time.html.twig' (length=42)
  'datetime' => string 'SonataIntlBundle:CRUD:list_datetime.html.twig' (length=45)
  'text' => string 'SonataAdminBundle:CRUD:list_string.html.twig' (length=44)
  'textarea' => string 'SonataAdminBundle:CRUD:list_string.html.twig' (length=44)
  'email' => string 'SonataAdminBundle:CRUD:list_string.html.twig' (length=44)
  'trans' => string 'SonataAdminBundle:CRUD:list_trans.html.twig' (length=43)
  'string' => string 'SonataAdminBundle:CRUD:list_string.html.twig' (length=44)
  'smallint' => string 'SonataIntlBundle:CRUD:list_decimal.html.twig' (length=44)
  'bigint' => string 'SonataIntlBundle:CRUD:list_decimal.html.twig' (length=44)
  'integer' => string 'SonataIntlBundle:CRUD:list_decimal.html.twig' (length=44)
  'decimal' => string 'SonataIntlBundle:CRUD:list_decimal.html.twig' (length=44)
  'identifier' => string 'SonataAdminBundle:CRUD:list_string.html.twig' (length=44)
  'currency' => string 'SonataIntlBundle:CRUD:list_currency.html.twig' (length=45)
  'percent' => string 'SonataIntlBundle:CRUD:list_percent.html.twig' (length=44)
  'choice' => string 'SonataAdminBundle:CRUD:list_choice.html.twig' (length=44)
  'url' => string 'SonataAdminBundle:CRUD:list_url.html.twig' (length=41)
  'html' => string 'SonataAdminBundle:CRUD:list_html.html.twig' (length=42)
  'user' => string 'admin/CRUD/list_user.html.twig' (length=30)
  'users' => string 'admin/CRUD/list_users.html.twig' (length=31)
```

Am I missing something?

**Comment by rande** [comment]
Hum ... I guess it is not the correct list ;)

**Comment by Soullivaneuh** [comment]
Indeed I didn't see the "From the admin". But:

```php
    public function buildActionFieldDescription(FieldDescriptionInterface $fieldDescription)
    {
        if (null === $fieldDescription->getTemplate()) {
            $fieldDescription->setTemplate($fieldDescription->getAdmin()->getTemplate('list__action'));
        }

        // [...]

        return $fieldDescription;
    }
```

Gave me the following error:

```
Error: Call to a member function getTemplate() on a non-object
```

Btw, if I understand well, I have to do the same thing on each doctrine bundle `ListBuilder`:

 * DoctrineORM: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Builder/ListBuilder.php#L165
 * DoctrineMonboDB: https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/master/Builder/ListBuilder.php#L160
 * https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/master/Builder/ListBuilder.php#L184

It's excatly the same code, too bad to have code duplication.

What about factoring it on sonata-admin with an `AbstractListBuilder` for example?

**Comment by Soullivaneuh** [comment]
ping @rande

**Comment by core23** [comment]
Any news on the @Soullivaneuh @rande

**Comment by Soullivaneuh** [comment]
Rebased on #3770.

**Pull request closed without merging**
