### PR TITLE
updated bin paths

### PR DESCRIPTION
**Pull request by codebakery-ch**
symfony 3 changed console paths to /bin

- [x] Update the documentation

## Subject

Simple fix for the documented path to the bin/console

### CODE REVIEW

**Comment by greg0ire** [comment]
> Added some `Class::newMethod` to do great stuff

Please fill the template

**Comment by greg0ire** [comment]
@OskarStark yeah but we decided what we show by default should be sf3, right? I remember discussing exactly that with you on another PR.

**Comment by greg0ire** [comment]
See https://github.com/sonata-project/dev-kit/issues/194

**Comment by codebakery-ch** [comment]
Sorry for the mess in this ticket! Didn't see the required markdown... Won't happen again!

**Comment by greg0ire** [comment]
~~Please change the changelog so that it looks like a human readable changelog (see http://keepachangelog.com/en/0.3.0/). What you put is a diff.~~ I think a PR on the docs does not warrant a changelog (users are not interested in small changes in the docs).

**Comment by codebakery-ch** [comment]
@greg0ire do I have to do anything else or is that ok for now? I was just seeing it and thought to give a fix...

**Comment by greg0ire** [comment]
You have to remove the changelog, and the items in your todo list that are not relevant (otherwise, reviewers might not even review this and dismiss it as unfinished).

**Comment by greg0ire** [comment]
@OskarStark if you agree, please dismiss your review so this can get merged.

**Comment by greg0ire** [comment]
ping @OskarStark

**Comment by nykopol** [comment]
I think that if we do this change it must be homogeneous across the documentation. A `git grep "app/console"` show  that there are some left.

**Comment by codebakery-ch** [comment]
I updated all the docs where I could find this path, also there was one app/cache/...env.../classes.php which I changed to var/cache/...env.../classes.php

**Comment by greg0ire** [comment]
I can't see anything new, did you forget to push?

**Comment by codebakery-ch** [comment]
sorry, pushed to wrong branch. I'm not the best at GitHubing ;) should be ok now.

**Comment by core23** [comment]
Thanks @codebakery-ch

**Comment by greg0ire** [comment]
Thanks @codebakery-ch ! @core23 please clean the commit message when you squash merge requests, https://github.com/sonata-project/SonataAdminBundle/commit/d6cb43652852b185f38bdb84cc8c8cb29226d42d does not look too good

**Pull request merged**
