### PR TITLE
Add support for timezone on datetime list format

### PR DESCRIPTION
**Pull request by lightglitch**
If you have a system that stores all dates in UTC, when a user is editing objects, she wants to see his local date, not the UTC date.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Please next time, correct your history instead of opening new PR.

Old one: #2976.

**Comment by Soullivaneuh** [comment]
@lightglitch Could you explain me how I can get it working?

I added:

```php
->add('usedAt', null, [
    'timezone' => 'Asia/Hong_Kong',
])
```

But the displayed time is not changed. Did I miss something?

**Comment by lightglitch** [comment]
@Soullivaneuh You need to define the format also.
Maybe I should change it to support without depending on the format but I need to check if the Twig date function supports it.

**Comment by lightglitch** [comment]
@Soullivaneuh It should be ok now.

**Comment by Soullivaneuh** [comment]
I'm sorry but I don't see any difference.

**Comment by lightglitch** [comment]
Strange because it's passing the tests, I'm going to check it.

**Comment by Soullivaneuh** [comment]
My bad, wrong section configuration for me. :-)

I'll test again.

**Comment by Soullivaneuh** [comment]
Works like a charm.

Juste a question: Could not be possible to set this option on general config? Better, detect user timezone?

**Comment by lightglitch** [comment]
You can in 2.7 (http://symfony.com/blog/new-in-symfony-2-7-default-date-and-number-format-configuration) but not in previous versions.
And you can also detect the user timezone and set the twig global option using a request listener but sometimes you need it to configure manually.

**Comment by Soullivaneuh** [comment]
Okay, good to know.

**Comment by Soullivaneuh** [comment]
Thank you @lightglitch. :+1:

**Pull request merged**
