### PR TITLE
Move fieldDescription class/interfaces

### LINKED ISSUE #6933: Move BaseFieldDescription, FieldDescriptionCollection, FieldDescriptionInterface and FieldDescriptionRegistryInterface to FieldDescription directory
## Feature Request

Now we have a FieldDescription directory, all related class should be inside.

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because BC.

Closes #6933

## Changelog

```markdown
### Added
- Added some `Class::newMethod()` to do great stuff.

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@sonata-project/contributors I'm not sure how to do it. Is it the right way to be BC ? Should it be the opposite ?

**Comment by VincentLanglet** [comment]
Maybe it's easier to do it on master...

**Comment by phansys** [comment]
See https://dev.to/greg0ire/how-to-deprecate-a-type-in-php-48cf.

**Comment by VincentLanglet** [comment]
> See https://dev.to/greg0ire/how-to-deprecate-a-type-in-php-48cf.

When I read this, I clearly think it's easier to do the PR on master instead...

**Comment by VincentLanglet** [comment]
Closing in favor of https://github.com/sonata-project/SonataAdminBundle/pull/6940

**Comment by franmomu** [comment]
IMO we should try to do it on `3.x` to provide an easy upgrade path to the users, I'll see if I can do it eventually.

**Pull request closed without merging**
