### PR TITLE
Removed associated_tostring, added 2 string types and wrote more info about `code` option

### PR DESCRIPTION
**Pull request by idchlife**
Made new commits in master. So. Should I squash them or leave as they are?

### CODE REVIEW

**Comment by greg0ire** [comment]
I think the 2 first commits should be squashed together : both stem from the deprecation of `associated_property`. And that's it. 3 commits for 3 unrelated things. Less commits would be a sin.

**Comment by idchlife** [comment]
done.

**Comment by greg0ire** [comment]
Good to merge IMO. Ping @OskarStark @core23

**Comment by OskarStark** [comment]
Thank you @idchlife and @greg0ire :+1:

**Pull request merged**
