### PR TITLE
Add methods DatagridMapper::getDatagrid and ListMapper::getList

### PR DESCRIPTION
**Pull request by hason**
I want to reorder columns in admin extension, but a mapper doesn't have a method to obtain columns from list.

```php
    public function configureListFields(ListMapper $listMapper)
    {
        $list = $listMapper->getList();
        $keys = array_keys($list->getElements());
        // ...
        $listMapper->reorder($keys);
    }
```

### CODE REVIEW

**Comment by OskarStark** [comment]
:+1:  could you add a test case for this and add a little info to the docs, maybe it could help other users?

**Comment by core23** [comment]
ping @hason

**Comment by OskarStark** [comment]
this are only getter, i think we can merge them without tests

what do you think @core23 @Soullivaneuh @greg0ire ?

**Comment by greg0ire** [comment]
@ju1ius : maybe we should start enforcing php docblock descriptions manually, and see how it goes? What would you propose for these getters? @Soullivaneuh : should the getters be final?

**Comment by Soullivaneuh** [comment]
> @Soullivaneuh : should the getters be final?

I think yes.

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
