### PR TITLE
Bump "knplabs/knp-menu-bundle" to ^3.0

### PR DESCRIPTION
**Pull request by dmaicher**
## Subject

I am targeting this branch, because this will allow to add compatibility with Symfony 5 in 3.x branch.

Replaces https://github.com/sonata-project/SonataAdminBundle/pull/6275 and https://github.com/sonata-project/SonataAdminBundle/pull/6276

See https://github.com/sonata-project/SonataAdminBundle/pull/6263#issuecomment-678780876

## Changelog

```markdown
### Changed
- Bump "knplabs/knp-menu-bundle" to ^3.0.
```

### CODE REVIEW

**Comment by OskarStark** [comment]
@dmaicher I have an issue after using this one:

[prod] Aug 28 14:56:08 |CRITI| REQUES Uncaught PHP Exception TypeError: “Argument 1 passed to Knp\Menu\MenuFactory::createItem() must be of the type string, null given, called in /app/vendor/sonata-project/admin-bundle/src/Menu/Provider/GroupMenuProvider.php on line 190” at /app/vendor/knplabs/knp-menu/src/Knp/Menu/MenuFactory.php line 2

Any idea 💡?

**Comment by dmaicher** [comment]
@OskarStark so the `$name` passed to `MenuFactory::createItem` is null? That seems odd :confused: 

What's the full stack trace?

**Comment by OskarStark** [comment]
That sounds correct, let me check that tomorrow 👍🏻 thank you for the fast response

**Comment by OskarStark** [comment]
Hmm, this is my config:

```yaml
sonata_admin:
    title: 'DROPSy'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

        groups:
            home:
                on_top: true
                label: Home
                label_catalogue: messages
                icon: '<i class="fa fa-home"></i>'
                items:
                    - route: app_default_index
                      label: ~
            sync:
                on_top: true
                label: Sync Jobs
                icon: '<i class="fa fa-dropbox"></i>'
                label_catalogue: messages
                items:
                    - App\Admin\SyncJobAdmin
            ignored_releases:
                on_top: true
                label: Ignored Releases
                icon: '<i class="fa fa-window-close"></i>'
                label_catalogue: messages
                items:
                    - App\Admin\IgnoredReleaseAdmin

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
```

and 

```yaml
    App\Admin\SyncJobAdmin:
        arguments:
            - ~
            - App\Entity\SyncJob
            - App\Controller\Admin\SyncJobAdminController
        tags:
            - { name: sonata.admin, manager_type: orm, label: SyncJob }

    App\Admin\IgnoredReleaseAdmin:
        arguments: [~, App\Entity\IgnoredRelease, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Ignored Releases }
```

Could not get the full stack trace now. Maybe it is because of `on_top` config option? 🤔

**Comment by dmaicher** [comment]
`label: ~` seems suspicious?

**Comment by OskarStark** [comment]
What do you mean? 🧐

**Comment by VincentLanglet** [comment]
It means "label: null" to me.
Which could be the issue

**Comment by dmaicher** [comment]
> What do you mean? monocle_face

I mean here

```yaml
groups:
    home:
        ...
        items:
            - route: app_default_index
              label: ~
```

the `label: ~` could be the problem. Maybe try setting a label :blush:

**Comment by OskarStark** [comment]
Hmm 🤔 will try

**Comment by OskarStark** [comment]
That fixes the problem 👍

**Comment by OskarStark** [comment]
But if you check the docs:
https://symfony.com/doc/master/bundles/SonataAdminBundle/cookbook/recipe_knp_menu.html#add-a-custom-controller-entry-in-the-menu

one should be able to remove the `label` entirely, this seems to be a problem now 🤔

**Comment by VincentLanglet** [comment]
What is this label used for ? Should we add a null check or use a default value when it's null ?

**Comment by VincentLanglet** [comment]
I made https://github.com/sonata-project/SonataAdminBundle/pull/6350 @OskarStark 
Can you confirm it works for you ?

**Pull request merged**
