### PR TITLE
Run the tests on php 7.3

### PR DESCRIPTION
**Pull request by greg0ire**
This is a proof PR, do not merge.

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Why not merge? it is in allowed_failure?

**Comment by greg0ire** [comment]
Because It will be introduced again by dev-kit. We could merge, it would be harmless, but then if we don't merge the PR on dev-kit, it will remove it, and then re-add it later when this is merged… confusing.

**Comment by kunicmarko20** [comment]
I thought this was dev-kit, ignore me...

**Comment by OskarStark** [comment]
https://github.com/sonata-project/dev-kit/pull/430 is merged

**Pull request closed without merging**
