### PR TITLE
Add option "show_in_dashboard" in configuration.

### PR DESCRIPTION
**Pull request by tim96**
Add option "show_in_dashboard" in configuration.
@OskarStark I create a new one PR, as you suggest here https://github.com/sonata-project/SonataAdminBundle/pull/3159#issuecomment-139980380

### CODE REVIEW

**Comment by OskarStark** [comment]
:+1:  thank you @tim96 

@Soullivaneuh @rande do we need more documentation?

**Comment by Soullivaneuh** [comment]
@tim96 stop me if I'm wrong but this new option is never used. Where is the process?

> do we need more documentation?

@OskarStark yes please, always for new feature.

**Comment by tim96** [comment]
> @tim96 stop me if I'm wrong but this new option is never used. Where is the process?

I think what options from services for admin service, and options from config parameters are the same. @Soullivaneuh Am I wrong?

**Comment by Soullivaneuh** [comment]
Possibly I don't know, have to look deeper.

But in anyway, this option as no reaction with code. And test are needed too.

**Comment by tim96** [comment]
> Possibly I don't know, have to look deeper.

@Soullivaneuh ok, I will try.

> But in anyway, this option as no reaction with code. 

Because, it's not my option. I only add description about this option, as @OskarStark suggest, because it is very important option IMO, a lot of question about it exists on SO, and no one mention in documentation. And I want to add some description in doc files about it.

**Comment by Soullivaneuh** [comment]
I don't undersand: this option is **added** on `Configuration`: https://github.com/sonata-project/SonataAdminBundle/pull/3251/files#diff-850942b3ba24ab03a40aaa81b6152852R126

Why are you saying that this option already exists? Where?

**Comment by tim96** [comment]
I see it here: https://github.com/sonata-project/SonataAdminBundle/blob/master/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L77
As I said before, I think what options from services for admin service, and options from config parameters are the same. But I was wrong, they are not the same, sorry @Soullivaneuh. It was small misunderstanding after @OskarStark comment, yesterday.

**Pull request closed without merging**
