### PR TITLE
Updates installation.rst, changes the default binary path in command samples

### PR DESCRIPTION
**Pull request by marijnz0r**
The console file is located in the bin folder and not in the app folder.

### CODE REVIEW

**Comment by core23** [comment]
Nope, only if you're using symfony 3.0

**Comment by marijnz0r** [comment]
> Nope, only if you're using symfony 3.0
That's true, that's why I created the pull request. I'm using Symfony 3.0. I want the documentation to be up to date.

**Comment by greg0ire** [comment]
Please change the commit message subject to something like use "the default binary path in command samples". You can keep the commit message body, it is good.

**Comment by marijnz0r** [comment]
@greg0ire Changed the commit message subject.

**Comment by greg0ire** [comment]
No, you change the PR subject, the commit message subject still is "installation.rst", please change that, this is what will show up in git's history.

**Comment by marijnz0r** [comment]
Ok, I never used GitHub for making pull requests, can I do this in the online editor?

**Comment by greg0ire** [comment]
I'm afraid you can't.

You have to checkout your branch locally, then use `git commit --amend` to change the commit message , adn then `git push --force` to overwrite this PR.

**Comment by marijnz0r** [comment]
Thanks for your quick responses, I will try this now.

**Comment by greg0ire** [comment]
> Thanks for your quick responses

Well, thanks for yours :)

**Comment by marijnz0r** [comment]
I tried `git push --force`, but I got `"fatal: unable to access 'https://github.com/sonata-project/SonataAdminBundle.git/': The requested URL returned error: 403"`

**Comment by greg0ire** [comment]
You're trying to force push to the main repository. Try pushing to your repo : 

```
git remote -vvv
git push --force your_remote
```

**Comment by greg0ire** [comment]
`git remote -vvv` will list your remotes. Ask for help if you do not see your repo in it.

**Comment by marijnz0r** [comment]
I appreciate your help, but could you hook me up to a guide or anything like that where all of this is explained, I am willing to learn it all.
`git remote -vvv` gives me:
`origin  ssh://git@github.com/sonata-project/SonataAdminBundle.git (fetch)
origin  ssh://git@github.com/sonata-project/SonataAdminBundle.git (push)`

**Comment by greg0ire** [comment]
Ok so your local repo does not know about your fork. Just do

```
git remote add fork git@github.com:marijnz0r/SonataAdminBundle.git
git push --force fork patch-1
```

**Comment by greg0ire** [comment]
Here is a guide about remotes : https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes

**Comment by marijnz0r** [comment]
Thank you very much for your help! I managed to work it out. At first I didn't know the whole repository was cloned into my account. I'm new to GitHub, but I'm trying to learn the ins and outs. Thanks again.

**Comment by greg0ire** [comment]
Well a big difference with SVN or things like that is that when you clone, you get the whole history : this can be quite long, but then other operation like looking up the history are way faster

**Comment by greg0ire** [comment]
I think the sf3 way can indeed be the default way. LGTM

**Pull request merged**
