### PR TITLE
Spanish and Catalan Translations

### PR DESCRIPTION
**Pull request by jordisala1991**
I am targeting this branch, because this only changes translations.

## Changelog

```markdown
## Fixed
- Improve Catalan and Spanish translations
```

## To do

- [x] Check everything is OK with those new translations

## Subject

Updated Spanish and Catalan translations. Some of them were wrong, specially in catalan, they looked like were generated using google translate.

### CODE REVIEW

**Comment by jordisala1991** [comment]
Ready to review

**Comment by greg0ire** [comment]
Your changelog misses a header

**Comment by jordisala1991** [comment]
Done 👍

**Comment by core23** [comment]
Thanks @jordisala1991 👍

**Pull request merged**
