### PR TITLE
DevKit updates for 3.x branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by OskarStark** [comment]
@Soullivaneuh only coveralls is failing

**Comment by greg0ire** [comment]
How can a change in a markdown file make it fail?

**Comment by OskarStark** [comment]
> How can a change in a markdown file make it fail?

I don't know... 😢

**Comment by greg0ire** [comment]
It shows way more files than it is supposed to : https://coveralls.io/jobs/14920326 @Soullivaneuh , any idea ?

**Comment by Soullivaneuh** [comment]
I opened an issue: https://github.com/lemurheavy/coveralls-public/issues/790

Let's merge this one for now and see if it happens again.

Later, I'll check if Coveralls has a public api to change settings. In this case, I'll check for the coverage decrease threshold, even if I don't like this...

**Pull request merged**
