### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by Kolyunya**
I am targeting this branch, because this patch doesn't break the BC.

### CODE REVIEW

**Comment by greg0ire** [comment]
Why not contribute that on the other PR?

**Comment by Kolyunya** [comment]
I prefer posting atomic PRs as soon as find something what can be fixed.

**Comment by greg0ire** [comment]
By that logic, you could make one PR for the first example in that PR and one for the second one. PR don't even need to be atomic, you could have one PR with one commit for missing curly braces and one for missing use statements.

I'm not sure, are you aware that you can add more commits to an existing PR?

**Comment by Kolyunya** [comment]
> you could make one PR for the first example in that PR and one for the second one.

I'd consider doing that. Thank you!

**Comment by jordisala1991** [comment]
Thanks @Kolyunya

**Comment by Kolyunya** [comment]
@jordisala1991 it's my pleasure.

**Pull request merged**
