### PR TITLE
feat(admin): add object name to ajax response for edit

### PR DESCRIPTION
**Pull request by qsomazzi**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
What the goal of this PR? Is that a bugfix? A feature?

Could you provide a concrete case?

**Comment by qsomazzi** [comment]
The goal of this PR is to improve the AJAX response return by the CRUDController to make it easier to manipulate with Javascript.

My concrete case : 
I'm developing a new dashboard feature, based on PageBundle Composer. I've got a functionnality which allow to manage containers settings. In thoose settings I can update the container's name.

With this PR, it's easier to update container's name on the left when I update the settings.
Screenshot will make it clearer i hope : 
capture d ecran 2015-08-04 a 15 18 08

**Comment by rande** [comment]
+1, @Soullivaneuh for information @qsomazzi is working on a SonataDashboardBundle - teasing ...

**Comment by qsomazzi** [comment]
Spoiler alert :p

**Pull request merged**
