### PR TITLE
Manual merge

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
I did a really bad job fixing that conflict, it should be better now :)

**Comment by greg0ire** [comment]
Apparently not :/

**Comment by greg0ire** [comment]
@franmomu can you please give it a try? I'm getting `You have requested a non-existent parameter "sonata.admin.configuration.use_intl_templates".`

**Comment by franmomu** [comment]
> @franmomu can you please give it a try? I'm getting `You have requested a non-existent parameter "sonata.admin.configuration.use_intl_templates".`

Oops sorry I missed this message, let me try

**Comment by greg0ire** [comment]
Yup and it seems a merge up happened cleanly tonight, so we can close this.

**Pull request closed without merging**
