### PR TITLE
3.x into Master

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
I also would like to merge https://github.com/sonata-project/SonataAdminBundle/pull/6713 into 3.x and merge again 3.x into master.

**Comment by benrcole** [comment]
Hi Team, Is this merge awaiting a particular timeframe?

**Comment by VincentLanglet** [comment]
> Hi Team, Is this merge awaiting a particular timeframe?

I need a review from another contributor. And I'd like to merge  #6713  in order to fix the conflict again.
The main blocking point is that it's Christmas, people have a life. I'm sorry, be patient, we're doing our best :)

**Comment by benrcole** [comment]
Thanks for the reply, I more meant if there was a merge every 4 weeks or
something, will happily wait patiently, Merry Christmas everyone!

**Comment by VincentLanglet** [comment]
This is ready @sonata-project/contributors :)

**Review by OskarStark — APPROVED** [review]

**Review by wbloszyk — APPROVED** [review]

**Pull request merged**
