### PR TITLE
added prophecy into composer.json to enable tests to continue

### PR DESCRIPTION
**Pull request by Lyndonbazza**
I am targetting this branch, because I am testing it - and the tests failed on my branch.

Closes #{put_issue_number_here}

### Changed
Added phpspec/prophecy to composer dependencies

```
## Subject

Added phpspec/prophecy to composer dependencies

### CODE REVIEW

**Comment by greg0ire** [comment]
Prophecy comes with phpunit nowadays, right? Why would we need to add it as a dependency?

**Comment by greg0ire** [comment]
Oddly, the tests are failing now, probably related to this https://github.com/sonata-project/dev-kit/issues/197

But as you can see, the build passed for branch 3.x yesterday : https://travis-ci.org/sonata-project/SonataAdminBundle/branches

**Comment by Lyndonbazza** [comment]
Hi.

My actions were:

`git clone git@github.com:sonata-project/SonataAdminBundle.git
cd SonataAdminBundle/
php composer.phar install --prefer-source --dev
php vendor/bin/simple-phpunit`

And many tests failed. Am I running the tests incorrectly?

Thanks

Lyndon

**Comment by greg0ire** [comment]
No you're not. Currently, you're supposed to use the global phpunit : 

```sh
composer install
wget "https://phar.phpunit.de/phpunit.phar" --output-document="${HOME}/bin/phpunit"
chmod u+x "${HOME}/bin/phpunit"
phpunit
```

If you want to contribute this instructions, you can do so [here](https://github.com/sonata-project/dev-kit/blob/master/project/CONTRIBUTING.md), but please test them before ;)

**Comment by Lyndonbazza** [comment]
Thanks @greg0ire is this page:
https://sonata-project.org/contributing
in git?

**Comment by greg0ire** [comment]
Yes, but not on a public repo

**Comment by Lyndonbazza** [comment]
How woul I suggest changes to it?

**Comment by greg0ire** [comment]
You shouldn't. You should suggest changes to [this one](https://github.com/sonata-project/dev-kit/blob/master/project/CONTRIBUTING.md) instead, it is dispatched on every Sonata package, and I think (and hope) is more read than the one you are pointing to.

**Comment by Lyndonbazza** [comment]
Thanks for your help again @greg0ire 

I think it's worth adding a link to https://github.com/sonata-project/dev-kit/blob/master/project/CONTRIBUTING.md on https://sonata-project.org/contributing or some instructions on this.

I would like to help the project - I use it - and think this would help new contributors such as myself.

**Comment by greg0ire** [comment]
Just made an MR for this : https://gitlab.com/sonataproject/sonata-project.org/merge_requests/5 (restricted access)

**Pull request closed without merging**
