### PR TITLE
Set alias for sonata.admin.admin_exporter

### PR DESCRIPTION
**Pull request by toooni**
## Add FQN alias for admin exporter

Exporting doesn't work on master without setting the AdminExporter FQN as an alias. The following error occurs:

> Service "sonata.admin.admin_exporter" not found: even though it exists in the app's container, the container inside "..." is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "logger", "message_bus", "messenger.default_bus", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session", "sonata.admin.audit.manager", "sonata.admin.breadcrumbs_builder", "sonata.admin.object.manipulator.acl.admin", "sonata.admin.pool", "sonata.exporter.exporter", "translator" and "twig" services. Try using dependency injection instead.

I am targeting this branch, because that's where the issue is.

## Changelog

```markdown
### Fixed
- Fixed exporting from CRUDAdminController
```

### CODE REVIEW

**Review by dmaicher — APPROVED** [review]
Seems legit to me this fix so that [this](https://github.com/sonata-project/SonataAdminBundle/blob/master/src/Controller/CRUDController.php#L82) can be autowired correctly

**Comment by VincentLanglet** [comment]
I don't know why some of the service have alias for FQCN and some don't.
I think @phansys @franmomu know more about this.
Cf: https://github.com/sonata-project/SonataAdminBundle/pull/6615#discussion_r566833610

We should have some consistency.
Why is there an alias for the breadcrumbuilder, but I couldn't add one for the CRUDController ?

**Comment by franmomu** [comment]
> I don't know why some of the service have alias for FQCN and some don't.

In this case, it is used because of how [`ServiceSubscriberInterface::getSubscribedServices()`](https://github.com/symfony/symfony/blob/71ca1f3c71eca055ad04ab3274ecb0e890d3b2ee/src/Symfony/Contracts/Service/ServiceSubscriberInterface.php#L52) works.

> Why is there an alias for the breadcrumbuilder, but I couldn't add one for the CRUDController ?

I just said that based on some earlier discussion about this (I don't remember where) and [Symfony documentation about best practices in bundle services](https://symfony.com/doc/current/bundles/best_practices.html#services), IMO we should not add them (this is not preventing anyone to add them, just my opinion). 

About the alias we have, we could probably deprecate them if they are not used.

**Review by franmomu — APPROVED** [review]

**Comment by franmomu** [comment]
thanks @toooni!

**Pull request merged**
