### PR TITLE
DevKit updates for 3.x branch

### PR DESCRIPTION
**Pull request by SonataCI**
```markdown
## Fixed
- php 7.4 compatibility
```

### CODE REVIEW

**Comment by greg0ire** [comment]
As predicted, dev-kit recreated this PR with this very simple change that has very weird results (50 mn build)

**Comment by greg0ire** [comment]
I'm out of ideas… maybe let's wait for XDebug 2.9.0 to end up in Travis? https://derickrethans.nl/crafty-code-coverage.html

**Comment by franmomu** [comment]
I tried in `master` and also takes the same time, maybe is what you said about XDebug 2.9.0

**Comment by greg0ire** [comment]
Thanks for trying this, it gives more visibility one what could be the issue

**Comment by franmomu** [comment]
Just tried setting [`HAS_DEBUG` to `1`](https://github.com/franmomu/SonataAdminBundle/blob/test74/Makefile#L57), and [it took less than 2 minutes](https://travis-ci.org/franmomu/SonataAdminBundle/builds/633206578).

**Comment by greg0ire** [comment]
Ok so, clearly has to do with XDebug… We should try to find a docker image that has it to and reproduce this locally, and if yes I think we can file a bug report

**Comment by franmomu** [comment]
```bash
PHP 7.4.1 (cli) (built: Jan  7 2020 18:34:20) ( ZTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.1, Copyright (c), by Zend Technologies
    with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans
$ composer --version
Composer version 1.9.1 2019-11-01 17:20:17
```
👏 now it works, I'm fixing the errors

**Comment by greg0ire** [comment]
Definitely was XDebug :) No idea why it only hit SonataAdminBundle though…

**Comment by greg0ire** [comment]
@franmomu you can push to this branch directly. Please rebase interactively to drop my commit called "troubleshoot slowness"

**Comment by franmomu** [comment]
> @franmomu you can push to this branch directly. Please rebase interactively to drop my commit called "troubleshoot slowness"

ok!

**Comment by greg0ire** [comment]
Thanks @franmomu !

**Comment by franmomu** [comment]
> Thanks @franmomu !

Thank you! No idea why only affected SonataAdminBundle...

**Pull request merged**
