### PR TITLE
fix failing tests, application requires container

### PR DESCRIPTION
**Pull request by wodka**

### CODE REVIEW

**Comment by greg0ire** [comment]
Can you reword like this : 

```
fix failing tests, application requires container

Fixes #3622
```

**Comment by greg0ire** [comment]
Looks like your fix works :)

**Comment by wodka** [comment]
renamed it :)

**Comment by greg0ire** [comment]
Good to merge :) @OskarStark @core23 , can you merge this ASAP please?

**Comment by greg0ire** [comment]
I think we might have been victim of this : https://github.com/symfony/symfony/pull/17742

**Pull request merged**
