### PR TITLE
Export format translatable

### PR DESCRIPTION
**Pull request by lumilo8**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
What is the interest of this? The format is the same for all languages.

**Comment by lumilo8** [comment]
If the user wants customize the label xls cause doesn't know this format but yes knows Excel or Spreadsheat, for example.

**Comment by Soullivaneuh** [comment]
I see your point of view but don't know if it receivable.

@rande can you give me your opinion?

@lumilo8 please fix the tests.

**Comment by rande** [comment]
@Soullivaneuh no pb.

**Comment by Soullivaneuh** [comment]
Ok so @lumilo8 I'm waiting you for test fix! ;-)

**Comment by Soullivaneuh** [comment]
Sounds good. Now please squash your commit then I can merge it. :+1:

**Comment by lumilo8** [comment]
I don't know if "Merge branch master" commit is a problem :S Thanks!!

**Comment by Soullivaneuh** [comment]
@lumilo8 Absolutely not. :-)

Now your have 4 commit.

Follow this documentation but with `fixup` keyword instead of `squash`: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

Ping me when it's ready or if you have some difficulties.

**Comment by lumilo8** [comment]
@Soullivaneuh I get it, but it shows a message:
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 4 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Sorry, is the first time i do this =)

**Comment by Soullivaneuh** [comment]
Yeah you have to force it.

You have now 1 commit on your local but 4 on the server and not the same.

In a nutshell, a force push will erase those 4 commits by replacing with your only commit. Do you get it?

Command to run `git push -f` or `git push --force`.

**Comment by lumilo8** [comment]
Woohoo!! Thanks you, i hope it's done :)

**Comment by Soullivaneuh** [comment]
Yes! Thanks for your contribution. :+1:

**Pull request merged**
