### PR TITLE
Removed commented code

### PR DESCRIPTION
**Pull request by core23**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Strange error from StyleCI... Oo

**Comment by Soullivaneuh** [comment]
@core23 is your branch sync with `upstream/master`?

**Comment by core23** [comment]
Rebased

**Comment by Soullivaneuh** [comment]
Yeah it works now.

StyleCI apply default settings if `.styleci.yml` is not present.

So bad we don't have option like travis to disable test if not present..

**Comment by OskarStark** [comment]
thx @core23

**Pull request merged**
