### PR TITLE
Autocomplete improvements & new customization options

### PR DESCRIPTION
**Pull request by keshancs**
This PR adds extra functionality to sonata_type_model_autocomplete, fixes few glitches & extends customization options:

- Added callback with possibility to modify each individual item in response.
- Removed form type check in HelperController: it made impossible to extend sonata_type_model_autocomplete without writing own controller with copying whole retrieveAutocompleteItemsAction method in case of extending it.
- Added way to customize any autocomplete select2 properties in js via adding sonata_type_model_autocomplete_select2_options_js block before initializing select2 element. Reason to do this is because select2 doesn't allow modification of several options after it has been initialized, you can only destroy it and initialize again from scratch.
- Make autocomplete item list independent of filters set in corresponding list via removing it's filters. Otherwise, if you set filter in, let's say, product list, and you're using product autocomplete elsewhere, it returns only products that match that filter, which is confusing.
- Set error bubbling to false - prevent passing error to parent form elements, which occurs by default for compound form types.

### CODE REVIEW

**Comment by greg0ire** [comment]
:thinking: why are you targetting 2.x? Are you still using that branch?

**Comment by keshancs** [comment]
Yes, I'm sorry. This is the first time I work with PRs and I was told that I need to make them into master branch, which I am going to do, but answering your question - yes, we still use 2.x, but with our own modifications.

**Comment by greg0ire** [comment]
> I was told that I need to make them into master branch,

By who? Because you actually don't.

> yes, we still use 2.x, but with our own modifications.

Consider migrating, it has not been maintained for 4 years now.

**Comment by keshancs** [comment]
In general it would be master, in your case that would be 4.x I assume. We are planning on updating, we are working through our forks trying to get rid of them

**Comment by keshancs** [comment]
Is there any chance you could merge it into 2.x though, at least for now?

**Comment by core23** [comment]
> Is there any chance you could merge it into 2.x though, at least for now?

No, because we are not supporting the 2.x branch for many reasons.

**Comment by greg0ire** [comment]
Sorry, we support a lot of things at Sonata, but what is not supported is not supported. @sonata-project/contributors maybe we should remove the old branches to make things perfectly clear. People can still look at the history with urls like this one: https://github.com/sonata-project/SonataAdminBundle/commits/3.4.0

**Pull request closed without merging**
