### PR TITLE
Update form_admin_fields "use" instead "extends"

### PR DESCRIPTION
**Pull request by sashaaro**

### CODE REVIEW

**Comment by greg0ire** [comment]
So you want to use horizontal reuse instead of inheritance. Why ?

**Comment by sashaaro** [comment]
why not? 
ye, I want to use
`
{% use "SonataAdminBundle:Form:form_admin_fields.html.twig" %}
{% use "MyAdminBundle:Form:form_fields.html.twig" %}
`

**Comment by greg0ire** [comment]
> why not? 

Because we don't change things without a reason.

> ye, I want to use
{% use "SonataAdminBundle:Form:form_admin_fields.html.twig" %} {% use "MyAdminBundle:Form:form_fields.html.twig" %}

And? This does not work because of inheritance? If yes, do you have an error message?

**Comment by greg0ire** [comment]
ping @sashaaro

**Pull request closed without merging**
