### PR TITLE
Do not try to find a route for `show` and `edit`

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

Bugfix

## Changelog

```markdown
### Fixed
- Fix `display_url.html.twig` template
```

### CODE REVIEW

**Comment by greg0ire** [comment]
> Do not try to find a route for show and edit

In what context and why not? To be squash merged or squashed by yourself if you add an explanation to your commit message.

**Comment by VincentLanglet** [comment]
Is it better @greg0ire ?

**Comment by greg0ire** [comment]
I am not sure I understood. Apparently, when `route.name` is either `edit` or `show`, then `value` is already a url (the desired result), and there is no need to generate a url since it is already generated somewhere. Is that correct?

If yes, why is that the case, and if it is "often" the case, what if it isn't? Won't something bad happen?

**Comment by VincentLanglet** [comment]
The fieldDescription has `route.name = show` by default and this is not a real route name so it should not be use.

**Comment by greg0ire** [comment]
Oh OK I think I get it now!

**Review by greg0ire — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @VincentLanglet !

**Pull request merged**
