### PR TITLE
Improve filter icon

### LINKED ISSUE #7187: Use checkbox instead of icon for filters
## Feature Request

When using font awesome 5, `fas` icons are solid and we are using icons for the checkbox in filters:

image

That makes checkboxes look strange to me, we could use a `<input type='checkbox'>` instead.

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

Before:
https://github.com/sonata-project/SonataAdminBundle/issues/7187#issue-890200720
After:
https://github.com/sonata-project/SonataAdminBundle/issues/7187#issuecomment-891621803

Closes #7187.

## Changelog

```markdown
### Changed
- Icon for filters
```

### CODE REVIEW

**Comment by franmomu** [comment]
Based on https://github.com/sonata-project/SonataAdminBundle/issues/7187#issuecomment-891621803, I guess some css has to be added to add some margin.

**Comment by VincentLanglet** [comment]
Indeed, there was this https://github.com/sonata-project/SonataAdminBundle/blob/master/assets/scss/admin-lte-fas.scss for `fas` icons.

Should we add the same BC-layer for `far`, `fad`, `fal` (this will allow user which override template to have the same css with different icons) or should we just do it when we need it @jordisala1991 ?

**Comment by VincentLanglet** [comment]
I decided to add the css for every possible syntaxes.
Like adminLTE does https://raw.githubusercontent.com/ColorlibHQ/AdminLTE/master/dist/css/adminlte.css

Also, I discover `fab` exists.

**Review by jordisala1991 — APPROVED** [review]

**Review by franmomu — APPROVED** [review]

**Comment by franmomu** [comment]
Thanks @VincentLanglet !

**Pull request merged**
