### PR TITLE
Fix some phpstan-strict issue

### PR DESCRIPTION
**Pull request by VincentLanglet**
Fixed some
- always true conditions
- non-boolean value passed to if
- using static method non-statically
- empty usage

### CODE REVIEW

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
This allows to use the phpstan-strict plugin?

**Comment by VincentLanglet** [comment]
> This allows to use the phpstan-strict plugin?

Not yet, there is still around 250 errors.

**Comment by soullivaneuh** [comment]
May we have this kind of change on the current active 3.x branch? You changes fix several issues, for example on xeditable fields with `0` values.

Also, should to fixes be done on the current active branch instead of the next one? I remember this was working that way before. :wink:

**Comment by soullivaneuh** [comment]
@VincentLanglet May we have this kind of change on the current active 3.x branch? You changes fix several issues, for example on xeditable fields with `0` values.

Also, should to fixes be done on the current active branch instead of the next one? I remember this was working that way before. :wink:

**Comment by VincentLanglet** [comment]
> @VincentLanglet May we have this kind of change on the current active 3.x branch? You changes fix several issues, for example on xeditable fields with `0` values.
> 
> Also, should to fixes be done on the current active branch instead of the next one? I remember this was working that way before. 😉

There is tons of pedantic changes which may not be worth to be backported to 3.x. When it had sens, I already backported some things to 3.x, for example adding `@final` annotation to more than 100 methods or some bug fix.
If you discover that one of these change is fixing a real issue in master which could and should be fixed in 3.x, a backport can be done, but currently I just consider that the backport does not worth it.

Also, the master branch is on psalm 3 level and phpstan level 8 check, which is not the 3.x. Keep in mind, a lot of code was modified/simplified/improved thanks to static analysis and a lot of next_major were resolved. Doing this kind of change on 3.x will just create literally a thousand conflict during the 3.x into master merge, with no real benefit and just the possibility to introduce bug during those kind of merge. I already did a lot of 3.x merge into master, almost all the recent ones and already have some merge with hundred of conflict. 

Since we're focusing on the release of Sonata 4 which should a release candidate this month, I prefer to focus on this.

**Comment by soullivaneuh** [comment]
> If you discover that one of these change is fixing a real issue in master which could and should be fixed in 3.x, a backport can be done.

For my case, this one: https://github.com/sonata-project/SonataAdminBundle/pull/7289/files#diff-7c4a3052182ec3c11e1950c6378705ba44e2af3cd27bb526aae25bed942c0a9fR149

On the list configuration, I want to add an editable field of an enum:

```php
$listMapper
    ->add('status', FieldDescriptionInterface::TYPE_CHOICE, [
        'template' => 'admin/CRUD/list_status.html.twig',
        'editable' => true,
        'choices' => Status::getClassPrefixedKeys('strtolower'),
        'catalogue' => 'global',
    ])
;
```

One of the choice has a value of `0`. This throw an error on submit because of the weak comparison.

But in general, any strict comparison fix is a bug fix to me.

> but currently I just consider that the backport does not worth it.

In a general way, something you fix should be done on the active branch until the new one is released if the related files already exists.

> Also, the master branch is on psalm 3 level and phpstan level 8 check, which is not the 3.x. Keep in mind, a lot of code was modified/simplified/improved thanks to static analysis and a lot of next_major were resolved. Doing this kind of change on 3.x will just create literally a thousand conflict during the 3.x into master merge, with no real benefit and just the possibility to introduce bug during those kind of merge. I already did a lot of 3.x merge into master, almost all the recent ones and already have some merge with hundred of conflict.

I may understand that, but this is maybe also why you have a lot of conflict : All bugfixes/cleaning should have be done before on 3.x IMO.

> Since we're focusing on the release of Sonata 4 which should a release candidate this month, I prefer to focus on this.

Hope you will! Coming from that, I know what the technical dept this project currently has. :wink:

**Comment by VincentLanglet** [comment]
> > If you discover that one of these change is fixing a real issue in master which could and should be fixed in 3.x, a backport can be done.
> 
> For my case, this one: https://github.com/sonata-project/SonataAdminBundle/pull/7289/files#diff-7c4a3052182ec3c11e1950c6378705ba44e2af3cd27bb526aae25bed942c0a9fR149
> 
> On the list configuration, I want to add an editable field of an enum:
> 
> ```
> $listMapper
>     ->add('status', FieldDescriptionInterface::TYPE_CHOICE, [
>         'template' => 'admin/CRUD/list_status.html.twig',
>         'editable' => true,
>         'choices' => Status::getClassPrefixedKeys('strtolower'),
>         'catalogue' => 'global',
>     ])
> ;
> ```
> 
> One of the choice has a value of `0`. This throw an error on submit because of the weak comparison.

I'm pretty happy to know that fixing those weak comparison were really fixing some bugs.
I'll see if we could try to add the phpstan strict plugin in order to avoid those in the futur.

> But in general, any strict comparison fix is a bug fix to me.
> 
> > but currently I just consider that the backport does not worth it.
> 
> In a general way, something you fix should be done on the active branch until the new one is released if the related files already exists.

I agree on this in general.

> I may understand that, but this is maybe also why you have a lot of conflict : All bugfixes/cleaning should have be done before on 3.x IMO.

Bumping phpstan level required BC-break that's why we stopped to level 5. Same for psalm.
Resolving the next levels issues sure introduce differences between the two branch.
Also, we started to resolved the NEXT_MAJOR comments in order to release an alpha and this introduced a lot of differences with the two branches.

> > Since we're focusing on the release of Sonata 4 which should a release candidate this month, I prefer to focus on this.
> 
> Hope you will! Coming from that, I know what the technical dept this project currently has. 😉

🤞🏻🍾

**Comment by soullivaneuh** [comment]
@VincentLanglet Please see https://github.com/sonata-project/SonataAdminBundle/pull/7335

**Comment by VincentLanglet** [comment]
> @VincentLanglet Please see #7335

Thanks, it will be in the 3.104.0 release

**Comment by soullivaneuh** [comment]
@VincentLanglet Thank you, shall I let you merge it?

**Comment by VincentLanglet** [comment]
> @VincentLanglet Thank you, shall I let you merge it?

I'll try to add https://github.com/sonata-project/SonataAdminBundle/pull/7325 in the 3.104 release, I just need review, so there is no urge to merge the #7335 ; I won't forget to merge it before the next release

**Pull request merged**
