### PR TITLE
Update deprecated twig paths

### PR DESCRIPTION
**Pull request by enleur**
I am targeting this branch, because https://github.com/sonata-project/dev-kit/issues/374.

Reference https://github.com/sonata-project/dev-kit/issues/374

## Changelog

```markdown
### Changed
- Replace twig paths with new naming conventions
```

## Subject
Colon separators in twig paths is no longer recommended https://symfony.com/doc/3.3/templating/namespaced_paths.html

### CODE REVIEW

**Comment by enleur** [comment]
Not that simple... I'll check php references to twig templates

**Comment by enleur** [comment]
ping @greg0ire

**Comment by jordisala1991** [comment]
Thank you @enleur. You dont need to ping someone if you dont get an answer after an hour ;)

**Comment by enleur** [comment]
@jordisala1991 sorry :)

**Pull request merged**
