### PR TITLE
Updated adminLTE to 2.3.11

### PR DESCRIPTION
**Pull request by jordisala1991**
I am targetting this branch, because this is BC.

## Changelog

```markdown
### Added
- Updated adminLTE to 2.3.11
```

## Subject

adminLTE vas on 2.3.6, updated to 2.3.11. This fixes atleast one bug on Sonata (there are many more on the changelog) were the sidebar menu arrow were not changing on active items from < to v.

### CODE REVIEW

**Comment by greg0ire** [comment]
@sonata-project/contributors so… patch?

**Comment by anacona16** [comment]
After this commit the img folder from admin-lte repo is missing, but the admin-lte 2.3.11 has that folder: https://github.com/almasaeed2010/AdminLTE/tree/v2.3.11/dist

**Comment by jordisala1991** [comment]
Will check, This commit doesn't remove any img folder

**Comment by jordisala1991** [comment]
@anacona16 this is on the gitignore, along with more other admin-lte exclusions: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/.gitignore#L11

I think those img were never on the admin project.

**Comment by anacona16** [comment]
@jordisala1991 I see, thanks for the clarification, but it's weird I have a lot of not found messagse in my logs regarding with that img folder

**Comment by jordisala1991** [comment]
Do you have any examples to show? screenshots or concrete routes would be nice

**Comment by anacona16** [comment]
This is the exception.

`Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /bundles/sonataadmin/vendor/admin-lte/dist/img/boxed-bg.jpg" (from "http://www.dominio.com/")" at /var/www/vhosts/dominio/var/cache/prod/classes.php line 3921`

**Pull request merged**
