### PR TITLE
Fix for hidden jQuery UI dialog close button

### LINKED ISSUE #4511: jQuery UI dialog close button not showing
#### Sonata packages

```
sonata-project/admin-bundle    3.18.2 The missing Symfony Admin Generator
sonata-project/block-bundle    3.3.2  Symfony SonataBlockBundle
sonata-project/cache           1.0.7  Cache library
sonata-project/core-bundle     3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle 2.2.1  Symfony SonataDatagridBundle
sonata-project/exporter        1.7.1  Lightweight Exporter library
```

#### Symfony packages

```
symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.2 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2 Symfony SwiftmailerBundle
symfony/symfony            v3.3.2 The Symfony PHP framework
```

#### PHP version

```
PHP 5.6.30 (cli) (built: Mar 11 2017 09:56:27) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject

When using a jQuery UI dialog in a Sonata Admin project, the close button "x" icon doesn't show.

This seems to be a [known problem](https://stackoverflow.com/a/20457891/192961) and can be solved by including the Bootstrap javascript file before the jQuery UI file, so simply [changing the order of these scripts](https://github.com/sonata-project/SonataAdminBundle/blob/466b047923416ce85bf9b6851f47d4aff6eefda3/DependencyInjection/Configuration.php#L366) (and updating the docs) should do it (if that doesn't bring any BC issues).

As a temp fix you can override the sonata_admin / assets / javascripts config section as defined here: https://sonata-project.org/bundles/admin/3-x/doc/reference/configuration.html

## Steps to reproduce

* Add an empty placeholder div
* Add some javascript to open the div as dialog, like so: `$('#some-div-selector').dialog();`

## Expected results

The close button "x" icon should be showing.

## Actual results

The close button "x" icon is not showing.

### PR DESCRIPTION
**Pull request by verheyenkoen**
I am targeting this branch, because it is a patch.

Closes #4511

## Changelog

```markdown
### Changed
- Reordered bootstrap.js javascript dependency fixes problems with jQuery UI dialogs
```

## Subject

When using the jQuery UI dialog window, the close button ("x") in the top right corner was missing because of interference with bootstrap. Reordering the javascript dependency files fixed this issue.

### CODE REVIEW

**Comment by jordisala1991** [comment]
Please apply the patch provided by flintCI

**Comment by verheyenkoen** [comment]
@jordisala1991 Any idea what went wrong now?

**Comment by jordisala1991** [comment]
Before, you probably had some extra whitespaces on a empty line. Now, for some reason, flintCI does not want to work

**Comment by verheyenkoen** [comment]
@jordisala1991 I know the feeling.

**Comment by kunicmarko20** [comment]
I guess we can merge it without flintCI?

**Comment by jordisala1991** [comment]
We can merge without flint approval, because we already saw it fixed, and the PR is really small

**Comment by jordisala1991** [comment]
Thank you @verheyenkoen

**Comment by pulzarraider** [comment]
This change reintroduce the problem with tooltips everywhere which was fixed in #3153.

**Comment by jordisala1991** [comment]
We have #5087 which basically reverts this one, does it fix the issue?

**Pull request merged**
