### PR TITLE
update documentation

### PR DESCRIPTION
**Pull request by acabala**
I am targeting this branch, because I found documentation outdated.

## Changelog

```markdown
### Fixed
- updated documentation for accessing `actions`
```
## Subject

type `action` is required to be passed in current version if you want to use sonata actions

### CODE REVIEW

**Comment by jordisala1991** [comment]
It shouldn't be required, it is?

**Comment by greg0ire** [comment]
> It shouldn't be required, it is?

Nope, I'm trying to find the name of the guy who touched this lately

**Comment by acabala** [comment]
I get `Notice: Undefined index: _action` in
` vendor/sonata-project/doctrine-mongodb-admin-bundle/Sonata/DoctrineMongoDBAdminBundle/Guesser/FilterTypeGuesser.php at line 64`
when trying to pass `null`

**Comment by greg0ire** [comment]
Might have to do with https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/673 @andrewmy, can you please comment on this? I'm afraid you might have introduced a BC-break

**Comment by jordisala1991** [comment]
It is not released yet, so we can fix it.

**Comment by andrewmy** [comment]
Hi! Here's what I changed, TypeGuesser is only mocked in the test: https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/210/files
Do you get the same result on the version before the merge?

**Comment by greg0ire** [comment]
Are you using Doctrine ORM or MongoDB?

**Comment by acabala** [comment]
I use MongoDB.
Not sure about version before merge - I do requirement for Sonata few days ago, so I started with current one already.

**Comment by greg0ire** [comment]
Oh didn't notice your post, of course you use MongoDB, silly me! [link for the lazy](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/3.x/Guesser/FilterTypeGuesser.php#L64)

**Comment by greg0ire** [comment]
Not sure why you get this error in the **filter** type guesser though... actions can't be used in the filter, can they?

**Comment by Soullivaneuh** [comment]
Even before discussion: Could you please update your PR and commit titles to be more accurate?

**Comment by OskarStark** [comment]
ping @acabala

**Comment by OskarStark** [comment]
Closing, as we got no feedback from the author.

Feel free to reopen this PR @acabala

**Pull request closed without merging**
