### PR TITLE
Fix Twig filter 'render_view_element_compare'

### PR DESCRIPTION
**Pull request by jhcasado**
Added the twig environment to the Twig extension 'render_view_element_compare'.

### CODE REVIEW

**Comment by greg0ire** [comment]
Please run

```
make cs
git commit --amend
git push --force
```

**Comment by greg0ire** [comment]
Thanks for fixing my mistake BTW :s

**Comment by jhcasado** [comment]
No prob, thanks to you.

"make cs" is trying to fix more coding standards in other files not related with this fix.

I only accepted the correction in my added line.

**Comment by OskarStark** [comment]
@greg0ire the cs looks wrong to me

**Comment by greg0ire** [comment]
Ugh right. I shouln't have merged like this, sorry

**Comment by jhcasado** [comment]
It was the change that php-cs-fixer fixed in my added line:

PHP CS Fixer version 1.12-DEV by Fabien Potencier and Dariusz Ruminski (731274b)


And also it looked ok to me because the same line is repeated twice in previous lines.

You are talking about the entire file and not only my addition, right?
If not, please tell me what to do that I will fix it.

**Comment by greg0ire** [comment]
@OskarStark : from now on, I'll always wait for a second look before merging :s It's not serious this time, thankfully.

@jhcasado 

this: 

```
                array('is_safe'     => array('html'),
                'needs_environment' => true, )
```

should look like this :

```
        array(
            'is_safe'     => array('html'),
            'needs_environment' => true
        )
```

**Comment by greg0ire** [comment]
> PHP CS Fixer version 1.12-DEV by Fabien Potencier and Dariusz Ruminski (731274b)

You mean you don't have the same php cs fixer version as travis CI ?

**Comment by OskarStark** [comment]
@greg0ire no problem, travis was green...

**Comment by jhcasado** [comment]
Ok, 
I manually fixed it because php-cs-fixer not, 
and I fixed the previous arrays declarations with the same CS problem.

I also tried the php-cs-fixer.phar version from [FriendsOfPHP/PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer), and it didn't fix nothing else.

My installed one is from the official, and stable, repositories of ArchLinux.

Hope it is ok now.

**Comment by greg0ire** [comment]
I can't see your changes.

**Comment by jhcasado** [comment]
It is in the same branch [patch-1](https://github.com/jhcasado/SonataAdminBundle/commit/6291232500dafa68d63edf2516f518f4a954025b).

Could it be that this PR was already closed and GitHub don't refresh it anymore with extra changes in the foreign branch?

**Comment by greg0ire** [comment]
> Could it be that this PR was already closed and GitHub don't refresh it anymore with extra changes in the foreign branch?

Yes. You have to open a new PR.

**Comment by jhcasado** [comment]
Done #3722

**Pull request merged**
