### PR TITLE
update example of code

### PR DESCRIPTION
**Pull request by axzx**
## Subject

parameters should be in filter key

### CODE REVIEW

**Comment by greg0ire** [comment]
Thanks @axzx !

**Comment by greg0ire** [comment]
See #4178

**Comment by axzx** [comment]
@greg0ire 
It should also be included in the branch 3.x?

**Comment by greg0ire** [comment]
Oh snap I forgot to check that! Damn. Can you cherry-pick your commit on branch 3.x and make another PR?

**Pull request merged**
