### PR TITLE
Do not specify 'actions' type on list _action field

### PR DESCRIPTION
**Pull request by Soullivaneuh**
This is not necessary to specify it to get it working.

Need @sonata-project/contributors opinions for this one.

### CODE REVIEW

**Comment by core23** [comment]
Sure there is no automapping for `null` value to `actions` or something else?

**Comment by Soullivaneuh** [comment]
> Sure there is no automapping for `null` value to `actions` or something else?

Not sure of what you mean. Can you please elaborate?

In any case, I tested it on my project:

```php
$listMapper->add('_action', null, ['actions' => $actions]);
```

Does the same thing as:

```php
$listMapper->add('_action', 'actions', ['actions' => $actions]);
```

**Comment by core23** [comment]
>> Sure there is no automapping for null value to actions or something else?

> Not sure of what you mean. Can you please elaborate?

If you don't specify a type (pass `null` as parameter) to the `FormMapper`, the type is guessed by some magic. Have you checked, that the new `null` parameter isn't mapped to `actions` again?

**Comment by Soullivaneuh** [comment]
> Have you checked, that the new `null` parameter isn't mapped to `actions` again?

-> https://github.com/sonata-project/SonataAdminBundle/pull/3827#issuecomment-219437644

Or I again did not understand. :-)

**Comment by greg0ire** [comment]
> Have you checked, that the new null parameter isn't mapped to actions again?

IMO this is exactly what is happening, and it is intended.

**Comment by Soullivaneuh** [comment]
test

**Comment by greg0ire** [comment]
"commentaire à la con"

**Comment by Soullivaneuh** [comment]
"réponse à la con"

**Comment by Soullivaneuh** [comment]
@core23 We are waiting for more detail if you think we did not understand.

Otherwise let's merge it.

**Comment by OskarStark** [comment]
what about the admin generator? Does it generates `actions` or `null` ?

**Comment by Soullivaneuh** [comment]
Good catch @OskarStark! Actually it generates `'actions'`. I'll update it.

**Pull request merged**
