### PR TITLE
Feature/add some twig block

### PR DESCRIPTION
**Pull request by kmelia**
I am targetting The 3.x branch, because it only add twig blocks

## Changelog

```markdown
### Added
- Twig blocks to simplify the template override.
```

## Subject

It will adds some twig block to simplify the template override.

### CODE REVIEW

**Comment by OskarStark** [comment]
I really like this change

**Comment by greg0ire** [comment]
- "Useful" is spelt with one "l".
- there should be only one commit

Otherwise, :+1: for this change, it makes overriding easier. Would love to have the thoughts @core23 and @Soullivaneuh , not sure what they think about the number of blocks growing.

**Comment by core23** [comment]
I think new blocks for this cases are okay, because there are several situation were you have the need to override this things.

**Comment by kmelia** [comment]
@greg0ire thanks!

Do I have to fix this PR with only one commit?

**Comment by greg0ire** [comment]
> Do I have to fix this PR with only one commit?

We can deal with both issues when squash-merging, so no, you don't have to.

**Comment by greg0ire** [comment]
Thanks @kmelia

**Pull request merged**
