### PR TITLE
[AdminPoolLoader] Extend Loader instead of FileLoader to avoid deprecation message

### PR DESCRIPTION
**Pull request by bgaleotti**
Ref. https://github.com/sonata-project/SonataAdminBundle/issues/3091#issuecomment-147698804

### CODE REVIEW

**Comment by OskarStark** [comment]
looks ok to me

ping @sonata-project/contributors

**Comment by OskarStark** [comment]
@bgaleotti can you use this commit message?

``
[AdminPoolLoader] Extend Loader instead of FileLoader to avoid deprecation message
``

**Comment by bgaleotti** [comment]
@OskarStark done!

**Comment by OskarStark** [comment]
are you :+1: with this change @rande ?

**Pull request merged**
