### PR TITLE
[Admin] Remove validation related methods

### LINKED ISSUE #6233: [NEXT_MAJOR] Remove `AbstractAdmin::validate` method and all validation-related methods.
As explained in the AdminInterface, the `validate` method doesn't work well (we have bug issue) and is useless since Symfony have his own form validation.
```
    /**
     * NEXT_MAJOR: remove this method.
     *
     * @param object $object
     *
     * @deprecated this feature cannot be stable, use a custom validator,
     *             the feature will be removed with Symfony 2.2
     */
    public function validate(ErrorElement $errorElement, $object);
```

I create this issue because we only added one `NEXT_MAJOR` comment but there is no real removal-plan, we'll have at least to:
- remove AbstractAdmin::attachInlineValidator.
- remove AbstractAdmin::validate.
- remove AbstractAdminExtension::validate.
- remove AdminExtensionInterface::validate.
- update the UPGRADE.md file.

We should also add a deprecation in 3.x.

### PR DESCRIPTION
**Pull request by tambait**
## Subject

Closes #6233 

## Changelog

```markdown

### Changed
- Changed `AbstractAdmin::buildForm()` removed line with call to `addEventListener()` which used `preValidate()`

### Removed
- Removed `AdminInterface::validate` method specification
- Removed `AbstractAdmin:validate` method implementation
- Removed `AbstractAdmin::attachInlineValidator()` method
- Removed `AbstractAdmin::preValidate()` method
- Removed `AdminExtensionInterface::validate()` method specification
- Removed `AbstractAdminExtension::validate()` method implementation

```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@tambait In order to reduce conflict, you should always wait for the merge in 3.x, then for the 3.x merge into master before doing the PR in master

**Review by core23 — APPROVED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Review by VincentLanglet — CHANGES_REQUESTED** [review]
I would say you can also remove 
- The property `protected $validator;` of the AbstractAdmin
- The set/getValidator method of the AbstractAdmin and the interface
- All the 4 `class_exists(\Sonata\Form\Validator\ErrorElement::class);` occurences
- `->scalarNode('validator')->defaultNull()->end()` in DependencyInjection/Configuration
- All the 'validator' occurence in AddDependencyCallsCompilerPass

**Comment by VincentLanglet** [comment]
I would say you can also remove 
- The property `protected $validator;` of the AbstractAdmin
- The set/getValidator method of the AbstractAdmin and the interface
- All the 4 `class_exists(\Sonata\Form\Validator\ErrorElement::class);` occurences
- `->scalarNode('validator')->defaultNull()->end()` in DependencyInjection/Configuration
- All the validator occurence in the doc
- All the 'validator' occurence in AddDependencyCallsCompilerPass

**Comment by tambait** [comment]
>     * All the 4 class_exists(\Sonata\Form\Validator\ErrorElement::class); occurences

I don't see these appearing in the master branch only in 3.x, so should I just add notice in 3.x for this to be removed in next major?

Also, should `Command\Validators` be removed or modified in any way?

**Comment by VincentLanglet** [comment]
> I don't see these appearing in the master branch only in 3.x, so should I just add notice in 3.x for this to be removed in next major?

If it's already removed, nothing to do ;)

> Also, should `Command\Validators` be removed or modified in any way?

I don't think so. These validators are used for the commands, not the admin.

**Comment by franmomu** [comment]
Sorry @tambait 🙏  I didn't see this PR before creating https://github.com/sonata-project/SonataAdminBundle/pull/6644, I just wanted to remove a comment that should be there and I ended up removing other `NEXT_MAJOR` comments because there were fails with phpstan.

**Comment by VincentLanglet** [comment]
> Sorry @tambait 🙏 I didn't see this PR before creating #6644, I just wanted to remove a comment that should be there and I ended up removing other `NEXT_MAJOR` comments because there were fails with phpstan.

Is there still something to keep in this PR ?

**Comment by tambait** [comment]
> > Sorry @tambait pray I didn't see this PR before creating #6644, I just wanted to remove a comment that should be there and I ended up removing other `NEXT_MAJOR` comments because there were fails with phpstan.

> Is there still something to keep in this PR ?

I  switched from working on this PR because there were things to be done on related PR #6633  on 3.x branch

**Comment by VincentLanglet** [comment]
Oh yes indeed, let's ask @franmomu A review for your PR introducing deprecations :p

**Pull request closed without merging**
