### PR TITLE
Cleanup dead setDefaultOptions(..) methods

### PR DESCRIPTION
**Pull request by dmaicher**
## Subject

While checking some of the phpstan errors on this [PR](https://github.com/sonata-project/SonataAdminBundle/pull/6263) I noticed some related to the non-existing `OptionsResolverInterface`.

So I propose here to cleanup this dead code to simplify maintenance a bit :blush: 

I don't see any way how this could be a BC break for anyone.

Those methods are not part of any contract and cannot be called anymore since `Symfony\Component\OptionsResolver\OptionsResolverInterface` does not even exist.

Or did I miss something?

Actually @franmomu also suggested to remove them [here](https://github.com/sonata-project/SonataAdminBundle/pull/6277#issuecomment-672666472).

I am targeting this branch, because I believe this is BC.

## Changelog

```markdown
### Removed
- long time deprecated and unused `setDefaultOptions` methods using `Symfony\Component\OptionsResolver\OptionsResolverInterface`
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Removing a public method is always a BC-break.
Even if there is no reason for someone to using it...

**Comment by dmaicher** [comment]
> Removing a public method is always a BC-break.
> Even if there is no reason for someone to using it...

Can you explain how this could be a BC break? In which scenario would this break anything?

**Comment by VincentLanglet** [comment]
> > Removing a public method is always a BC-break.
> > Even if there is no reason for someone to using it...
> 
> Can you explain how this could be a BC break? In which scenario would this break anything?

Someone really crazy could have written in his code
```
$foo = new FormTypeFieldExtension([], []);
$foo->setDefaultOptions(...);
```

It's not because symfony doesn't use it anymore that we can be sure that no one use it.

**Comment by dmaicher** [comment]
> > > Removing a public method is always a BC-break.
> > > Even if there is no reason for someone to using it...
> > 
> > 
> > Can you explain how this could be a BC break? In which scenario would this break anything?
> 
> Someone really crazy could have written in his code
> 
> ```
> $foo = new FormTypeFieldExtension([], []);
> $foo->setDefaultOptions(...);
> ```

Doing a `$foo->setDefaultOptions(...);` call is literally impossible without a type error. Since the interface `Symfony\Component\OptionsResolver\OptionsResolverInterface` does not event exist anymore but its the typehint for the argument

**Comment by VincentLanglet** [comment]
Oh ! Ok, I understand.

**Review by VincentLanglet — APPROVED** [review]

**Comment by dmaicher** [comment]
> IMO we should remove it in BlockBundle 3.x too. We should not using not ower namespaces.
> 
> @dmaicher Can you do it for BlockBundle too?
> 
> https://github.com/sonata-project/SonataBlockBundle/blob/3.x/src/Block/Service/AbstractBlockService.php#L135-L144
> `if (!$resolver instanceof OptionsResolver) {` wil be always true and will throw `BadMethodCallException`

Oh wow. That is an interesting "hack" on the BlockBundle.

Unfortunately there we cannot remove it yet I think.

There is this class: https://github.com/sonata-project/SonataBlockBundle/blob/3.x/src/Util/OptionsResolver.php

Which is used on the bundle itself and will use the stub interface

**Comment by wbloszyk** [comment]
I didn't dig so much. You show me `Sonata\BlockBundle\Util\OptionResolver`. In my case it is `Symfony\Component\OptionsResolver\OptionsResolver`.

**Comment by dmaicher** [comment]
> @dmaicher
> I didn't dig so much. You show me `Sonata\BlockBundle\Util\OptionResolver`. In my case it is `Symfony\Component\OptionsResolver\OptionsResolver`.
> 
> https://github.com/sonata-project/SonataBlockBundle/blob/3.x/src/Block/Service/AbstractBlockService.php#L135-L144

@wbloszyk but the instance passed to those `setDefaultSettings` methods is this one:

https://github.com/sonata-project/SonataBlockBundle/blob/3.x/src/Block/BlockContextManager.php#L240

So the methods are still called. Which means removing them would break BC for sure.

**Review by core23 — APPROVED** [review]

**Comment by wbloszyk** [comment]
> > @dmaicher
> > I didn't dig so much. You show me `Sonata\BlockBundle\Util\OptionResolver`. In my case it is `Symfony\Component\OptionsResolver\OptionsResolver`.
> > https://github.com/sonata-project/SonataBlockBundle/blob/3.x/src/Block/Service/AbstractBlockService.php#L135-L144
> 
> @wbloszyk but the instance passed to those `setDefaultSettings` methods is this one:
> 
> https://github.com/sonata-project/SonataBlockBundle/blob/3.x/src/Block/BlockContextManager.php#L240
> 
> So the methods are still called. Which means removing them would break BC for sure.

It is strange hack which is remove in 4.x. I think it is OK. 

@dmaicher Thanks for check it.

**Comment by wbloszyk** [comment]
Thanks @dmaicher

**Pull request merged**
