### PR TITLE
Use present tense sentences instead of past tense

### PR DESCRIPTION
**Pull request by OskarStark**
### Subject

As defined [here](http://keepachangelog.com/) the changelog should be in **present** tense instead of *past* tense
.
### To do

- [x] Fixed old changelog entries

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
> The don't merge this PR message is a really good idea, but it's necessary to let the cron few minutes, by adding a date check on last commit.

Where exactly? On the example we have both:

```
## [0.0.7] - 2015-02-16
### Added
- Link, and make it obvious that date format is ISO 8601.

### Changed
- Clarified the section on "Is there a standard change log format?".

### Fixed
- Fix Markdown links to tag comparison URL with footnote-style links.

## [0.0.6] - 2014-12-12
### Added
- README section on "yanked" releases.

## [0.0.5] - 2014-08-09
### Added
- Markdown links to version tags on release headings.
- Unreleased section to gather unreleased changes and encourage note
keeping prior to releases.
```

**Comment by OskarStark** [comment]
@greg0ire told me and i trusted him 😄 

https://github.com/sonata-project/SonataAdminBundle/pull/3822#discussion_r63692666

**Comment by Soullivaneuh** [comment]
Maybe ask directly on keepachangelog repository?

**Comment by greg0ire** [comment]
> @greg0ire told me and i trusted him :smile: 

Apparently my read was a bit too cursory

Maybe instead of using present tense, we should remove the verbs, like this : 

```
Added
- an orange
- an apple
```

**Comment by Soullivaneuh** [comment]
I'm sure asking it on the github repo to improve the way to do would be the best way. :+1:

**Comment by greg0ire** [comment]
https://github.com/olivierlacan/keep-a-changelog/issues/54

**Comment by greg0ire** [comment]
I added a comment on this thread, please have a look at it and express your feelings if they differ.

**Pull request closed without merging**
