### PR TITLE
Widget test

### PR DESCRIPTION
**Pull request by greg0ire**
This PR makes tests easier to write, and removes a condition that leaked into the code (my fault). This could benefit #3127

### CODE REVIEW

**Comment by greg0ire** [comment]
Looks like I broke my own test :(

**Comment by greg0ire** [comment]
This is way harder than I thought, I'll have to give it some time later.

**Comment by greg0ire** [comment]
Yeaaaah! All good! Ping @OskarStark

**Comment by OskarStark** [comment]
Nice, thank you @greg0ire

**Pull request merged**
