### PR TITLE
Change icon on list column sorting

### LINKED ISSUE #5246: Incorrect icon on list column sorting.
#### Sonata packages

```
$ *composer show --latest 'sonata-project/'
# Put the result here.
sonata-project/admin-bundle              3.31.0             3.39.0             The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1             3.12.1             Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              2.0.1              Cache library
sonata-project/cache-bundle              2.4.2              3.0.0              This bundle provides caching services
sonata-project/core-bundle               3.9.1              3.11.2             Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              2.3.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              1.1.0              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.4.2              3.6.2              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0              2.5.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              1.9.1              Lightweight Exporter library
sonata-project/formatter-bundle          3.4.1              4.1.1              Symfony SonataFormatterBundle
sonata-project/media-bundle              3.10.0             3.16.1             Symfony SonataMediaBundle
sonata-project/notification-bundle       3.3.1              3.5.1              Symfony SonataNotificationBundle
sonata-project/translation-bundle        dev-master f1a2a97 dev-master 3bba26d SonataTranslationBundle
sonata-project/user-bundle               dev-master c8aa3ca dev-master eff35d5 Symfony SonataUserBundle

```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
# Put the result here.
symfony/monolog-bundle     v3.1.1  v3.3.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.10 v4.1.6 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.8.0  v1.9.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.8.0  v1.9.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu  v1.8.0  v1.9.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.8.0  v1.9.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.8.0  v1.9.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.8.0  v1.9.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.8.0  v1.9.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v3.2.2  v3.2.3 Symfony SwiftmailerBundle
symfony/symfony            v3.4.13 v4.1.6 The Symfony PHP framework

```

#### PHP version

```
$ php -v
# Put the result here.
PHP 7.1.18 (cli) (built: Jun 20 2018 22:10:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.18, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

```

## Subject

Incorrect icon for css class  `.sonata-ba-list-field-header-order-desc` and `.sonata-ba-list-field-header-order-asc`. For `desc` sorting asc icon is showing near sortable field. Same issue you can see on http://demo.sonata-project.org/

## Steps to reproduce

1. Go to any list in admin panel with sort
2. Try to sort by desc
3. See asc icon instead of desc 
4. Same actions for asc sorting

## Expected results

Asc icon instead of desc 
Desc icon instead of asc 

## Actual results

Asc icon for asc sorting
Desc icon  for desc sorting

### PR DESCRIPTION
**Pull request by IvAndrew**
I am targeting this branch, because this is BC change (only style fix).

Closes #5246 

## Changelog

```markdown
### Fixed
- Change icon on list column sorting
```

## Subject
Change icon on list column sorting

Icon in list column sotring was inverted by vertical. This fix change layout.css file only (swap several css rules for icon).

### CODE REVIEW

**Comment by OskarStark** [comment]
Hey @IvAndrew, thank you for your first contribution.

Can you provide a screenshot before/after?

**Comment by IvAndrew** [comment]
Hello.
### Before patch:

- sort by ASC but icon show DESC
image
- list sort by desc but icon show asc
image


### After patch:
- ASC sort and icon
image

- Desc sort and icon
image


### ----
May be better use utf-8 arrow? Like this:
image

**Comment by OskarStark** [comment]
> May be better use utf-8 arrow? Like this:

uh this looks nice

**Comment by greg0ire** [comment]
Is the current code using the utf-8 arrow?

**Comment by IvAndrew** [comment]
Hello. I am change icon now. And fix position for multiline column title
### Before:
image

image

### After:
image

image

**Comment by greg0ire** [comment]
Thanks @IvAndrew !

**Pull request merged**
