### PR TITLE
Add final for every method of abstract classes

### LINKED ISSUE #5791: [Next Major] Close API
- [ ] Add `final` modifier
- [ ] Reduce visiblity to `private`
- [ ] Add type hints

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because BC.

Closes #5791. (I think)

## Changelog

```markdown
### Added
- `final` for method of every abstract classes.
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
I need to check if the `haveToPaginate` override in the Simple Pager could be removed.

**Comment by VincentLanglet** [comment]
> I need to check if the `haveToPaginate` override in the Simple Pager could be removed.

Maybe you can help me @franmomu since you're using the Simple Pager ; do you see any differences if you remove the override of the method ?

**Comment by franmomu** [comment]
> > I need to check if the `haveToPaginate` override in the Simple Pager could be removed.
> 
> Maybe you can help me @franmomu since you're using the Simple Pager ; do you see any differences if you remove the override of the method ?

I haven't checked in a project and I guess it would be the same, but in `SimplePager` I guess it's implemented that way for performance reasons.

**Comment by VincentLanglet** [comment]
> I haven't checked in a project and I guess it would be the same, but in `SimplePager` I guess it's implemented that way for performance reasons.

Since the `countResults` method is not doing any queries:
```
    public function countResults(): int
    {
        $n = ($this->getLastPage() - 1) * $this->getMaxPerPage();
        if ($this->getLastPage() === $this->getPage()) {
            return $n + $this->thresholdCount;
        }

        return $n;
    }
```
I don't see real perfomance improvements.

**Comment by franmomu** [comment]
When iterating results:

https://github.com/sonata-project/SonataAdminBundle/blob/7805e4af7999656f86b44c24e58e03fd68d14b50/src/Datagrid/SimplePager.php#L92-L113

`this->haveToPaginate` is set, so there is no need to even make any call, I haven't check the real performance though.

**Comment by VincentLanglet** [comment]
> `this->haveToPaginate` is set, so there is no need to even make any call, I haven't check the real performance though.

I agree, but only a multiplication and a sum is done, so it's not significant.

**Comment by jordisala1991** [comment]
> I need to check if the `haveToPaginate` override in the Simple Pager could be removed.

IMO we should not mark it final if the simple pager overrides it, have you tried performance implications of it?

**Comment by VincentLanglet** [comment]
> IMO we should not mark it final if the simple pager overrides it, have you tried performance implications of it?

Previously it was 
```
    public function haveToPaginate()
    {
        return $this->haveToPaginate || $this->getPage() > 1;
    }
```
Now it's 
```
        $n = ($this->getLastPage() - 1) * $this->getMaxPerPage();
        if ($this->getLastPage() === $this->getPage()) {
            return $n + $this->thresholdCount;
        }

        return $n > $this->getMaxPerPage();
```

It only cost a multiplication.

**Comment by VincentLanglet** [comment]
Please review @sonata-project/contributors

**Review by core23 — APPROVED** [review]

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thank you @VincentLanglet

**Pull request merged**
