### PR TITLE
Add final annotation for AbstractAdmin method final in master

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Changelog

```markdown
### Deprecated
- Overriding `AbstractAdmin::getDataSourceIterator()`
- Overriding `AbstractAdmin::create()`
- Overriding `AbstractAdmin::delete()`
- Overriding `AbstractAdmin::getFilterParameters()`
- Overriding `AbstractAdmin::getParentAssociationMapping()`
- Overriding `AbstractAdmin::getBaseRoutePattern()`
- Overriding `AbstractAdmin::getBaseRouteName()`
- Overriding `AbstractAdmin::getClass()`
- Overriding `AbstractAdmin::getSubClasses()`
- Overriding `AbstractAdmin::setSubClasses()`
- Overriding `AbstractAdmin::hasSubClass()`
- Overriding `AbstractAdmin::hasActiveSubClass()`
- Overriding `AbstractAdmin::getActiveSubClass()`
- Overriding `AbstractAdmin::getActiveSubclassCode()`
- Overriding `AbstractAdmin::getBatchActions()`
- Overriding `AbstractAdmin::getRoutes()`
- Overriding `AbstractAdmin::hasRoute()`
- Overriding `AbstractAdmin::isCurrentRoute()`
- Overriding `AbstractAdmin::generateObjectUrl()`
- Overriding `AbstractAdmin::generateUrl()`
- Overriding `AbstractAdmin::generateMenuUrl()`
- Overriding `AbstractAdmin::getFormBuilder()`
- Overriding `AbstractAdmin::defineFormBuilder()`
- Overriding `AbstractAdmin::attachAdminClass()`
- Overriding `AbstractAdmin::getForm()`
- Overriding `AbstractAdmin::getList()`
- Overriding `AbstractAdmin::getDatagrid()`
- Overriding `AbstractAdmin::getSideMenu()`
- Overriding `AbstractAdmin::getRootCode()`
- Overriding `AbstractAdmin::getRoot()`
- Overriding `AbstractAdmin::setBaseControllerName()`
- Overriding `AbstractAdmin::getBaseControllerName()`
- Overriding `AbstractAdmin::getMaxPerPage()`
- Overriding `AbstractAdmin::setMaxPageLinks()`
- Overriding `AbstractAdmin::getMaxPageLinks()`
- Overriding `AbstractAdmin::getFormGroups()`
- Overriding `AbstractAdmin::setFormGroups()`
- Overriding `AbstractAdmin::removeFieldFromFormGroup()`
- Overriding `AbstractAdmin::reorderFormGroup()`
- Overriding `AbstractAdmin::getFormTabs()`
- Overriding `AbstractAdmin::setFormTabs()`
- Overriding `AbstractAdmin::getShowTabs()`
- Overriding `AbstractAdmin::setShowTabs()`
- Overriding `AbstractAdmin::getShowGroups()`
- Overriding `AbstractAdmin::setShowGroups()`
- Overriding `AbstractAdmin::reorderShowGroup()`
- Overriding `AbstractAdmin::setParentFieldDescription()`
- Overriding `AbstractAdmin::getParentFieldDescription()`
- Overriding `AbstractAdmin::hasParentFieldDescription()`
- Overriding `AbstractAdmin::setSubject()`
- Overriding `AbstractAdmin::getSubject()`
- Overriding `AbstractAdmin::hasSubject()`
- Overriding `AbstractAdmin::getFormFieldDescriptions()`
- Overriding `AbstractAdmin::getFormFieldDescription()`
- Overriding `AbstractAdmin::hasFormFieldDescription()`
- Overriding `AbstractAdmin::addFormFieldDescription()`
- Overriding `AbstractAdmin::getShowFieldDescriptions()`
- Overriding `AbstractAdmin::getShowFieldDescription()`
- Overriding `AbstractAdmin::hasShowFieldDescription()`
- Overriding `AbstractAdmin::addShowFieldDescription()`
- Overriding `AbstractAdmin::removeShowFieldDescription()`
- Overriding `AbstractAdmin::getListFieldDescriptions()`
- Overriding `AbstractAdmin::hasListFieldDescription()`
- Overriding `AbstractAdmin::addListFieldDescription()`
- Overriding `AbstractAdmin::removeListFieldDescription()`
- Overriding `AbstractAdmin::getFilterFieldDescription()`
- Overriding `AbstractAdmin::hasFilterFieldDescription()`
- Overriding `AbstractAdmin::addFilterFieldDescription()`
- Overriding `AbstractAdmin::removeFilterFieldDescription()`
- Overriding `AbstractAdmin::getFilterFieldDescriptions()`
- Overriding `AbstractAdmin::addChild()`
- Overriding `AbstractAdmin::hasChild()`
- Overriding `AbstractAdmin::getChildren()`
- Overriding `AbstractAdmin::getChild()`
- Overriding `AbstractAdmin::isChild()`
- Overriding `AbstractAdmin::hasChildren()`
- Overriding `AbstractAdmin::setUniqid()`
- Overriding `AbstractAdmin::getUniqid()`
- Overriding `AbstractAdmin::getClassnameLabel()`
- Overriding `AbstractAdmin::getPersistentParameter()`
- Overriding `AbstractAdmin::setCurrentChild()`
- Overriding `AbstractAdmin::isCurrentChild()`
- Overriding `AbstractAdmin::getCurrentChildAdmin()`
- Overriding `AbstractAdmin::setTranslationDomain()`
- Overriding `AbstractAdmin::getTranslationDomain()`
- Overriding `AbstractAdmin::getTranslationLabel()`
- Overriding `AbstractAdmin::setRequest()`
- Overriding `AbstractAdmin::getRequest()`
- Overriding `AbstractAdmin::hasRequest()`
- Overriding `AbstractAdmin::getCode()`
- Overriding `AbstractAdmin::getBaseCodeRoute()`
- Overriding `AbstractAdmin::showIn()`
- Overriding `AbstractAdmin::createObjectSecurity()`
- Overriding `AbstractAdmin::isGranted()`
- Overriding `AbstractAdmin::getUrlSafeIdentifier()`
- Overriding `AbstractAdmin::getNormalizedIdentifier()`
- Overriding `AbstractAdmin::getShow()`
- Overriding `AbstractAdmin::setFormTheme()`
- Overriding `AbstractAdmin::getFormTheme()`
- Overriding `AbstractAdmin::setFilterTheme()`
- Overriding `AbstractAdmin::getFilterTheme()`
- Overriding `AbstractAdmin::addExtension()`
- Overriding `AbstractAdmin::getExtensions()`
- Overriding `AbstractAdmin::supportsPreviewMode()`
- Overriding `AbstractAdmin::determinedPerPageValue()`
- Overriding `AbstractAdmin::isAclEnabled()`
- Overriding `AbstractAdmin::setListMode()`
- Overriding `AbstractAdmin::getListMode()`
- Overriding `AbstractAdmin::getAccessMapping()`
- Overriding `AbstractAdmin::checkAccess()`
- Overriding `AbstractAdmin::hasAccess()`
- Overriding `AbstractAdmin::getActionButtons()`
```

### CODE REVIEW

**Review by core23 — APPROVED** [review]
:+1: 

I'm sure that some of these methods are overridden by a few users.

**Comment by VincentLanglet** [comment]
> 👍
> 
> I'm sure that some of these methods are overridden by a few users.

Yes, that's why I want to help them migrate or opening issue in order to see if we should stop making them final or proposing another extension point.

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thanks @VincentLanglet

**Comment by tbyte80** [comment]
Hello,

I am overriding generateUrl to dynamically apply filter parameters in my Admin. What is the suggested replacement?

    public function generateUrl($name, array $parameters = [], $absolute = RoutingUrlGeneratorInterface::ABSOLUTE_PATH)
    {
        if($name == 'create') {
            $parameters = $this->getFilterParameters();
        }
        return parent::generateUrl($name, $parameters, $absolute);
    }

**Comment by VincentLanglet** [comment]
> Hello,
> 
> I am overriding generateUrl to dynamically apply filter parameters in my Admin. What is the suggested replacement?
> 
> ```
> public function generateUrl($name, array $parameters = [], $absolute = RoutingUrlGeneratorInterface::ABSOLUTE_PATH)
> {
>     if($name == 'create') {
>         $parameters = $this->getFilterParameters();
>     }
>     return parent::generateUrl($name, $parameters, $absolute);
> }
> ```

I recommend you to create an issue explaning why you're doing this.

**Pull request merged**
