### PR TITLE
Add cache clear

### PR DESCRIPTION
**Pull request by VincentLanglet**
@jordisala1991 I tried and coverage is untouched.

### CODE REVIEW

**Comment by jordisala1991** [comment]
This only applies if you execute previous commands inside this bootstrap file, otherwise it does not affect (well it only makes each local build start clean, on ci makes no difference)

**Comment by VincentLanglet** [comment]
> This only applies if you execute previous commands inside this bootstrap file, otherwise it does not affect (well it only makes each local build start clean, on ci makes no difference)

So it's only useful for project with a custom_bootstrap file ?
But the coverage is also untouched here: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1668

Did you notice a real diff on FormatterBundle ? Cause I don't see one so far.

**Comment by jordisala1991** [comment]
Maybe it is because FormatterBundle wasnt good covered on unit and integration tests?

**Comment by VincentLanglet** [comment]
> Maybe it is because FormatterBundle wasnt good covered on unit and integration tests?

The diff is not that huge: 86,96 vs 87,64 when I try locally and the only diff is on 
```
Sonata\FormatterBundle\Admin\CkeditorAdminExtension
```
Maybe the `configureRoutes` method.

**Comment by jordisala1991** [comment]
To me even if it not increases a lot the coverage, having the cache clear improves a lot the DX of local development of Sonata. Otherwise you have to manually change cache directory or remove the cache folder manually between each run of phpunit.

**Comment by VincentLanglet** [comment]
> Otherwise you have to manually change cache directory or remove the cache folder manually between each run of phpunit.

I never had to do this when running tests, but if you prefer, we can merge this PR

**Pull request closed without merging**
