### PR TITLE
Enhancement: Split QA workflow files

### PR DESCRIPTION
**Pull request by OskarStark**
This change is needed for https://github.com/sonata-project/dev-kit/pull/1135

### CODE REVIEW

**Review by jordisala1991 — DISMISSED** [review]

**Comment by jordisala1991** [comment]
The file naming seems a strange tbh. What about using a flag on the twig file on dev-kit?

**Comment by OskarStark** [comment]
> The file naming seems a strange tbh. What about using a flag on the twig file on dev-kit?

I thought about this, but it will be more complicated, because if a project does not use one of them we don't have to generate the file :-(

**Comment by core23** [comment]
I don't understand the reason. Can't we auto-generate a file for both tools?

**Comment by OskarStark** [comment]
> I don't understand the reason. Can't we auto-generate a file for both tools?

As I explained, sure we can, but we need to decide beforehand if it should be generated and if, with which content.

I would like to go with this as a first step and don't want to build new stuff into dev-kit

**Comment by OskarStark** [comment]
If you are completely against it, I will respect that and will find a solution for one file

**Comment by core23** [comment]
I like the solution from the ergebnis repos: https://github.com/ergebnis/composer-normalize/blob/main/.github/workflows/integrate.yaml

There is one workflow file for one problem: integration, yearly update, closing issues,... This allows creating a [dependent job](https://github.com/ergebnis/composer-normalize/blob/main/.github/workflows/integrate.yaml#L429-L440).

Not sure if we should follow this and if that's even possible with our dev-kit.

**Comment by jordisala1991** [comment]
> If you are completely against it, I will respect that and will find a solution for one file

I am not against it, maybe we could name it qa-phpstan and qa-psalm to be more consistent. The idea should be that the flags on dev-kit disappear as soon as every bundle gets phpstan and psalm, so maybe at that point we can unify again. Another option is to get both qa tools with one flag

**Comment by OskarStark** [comment]
NVM I think I got it working, lets close here

@core23 I agree this is nice, but would be a lot more complicated, because not all of our repos have all tools, so calculating which it really depends on could be hard.

**Pull request closed without merging**
