### PR TITLE
allow symfony/translation ^5.1 as its fully compatible

### PR DESCRIPTION
**Pull request by dmaicher**
## Subject
Actually all references to the deprecated translator interface and `transChoice` have been removed already on master. So its fully compatible with `symfony/translation` 5.1 :blush: 

Cannot see any other issues here: https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md#translation

Replaces https://github.com/sonata-project/SonataAdminBundle/pull/6342

## Changelog

```markdown
### Added
- Added support for `symfony/translation ^5.1`
```

### CODE REVIEW

**Comment by wbloszyk** [comment]
Can you also replace TranslatorInterface to this from contracts? Simmilar work as you done in the previous PR. Here it not be BC-break. :smile:

**Comment by dmaicher** [comment]
> Can you also replace TranslatorInterface to this from contracts? Simmilar work as you done in the previous PR. Here it not be BC-break. smile

Its done already on master. Nothing else to be done there I believe.

**Review by wbloszyk — APPROVED** [review]

**Review by jordisala1991 — CHANGES_REQUESTED** [review]
I dont see it being installed on the github actions

**Comment by VincentLanglet** [comment]
> I dont see it being installed on the github actions

```
composer why-not symfony/translation \^5.1
sonata-project/admin-bundle  3.x-dev    requires   symfony/translation (^4.4)           
symfony/translation          5.1.x-dev  conflicts  symfony/dependency-injection (<5.0)  
symfony/translation          5.1.x-dev  conflicts  symfony/http-kernel (<5.0)           
symfony/translation          5.1.x-dev  conflicts  symfony/twig-bundle (<5.0)
```

**Comment by dmaicher** [comment]
yeah cannot be installed yet.

**Pull request closed without merging**
