### PR TITLE
translate form group descriptions

### PR DESCRIPTION
**Pull request by greg0ire**
There is no reason not to (that I can think of).

### CODE REVIEW

**Comment by OskarStark** [comment]
has to be merged in master afterwards

**Comment by greg0ire** [comment]
@OskarStark isn't 2.3 merged into master regularly ? I think it should…

**Comment by core23** [comment]
IMO there is an existing translation for form groups @greg0ire

**Comment by greg0ire** [comment]
@core23 : ok, I can't find why I wrote this, so I'll just reopen if I find the reason. Closing for now.

**Comment by OskarStark** [comment]
i use it right now on master :+1:

**Comment by greg0ire** [comment]
Ok then, I must have been tired I guess :)

**Pull request closed without merging**
