### PR TITLE
#4152 fixed trying to access private property from CRUD Controller

### PR DESCRIPTION
**Pull request by mdstorage**
I am targetting this branch, because…

Closes #
Fixes #
## Changelog

``` markdown
### Added
- Added some `Class::newMethod` to do great stuff

### Changed

### Deprecated

### Removed

### Fixed

### Security
```
## To do

- [ ] Update the tests
- [ ] Update the documentation
- [ ] Add an upgrade note

### CODE REVIEW

**Comment by OskarStark** [comment]
@core23 i think we already have an issue ticket for this, right?

**Comment by OskarStark** [comment]
@mdstorage can you please fill the PR header template correct?

**Comment by core23** [comment]
This should be fixed, but we will replace it with https://github.com/sonata-project/SonataAdminBundle/issues/4088

**Comment by core23** [comment]
Please update the PR template and rebase, so we can merge this. @mdstorage

**Comment by greg0ire** [comment]
ping @mdstorage

**Comment by Koc** [comment]
@greg0ire I've opened another PR

**Comment by greg0ire** [comment]
Closing in favor of #4216

**Pull request closed without merging**
