### PR TITLE
Update search.rst

### PR DESCRIPTION
**Pull request by adumas37**
## Subject

Fix a typo in url 

I am targeting this branch, because it's only a typo.

### CODE REVIEW

**Comment by phansys** [comment]
@adumas37, in order to target `3.x` you could do the following:
```
git fetch upstream 3.x:patch-1-3.x
git checkout patch-1-3.x
git cherry-pick 53cfb4aafc021cafe0540d2ddaf3ec641beb9b86
git push origin patch-1-3.x:patch-1 -f
```
Then, you can change the target branch to `3.x` again.

**Comment by adumas37** [comment]
Sorry to bother you again with such a small change, but when cherry-picking my commit onto the 3.x branch, it seems that the file I modified does not exists (and I can't find the link I updated in the project either). The wrong link is present here however: https://symfony.com/doc/3.x/bundles/SonataAdminBundle/reference/search.html#case-sensitive-insensitive
Should I rebase onto another branch ?

**Comment by adumas37** [comment]
The problem was that my fork was not up to date, sorry for taking your time :/
Thx for beeing so reactive :)

**Comment by greg0ire** [comment]
The Travis build did not run let's try to close and reopen

**Pull request merged**
