### PR TITLE
Remove duplicate code from Admin

### PR DESCRIPTION
**Pull request by afurculita**
Removes duplicate code and adds one more rule for ```$action == 'create'```

### CODE REVIEW

**Comment by core23** [comment]
@afurculita Please rebase

**Comment by afurculita** [comment]
@core23 This have been rebased

**Comment by core23** [comment]
Can you please change the PR title and your commit message @afurculita

**Comment by afurculita** [comment]
@core23 Done

**Comment by core23** [comment]
Thank you @afurculita

**Pull request merged**
