### PR TITLE
Display create button on tree view

### PR DESCRIPTION
**Pull request by qsomazzi**
The goal of this PR is to give to possibility to add something when you are on tree view.
Tree view is pretty much like List so I think this makes sense.

### CODE REVIEW

**Comment by qsomazzi** [comment]
ping @rande

**Comment by core23** [comment]
Thank you @qsomazzi

**Comment by OskarStark** [comment]
what about `mosaic`

**Comment by core23** [comment]
Mosaic has the same ``action`` like the normale ``list`` view. @OskarStark

**Comment by OskarStark** [comment]
ok strange, that `tree` is a separate one...

**Comment by core23** [comment]
The mosaic view is basically a list view, that's why we use the same action. The tree view needs something more calculation in the back.

**Comment by qsomazzi** [comment]
But finally it's the same effect, display a list of something, maybe it should be the same action. Usually on a website, if a user as access to the list view, he got access to mosaic and tree.

**Comment by OskarStark** [comment]
@qsomazzi thats my opinion

**Comment by core23** [comment]
No it's different. You can filter a list but no tree

**Comment by OskarStark** [comment]
ok

**Pull request merged**
