### PR TITLE
add spaces

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by rande** [comment]
@OskarStark test are red: http://91.121.3.21/job/sonata-ci-bundle-admin/213/console

**Comment by OskarStark** [comment]
sorry, will fix

**Comment by Soullivaneuh** [comment]
Why using quotes?

**Comment by OskarStark** [comment]
in My Case i generate for ```Video``` ```Video List``` and i think if you use whitespace between, quotes are recommended, or?

i can revert the quotes change if you like

**Comment by Soullivaneuh** [comment]
Quotes are not necessary, see this working configuration sample:

```yaml
    admin.ssh_key:
        class: AppBundle\Admin\SshKeyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: User, label: SSH Key }
        arguments: [ ~, AppBundle\Entity\SshKey, ~ ]
```

**Comment by Soullivaneuh** [comment]
Tests are style failing.

**Comment by OskarStark** [comment]
let's try again

**Comment by OskarStark** [comment]
done @Soullivaneuh and removed the quotes

**Comment by OskarStark** [comment]
thank you

**Pull request merged**
