### PR TITLE
Hide empty block groups. Issue #2294.

### PR DESCRIPTION
**Pull request by tim96**
Q | A
------------ | -------------
Bug fix? |	no
New feature? |	yes
BC breaks? |	no
Deprecations? |	no
Tests pass? |	yes
Fixed tickets |	#2294 
License |	MIT
Doc PR |	no
Hide empty block groups if it doesn't contain any elements.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@tim96 Why this should solve #2294?

AFAIK they are talking about a `removeGroup` feature, not hiding empty groups.

This look like more a workaround IMO.

**Comment by tim96** [comment]
Hello @Soullivaneuh .
I understand that they want to hide "social" block. if delete all fields from "social" block this code hide empty group block.

**Comment by Soullivaneuh** [comment]
> if delete all fields from "social" block this code hide empty group block.

Yes, this is especially why I think it's a workaround and not an enhancement.

Will investigate harder on this issue.

**Comment by Soullivaneuh** [comment]
I close this for #2996 as this PR fit more with the issue resolution.

Thanks for your contribution.

**Pull request closed without merging**
