### PR TITLE
Construct form with 'tab' without group indicate the 'with' and finalize...

### PR DESCRIPTION
**Pull request by webcomeus**
... with one 'end'

For close tab with one only end:
```php      
             $formMapper
                ->tab('tab1', array('tabwith' => true))
                    ->add('username')
                    ->add('password')
                ->end()
                ->tab('tab2', array('tab' => true))
                    ->with('group1')
                        ->add('username')
                        ->add('password')
                    ->end()
                    ->with('group2', array('collapsed' => true))
                        ->add('enabled')
                        ->add('createdAt')
                    ->end()
                ->end();
```

### CODE REVIEW

**Comment by ckmm** [comment]
Construct form with 'tab' without group indicate the 'with' and finalize...

**Comment by core23** [comment]
Don't get the benefit for this change

**Comment by core23** [comment]
Are you still working on this? Please squash and rebase or close this PR @webcomeus

**Comment by core23** [comment]
There is no gain to the normal way

**Pull request closed without merging**
