### PR TITLE
Update LockExtension.php

### PR DESCRIPTION
**Pull request by phiamo**
#  Subject
The modelmanager lock function requires an int since 4 month, but we are having request data here, which has not been casted yet

I am targeting this branch, because for the recent versions that would make it working.

```markdown
### Changed
- Cast to int before calling typed parameter
```

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]
Since lock expect an int, I think we can update
```
/**
     * @return mixed
     */
    public function getLockVersion(object $object);
```
to
```
    public function getLockVersion(object $object): ?int;
```

**Comment by franmomu** [comment]
Why is this an `int`? couldn't be a `string`?

**Comment by phansys** [comment]
> Why is this an `int`? couldn't be a `string`?

I think a string could be a more flexible decision, since it could allow even semver-like versions.
I guess it's currently using integers because it is tied to the implementation provided by `simplethings/entity-audit-bundle`.

**Comment by VincentLanglet** [comment]
The change was made by @jordisala1991  here: https://github.com/sonata-project/SonataAdminBundle/pull/6261/files#diff-025069819bd8784c6978a0b139f2ecca9d843048035ed18a20e9f60c388259caR31

Maybe we just need to change the typehint.

**Comment by VincentLanglet** [comment]
> I guess it's currently using integers because it is tied to the implementation provided by `simplethings/entity-audit-bundle`.

`Lock` is not tied to auditBundle but the lock method of the EntityManager.
```
    /**
     * Acquire a lock on the given entity.
     *
     * @param object   $entity
     * @param int      $lockMode
     * @param int|null $lockVersion
     *
     * @return void
     *
     * @throws OptimisticLockException
     * @throws PessimisticLockException
     */
    public function lock($entity, $lockMode, $lockVersion = null);
```

**Comment by VincentLanglet** [comment]
@phansys @franmomu What should we do about this PR ?

IMHO we have two solutions
- Merge this
- Allow mixed, and casting to `int` in SonataDoctrineORM bundle (and throwing an exception if it's not numeric ?)

**Comment by franmomu** [comment]
I'm fine leaving an `int`, the only problem I see is that that value could also be `null` I guess and it would return `0` with the casting.

**Comment by VincentLanglet** [comment]
> I'm fine leaving an `int`, the only problem I see is that that value could also be `null` I guess and it would return `0` with the casting.

It won't happen since there is the check:
```
if (!isset($data[$this->fieldName])) {
            return;
        }
```

**Comment by ZZromanZZ** [comment]
This patch cannot merged to v3.* ?

**Comment by ZZromanZZ** [comment]
doctrine/orm >= v2.8 started to compare strictly (`$entityVersion !== $lockVersion`), so `lock_protection` feature is basically unusable

**Pull request merged**
