### PR TITLE
Proof PR dev-kit 503

### PR DESCRIPTION
**Pull request by franmomu**

### CODE REVIEW

**Comment by greg0ire** [comment]
Any idea why the Travis build is now super slow?

**Comment by franmomu** [comment]
> Any idea why the Travis build is now super slow?

Nope, I'll try to see if I can find out something.

**Comment by phansys** [comment]
`make` is consuming [near 10 minutes](https://travis-ci.org/github/sonata-project/SonataAdminBundle/jobs/662628772#L573). I'll try to check that too.

**Comment by greg0ire** [comment]
out of these 10 mn, phpunit reports it is spending 8 of them. Maybe it's the xdebug filter no longer working properly/not being passed to the underlying phpunit?

**Comment by phansys** [comment]
The slower tests seem to be affecting only PHP 7.2.

**Comment by greg0ire** [comment]
Looks like it's already slower on 7.2 in normal builds:

- https://travis-ci.org/github/sonata-project/SonataAdminBundle/builds/662746389?utm_medium=notification&utm_source=github_status
- https://travis-ci.org/github/sonata-project/SonataAdminBundle/builds/662690068?utm_medium=notification&utm_source=github_status

**Comment by VincentLanglet** [comment]
Yeah but we're going from 7 min to 10 min.
And others build goes from 2 min to 4 min.

Isn't cache related ? We should re-run tests.

**Comment by greg0ire** [comment]
I think it might be about the xdebug_prepend_filter not taking into account classes from the `.phpunit` directory. Note that we have switched to phpunit 8 lately, meaning we could probably use pcov now.

**Comment by greg0ire** [comment]
See https://github.com/sonata-project/SonataAdminBundle/pull/5955

**Comment by greg0ire** [comment]
> test pcov

not bad

**Comment by franmomu** [comment]
> > test pcov
> 
> not bad

hahaha nice work @greg0ire !

**Pull request closed without merging**
