### PR TITLE
Possibility to use magic __call for Batch Action in CRUDController

### PR DESCRIPTION
**Pull request by TheRatG**
## Batch actions name

It will be good to have an opportunity use __call() method in CRUDController. Now __call() method is ignored.

As noted [elsewhere] method_exists() does not care about the existence of __call(), whereas is_callable() does. http://php.net/manual/ru/function.method-exists.php#101507

For example, we have actions
```
changeStatus1
changeStatus2
changeStatus3
```
The all could be handled by one common method **batchActionChangeStatus**

### CODE REVIEW

**Comment by TheRatG** [comment]
Hello, thanks for answer. 

Title was updated, some CI checks too. However, I don't know how to pass Travis CI, because there are many errors which aren't relevant to this commits.

**Comment by OskarStark** [comment]
Please rebase your PR to make Travis happy.

Thank you

**Comment by OskarStark** [comment]
Hey 👋 

Travis is still failing, can you have a look?

**Comment by TheRatG** [comment]
Hell @OskarStark thanks for notice.

\Sonata\AdminBundle\Controller\CRUDController::__call already exists as a result method * is_callable* always returns true.

**Pull request closed without merging**
