### PR TITLE
fix(deprectaion): fix deprecation of resolving paremeters in calss name

### PR DESCRIPTION
**Pull request by amine2z**
resolving of parameters in class name will be deprecated in symfony 3. This PR fix this for security secvice declaration

### CODE REVIEW

**Comment by jvasseur** [comment]
I'm not sure but AFAIK the resolving of parameters in class name isn't deprecated, they just stopped using it in the Symfony core.

And this PR is breaking BC.

**Comment by amine2z** [comment]
@jvasseur i dont see how this change can be a BC Break :)

**Comment by rande** [comment]
People using parameters cannot with this PR. It is a BC breaks

**Comment by Koc** [comment]
We can schedule it for 3.0 version of bundle

**Pull request closed without merging**
