### PR TITLE
Remove jquery-form

### PR DESCRIPTION
**Pull request by onEXHovia**
## Subject

Sonata not used this plugin, im not found ajaxForm calls.
Projects that use this plugin should add it to root package.json.

## Changelog

```markdown
### Removed
- Remove jquery-form plugin
```

### CODE REVIEW

**Comment by onEXHovia** [comment]
(rebased)

**Review by core23 — APPROVED** [review]

**Comment by dmaicher** [comment]
@onEXHovia this unfortunately broke some things for me. `ajaxSubmit` is still being used: https://github.com/search?q=repo%3Asonata-project%2FSonataAdminBundle%20ajaxSubmit&type=code

**Comment by VincentLanglet** [comment]
Can someone open a revert/fix ?

**Comment by onEXHovia** [comment]
> @onEXHovia this unfortunately broke some things for me. `ajaxSubmit` is still being used: https://github.com/search?q=repo%3Asonata-project%2FSonataAdminBundle%20ajaxSubmit&type=code

You are right, `jquery-form` plugin provide `ajaxForm` and `ajaxSubmit` methods, im was search only `ajaxForm` method.

**Pull request merged**
