### PR TITLE
3.98.2

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Review by jordisala1991 — APPROVED** [review]

**Comment by jmros** [comment]
the form is broken on this update.  doesn't add "form-control" class to inputs or translate labels.

**Comment by VincentLanglet** [comment]
> the form is broken on this update.  doesn't add "form-control" class to inputs or translate labels.

Do you have the latest persistence bundle version ?

**Comment by jmros** [comment]
no. sorry i don't understand. is not required in composer?  what package you say?

**Comment by VincentLanglet** [comment]
With the sonata admin bundle you certainly use doctrineOrmadminBundle. Which version ?

**Comment by jmros** [comment]
thanks for your answer. is my problem i habe an old version fixed of doctrine-orm-admin-bundle 
 - Upgrading sonata-project/doctrine-orm-admin-bundle (3.23.0 => 3.34.0)

now works.

sorry for my mistake and tanks for your your work

**Pull request merged**
