### PR TITLE
Improve search results hotfix

### LINKED ISSUE #3946: Make search results more ergonomic
I have a project with a **lot** of admin classes.

So when we do a global search, we have this kind of result:

image

As you can see (or not), only one box has a result. This is hard to find it.

I'm thinking of two solution:
- [ ] Colorize by default the boxes with results, with `primary` or `info` colors. An option to deactivate it may be added
- [ ] Add a `show_empty_boxes` option for search. If set to `false`, only boxes with results will be shown

Another idea?

### PR DESCRIPTION
**Pull request by muspelheim**
I am targeting this branch, because another PR was in this branch

Closes #3946, #4334

## Changelog

```markdown
### Added
- Fixed mistake in code
```

## Subject

Mistake in code was found, this mistake throw exception in search page.

### CODE REVIEW

**Comment by jordisala1991** [comment]
You need to rebase on 3.x probably, it is showing a lot of commits.

**Comment by greg0ire** [comment]
@jordisala1991 alternatively we can squash merge

**Comment by jordisala1991** [comment]
Is this pedantic? IMO this has no changelog

**Comment by greg0ire** [comment]
It's an edge case, technically a bugfix but since the bug itself was not released, we should indeed label it as pedantic to help @Soullivaneuh

**Comment by jordisala1991** [comment]
Removed changelog then

**Pull request merged**
