### PR TITLE
Remove unneeded executable bit

### PR DESCRIPTION
**Pull request by greg0ire**
No files should be executable except (maybe) travis scripts.

### CODE REVIEW

**Comment by jordisala1991** [comment]
My laptop is unable to show me all diff.

Can you explain what files did you change? `chmod -x *`?

**Comment by axzx** [comment]
@jordisala1991  755 -> 644

**Comment by jordisala1991** [comment]
Yes, I see, but to what files? all repository or some of the files? Will this make a huge merge conflict on master?

**Comment by greg0ire** [comment]
Here are the affected files : 
- `Resources/public/famfamfam/*`
- `Resources/views/Form/form_admin_fields.html.twig`
- `Tests/Admin/PoolTest.php`

**Comment by greg0ire** [comment]
> Will this make a huge merge conflict on master?

No, git is clever ;)

**Comment by greg0ire** [comment]
This will not blow up the size of the repo either, in case you are wondering ;)

**Comment by jordisala1991** [comment]
styleCI is stuck again?

**Comment by OskarStark** [comment]
Thank you @greg0ire 👍

**Pull request merged**
