### PR TITLE
Remove deprecations

### PR DESCRIPTION
**Pull request by phansys**
## Subject
Remove deprecations.

I am targeting this branch, because these changes respect BC.

Closes #{put_issue_number_here}

## Changelog

```markdown
### Fixed
- Some deprecations in tests.

### CODE REVIEW

**Comment by franmomu** [comment]
Thanks @phansys ! Since this changes don't affect the end user, I changed the label to pedantic and removed the changelog.

**Comment by greg0ire** [comment]
@franmomu we're a library, so in our case the end user is the developer, and we usually consider fixing a deprecations affects them (while changing our coding style or our CI will not).

**Comment by greg0ire** [comment]
Oh but this in tests and only there… so you're right, sorry!

**Comment by greg0ire** [comment]
(plus it should have been patch, minor is for introducing deprecations :sweat_smile: )

**Pull request merged**
