### PR TITLE
Add stimulus bundle in dependency

### PR DESCRIPTION
**Pull request by onEXHovia**
## Subject

Add https://github.com/symfony/stimulus-bundle in dependency
Need for #8221 and next PRs

## Changelog

```markdown
### Added
- Add stimulus bundle in dependency

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

### CODE REVIEW

**Comment by onEXHovia** [comment]
@VincentLanglet failed on 8.0, shouldn't drop PHP 8.0 support in 5.x branch?

or we do bold move for drop php 8.0 in branch 4.x if you look at the statistics https://packagist.org/packages/sonata-project/admin-bundle/php-stats PHP 8.0 percentage is too low

**Comment by VincentLanglet** [comment]
Hi @onEXHovia I'm going to drop PHP 8 and symfony < 6.4 on every project 
cf https://github.com/sonata-project/SonataAdminBundle/pull/8225

**Comment by onEXHovia** [comment]
Rebased

**Comment by VincentLanglet** [comment]
Why is needed as dependency if it's not used yet ?
You can add it the day you'll use it, no ?

Also, we should first decide if the x-editable replacement is ok on 4.x or will be done in 5.x.
If it's in 5.x stimulus is not needed in 4.x.

**Comment by onEXHovia** [comment]
> Why is needed as dependency if it's not used yet ?
> You can add it the day you'll use it, no ?

This package is needed because we will update what is possible in branch 4.x, for example split [admin](https://github.com/sonata-project/SonataAdminBundle/blob/4.x/assets/js/admin.js) to many controllers, move [inline javascript](https://github.com/sonata-project/SonataAdminBundle/issues/7158) from templates to controllers and etc

Step by step will remain js/libs with serious BC, this xeditable, select2... they will already be migrate on branch 5.x with replace to other solutions. Branch 5.x will also include(in my opinion) remove jquery from dependency and full migrate from adminlte to native bootstrap without custom template(adminlte, tabler etc)

Regarding this PR if it is so critical, i can add the library in another PR when start update js.

**Comment by VincentLanglet** [comment]
> Regarding this PR if it is so critical, i can add the library in another PR when start update js.

Yes, I think it's better to add it in another PR when you start to update js.

**Pull request closed without merging**
