### PR TITLE
Docs action_list timezone options

### PR DESCRIPTION
**Pull request by gam6itko**
Based on

https://github.com/sonata-project/SonataAdminBundle/blob/9dc6d53b9563299cee5cf2fbf3c2e358498d97dd/src/Resources/views/CRUD/display_date.html.twig#L18

https://github.com/sonata-project/SonataAdminBundle/blob/9dc6d53b9563299cee5cf2fbf3c2e358498d97dd/src/Resources/views/CRUD/display_datetime.html.twig#L18

### CODE REVIEW

**Comment by phansys** [comment]
Thank you for your first contribution @gam6itko!
SInce this change is not breaking BC, it must target the `3.x` branch.

**Comment by gam6itko** [comment]
@phansys You mean I should to close this PR and create new for 3.x branch?

**Comment by core23** [comment]
You could also change the branch and rebase.

**Comment by gam6itko** [comment]
@core23 here #5810

**Pull request closed without merging**
