### PR TITLE
Cleanup breadcrumbs builder

### LINKED ISSUE #3895: Clean NEXT_MAJOR for #3872

### PR DESCRIPTION
**Pull request by greg0ire**
Closes #3895 

### Changelog

```markdown
### Removed
- The breadcrumbs builder is no longer a dependency of an admin, it must be used directly
```

### Subject

This PR removes the knowledge the admin has of breadcrumbs building completely, reducing it to a still whopping 3061 loc (as opposed to 3127 loc) before.

### CODE REVIEW

**Comment by greg0ire** [comment]
Blocked until #3904 is resolved.

**Comment by greg0ire** [comment]
About the upgrade note, there already is one saying every deprecated thing will be removed. Does this mean I don't need to add an upgrade note?

**Comment by Soullivaneuh** [comment]
> About the upgrade note, there already is one saying every deprecated thing will be removed. Does this mean I don't need to add an upgrade note?

No. Except you think your case is very special and should be detailed. :+1:

**Comment by greg0ire** [comment]
> 416 deletions

:)

**Comment by Soullivaneuh** [comment]
> > 416 deletions

> :)

You such a badass. :stuck_out_tongue:

**Comment by Soullivaneuh** [comment]
LGTM for me.

**Comment by greg0ire** [comment]
> You such a badass. :stuck_out_tongue: 

deal with it

**Comment by Soullivaneuh** [comment]
@greg0ire Coveralls says the coverage decreased on `AbstractAdmin`. Could you take a look and tell me if it's a false positive or not? Thanks.

**Comment by greg0ire** [comment]
> @greg0ire Coveralls says the coverage decreased on AbstractAdmin. Could you take a look and tell me if it's a false positive or not? Thanks.

I removed code that was covered but is not needed anymore (and has therefore no equivalent in the breadcrumbs builder : the admin breadcrumbs builder are no longer needed). I guess this is why coveralls says coverage decreased… If 100% covered code is removed, code coverage can only decrease.

**Comment by Soullivaneuh** [comment]
Ok I trust you for the coverage. :+1: 

The code looks good. I let you review it again and feel free to merge it after that. :+1:

**Comment by Soullivaneuh** [comment]
@greg0ire And if possible, do a merge by squash please. :+1:

**Comment by greg0ire** [comment]
> The code looks good. I let you review it again and feel free to merge it after that. :+1: 

How ? The manually? The button is not clickable…

**Pull request merged**
