### PR TITLE
Autocomplete options

### PR DESCRIPTION
**Pull request by bgaleotti**
Allow to configure *quietMills* and *cache* options.

### CODE REVIEW

**Comment by pulzarraider** [comment]
Please add documentation for this new options in [form_types.rst](https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/doc/reference/form_types.rst)  and than squash the commits.

**Comment by bgaleotti** [comment]
@pulzarraider done!

**Comment by OskarStark** [comment]
thank you, can you please squash your commits?

**Comment by pulzarraider** [comment]
I think, that the commits are ok, because @bgaleotti separates each option into each commit. It could be separated into two PRs.

**Comment by pulzarraider** [comment]
Thank you @bgaleotti

**Pull request merged**
