### PR TITLE
Remove sonataIntl dependency

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because {reason}.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@jordisala1991 Seems like we don't need SonataIntl for tests currently in SonataAdmin.

Maybe it's better to keep templates in SonataIntl and add test there then ?

If 10 repository provides customs template for Sonata, we should'nt had all of them in SonataAdmin, no ?

WDYT ?

**Comment by jordisala1991** [comment]
Then sonata intl will require admin-bundle as dev-dep?

**Comment by jordisala1991** [comment]
SEems like someone already reverted a removal of intlbundle: https://github.com/sonata-project/SonataAdminBundle/pull/5981, maybe we need to investigate further on why it was removed, and then reverted.

**Comment by VincentLanglet** [comment]
> SEems like someone already reverted a removal of intlbundle: #5981, maybe we need to investigate further on why it was removed, and then reverted.

This was done first https://github.com/sonata-project/SonataAdminBundle/pull/5835, the idea of copy pasting the template was the same (but also using others twig extensions)
but this wasn't working so it was reverting.

IMHO we should
- remove sonataIntl from the dev-dependency
- adding test on sonataIntl with sonataAdmin in dev-dependency

In next major we could remove to automatically override the template when sonataIntl is installed. And instead updating the doc for people to do it manually (or to move the code to sonataIntl).

This way
- You can use sonataAdmin without SonataIntl and no occurence of SonataIntl will be in sonataAdmin
- You can use sonataAdmin and SonataIntl without using the templates from SonataIntl
- You can use sonataAdmin and SonataIntl and using the templates from SonataIntl

**Comment by jordisala1991** [comment]
Agree with all.

**Review by jordisala1991 — APPROVED** [review]

**Pull request merged**
