### PR TITLE
Replace twig extensions with twig extra bundle

### PR DESCRIPTION
**Pull request by franmomu**
## Subject

[Twig/extensions is deprecated](https://github.com/twigphp/Twig-extensions). I have only found that we use `truncate` and `trans` filters. `trans` is in `symfony/twig-bridge` that we already use and for the `truncate` filter I added `twig/string-extra`. 

To make it work we can or define a service with the `StringExtension` or tell the user to define that service (but it would be BC break as `u.truncate` won't work without it) or I decided to use `twig/extra-bundle` that will load the extensions used (right now it is only the StringExtension, but [we would probably use IntlExtension as well](https://github.com/sonata-project/SonataAdminBundle/pull/5835)).

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Added
- Added `twig/string-extra` to use `u.truncate` filter
### Removed
- Removed deprecated `twig/extensions` library 
```

### CODE REVIEW

**Comment by franmomu** [comment]
There is a problem I didn't realised, it looks like [the `truncate` function from `String`](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/String/AbstractString.php#L625) doesn't have [the `preserve` parameter that TextExtension has](https://github.com/twigphp/Twig-extensions/blob/master/src/TextExtension.php#L36).

And we are using it in [list_html.html.twig](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/CRUD/list_html.html.twig) and [show_html.html.twig](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/CRUD/show_html.html.twig). Looking at the symfony issues, I haven't found anything about this, maybe there is another way to specify this in the String Component, I'm going to take a look.

**Comment by greg0ire** [comment]
I removed the double backticks from your changelog, since this is markdown.

**Comment by jorrit** [comment]
The String component is still experimental. Perhaps it is not too late to try to make the `|u.truncate()` signature identical to the old `|truncate()` signature? Another solution to be able to remove twig-extensions is perhaps to copy `twig_truncate_filter()` / `twig_wordwrap_filter()` to let's say sonata-project / twig-extensions?

**Comment by franmomu** [comment]
> The String component is still experimental. Perhaps it is not too late to try to make the `|u.truncate()` signature identical to the old `|truncate()` signature? Another solution to be able to remove twig-extensions is perhaps to copy `twig_truncate_filter()` / `twig_wordwrap_filter()` to let's say sonata-project / twig-extensions?

Yes, I created this morning an issue in Symfony, let's see how it goes and if not, we can do as you say and copy/create a function for that.

**Comment by OskarStark** [comment]
For the record https://github.com/symfony/symfony/issues/35567

**Comment by VincentLanglet** [comment]
It's merged https://github.com/symfony/symfony/pull/35649 but it means we need symfony 5.1 to drop Twig extension.

Does it mean we have to write a sonata_truncate filter we a comment `Remove when we drop support of Symfony 4` ?

**Comment by OskarStark** [comment]
IMO we just need to require symfony/string:^5.1 which is fine, as its standalone usable, isn't it?

**Comment by franmomu** [comment]
Closed in favor of https://github.com/sonata-project/SonataAdminBundle/pull/5973

**Pull request closed without merging**
