### PR TITLE
Exclude admin from search when class is null

### PR DESCRIPTION
**Pull request by guillaumesmo**

### CODE REVIEW

**Comment by rande** [comment]
Can you respect CS and add unit test ? thanks

**Comment by Soullivaneuh** [comment]
@guillaumesmo Thanks for your contribution. Some requirements please:

* Could you please explain a little more the use case of this feature?
* Could you please rebase your PR?
* As @rande said, text needs to be fixed and CS respected. Use `make cs` after your rebase to correct it automatically.

Regards.

**Comment by core23** [comment]
ping @guillaumesmo

**Comment by OskarStark** [comment]
btw when could it be possible that getClass() === null ? do you have an example?

**Comment by guillaumesmo** [comment]
Whenever you want to add a page in the admin which is not really related to an entity... I didn't really find an easy way to do that except implementing an admin class with a null entity.

**Comment by core23** [comment]
Please check travis @guillaumesmo

**Pull request closed without merging**
