### PR TITLE
Add missing space when merging label classes

### PR DESCRIPTION
**Pull request by EmmanuelVella**
## Changelog

```markdown
### Fixed
- Fixed missing space when form class is defined in label_attr
```
## Subject

Small PR to fix missing space in form label class attribute.

### CODE REVIEW

**Comment by EmmanuelVella** [comment]
@greg0ire Could you elaborate ? How to do this in PHP ?

**Comment by greg0ire** [comment]
@EmmanuelVella find whatever builds `label_attr` php side, and modify that piece of code to do the merging/whatever is needed.

**Comment by EmmanuelVella** [comment]
Yeah ok, that should be possible ;)

**Comment by jordisala1991** [comment]
Thanks @EmmanuelVella

**Comment by greg0ire** [comment]
@jordisala1991 I'm not completely sure you were supposed to merge that, but it's probably best to patch first and refactor later, so no harm done :P

**Pull request merged**
