### PR TITLE
Use real default LabelTranslatorStrategy in tests

### PR DESCRIPTION
**Pull request by peter-gribanov**
Reproduce bug #4615

## Changelog

```markdown
### Added
- Use real default `LabelTranslatorStrategy` in tests of `ListMapper`
```

## Subject

It's only reproduce bug. It's not fix real bug.

### CODE REVIEW

**Comment by OskarStark** [comment]
shouldn't we have a test for both label strategies?

**Comment by peter-gribanov** [comment]
> shouldn't we have a test for both label strategies?

You asked

> Could you add a failing test here with your configuration, so that we can fix it?

I demonstrated what happens if you write tests with the expectation that the default values are incorrect.
If earlier you would use a correct label translator strategy, then problem #4615 could be avoided.

**Comment by peter-gribanov** [comment]
How long will this continue?

**Comment by OskarStark** [comment]
Imo we can close this, as it is fixed in #4615 

https://github.com/sonata-project/SonataAdminBundle/issues/4615#issuecomment-324562665

**Comment by peter-gribanov** [comment]
@OskarStark  Let's hope that this problem does not happen again.

**Pull request closed without merging**
