### PR TITLE
Move initialization of filters before select2 to properly detect if advanced filters should be visible

### PR DESCRIPTION
**Pull request by pulzarraider**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3347
| License       | MIT

Fixed by moving the code before select2 initializing code.

### CODE REVIEW

**Comment by whitewhidow** [comment]
will try to test & verify this later on this day, thx @pulzarraider

**Comment by clytemnestra** [comment]
Any progress? @whitewhidow

**Comment by whitewhidow** [comment]
sorry was really bussy for a sec,  will try to take a look today, again, sorry for the delay

**Comment by OskarStark** [comment]
thank you for the testing @whitewhidow :+1:

**Comment by whitewhidow** [comment]
@OskarStark @clytemnestra , i can confirm this does the trick ! (srry about the delay :) )

**Comment by OskarStark** [comment]
@pulzarraider can you then please merge your PR?

**Comment by pulzarraider** [comment]
Done :) Thank you for testing @whitewhidow

**Comment by Soullivaneuh** [comment]
Should not be merged on 2.3 @pulzarraider?

**Comment by pulzarraider** [comment]
No, this bug affects only refactored advanced filters from `master` version.

**Pull request merged**
