### PR TITLE
#3529 "Undefined index: choice_list" with Symfony 3.0

### PR DESCRIPTION
**Pull request by sbooker**

### CODE REVIEW

**Comment by zajca** [comment]
Why this is failing? I'm actually using this patch other way choice type is not working with 3.0

**Comment by sbooker** [comment]
@zajca 
Show you code please.

**Comment by zajca** [comment]
@sbooker 
I don't have to, I'm using yours :D
I wasn't accurate, this fixed for me, ```sonata_type_model``` not choice
```
                $builder->addViewTransformer(
                    new ModelsToArrayTransformer(
                        new LazyChoiceList($options['choice_loader']),
                        $options['model_manager'],
                        $options['class']),
                    true
                );
```
without your patch this is not working on sf3
```
->add(
                'tags',
                'sonata_type_model',
                [
                    'btn_add' => false,
                    'required' => false,
                    'by_reference' => false,
                    'multiple' => true,
                    'property' => 'title',
                ]
            )
```

**Comment by murnieza** [comment]
You need to order `use` statements alphabetically. See https://github.com/murnieza/SonataAdminBundle/commit/a7c94b3680619f5cb9198266fc03d50056dacd68

**Comment by sbooker** [comment]
@murnieza 
Done

**Comment by OskarStark** [comment]
@core23 @rande can we merge this safely?

**Comment by greg0ire** [comment]
Your P.R. has 2 commits with the exact same message. You need to fix up the second one with the first one.

**Comment by greg0ire** [comment]
Could you please add a test ? It would answer the "safely" part. See #3558 for how to test a widget.

**Comment by core23** [comment]
Not sure if this works with symfony 2.3

**Comment by core23** [comment]
This is a BC break. ``LazyChoiceList`` doesn't exist in symfony 2.3.

**Comment by Soullivaneuh** [comment]
> This is a BC break. LazyChoiceList doesn't exist in symfony 2.3.

@core23 any chance to make it BC?

**Comment by Soullivaneuh** [comment]
@sbooker Directly merge a BC break of this kind is not acceptable.

If you want to continue, please reopen a new PR base on the `3.x` branch with a BC way of your modification.

Don't forget to link the old one. :+1:

**Pull request closed without merging**
