### PR TITLE
Fix admin code escaping in autocomplete

### PR DESCRIPTION
**Pull request by Koc**
I am targeting this branch, because this is bug fix.

Closes -

## Changelog

```markdown
### Fixed
- Fixed autocomplete for cases when admin code uses service id and service id is equal to FQCN ('AppBundle\Admin\CompanyAdmin')
```

## To do

- [x] Use `autoescape js`

### CODE REVIEW

**Comment by jlamur** [comment]
I think that almost everything (if not everything) that is used as a string variable in javascript should be escaped (correct me if I'm wrong). It would be the right moment to ask @Koc to do it, at least in this file. WDYT @OskarStark @jordisala1991?

**Comment by Koc** [comment]
we can wrap some js code with `autoescape js` instead of escaping each item separateley.

**Comment by greg0ire** [comment]
> we can wrap some js code with autoescape js instead of escaping each item separately.

Yes please, please do that instead, it makes sense.

**Comment by greg0ire** [comment]
Also, please update your todo list

**Comment by javiereguiluz** [comment]
Is there anything we could do to help you prioritize this bug fix? Thanks!

**Comment by greg0ire** [comment]
Anyone in a hurry can feel free to carry this PR and use `autoescape js` as asked.

ping @Koc though if you want to change this yourself.

**Comment by Koc** [comment]
I've rebased by commit and rewrited with autoescape (with removing old `|e('js')`

But travis failed. https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Tests/Controller/CRUDControllerTest.php#L619 we rewrite `parameters` field with an empty array and expexts that this empty array contains `admin` index. WTF?

**Comment by greg0ire** [comment]
@Koc I think this is unrelated, because it only fails on sf3.3. Do you reproduce it locally w/o your changes?

**Comment by greg0ire** [comment]
See #4685

**Comment by Koc** [comment]
@greg0ire my laptop now in repair shot and I haven't properly configured env for checking it. In any case - tests seems invalid. Why we expects some key in empty array?

Can anybody do manual checks of this branch? I am afraid that `block` can override `autoescape` outside it.

**Comment by greg0ire** [comment]
Triggering a new build, the tests are supposed to pass now. Sorry for your laptop @Koc !
@javiereguiluz , or anyone else, can you test if this fixes the issue you experienced?

**Comment by jordisala1991** [comment]
ping @javiereguiluz 

Can you test if it works? Code looks ok to me

**Comment by greg0ire** [comment]
please give this a final review @sonata-project/contributors

**Comment by greg0ire** [comment]
Thanks @Koc !

**Pull request merged**
