### PR TITLE
Remove large and unneeded resources

### PR DESCRIPTION
**Pull request by jorrit**
## Subject

I am trying to optimize the size of my Docker container and a quick review using WinDirStat gave some surprising large files in src/Resources/private/SonataCoreBundleAssets/vendor:

- moment/min/tests.js: 3.3 MB
- ionicons/cheatsheet.html: 1.2 MB
- eonasdan-bootstrap-datetimepicker/src/nuget/NuGet.exe: 1.6 MB

These files are copied to public on `assets:install` so they count twice if sym/hardlinking is not available. I think that these files are unnecessary under any circumstance and can be removed without breaking the backwards compatibility promise. Many more files could be removed, but the ones above are the largest by a wide margin.

I am targeting this branch, because no user should depend on these files.

## Changelog

```markdown
### Removed
- Removed several large unnecessary resources from public/bundles/sonatacore/vendor.
```

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

**Review by core23 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Those assets are handled by bower, so if someone updates packages they will appear again

**Comment by VincentLanglet** [comment]
> Those assets are handled by bower, so if someone updates packages they will appear again

I'm not sure we're doing that often

**Comment by jorrit** [comment]
I could add a .gitignore to the SonataCoreBundle directory excluding these files so they will never be committed again.

**Comment by VincentLanglet** [comment]
> I could add a .gitignore to the SonataCoreBundle directory excluding these files so they will never be committed again.

I like this idea

**Comment by jorrit** [comment]
I've added the .gitignore file.

**Review by VincentLanglet — APPROVED** [review]

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thank you @jorrit

**Pull request merged**
