### PR TITLE
Replace maximumSelectionSize by maximumSelectionLength

### LINKED ISSUE #7980: maximumSelectionSize has been replaced by maximumSelectionLength in Select 2
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              4.21.0 4.21.0 The missing Symfony Admin Generator
sonata-project/block-bundle              4.19.0 4.19.0 Symfony SonataBlockBundle
sonata-project/cache                     2.2.0  2.2.0  Cache library
Package sonata-project/cache is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/doctrine-extensions       2.0.1  2.0.1  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 4.8.0  4.8.0  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  3.0.0  3.0.0  Lightweight Exporter library
sonata-project/form-extensions           1.18.0 1.18.0 Symfony form extensions
sonata-project/twig-extensions           2.0.0  2.0.0  Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/asset                      v6.1.5  v6.1.5  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/cache                      v6.1.7  v6.1.7  Provides extended PSR-6, PSR-16 (and tags) implementations
symfony/cache-contracts            v3.1.1  v3.1.1  Generic abstractions related to caching
symfony/config                     v6.1.3  v6.1.3  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v6.1.7  v6.1.7  Eases the creation of beautiful and testable command line interfaces
symfony/dependency-injection       v6.1.5  v6.1.5  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v3.1.1  v3.1.1  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v6.1.7  v6.1.7  Provides integration for Doctrine with various Symfony components
symfony/dotenv                     v6.1.0  v6.1.0  Registers environment variables from a .env file
symfony/error-handler              v6.1.7  v6.1.7  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v6.1.0  v6.1.0  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v3.1.1  v3.1.1  Generic abstractions related to dispatching event
symfony/expression-language        v6.1.6  v6.1.6  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v6.1.5  v6.1.5  Provides basic utilities for the filesystem
symfony/finder                     v6.1.3  v6.1.3  Finds files and directories via an intuitive fluent interface
symfony/flex                       v2.2.3  v2.2.3  Composer plugin for Symfony
symfony/form                       v6.1.7  v6.1.7  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v6.1.7  v6.1.7  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-foundation            v6.1.7  v6.1.7  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v6.1.7  v6.1.7  Provides a structured process for converting a Request into a Response
symfony/intl                       v6.1.7  v6.1.7  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/maker-bundle               v1.48.0 v1.48.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/monolog-bridge             v6.1.2  v6.1.2  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.8.0  v3.8.0  Symfony MonologBundle
symfony/options-resolver           v6.1.0  v6.1.0  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v6.1.3  v6.1.3  Provides password hashing utilities
symfony/polyfill-intl-grapheme     v1.27.0 v1.27.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.27.0 v1.27.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-normalizer   v1.27.0 v1.27.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.27.0 v1.27.0 Symfony polyfill for the Mbstring extension
symfony/property-access            v6.1.7  v6.1.7  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v6.1.7  v6.1.7  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v6.1.0  v6.1.0  Provides integration for ProxyManager with various Symfony components
symfony/routing                    v6.1.7  v6.1.7  Maps an HTTP request to a set of configuration variables
symfony/runtime                    v6.1.3  v6.1.3  Enables decoupling PHP applications from global state
symfony/security-acl               v3.3.2  v3.3.2  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v6.1.3  v6.1.3  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v6.1.7  v6.1.7  Symfony Security Component - Core Library
symfony/security-csrf              v6.1.0  v6.1.0  Symfony Security Component - CSRF Library
symfony/security-http              v6.1.7  v6.1.7  Symfony Security Component - HTTP Integration
symfony/serializer                 v6.1.6  v6.1.6  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts          v3.1.1  v3.1.1  Generic abstractions related to writing services
symfony/stopwatch                  v6.1.5  v6.1.5  Provides a way to profile code
symfony/string                     v6.1.7  v6.1.7  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                v6.1.6  v6.1.6  Provides tools to internationalize your application
symfony/translation-contracts      v3.1.1  v3.1.1  Generic abstractions related to translation
symfony/twig-bridge                v6.1.7  v6.1.7  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v6.1.1  v6.1.1  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v6.1.7  v6.1.7  Provides tools to validate values
symfony/var-dumper                 v6.1.6  v6.1.6  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v6.1.3  v6.1.3  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-profiler-bundle        v6.1.6  v6.1.6  Provides a development tool that gives detailed information about the execution of any request
symfony/yaml                       v6.1.6  v6.1.6  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

```
$ php -v
HP 8.1.9 (cli) (built: Aug  5 2022 23:55:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies
    with blackfire v1.80.0~linux-musl-x64-non_zts81, https://blackfire.io, by Blackfire
```

## Subject

In a form element using select2, the `data-sonata-select2-maximumSelectionSize` attribute does not work anymore.
Since the version 4.0 of select2 `maximumSelectionSize` has been replaced by `maximumSelectionLength`.

### PR DESCRIPTION
**Pull request by sterrien**
## Subject

I am targeting the last stable branch, because i'm using it in production.

Closes #7980.

## Changelog

 Since version 4.0 of Select2, maximumSelectionSize has been replaced by maximumSelectionLength

```markdown
### Fixed
- `data-sonata-select2-maximumSelectionLength` attribute
```

### CODE REVIEW

**Comment by eerison** [comment]
Hey @sterrien when you run the production  script 

It changes some files into public folder 
https://github.com/sonata-project/SonataPageBundle/pull/1626/files

Are you committing them?
Like this

**Comment by eerison** [comment]
I guess you need to run the build 

https://github.com/sonata-project/SonataAdminBundle/blob/4.x/package.json#L58

**Comment by eerison** [comment]
to have this fixed, you didn't need to update any js dependency?

**Comment by sterrien** [comment]
> to have this fixed, you didn't need to update any js dependency?

did I update js dependency ? I am not a frontend developer.

I start with a too old version of node. Then a too new.

I finally run with success the `npx encore production` command. Here is my environment :

```
$ node -v
v14.16.0
```

```
$ npm -v
6.14.11
```

```
$ npx -v
6.14.11
```

I have run these too commands :
```
npm clean-install
npx encore production
```

And I've commited the `app.js` file.

**Comment by eerison** [comment]
your pipeline is falling because it's missing you compile something!

**Comment by eerison** [comment]
Thanks @VincentLanglet 😄 ❤️

**Comment by eerison** [comment]
I guess you can put your PR ready to review @sterrien :)

**Review by VincentLanglet — DISMISSED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
And thanks @sterrien :)

**Comment by sterrien** [comment]
Thx @VincentLanglet for your help !

I'm definitely not a frontend dev 😆

**Pull request merged**
