### PR TITLE
Removed extra 't' in targetting

### PR DESCRIPTION
**Pull request by RomainSanchez**
I am targetting this branch, because this is pedantic.

### CODE REVIEW

**Comment by greg0ire** [comment]
http://www.future-perfect.co.uk/grammar-tip/is-it-targetted-or-targeted/

> Mistakes are also often made with ‘target’. This happens because it is thought to be like ‘get’ and ‘getting’, but it is not, as the natural stress is not in the same place.
>
> This follows the standard rules exactly. It becomes just ‘targeting/targeted’, because there is usually no doubling when the preceding vowel is unstressed.

**Comment by greg0ire** [comment]
Thanks @RomainSanchez

**Comment by core23** [comment]
This is a typo in the admin bundle only? Not part of the dev kit?

**Comment by greg0ire** [comment]
Woops, you're right, this PR should have been done on dev kit. Can you fix it @RomainSanchez ?

**Comment by OskarStark** [comment]
Imo this wasn't wrong: https://en.wiktionary.org/wiki/targetting

**Comment by greg0ire** [comment]
Maybe not wrong but obsolete at least.

**Comment by RomainSanchez** [comment]
> Can you fix it @RomainSanchez ?

Yea but how ?

**Comment by greg0ire** [comment]
Here is the offending repo/file : https://github.com/sonata-project/dev-kit/search?utf8=%E2%9C%93&q=targetting

**Comment by RomainSanchez** [comment]
https://github.com/sonata-project/dev-kit/pull/235

**Comment by RomainSanchez** [comment]
Anything else ?

**Comment by greg0ire** [comment]
Nope.

**Pull request merged**
