### PR TITLE
Fix collection management

### PR DESCRIPTION
**Pull request by netounet**
setup_collection_buttons only need to be run once on document scope.
Call it in shared setup register multiple listener on add button in ajax loaded admin and add multiple item in collection on click

### CODE REVIEW

**Comment by netounet** [comment]
Fix PR to handle new collection counter management. Need to initialize counter of loaded collections

**Comment by netounet** [comment]
Just adding a fix for collection in collection

**Comment by rande** [comment]
I think this issue was already fixed.

ping @EmmanuelVella

**Comment by netounet** [comment]
@rande : No this PR fix 2 bugs : 
- setup_collection_buttons dont have to be called more than one time so it can't be in shared setup
- Collection counter must be called in shared_setup AND in event sonata-admin-append-form-element to init counter on embed collection

That's why i add a setup_collection_counter 

@EmmanuelVella : what do you think about it ?

**Comment by Storke** [comment]
This PR resolves an issue in dev-master (already exists as #2909). 

I replaced dev-master's file Admin.js by netounet's one and it works fine.

**Comment by netounet** [comment]
@rande the issue still exists, what about merging the PR ?

**Comment by Soullivaneuh** [comment]
@netounet not sure but I think @rande is right.

This is already fixed in #2858 and #2889.

Just rebase your PR, you will see if it's the same and solve your issue.

**Comment by netounet** [comment]
I've just rebased my PR on master (first time i do it, hope made it correct :p)

It fix issue #2909 as @Storke comment earlier

**Comment by Soullivaneuh** [comment]
@netounet have you check for no regressions like revealed on #2858 and #2889?

Do not want to get this broken again. :-)

**Comment by netounet** [comment]
No regression at this point, if you look at my PR i only refactor to separate counter initialization and binding listener on add button to call the counter initialization in shared setup and on sonata-admin-append-form-element event for embed form with collections

**Comment by Soullivaneuh** [comment]
OK for me so. :+1:

**Comment by Soullivaneuh** [comment]
@Storke is right. This fixes #2909 too. :+1:

**Pull request merged**
