### PR TITLE
Enhancement: Use symfony/deprecation-contracts

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
I'm wondering if we should delay this to 4.0, in order to keep consistency with all our deprecation message

**Comment by franmomu** [comment]
I guess the `$package` argument makes sense for a monorepo, but since here it's always the same, maybe we can create our function (that could call that one) with always in this case `sonata-project/admin-bundle`, a `sonata_trigger_deprecation` or something like that.

**Comment by OskarStark** [comment]
I thought the same, maybe we should create a package 📦 which depends on this contract to have simpler methods:

deprecate_method_with_replacement

deprecate_method_without_replacement

and ofc simplify the package parameter

**Comment by OskarStark** [comment]
Closing for now

**Pull request closed without merging**
