### PR TITLE
Remove useless dependency

### PR DESCRIPTION
**Pull request by VincentLanglet**
Pedantic

### CODE REVIEW

**Review by phansys — APPROVED** [review]

**Comment by phansys** [comment]
Maybe this should be considered for a minor, and the removed dependency should be listed in the "Removed" section of the changelog, regardless it was used or not.

**Comment by phansys** [comment]
Just for the records, the requirement was introduced at #6288.

**Comment by VincentLanglet** [comment]
> Maybe this should be considered for a minor, and the removed dependency should be listed in the "Removed" section of the changelog, regardless it was used or not.

It's a dev dependency

**Comment by phansys** [comment]
>It's a dev dependency

You're right. Forget about my comment.

**Review by OskarStark — APPROVED** [review]

**Pull request merged**
