### PR TITLE
Better translation for subclass admins

### PR DESCRIPTION
**Pull request by core23**
With this commit you have a better translation key if you are using the same subclass for multiple admins.

Before:
If you have a child class with the key "bar" in the FooAdmin, the translation label would be "bar".

After:
If you have a child class with the key "bar" in the FooAdmin, the translation label would be "foo_bar".

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Nice idea but would be BC break for existing project translations.

Do we have a way to handle BC?

**Comment by core23** [comment]
This would indeed be a BC. In my oppinion there is no beautiful way to handle a translation fallback like

    {% if (admin.label ~ '_' ~ subclass) == (admin.label ~ '_' ~ subclass)|trans({}, admin.translationdomain|default('SonataAdminBundle')) %}
        {{ subclass|trans({}, admin.translationdomain|default('SonataAdminBundle')) }}
    {% else %}
        {{ (admin.label ~ '_' ~ subclass) == (admin.label ~ '_' ~ subclass)|trans({}, admin.translationdomain|default('SonataAdminBundle')) }}
    {% endif %}

**Comment by core23** [comment]
Added BC hint in changelog

**Comment by Soullivaneuh** [comment]
If this is BC and can't be resolved, this should be on an upgrade note.

And this PR will not be merged until 3.0.

**Pull request closed without merging**
