### PR TITLE
removed outdated and not used CREDITS file

### PR DESCRIPTION
**Pull request by OskarStark**
### Changelog

```markdown
### Removed
- CREDITS file
```

### Subject

We don't want to maintain all vendor libraries here

### CODE REVIEW

**Comment by OskarStark** [comment]
ping @greg0ire

**Comment by greg0ire** [comment]
Django is not a vendor. This file is not about vendors, it's about thanking inspiring or useful projects.

**Comment by OskarStark** [comment]
but we only have this in the admin bundle

**Comment by OskarStark** [comment]
otherwise we could create the file in the dev kit an use it across all our bundles

**Comment by greg0ire** [comment]
The Django project only inspired the admin bundle

**Comment by Soullivaneuh** [comment]
> Django is not a vendor.

:+1: 

> This file is not about vendors

:-1:, famfamfam is a vendor used befor font-awesome and jQuery is a still used library.

> otherwise we could create the file in the dev kit an use it across all our bundles

:+1: IMHO. BTW, we could take profit to add missing big dependencies like AdminLTE.

**Comment by greg0ire** [comment]
AdminLTE is not used in every bundle, is it ?

**Comment by OskarStark** [comment]
> AdminLTE is not used in every bundle, is it ?

we are using the markup in all bundles to integrate them seamlessy into the admin bundle

anyway, we could maintain it in the dev kit, because we, as sonata would give credits in general.

font-awesome for example is used across a lot of sonata bundles

**Comment by greg0ire** [comment]
Ok then.

**Comment by OskarStark** [comment]
Created a dev-lkit PR here: https://github.com/sonata-project/dev-kit/pull/102

**Pull request merged**
