### PR TITLE
Add support for translation-contracts v3

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Added
- Added support for `symfony/translation-contracts` v3.
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
Latest release for string-extra added support for it, so it is unlocked: https://github.com/twigphp/string-extra/commit/fad4d7f2b17aa8b655d3f7c0fd318ef2980c077b

It has to be added to media-bundle too.

**Comment by VincentLanglet** [comment]
Phpstan failing

This seems weird, it seems related to the 2.10 version, but SourceIteratorInterface is not supposed to be generic... https://github.com/sonata-project/exporter/blame/2.x/src/Source/SourceIteratorInterface.php

**Comment by jordisala1991** [comment]
> Phpstan failing
> 
> This seems weird, it seems related to the 2.10 version, but SourceIteratorInterface is not supposed to be generic... https://github.com/sonata-project/exporter/blame/2.x/src/Source/SourceIteratorInterface.php

I am trying to fix phpstan, lets see if psalm is happy too... about the generic thing it is strange indeed.

**Comment by jordisala1991** [comment]
The remaining error should be a problem for exporter library or something wrong in phpstan side. @VincentLanglet  it does complain if I add the generic or if I don't add it.

**Comment by VincentLanglet** [comment]
> The remaining error should be a problem for exporter library or something wrong in phpstan side. @VincentLanglet it does complain if I add the generic or if I don't add it.

Does https://github.com/sonata-project/exporter/pull/567 solve the issue ? You can just copy paste the template of SourceIteratorInterface in your vendor and run again phpstan after you removed the cache

**Comment by jordisala1991** [comment]
> > The remaining error should be a problem for exporter library or something wrong in phpstan side. @VincentLanglet it does complain if I add the generic or if I don't add it.
> 
> Does [sonata-project/exporter#567](https://github.com/sonata-project/exporter/pull/567) solve the issue ? You can just copy paste the template of SourceIteratorInterface in your vendor and run again phpstan after you removed the cache

Maybe here it misses a second argument on the generic? https://github.com/sonata-project/exporter/blob/b989c08df340fcb5925ad7f17d86e7d86cc2c8aa/src/Source/SourceIteratorInterface.php#L21

I will try to find time tomorrow to test it.

**Comment by VincentLanglet** [comment]
> Maybe here it misses a second argument on the generic? https://github.com/sonata-project/exporter/blob/b989c08df340fcb5925ad7f17d86e7d86cc2c8aa/src/Source/SourceIteratorInterface.php#L21

I tried without succees.
I think it's better to make the SourceIteratorInterface generic since Iterator will be.
This way in next major the update will be easier for the phpdoc.

**Comment by VincentLanglet** [comment]
Should be fixed by https://github.com/sonata-project/exporter/pull/567

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
I assume a release will be needed for the media bundle @jordisala1991 ? ^^
I'll try tomorrow

**Pull request merged**
