### PR TITLE
Adding html field conversion for xEditable

### PR DESCRIPTION
**Pull request by netounet**
Permit inline edit of html field in list.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Can you please explain the goal of this PR with a concrete use case?

**Comment by netounet** [comment]
enable xeditable on list field which type is set to html.
actually if you set 'editable' => true for html typed fields it doesn't work as it is not declared in SonataAdminExtension.
The next step could be to implement wysihtml5 in sonata admin to enable rich text editing

**Comment by netounet** [comment]
@Soullivaneuh give you a use case of this PR to be as clear as possible.

in configureListFields i configure a field to display as follow

->add('end_call_comment','html',array('editable' => true, 'truncate' => true,))

For the moment 'editable' => true as no effect because the template base_list_field.html.twig search xeditable type corresponding to sonata "html" type (which is handle by SonataAdminExtension) to activate xeditable

**Comment by Soullivaneuh** [comment]
@rande I let you the choice for this PR.

**Comment by OskarStark** [comment]
@Soullivaneuh i think the use case is valid and the code change is small, so why not?

**Comment by Soullivaneuh** [comment]
@OskarStark I didn't say no. I just don't have enough knowledge of this section to make a decision alone.

So I prefer to let @rande review and decide.

**Comment by OskarStark** [comment]
:+1:

**Comment by netounet** [comment]
@rande nice thks for merge

**Pull request merged**
