### PR TITLE
Merge 3.x

### PR DESCRIPTION
**Pull request by greg0ire**
Maintenance merge

### CODE REVIEW

**Comment by jordisala1991** [comment]
I could be wrong, but seems like the error is located on `AbstractAdmin::getExtensions()`. Maybe is not mocked?

**Comment by greg0ire** [comment]
You're right, but also, `getBatchActions` is final…

**Comment by greg0ire** [comment]
I recall telling someone to mock the class and not the interface b/c of missing methods. The right solution might be to use a real admin.

**Comment by jordisala1991** [comment]
Ugh, it is only final on master....

But on master you should have all methods on the interface right?

**Comment by greg0ire** [comment]
Maybe… but that back and forth between mocking the class / the interface could be solved once and for all by not mocking them :P

**Comment by jordisala1991** [comment]
I am not sure about the implications of not mocking AbstractAdmin there. it could create more troubles because we are calling some methods like `hasRoute`, or `hasAccess`. Do you want to mock that internal code?

IMO I prefer to not use mocks only for small classes that will not hurt if we do not mock them. I would say, lets try to use the interface, and if it doesn't work, try with a real admin, maybe is not that bad.

**Comment by greg0ire** [comment]
@jordisala1991 I reverted to mocking the interface, which… seems to work! Maybe missing methods were added on master? Anyway, this class is the biggest ISP violation I have ever seen :P

**Comment by jordisala1991** [comment]
Yep, it was missing on 3.x because adding method to interface is BC break

**Comment by greg0ire** [comment]
It's green :) Please merge!

**Comment by jordisala1991** [comment]
Thanks @greg0ire :)

**Pull request merged**
