### PR TITLE
Support editable mode on FieldDescriptionInterface::TYPE_ENUM

### PR DESCRIPTION
**Pull request by onEXHovia**
## Subject

```php
    protected function configureListFields(ListMapper $list): void
    {
        $list
            ->add('status', FieldDescriptionInterface::TYPE_ENUM, [
                'editable' => true,
                'class' => Status::class,
                'choices' => Status::cases(),
            ])
            ->add(ListMapper::NAME_ACTIONS, null, [
                ListMapper::TYPE_ACTIONS => [
                    'edit' => [],
                    'delete' => [],
                ],
            ])
        ;
    }
```

## Changelog

```markdown
### Added
- Support editable mode on `FieldDescriptionInterface::TYPE_ENUM`
```

### CODE REVIEW

**Review by VincentLanglet — DISMISSED** [review]

**Comment by VincentLanglet** [comment]
CI need to be fixed, but PR looks ok

**Review by VincentLanglet — COMMENTED** [review]
You'll have to skip the test in PHP 8 since BackedEnum doesn't exist I think

**Comment by onEXHovia** [comment]
CI green, ready for review

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks

**Pull request merged**
