### PR TITLE
Removed inline scripts

### PR DESCRIPTION
**Pull request by core23**
I am targeting this branch, because this is BC.

## Changelog

```markdown
### Removed
- Removed inline scripts for `SONATA_CONFIG` and `SONATA_TRANSLATIONS`
```

## Subject
Inline scripts are bad, because they allow XSS and other evil stuff.

### CODE REVIEW

**Comment by greg0ire** [comment]
Thanks @core23 !

**Comment by psyray** [comment]
[This part](https://github.com/sonata-project/SonataAdminBundle/pull/5240/files#diff-072497236e2956a1ca2fc388be05034eR104) seems to be a BC break.
A lot of bundles (like SonataUser and others custom bundle based on sonata admin) overrides this part to change the class (to change skin for example) or add one more class.
By adding the sonata config here this breaks a lot of JS thing, look at my [issue opened](https://github.com/sonata-project/SonataUserBundle/issues/1051).
I think you should add a block for this configuration, by this way we can add it to the override with {{ parent() }}.
This prevents adding the sonata config in the override, which is bad.
What do you think ?

**Comment by psyray** [comment]
FYI
SonataPageBundle is also overriding this block in the [compose.html.twig](https://github.com/sonata-project/SonataPageBundle/blob/973e209f5c0856e66a3b4f1728bcb7b452481f32/src/Resources/views/PageAdmin/compose.html.twig#L22)

**Comment by psyray** [comment]
PR submitted #5261

**Comment by core23** [comment]
> @core23 any chance you can check this out and fix it, or we should revert maybe.

We could also make a hotfix by moving the code to an other element, e.g. 
```html
<meta data-sonata-admin=... />
```

**Comment by psyray** [comment]
This could be a solution.
Anyway I think the sonata config should be in a block which is exclusive to permit override without breaking anything.

**Pull request merged**
