### PR TITLE
Fixed 2 misspellings of "sonata_choice_field_mask"

### PR DESCRIPTION
**Pull request by blaues0cke**
Found some typos in https://sonata-project.org/bundles/admin/master/doc/reference/form_types.html# an fixed them.

### CODE REVIEW

**Comment by greg0ire** [comment]
The docs build is failing

**Comment by greg0ire** [comment]
```
/home/travis/build/sonata-project/SonataAdminBundle/Resources/doc/reference/form_types.rst:327: WARNING: Title underline too short.

sonata_type_choice_field_mask

^^^^^^^^^^^^^^^^^^^^^^^^
```
Please make it longer

**Comment by OskarStark** [comment]
Ping @blaues0cke

**Comment by OskarStark** [comment]
I fixed the underline

**Comment by greg0ire** [comment]
Thanks @OskarStark @blaues0cke

**Pull request merged**
