### PR TITLE
fast fix for row numbering

### PR DESCRIPTION
**Pull request by Spektr**

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you explain what the Problem is?

**Comment by Spektr** [comment]
For example, I have a collection of 5 elements (ids is 1,2,3,4,5). Then I delete 3rd element (ids: 1,2,4,5) and add a new one (ids:1,2,4,5,5). It happens because next id is calculated through child elements length. This bug is fixed in next versions, but I want a fix for v.2.3.

**Comment by OskarStark** [comment]
Can you find the commit in the current master, so that we can cherry pick this one instead of creating a new commit?

**Comment by Spektr** [comment]
I think, it is not single commit. Maybe #2831 (but it tries to detect children array length before they added). Final solution is #2892 (but it is not complete).

**Comment by OskarStark** [comment]
Ok, please squash your commit

**Comment by Spektr** [comment]
Sorry, but i looked closer and there is another bug. In fact, this is not a good idea to generate field name using counter of DOM elements. New bug appears when we start to edit already created collection with ids like (1,2,5,8) and do not have a js counter tracking real ids instead of DOM count.

**Comment by OskarStark** [comment]
this looks ok to me, why do we have 1,2,3,4 ??

1,2,5,8 is :+1:

**Comment by OskarStark** [comment]
ping @sonata-project/contributors

**Comment by Spektr** [comment]
Because next element will be 5-th ([1,2,5,8].length === 4) and it'll overwrite existing one.

**Comment by OskarStark** [comment]
next element should be 9 then, just find the biggest number and add +1, what do you think?

**Comment by Spektr** [comment]
This solution requires using regexp for detecting all ids on page and I do not want to be involved in it ^_^. Sorry for your time.

**Pull request closed without merging**
