### PR TITLE
Add flash manager interface.

### PR DESCRIPTION
**Pull request by tim96**

### CODE REVIEW

**Comment by core23** [comment]
Why do you need a FlashManager in an ``Admin``? Please use the ``CRUDController`` for messaging stuff.

**Comment by tim96** [comment]
@core23 hello. 

>  Please use the CRUDController for messaging stuff.

It was my first idea to put flash message with different function in CRUDController instead of replace whole action. I try to do it, but after @Soullivaneuh suggest #3167 to using admin class to override flash message without create controller and override message. I only try to check this idea.

**Comment by core23** [comment]
Sorry, we will not doing this :-1: 

The Admin class in big enough. We should reduce this class instead of adding new stuff.

**Comment by tim96** [comment]
@core23 hello. If you close this PR, what do you think about this approach #3587 ?

**Pull request closed without merging**
