### PR TITLE
[Show] Add param & return type hints to all files in the Show dir

### PR DESCRIPTION
**Pull request by tambait**
## Subject

This is a follow up of #6404 to add param & return type hints.

## Changelog

```markdown
### Added
- Added parameter type hints to `ShowMapper`

### CODE REVIEW

**Review by core23 — CHANGES_REQUESTED** [review]
Can you do this on the stable branch?

**Comment by VincentLanglet** [comment]
I agree that 100% on this PR can be done on 3.x @tambait :)

**Comment by tambait** [comment]
Thanks for reviewing. What about other return type hints which were added to the same file on master branch before my additions? I changed just few lines based on missing type hint report, but I see that ShowMapper on master branch have more type hints added compared to the file on 3.x branch.

**Comment by VincentLanglet** [comment]
> Thanks for reviewing. What about other type hints (both param & return) which were added to the file on master branch before my additions? I changed just few lines based on missing type hint report, but I see that ShowMapper on master branch have more type hints added compared to the file on 3.x branch. 

I would recommend to just backport this pr (with only phpdoc) to 3.x (without changing anything else) and then we will merge 3.x into master.

Adding typehint on 3.x is a BC-break.

**Comment by tambait** [comment]
Can I do that just by editing this PR and changing base from master to 3.x?
Do you recommend to also add (in separate PR) phpdoc parts from PR's 6487 & 6489 to 3.x that were discussed by you and other contributors?

**Comment by VincentLanglet** [comment]
> Can I do that just by editing this PR and changing base from master to 3.x?

I think you can't, but maybe a cherry pick will work without (too many) conflict

```
git checkout 3.x
git checkout -b myBranch
git cherry-pick 422a810
```

> Do you recommend to also add now (in separate PR) phpdoc parts from PR's 6487 & 6489 to 3.x that were discussed by you and other contributors?

It's not mandatory, but it's more than welcomed !

**Comment by VincentLanglet** [comment]
Closing in favor of https://github.com/sonata-project/SonataAdminBundle/pull/6496

**Pull request closed without merging**
