### PR TITLE
Remove core-bundle presence check

### PR DESCRIPTION
**Pull request by Soullivaneuh**
### Subject

The bundle is required on the composer.json file.

Check it manually makes no sense.

### CODE REVIEW

**Comment by Koc** [comment]
bundle can be downloaded but not enabled in the kernel

**Comment by Soullivaneuh** [comment]
Then the application will not work.

According to the message, this is more a transition message when moving things to core-bundle, on a new minor version, when semver was not... very respected. :wink:

**Comment by Soullivaneuh** [comment]
Plus, this bundle require BlockBundle too and certainly others to work.

Shall me check the present of each one? No, this is not our work.

**Comment by Koc** [comment]
Sounds reasonable, thanx

**Pull request merged**
