### PR TITLE
Replace calls to `call_user_func()` and `call_user_func_array()`

### PR DESCRIPTION
**Pull request by phansys**
## Subject

Replace calls to `call_user_func()` and `call_user_func_array()`.

I am targeting this branch, because these changes respect BC.

### CODE REVIEW

**Comment by core23** [comment]
Can you give a hint, why we should use these syntax?

**Comment by phansys** [comment]
> Can you give a hint, why we should use these syntax?

I feel this syntax more natural, since the removed functions were not required at all. IMO, all the possible cases are supported without calling them (https://3v4l.org/rPCnT). Also, avoiding the overhead of a unnecessary function call is not depreciable for me.

BTW, I didn't remember that I've created a PR with some of these changes against `master` some time ago (#5459).

**Comment by core23** [comment]
Do you know if this will work with phpstan or what is suggested in general?

**Comment by phansys** [comment]
> Do you know if this will work with phpstan or what is suggested in general?

I just ran `phpstan analyze src/ --level 0` and there are no issues related to these changes.

**Comment by greg0ire** [comment]
Thanks @phansys !

**Pull request merged**
