### PR TITLE
forgotten read_only options

### PR DESCRIPTION
**Pull request by axzx**

### CODE REVIEW

**Comment by wslaghekke** [comment]
Works like a charm,
Thanks :+1:

**Comment by OskarStark** [comment]
looks good to me

@axzx can oyu please provide a screenshot WITH and WITHOUT readonly set for this input? thank you

@greg0ire @core23 what do you think?

**Comment by greg0ire** [comment]
LGTM

**Comment by OskarStark** [comment]
thanks!

**Comment by axzx** [comment]
WITHOUT readonly I had an error. 
thanks for a merge

**Comment by OskarStark** [comment]
youre welcome, keep on contributing ;-)

**Pull request merged**
