### PR TITLE
Header comment fixer

### PR DESCRIPTION
**Pull request by Soullivaneuh**
@rande We have two different header:

* `This file is part of the Sonata package.`
* `This file is part of the Sonata project.`

Which one should we choose?

### CODE REVIEW

**Comment by rande** [comment]
@Soullivaneuh the official name is : "Sonata Project", so the header should be "Sonata Project package" or just "Sonata Project"

**Comment by Soullivaneuh** [comment]
> so the header should be "Sonata Project package" or just "Sonata Project"

Well, which one? :-P

BTW, didn't find any `Sonata Project package` on the code.

**Comment by rande** [comment]
The "Sonata Project" is present on some files... So yes, the correct header should be "This file is part of the Sonata Project package."

You can also add the missing licence file :/

**Comment by Soullivaneuh** [comment]
> You can also add the missing licence file :/

Yes indeed. The MIT one ? Like Symfony?

**Comment by rande** [comment]
Yes, MIT

**Comment by Soullivaneuh** [comment]
@rande Can you validate the diff for header? Going to add License file on another PR.

**Comment by Soullivaneuh** [comment]
@rande PR ready. Merge it if seems OK for you.

**Pull request merged**
