### PR TITLE
Fix violations error handling

### LINKED ISSUE #7945: Validation error doesn't contain expected fields
#### Sonata packages

<details><summary>show</summary>
<p>

```
Direct dependencies required in composer.json:
sonata-project/admin-bundle              4.19.0 4.19.0 The missing Symfony Admin Generator
sonata-project/doctrine-orm-admin-bundle 4.8.0  4.8.0  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.13.0 3.0.0  Lightweight Exporter library
sonata-project/media-bundle              4.5.1  4.5.1  Symfony SonataMediaBundle

Transitive dependencies not required in composer.json:
sonata-project/block-bundle              4.18.0 4.18.0 Symfony SonataBlockBundle
sonata-project/cache                     2.2.0  2.2.0  Cache library
Package sonata-project/cache is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/doctrine-extensions       2.0.1  2.0.1  Doctrine2 behavioral extensions
sonata-project/form-extensions           1.18.0 1.18.0 Symfony form extensions
sonata-project/twig-extensions           1.12.0 2.0.0  Sonata twig extensions

```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
Direct dependencies required in composer.json:
symfony/monolog-bundle           v3.8.0  v3.8.0  Symfony MonologBundle
symfony/phpunit-bridge           v4.4.44 v6.1.6  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/symfony                  v4.4.46 v6.1.6  The Symfony PHP framework

Transitive dependencies not required in composer.json:
symfony/contracts                v1.1.13 v3.1.1  A set of abstractions extracted out of the Symfony components
symfony/deprecation-contracts    v3.1.1  v3.1.1  A generic function and convention to trigger deprecation notices
symfony/polyfill-ctype           v1.26.0 v1.26.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme   v1.26.0 v1.26.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu        v1.26.0 v1.26.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn        v1.26.0 v1.26.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer v1.26.0 v1.26.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring        v1.26.0 v1.26.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72           v1.26.0 v1.26.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73           v1.26.0 v1.26.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80           v1.26.0 v1.26.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81           v1.26.0 v1.26.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/security-acl             v3.3.2  v3.3.2  Symfony Security Component - ACL (Access Control List)
symfony/string                   v5.4.13 v6.1.6  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters i...
b
```

</p>
</details>

#### PHP version
8.1

## Subject
Steps:
- Frontend makes ajax request
- Backend generates validation error and handle it [here](https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Controller/CRUDController.php#L1364)
- FormErrorIteratorToConstraintViolationList::transform generates list of violations `ConstraintViolationListInterface`
- `$this->json` goes result to the code (`ControllerTrait`)
```
$this->container->get('serializer')->serialize($data, 'json', array_merge([
                'json_encode_options' => JsonResponse::DEFAULT_ENCODING_OPTIONS,
            ], $context))
```
- `$data` normalized in \Symfony\Component\Serializer\Normalizer\ConstraintViolationListNormalizer
-
 <details><summary>result translates to response (slider)</summary>
<p>
{"type":"https:\/\/symfony.com\/errors\/validation","title":"Validation Failed","detail":"s63492c556297a[media_en][translation]: Media with this filename already exists","violations":[{"propertyPath":"s63492c556297a[media_en][translation]","title":"Media with this filename already exists","parameters":{"{{ value }}":"\u00222--[en]\u0022"},"type":"urn:uuid:23bd9dbf-6b9b-41cd-a99e-4844bcf3077f"}]}
</p>
</details>

- Frontend tries to read result [here](https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/CRUD/Association/edit_many_script.html.twig#L371), but it doesn't contain `message` and `errors`, but has `title` and `violations`

### PR DESCRIPTION
**Pull request by dmitryuk**
fixes https://github.com/sonata-project/SonataAdminBundle/issues/7945

## Changelog

```markdown
### Fixed
- Violations error handling
```

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

**Comment by ggabrovski** [comment]
Hi @dmitryuk thanks for your fix, I suggest to extending the logic so we can attach the message to the field. Please take a look on this #7948 I have added some logic to attache the violation error to the field. What do you think?

**Comment by dmitryuk** [comment]
@ggabrovski your PR is great. @VincentLanglet please merge any, because now validation errors does not show at all

**Comment by VincentLanglet** [comment]
Lets merge the other pr then

**Comment by dmitryuk** [comment]
@VincentLanglet may be reopen the MR and release it? Because last tag is broken

**Comment by VincentLanglet** [comment]
You can still use an older tag / a fork.
I'm just waiting for the review on https://github.com/sonata-project/SonataAdminBundle/pull/7948, it should be fixed soon but people are not 24/24 7/7 available for free open source.

**Pull request closed without merging**
