### PR TITLE
prettify file inputs

### PR DESCRIPTION
**Pull request by digitalkaoz**
current file uploads are ugly by default and bootstrap itself doenst provide a solution for it (why?)

so i implemented http://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3/ into Sonata

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Is this W3C compatible? Especially for browser accessibility.

**Comment by digitalkaoz** [comment]
i dont know...but since the whole admin wont work without JS i dont see the a problem

**Comment by Soullivaneuh** [comment]
JS is not especially an issue if only you have correct tags and implementations in addition for accessibility. ;-)

I'll take a look.

**Comment by Soullivaneuh** [comment]
Could you please rebase your PR?

**Comment by digitalkaoz** [comment]
@Soullivaneuh done...

**Comment by Soullivaneuh** [comment]
Failing CS: https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/73870544#L469

**Comment by digitalkaoz** [comment]
ill close this...i did a wrong rebase and now to original code ist lost...

**Pull request closed without merging**
