### PR TITLE
Fix some phpstan 6 issues

### PR DESCRIPTION
**Pull request by VincentLanglet**
I fixed aroung 100 errors.

There is still 405 errors for level 6 and 559 for max-level

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@jordisala1991 The build `Webpack Encore` is required but not triggered since I didn't touch the files related...

**Comment by jordisala1991** [comment]
Maybe it is better to always trigger the build, like we do with docs builds?

**Review by jordisala1991 — APPROVED** [review]

**Comment by OskarStark** [comment]
Yes let's do it

**Comment by jordisala1991** [comment]
I think it was already merged @OskarStark https://github.com/sonata-project/dev-kit/pull/1514, you merged it.

**Comment by OskarStark** [comment]
You are right and it is deployed

**Pull request merged**
