### PR TITLE
Proof PR dev-kit 621

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by franmomu** [comment]
wow! about 30s faster and for php 7.2 6m less, let me try with simple-phpunit

**Comment by greg0ire** [comment]
I'm preparing a dev-kit PR.

**Comment by VincentLanglet** [comment]
@franmomu @greg0ire Are you sure the tests are executed ?

**Comment by greg0ire** [comment]
@VincentLanglet they weren't at first, hence b17e907

**Pull request closed without merging**
