### PR TITLE
Update AbstractAdmin.php

### LINKED ISSUE #5651: filter[_per_page] still not working
Sonata Admin Bundle Version 3.51.0
Sumfony 3.4

Not working for me still, updated to the most stable version.

I found the issue, it is around determinedPerPageValue and it checks the value against list of available pagination options and also checks against the data type. so I think we need to add the following setting on `vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php` on l`ine 786 before` `if (!$this->determinedPerPageValue($parameters['_per_page'])) {` and it will work.

```
if (isset($parameters['_per_page'])) {
    $parameters['_per_page'] = (int) $parameters['_per_page'];
}
```

Reason being the `$parameters['_per_page']` is string while `determinedPerPageValue` expecting it to be integer. Or, otherwise on `determinedPerPageValue` function code sniff we should remove the data type check setting and only check the values.

### PR DESCRIPTION
**Pull request by farshidalavim**
https://github.com/sonata-project/SonataAdminBundle/issues/5651

## Subject

I am targeting this branch, because the parameter _pe_page is still not working.

Closes #5651 

## Changelog

```markdown
### Added
- Added a new `Comparison and data type check` to make sure the _per_page parameter is matched with the expected data format (int)

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

### CODE REVIEW

**Comment by farshidalavim** [comment]
My apologies, I mistakenly deleted the other PR

**Comment by farshidalavim** [comment]
Can you please approve this PR?

**Comment by phansys** [comment]
Thank you so much for your first contribution @farshidalavim.
Please, try to update the PR description in order to tell what your changes are fixing.
Additionally, as suggested previously, you should add a test covering what is resolved in order to avoid future regressions.
Take a look at [CONTRIBUTING.md](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/CONTRIBUTING.md#writing-a-pull-request).

**Comment by core23** [comment]
This PR looks dead. Feel free to reopen if you will continue working on this.

**Pull request closed without merging**
