### PR TITLE
Merge 3.x

### PR DESCRIPTION
**Pull request by dmaicher**

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
You don't need to create a branch for the merge, you can use your local master.
```
git pull origin 3.x
git checkout master
git pull origin master
git merge 3.x
git push your_remote
open the PR master into master
get an approval
git push origin master
```

**Comment by dmaicher** [comment]
> You don't need to create a branch for the merge, you can use your local master.
> 
> ```
> git pull origin 3.x
> git checkout master
> git pull origin master
> git merge 3.x
> git push your_remote
> open the PR master into master
> get an approval
> git push origin master
> ```

@VincentLanglet sure I could do it on master directly but I'm used to working on branches and not pushing to master directly. So I will keep doing it this way.

**Comment by VincentLanglet** [comment]
It was to avoid this kind of commit:
image

In favor of 
image

**Comment by dmaicher** [comment]
> It was to avoid this kind of commit:
> image
> 
> In favor of
> image

Ahh that's interesting. The repository is configured to always squash on merge... wondering why this is not done in your second example then

**Comment by VincentLanglet** [comment]
> Ahh that's interesting. The repository is configured to always squash on merge... wondering why this is not done in your second example then

You can also rebase-merge in general case, but I never was able to rebase-merger a PR of "Merge 3.x".
Github saying it creates conflict, even if you solved them ^^'

**Pull request merged**
