### PR TITLE
Fixed autocomplete not showing pre-populated values

### PR DESCRIPTION
**Pull request by joshlopes**
Q   |   A
------|-------
Bug fix? |	yes
New feature? |	no
BC breaks? |	no
Deprecations? |	no
Tests pass? | yes
Fixed tickets | #3206
License | 
Doc PR |

### CODE REVIEW

**Comment by rande** [comment]
@pulzarraider Can you review this PR ?

**Comment by joshlopes** [comment]
I just realize that the problem was the new Select2 -- it also was released in version 4 may be worth taking a view.

Also when in multiple it does not accept select box (dunno why) needs to have a if state where it check if is multiple or not and use input or select accordingly.

**Comment by joshlopes** [comment]
I'm sorry -- i have digged to much actually is even simpler the solution. I have commit the simpler solution.

Select2.min.js  3.5.3 requries opts variable to be defined, dunno where it comes. I set it globaly debug false so it is working again.

Sorry again :)

**Comment by pulzarraider** [comment]
@joshlopes Yes, your solution is not good. There is no bug in the `sonata_type_model_autocomplete`, but in the select2 3.5.3. 

Your solution also breaks autocomplete if the `multiple=true` is enabled.  We should upgrade to version 3.5.4. I will create a PR.

**Comment by pulzarraider** [comment]
PR created sonata-project/SonataCoreBundle#189

**Comment by rande** [comment]
@joshlopes thanks for helping us ;)

**Pull request closed without merging**
