### PR TITLE
Fix arrow function scope issue

### PR DESCRIPTION
**Pull request by 1ed**
## Subject

Fixes a js issue about the per page select.

I am targeting this branch, because it was introduced in https://github.com/sonata-project/SonataAdminBundle/commit/0f0cf90cc15007866337dc5ac8ae58d81533ad79

## Changelog

Based on github it was not released yet, so I think it is not required. 

```markdown
### Fixed
- Pagination results per page selector
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
Nice catch, can you:

```
yarn install --frozen-lockfile
yarn encore production
```

**Comment by jordisala1991** [comment]
Also, please introduce a changelog to know what you are fixing.

**Comment by 1ed** [comment]
Done, thanks!

**Review by VincentLanglet — APPROVED** [review]

**Review by jordisala1991 — APPROVED** [review]
Approved, but the changelog message should be direct to our end users. It should not mention some javascript fixing, but what do we fix with that change? Is the pagination broken? Is the selector of number of items per page broken? we should explain what we fixed.

**Comment by 1ed** [comment]
> Approved, but the changelog message should be direct to our end users. It should not mention some javascript fixing, but what do we fix with that change? Is the pagination broken? Is the selector of number of items per page broken? we should explain what we fixed.

Changed it, but what is the purpose of that anyway? That bug have never been released, so in the next release there will be a changelog entry to fix something what have never been released as broken?

**Comment by VincentLanglet** [comment]
> Changed it, but what is the purpose of that anyway? That bug have never been released, so in the next release there will be a changelog entry to fix something what have never been released as broken?

I think it was releaded https://github.com/sonata-project/SonataAdminBundle/releases/tag/4.0.0-alpha-2

**Comment by 1ed** [comment]
Ohh, sorry, you are right. I've only seen this 

image

and apparently GitHub does not show tags there any more.

**Pull request merged**
