### PR TITLE
Introduce ClassMetadataReaderInterface

### PR DESCRIPTION
**Pull request by franmomu**
## Subject

phpstan reported in [`FormContractor`](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/3.x/src/Builder/FormContractor.php) (and [other files](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/search?q=hasMetadata&unscoped_q=hasMetadata)):
```
 ------ --------------------------------------------------------------------------------------------
  Line   Builder/FormContractor.php
 ------ --------------------------------------------------------------------------------------------
  51     Call to an undefined method Sonata\AdminBundle\Model\ModelManagerInterface::hasMetadata().
  52     Call to an undefined method Sonata\AdminBundle\Model\ModelManagerInterface::getMetadata().
 ------ --------------------------------------------------------------------------------------------
```

These methods are already implemented in the persistence bundles: [ORM](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Model/ModelManager.php#L88) and [MongoDB](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/3.x/src/Model/ModelManager.php#L68).

So this adds a new interface with those methods, any suggestion about the name is more than welcome, I wasn't going to use the `Interface` suffix, but just to follow the other files convention.

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Added
- Added `ClassMetadataReaderInterface` to be able to read ClassMetadata from ModelManagerInterface.
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
> These methods are already implemented in the persistence bundles: [ORM](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Model/ModelManager.php#L88) and [MongoDB](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/3.x/src/Model/ModelManager.php#L68).
> 
> So this adds a new interface with those methods, any suggestion about the name is more than welcome, I wasn't going to use the `Interface` suffix, but just to follow the other files convention.

Are these method relevant for every possible persistence bundle ?
I mean, if someone else implements a persistence bundle, will he need these methods ?

Shouldn't SonataAdminBundle define only Interface and methods he need.
This interface could be added to our storage bundle, and then we'll write
```
public function fixFieldDescription(AdminInterface $admin, FieldDescriptionInterface $fieldDescription)
    {
        $modelManager = $admin->getModelManager();
        if (!$modelManager instanceof ClassMetadaInterface) {
            throw new LogicException('...');
        }

        if ($modelManager->hasMetadata($admin->getClass())) {
```
I feel like this strategy theoretically better, but the issue is that we'll write the same code in our storage bundle.
The best seems to be a SonataDoctrineBundle with every interface and abstract class used by our storage bundle.

Of course all of this is theoretical.

I feel like we have already a lot of doctrine-specific code in SonataAdmin, so I'm totally ok with this PR.

**Comment by phansys** [comment]
I've implemented some model managers that aren't using doctrine persistence at all. In these cases, I'm using `Symfony\Component\PropertyInfo\PropertyInfoExtractor` at `getMetadata()` in order to generate part of the required metadata, since the data I'm handling there comes from ReST APIs.
This is a ugly workaround, since I'm returning an instance of `Doctrine\ORM\Mapping\ClassMetadata` there.
Given that, I think we could analyze if `getMetadata()` must be added in `ModelManagerInterface` in order to declare our own requirements regarding the model metadata.
WDYT?

**Comment by VincentLanglet** [comment]
Either we add this interface to SonataAdmin, which is not great for non-doctrine-related persistence bundle.
Either we add this interface to our persistence bundle, which is not great because we'll duplicate code.

I see no perfect solution here.

**Comment by franmomu** [comment]
I converted the PR as a draft since this needs more thinking.

**Comment by VincentLanglet** [comment]
There is a similar issue with `getParentMetadataForProperty`:
- https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/DatagridBuilder.php#L75
- https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/ListBuilder.php#L83
- https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/ShowBuilder.php#L70

**Comment by VincentLanglet** [comment]
Closing in favor of https://github.com/sonata-project/SonataAdminBundle/pull/6375

**Pull request closed without merging**
