### PR TITLE
Update composer.json to enable with Symfony 4.x

### PR DESCRIPTION
**Pull request by andreybolonin**
I am targeting this branch, because {reason}.

Closes #{put_issue_number_here}

## Changelog

```markdown
### Added
- Added some `Class::newMethod` to do great stuff

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

## To do

- [ ] Update the tests
- [ ] Update the documentation
- [ ] Add an upgrade note

### CODE REVIEW

**Comment by jordisala1991** [comment]
Closing, because this change is not needed, and the PR template was not filled.

**Comment by andreybolonin** [comment]
http://symfony.com/blog/symfony-4-1-0-beta1-released

**Comment by covex-nn** [comment]
@andreybolonin `^4.0` constraint means `>=4.0 and <5.0`

**Comment by andreybolonin** [comment]
ups... ok, thx ))

**Pull request closed without merging**
