### PR TITLE
[bugfix] Prioritize jQuery UI scripts in "assets.javascripts" config in order to avoid initialization issues

### PR DESCRIPTION
**Pull request by phansys**
I am targeting this branch, because this guards BC.

## Changelog

```markdown
### Changed
- Default load order of `assets.javascripts` at `Configuration::getConfigTreeBuilder()`
### Fixed
- ECMAScript error `jquery.js:250 Uncaught Error: cannot call methods on button prior to initialization;` while trying to use `$.fn.button()` (ref: https://github.com/twbs/bootstrap/issues/6094)
```

## Todo:
- [x] ~~Check if changes made at 359ce81fb967004ba8026dd3776171fa9aa7a26b can be reverted (using `noConflict()` instead).~~

### CODE REVIEW

**Comment by phansys** [comment]
I'm afraid we can't.

**Comment by jordisala1991** [comment]
https://github.com/sonata-project/SonataAdminBundle/pull/5047

we changed this a few PRs ago... does this PR revert the older one?

**Comment by phansys** [comment]
>does this PR revert the older one?

That seems to be true. Then, I'll try to make some tests around `noConflict()` approach and will be back with the results. Thank you for pointing the previous change ;)

**Comment by phansys** [comment]
@verheyenkoen, are you sure the only way to fix the issue you've reported on #5047 is to change the order of the scripts? AFAIK, the embedded version of jQuery doesn't support `noConflict()` (Bootstrap does, see https://github.com/twbs/bootstrap/issues/6094#issuecomment-17249829), so with your PR, I'm not able to use features from `button`: `jquery.js:250 Uncaught Error: cannot call methods on button prior to initialization;`.
Thank you in advance.

**Comment by verheyenkoen** [comment]
@phansys I don't know. This is a fix I found. If it's no good I guess we have to revert it.

**Comment by phansys** [comment]
Ok, let me do some checks in order to determine how we could make both fixes to co-exist.

**Comment by jordisala1991** [comment]
Any idea on how to deal with this one @greg0ire ?

**Comment by greg0ire** [comment]
Pick the lesser of the 2 bugs?

**Comment by jordisala1991** [comment]
Then, probably this bug is bigger than the other? @phansys the StackOverflow you linked covers the other bug report?

**Comment by jordisala1991** [comment]
Please edit the docs like the other PR: https://github.com/sonata-project/SonataAdminBundle/pull/5047/files#diff-e252be027e26148c11d971dc969f4be0R205

**Comment by phansys** [comment]
>the StackOverflow you linked covers the other bug report?

I think not, because I don't know how to provide the `button.noConflict()` instance to `$(selector).dialog()`.

In my particular use case, my app was using `$(selector).button('loading')`, `$(selector).button('reset')`, etc; and the change introduced in #5047 broke these calls.

Update at `configuration.rst` is done.

**Comment by jordisala1991** [comment]
We might merge this one after all

**Comment by OskarStark** [comment]
> Merge it and wait for people to scream?

Yes 👍

**Comment by OskarStark** [comment]
Thank you @phansys

**Pull request merged**
