### PR TITLE
Do not throw exception in next major in attachAdminClass if there is no class to attach

### PR DESCRIPTION
**Pull request by VincentLanglet**
Pedantic 

Related to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1282#issuecomment-767161673

### CODE REVIEW

**Comment by franmomu** [comment]
Now I see it, what about to create a `Pool::getAdminByFieldDescription` and we could move the entire `if-else` there and maybe create also a `hasser`.

**Comment by VincentLanglet** [comment]
> Now I see it, what about to create a `Pool::getAdminByFieldDescription` and we could move the entire `if-else` there and maybe create also a `hasser`.

How do you avoid to duplicate the logic in the hasser and the getter ?

getAdminByFieldDescription will throw possibly 3 InvalidArgumentException but the hasser should only throw 2, IMHO.
If there is multiple admin or if the admin_code is invalid, we should throw an exception in the hasser I think.

**Comment by VincentLanglet** [comment]
Should we create an issue about `Pool::getAdminByFieldDescription` ?
I would like to merge this quickly in order to fix it in master @sonata-project/contributors :)

**Review by dmaicher — APPROVED** [review]
let's keep 3.x behavior for now and re-visit if we can change it with BC or postpone to 5.0?

**Review by franmomu — APPROVED** [review]
I'm fine postponing this, but I think we could improve things in the way. 
I'll try it if I find some time, for example, we could throw our own exception in `Pool` when an admin is not found, like `AdminNotFoundException` or whatever and in `Abstract::attachAdminClass()` catch that exception and do nothing if it's the case.

**Comment by VincentLanglet** [comment]
> I'm fine postponing this, but I think we could improve things in the way.
> I'll try it if I find some time, for example, we could throw our own exception in `Pool` when an admin is not found, like `AdminNotFoundException` or whatever and in `Abstract::attachAdminClass()` catch that exception and do nothing if it's the case.

I made https://github.com/sonata-project/SonataAdminBundle/pull/6821

**Pull request merged**
