### PR TITLE
Keep menu on left side hidden when browsing

### LINKED ISSUE #4837: Keep menu on left side hidden when browsing
It would be great to make it possible to keep the left side menu hidden when navigating between pages.

Ref: https://stackoverflow.com/questions/47665087/how-to-keep-sonata-admin-menu-on-left-side-hidden-when-browsing

### PR DESCRIPTION
**Pull request by kunicmarko20**
I am targeting this branch, because I am adding a feature.

Closes #4837

## Changelog

```markdown
### Changed
- Menu on the left side stays hidden while changing pages.
```

## Subject

Something I wished I had when working with multiple pages on one screen. When I saw the issue I asked on slack and @Xymanek mentioned that cookies would be a good solution so here it is. I was not sure where should I put the javascript (or should I even use jquery?) so I will move it if you tell me where.

### CODE REVIEW

**Comment by greg0ire** [comment]
Having zero javascript in Twig would be great, if you can manage that

**Comment by kunicmarko20** [comment]
Agree, there are currently [2 javascript files (Admin.js, treeview.js)](https://github.com/sonata-project/SonataAdminBundle/tree/3.x/src/Resources/public) but I do not think this fits there (or am I wrong?), also do not see the point of creating a new file just for this.

**Comment by greg0ire** [comment]
I have no issue with a new, tiny file that will get cached. Maybe call it `sidebar.js`?

**Comment by kunicmarko20** [comment]
No problem will be moved. Another problem that I saw is if someone changes `body_attributes` block this won't work anymore, is that ok? as I can't just move class attribute out of that block.

**Comment by greg0ire** [comment]
It's ok, it does not break anything.

**Comment by Xymanek** [comment]
`sonata_left_side_hide` why not `sonata_sidebar_hide`? `left_side` is kinda confusing...

**Comment by kunicmarko20** [comment]
Block name in twig was `sonata_left_side` so I just went with that, `sonata_sidebar_hide` is better. Did not know I would break tests with a new file :smile:

**Comment by kunicmarko20** [comment]
Fixed and renamed :tada:

**Comment by kunicmarko20** [comment]
Just found this place in configuration.rst, I guess that is it.

**Comment by kunicmarko20** [comment]
@OskarStark could you review again, needed this just now 😄

**Comment by greg0ire** [comment]
Thanks @kunicmarko20 !

**Comment by jordisala1991** [comment]
The only problem I found using this is that every page have its own `sonata_sidebar_hide` cookie, that leads to "strange" behaviors where you can move to a specific admin and lose admin even though you come from a page with the sidebar open

Maybe we should specific the path to avoid that. WDYT @kunicmarko20 ?

**Comment by kunicmarko20** [comment]
@jordisala1991 you were right, https://github.com/sonata-project/SonataAdminBundle/pull/4877 this should fix it.

**Comment by braianj** [comment]
Hi, Where should we use `sonata_sidebar_hide`?

**Comment by kunicmarko20** [comment]
@braianj it is used by default, when you collapse sidebar and refresh, it should stay collapsed.

**Comment by braianj** [comment]
Yes, but I want to start it always collapsed, how should I do that without changing the layout?

**Comment by kunicmarko20** [comment]
hm, there is no support for that, maybe you can create a PR and add it.

**Pull request merged**
