### PR TITLE
Correct view for mobile devices

### PR DESCRIPTION
**Pull request by peter-gribanov**
Fix for issues #3570 and #3576

### CODE REVIEW

**Comment by OskarStark** [comment]
can you please add some before/after screenshots?

Thank you

**Comment by peter-gribanov** [comment]
# Screenshots before

## landscape
bug_before_landscape
## landscape scroll
bug_before_landscape_scroll
## portrait
bug_before_portrait
## portrait scroll
bug_before_portrait_scroll

# Screenshots after
## landscape
bug_after_landscape
## landscape scroll
bug_after_landscape_scroll
## portrait
bug_after_portrait
## portrait scroll
bug_after_portrait_scroll

**Comment by ju1ius** [comment]
Hi,
This is not a very good idea to try to fix this, because this "sticky" feature should be purely and simply **removed**.
## Why?

### Usability
There's the obvious usability issue you pointed out. Having the top nav + the actions header + the forrm action buttons "sticky" just eats about **half** of the screen space on mobile, for no good reason. And it looks quite amateurish... Screenshot :dizzy_face: :

sonata_sticky


### Performance
BUT, the most important issue is rendering performance. When a browser thinks something on the page should be rerendered, it computes  the **union** of all the damaged regions per compositing layer.
Now, say you have a full-height fixed region (the sidebar) and a full-width fixed region (the top nav), what is the union of these two regions ? **The whole screen !** The whole screen is repainted on **each** scroll event. Jank.

There's a way to get around this: promote each fixed element to it's own compositing layer (e.g. using the `will-change` css property). But the browser differences can be subtle and tricky to get right. And when you promote to the GPU, you loose sub-pixel aliasing on text, which is undesirable on non high-dpi devices. And promoting too much stuff to the GPU can end-up in performance issues as well on devices with low-end hardware.

## So?

If it were me, I would just remove this feature entirely. And only then maybe look for something actually pertinent for the general usability.

**Comment by peter-gribanov** [comment]
I agree, the "sticky" feature is not necessary on mobile devices. However, this is a very handy feature on the big screens. I'm not sure that it is need completely disable.

**Comment by ju1ius** [comment]
> However, this is a very handy feature on the big screens.
 
I agree for the list view, where you can have really long lists.
For the edit view, it's just too much I think. We have to think about what the user wants to do 80% of the time, and improve that. The rest is just widgets IMO.

**Comment by core23** [comment]
I would like to merge this, if you have no other idea @ju1ius @peter-gribanov 

This fixes the current bug

**Comment by ju1ius** [comment]
> This fixes the current bug

Indeed

**Comment by peter-gribanov** [comment]
If no one has any idea how to disable "sticky" feature on mobile devices, i believe that this decision is sufficient

**Comment by core23** [comment]
Thank you @peter-gribanov @ju1ius

**Pull request merged**
