### PR TITLE
add actions buttons tests in templates

### PR DESCRIPTION
**Pull request by fbourigault**
This fix regressions I added in #4062.

## Changelog
Should I write a changelog?

## Subject

This re-add conditions that were removed in #4062.

@axzx can you test this with your project/code ?

### CODE REVIEW

**Comment by fbourigault** [comment]
@greg0ire here is the fix for #4062. I didn't tested yet all the cases. I hope I didn't do any typo.

**Comment by greg0ire** [comment]
LGTM

**Comment by fbourigault** [comment]
I think what I wrote in #4062 is breaking backward compatibility because users who removed routes using `AbstractAdmin::configureRoutes` still have a valid entry in `AbstractAdmin::getAccess`. To keep backward compatibility, we should keep the `admin.hasRoute` call.

**Comment by greg0ire** [comment]
Ok, please do that.

**Comment by fbourigault** [comment]
should I add a comment about removing the `hasRoute` calls in next major release?

**Comment by greg0ire** [comment]
> should I add a comment about removing the hasRoute calls in next major release?

Not if you don't add a deprecation message that is triggered when someone relies on this call when they should not.

**Comment by fbourigault** [comment]
@greg0ire PR is ready IMHO. Do I need to write something for the changelog?

**Comment by greg0ire** [comment]
> @greg0ire PR is ready IMHO. Sorry for breaking things. Do I need to write something for the changelog?

No, but if there is something to change in the changelog for #4062 , please change it.

**Comment by greg0ire** [comment]
ping @azxz, can you test this change ? Here is how to get the code : 

```
git checkout -b fbourigault-fix-pull-4062-regression 3.x
git pull https://github.com/fbourigault/SonataAdminBundle.git fix-pull-4062-regression
```

**Comment by axzx** [comment]
@greg0ire 
tested, it works well

**Comment by greg0ire** [comment]
Looks like the build suddenly broke, but I don't think it is your fault.

**Comment by greg0ire** [comment]
See #4079

**Comment by greg0ire** [comment]
Can you please rebase on the latest 3.x?

**Comment by greg0ire** [comment]
Thanks @fbourigault

**Pull request merged**
