### PR TITLE
renamed Symfony2 to Symfony

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Comment by rande** [comment]
Why?

**Comment by jvasseur** [comment]
With symfony 3.0 coming soon, this make more sense (They did the same in the symfony doc).

**Comment by OskarStark** [comment]
The Symfony guys decided this, maybe @javiereguiluz can explain a little more in detail

**Comment by rande** [comment]
Ok, for me then.

**Comment by OskarStark** [comment]
Thank you @rande

**Comment by rande** [comment]
@OskarStark no need for PR for other bundles, you can push directly

**Comment by OskarStark** [comment]
:+1:

**Pull request merged**
