### PR TITLE
Moment variable is now global

### PR DESCRIPTION
**Pull request by jordisala1991**
We add locale translations for moment after the main app.js gets loaded.
This only works if the moment is available at global scope because it
calls a method on global.moment.

## Subject

I am targeting this branch, because this only applies to master.

It is a bug fix but it wasn't released, so that's why I added the pedantic label. Changelog is already on another PRs not released.

@dbu can you try before merging this?

### CODE REVIEW

**Comment by dbu** [comment]
thanks for looking into this! i still get 

"Uncaught TypeError: Cannot read property 'defineLocale' of undefined"

i can try tomorrow to create a repo with a minimal sonata admin that demonstrates the problem (hoping i can reproduce it in a fresh install)

**Review by dbu — APPROVED** [review]
yay, this fixes the error in my installation, so i guess it does help.

thanks a lot for the quick fix :+1:

**Comment by dbu** [comment]
> thanks for looking into this! i still get
> 
> "Uncaught TypeError: Cannot read property 'defineLocale' of undefined"
> 
> i can try tomorrow to create a repo with a minimal sonata admin that demonstrates the problem (hoping i can reproduce it in a fresh install)

too late at night. forgot to assets:install and did not realize that they have not been installed with symlink, sorry. will delete this and the other wrong comment. it seems correct to me :+1:

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks !

**Pull request merged**
