### PR TITLE
Allow using overriden layout template in empty_layout

### PR DESCRIPTION
**Pull request by Koc**
We have overriden layout template using bundle configuration, but our layout not applied

### CODE REVIEW

**Comment by greg0ire** [comment]
Your changes seem to partially break the build. You should try your code with Symfony 2.8 and fix it.

**Comment by Koc** [comment]
@OskarStark travis is green for now

**Comment by core23** [comment]
Thank you @Koc

**Comment by OskarStark** [comment]
:+1:

**Pull request merged**
