### PR TITLE
Upgrade frontend deps

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

Closes #7788.

## Changelog

```markdown
### Fixed
- Fix vulnerabilities on several frontend dependencies by upgrading them: `async`, `minimist`, `ansi-regex` and `moment`, 
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Shouldn't we add a changelog ?

**Comment by jordisala1991** [comment]
Wasn't sure if it is worth it, some of the updated deps contained fixes for security vulnerabilities, so maybe yes?

**Comment by jordisala1991** [comment]
How do you see it now?

**Comment by VincentLanglet** [comment]
> Wasn't sure if it is worth it, some of the updated deps contained fixes for security vulnerabilities, so maybe yes?

Pedantic doesnt trigger a release. We might doesnt want to wait in order to release this so patch is good.

Also, the dependencies might have introduced bugs, so it's always useful to say "be aware we updated them"

**Pull request merged**
