### PR TITLE
Bump "twig/twig" to "^2.9" in order to replace usages of deprecated features

### LINKED ISSUE #5573: [RFC] Bump "twig/twig" in order to avoid deprecations
## Feature Request

Bump Twig to version `^2.9` in order to use [`apply spaceless`](https://twig.symfony.com/doc/2.x/filters/spaceless.html) filter instead of the deprecated [`spaceless`](https://twig.symfony.com/doc/2.x/tags/spaceless.html) tag.

https://github.com/sonata-project/SonataAdminBundle/blob/a2524e7a6f03de2f8b8e84203088f6e57b209a30/composer.json#L55

### PR DESCRIPTION
**Pull request by phansys**
## Subject

Bump "twig/twig" to "^2.9" in order to replace usages of deprecated features.

I am targeting this branch, because the changes are considered BC.

Closes #5573

## Changelog

```markdown
### Changed
- Bumped "twig/twig" dependency to "^2.9";
- Changed usages of `{% spaceless %}` tag, which is deprecated as of Twig 1.38 with `{% apply spaceless %}` filter;
- Changed usages of `{% for .. if .. %}`, which is deprecated as of Twig 2.10 with `filter` filter'.
```

**To Do**:
- [x] Update usages of `{% for .. if .. %}`, which are deprecated since Twig `2.10`.

### CODE REVIEW

**Comment by greg0ire** [comment]
Please write a changelog directed at end users. Keep in mind that they probably do not care what file or class you changed, but what features you provided / what bugs you fixed. Try to answer the question "What benefit do I get from upgrading?"
More on http://keepachangelog.com

**Comment by phansys** [comment]
From my point of view, end users for this package are developers, not application users; so telling them when a dependency constraint was updated or when a syntax (that could be overridden in their own implementations) has been changed is important.

**Comment by Hanmac** [comment]
About this part:

```
{% set groups = [] %}
{% for group in sonata_admin.adminPool.dashboardgroups %}
        {% set display_group = false %}

        {% for admin in group.items|filter(admin => admin.hasRoute('create') and admin.hasAccess('create')) %}
            {% if display_group == false %}
                {% set display_group = true %}
                {% set groups = [group]|merge(groups) %}
            {% endif %}
        {% endfor %}
{% endfor %}
```

the loop for admin isn't even needed there because it isn't used, if using filter on group.items, why not just call length there too?

```
{% set groups = [] %}
{% for group in sonata_admin.adminPool.dashboardgroups %}
  {% if group.items|filter(admin => admin.hasRoute('create') and admin.hasAccess('create'))|length > 0 %}
      {% set groups = [group]|merge(groups) %}
   {% endif %}
{% endfor %}
```

**Comment by phansys** [comment]
You're right!
What about this?
```
{% set groups = [] %}

{% for group in sonata_admin.adminPool.dashboardgroups|filter(group => group.items|filter(admin => admin.hasRoute('create') and admin.hasAccess('create'))|length > 0) %}
    {% set groups = [group]|merge(groups) %}
{% endfor %}
```

**Comment by Hanmac** [comment]
yeah looks better imo, i don't know if it can be combined even shorter

**Comment by phansys** [comment]
I think it's not possible since the result is an iterator and there is a use of the `length` filter over `groups`, which will consume all the iterations:
```
{% set groups = sonata_admin.adminPool.dashboardgroups|filter(group => group.items|filter(admin => admin.hasRoute('create') and admin.hasAccess('create'))) %}

{% set column_count = (groups|length / items_per_column)|round(0, 'ceil') %}

{# 
  groups is already consumed:
  An exception has been thrown during the rendering of a template ("Cannot traverse an already closed generator").
#}

{% for group in groups|reverse %}
{% endfor %}
```

**Comment by phansys** [comment]
Just for the records, the behavior of `filter` filter about the consumed iterations was fixed on Twig 2.11.3: https://github.com/twigphp/Twig/pull/3065.

**Comment by ossinkine** [comment]
Why Twig version was bumped to `^2.9` if [arrow functions for filters were added in 2.10](https://github.com/twigphp/Twig/blob/2.x/CHANGELOG#L38)?

**Comment by phansys** [comment]
Good catch @ossinkine!
The reason is that this PR was born with the replacement of the `spaceless` tag as its main goal; and then I've added more changes without notice about the constraint you're pointing.
I'll try to provide a patch for this soon.

Thank you so much!

**Pull request merged**
