### PR TITLE
Use phpstan extension installer

### PR DESCRIPTION
**Pull request by VincentLanglet**
This automatically use phpstan-symfony (and others extensions if installed).

### CODE REVIEW

**Comment by OskarStark** [comment]
PHPStan is failing now 🥲

**Comment by greg0ire** [comment]
I guess that means the plugin is useful :)

**Comment by VincentLanglet** [comment]
It's failing because of the new version of phpstan, I applied the fix here: https://github.com/sonata-project/SonataAdminBundle/pull/6591, I was expecting to quickly merge the bugfix in order to release 3.80.1

**Comment by greg0ire** [comment]
`git cherry-pick 0d1b1d9da4b7cb7dae4842875db6fd4d5715627e` then :)

**Comment by VincentLanglet** [comment]
> `git cherry-pick 0d1b1d9da4b7cb7dae4842875db6fd4d5715627e` then :)

Done

**Review by franmomu — APPROVED** [review]

**Pull request merged**
