### PR TITLE
Removed table-striped class from the table

### PR DESCRIPTION
**Pull request by axzx**
I am targeting this branch, because it's an improvement.

## Changelog

```markdown
### Removed
- Removing the effect of stripes from the table in the list
```

## Subject

Deleting a striped causes the table to look more aesthetically. In combination with https://github.com/sonata-project/SonataAdminBundle/pull/5104 it will also be friendlier.

removed_table_striped

### CODE REVIEW

**Comment by OskarStark** [comment]
@axzx could you add a screenshot before/after ?

**Comment by axzx** [comment]
@OskarStark done
@kunicmarko20 Do you mean tests in the custom application? In SonataAdmin, this class is nowhere used.

**Comment by kunicmarko20** [comment]
Yes, I am talking about custom app testing, what if someone is depending on that class?

**Comment by axzx** [comment]
@kunicmarko20 The `table-striped` is a class of appearance. The `sonata-ba-list` class is more suitable for testing.

**Comment by OskarStark** [comment]
@kunicmarko20 we have 2 👍 on the PR header

**Comment by kunicmarko20** [comment]
I just now saw the screenshoots, I am also 👎 for this.

**Comment by OskarStark** [comment]
> I am 👎 for this, what do rest of people think @sonata-project/contributors

Ok, so lets close here.
Sorry @axzx , but the real improvement is done by you in #5104 😄 👍

**Comment by axzx** [comment]
@OskarStark This PR was supposed to be the complement of #5104 . There are a lot of stripes now.

**Comment by axzx** [comment]
My solution:
```
.table.sonata-ba-list > tbody > tr:nth-of-type(odd) {
    background-color: #ffffff;
}
```

**Comment by OskarStark** [comment]
I thought it is only the hover effect

**Comment by jordisala1991** [comment]
mmmh if we dont merge this one, there is no reason to have hovers on the table.

**Comment by greg0ire** [comment]
Is there? What if the hover is a 3rd color… regarding this PR, I recall seeing a blog post and gif/video about "less is more" - style tables without borders, but cannot find it back, maybe you can @axzx ?

**Comment by kunicmarko20** [comment]
I am with @greg0ire on this, can't we just leave the stripes and make hover darker?

**Comment by jordisala1991** [comment]
With a clearly different color it could work, but with almost the same color, it does not work at all

**Pull request closed without merging**
