### PR TITLE
Put all flash messages in separate functions

### PR DESCRIPTION
**Pull request by tim96**
Put all flash messages in separate functions

### CODE REVIEW

**Comment by core23** [comment]
Don't get the concrete use case for this. Why should we override the flash messages and why are they public?

**Comment by tim96** [comment]
> Don't get the concrete use case for this. Why should we override the flash messages and why are they public?

@core23 The main idea I try explain here #3197 and some variants discuss here #3167 . I don't want to override a whole action only for change 'flashbag' message, because after that this action is hard to support.

**Comment by OskarStark** [comment]
:-1:

**Comment by tim96** [comment]
@OskarStark hello. I am sorry to disturb you, but can you explain your decision a little bit? Do you prefer using hard copy big pieces of code instead of using inheritance?

**Pull request closed without merging**
