### PR TITLE
Fix undefined subject

### PR DESCRIPTION
**Pull request by morgangiraud**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
I don't know if it's the best way. What is the actual error?

**Comment by morgangiraud** [comment]
Hello @Soullivaneuh,  I've also created an issue here : #3220 :)

**Comment by morgangiraud** [comment]
It might not be the best way, but at least, you don't have an undefined var anymore,it breaks nothing on your side and solve all my bugs on my side. 

We might agree, there is an improvement here.

**Comment by rande** [comment]
@pulzarraider has been working on improving this code. @morgangiraud can you add a test case for your issue.

**Comment by morgangiraud** [comment]
@pulzarraider I would like to, but i don't fully understand what makes my code not working.
Can you help me to understand why there is only a check for `instanceof Collection` and nothing else nor default behavior ?

**Comment by core23** [comment]
Please add some tests. We can't merge this without @morgangiraud

**Comment by core23** [comment]
Please have a look at the ref'd ticket. Please close if the problem is solved

**Comment by core23** [comment]
Are you still working on this? @morgangiraud

**Comment by morgangiraud** [comment]
@core23 
Sorry, no.
I was on a freelance project at that moment and not enough time to dig in. The fix i made seems to be enough at the time.
You can dispose of the PR as you see fit.

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
