### PR TITLE
2.3

### PR DESCRIPTION
**Pull request by kazami0083**
I have found one problem for sonata admin bundle. 
in file SonataAdminBundle/Resources/public/Admin.js, 
line 316: "var highestCounterRegexp = new RegExp('_([0-9])+$');"
it should be "var highestCounterRegexp = new RegExp('_([0-9]+)$');"
Otherwise, we can not edit more than 10 elements for "collection type".

### CODE REVIEW

**Comment by rande** [comment]
Can you rebase this PR +

**Comment by Soullivaneuh** [comment]
@rande This PR mean merge 2.0 branch onto 2.3.

Don't think this is useful.

**Comment by OskarStark** [comment]
@Soullivaneuh @rande any news on this PR?

**Comment by OskarStark** [comment]
And we already have PR which fixes this: #3145

so i'm for closing this Merge-PR-including-a-bug-fix

**Pull request closed without merging**
