### PR TITLE
Drop CoreBundle dependency

### LINKED ISSUE #5762: [Next Major] Drop CoreBundle dependency

### PR DESCRIPTION
**Pull request by core23**
## Subject

I am targeting this branch, because this is a BC break.

Closes #5762

## Changelog

```markdown
### Removed
- Drop CoreBundle dependency
```

## To do
    
- [x] Drop `DiExtraBundle`

### CODE REVIEW

**Comment by core23** [comment]
I made some adjustments for Travis, because SonataBlock 4 requires symfony 4
- Removed CoreBundle tests
- Removed BlockBundle 3.x tests
- Removed symfony 3 tests

**Comment by franmomu** [comment]
just in case, I'm going to work on fixing the tests

**Comment by core23** [comment]
We still need a dev-kit update  🙁

**Comment by franmomu** [comment]
Taking a look at the conflict in AppKernel:
```php
<<<<<<< HEAD:tests/App/AppKernel.php
        $loader->load($this->getProjectDir().'/config/services.yml');
=======
        $twigStringFilter = new Definition(TextExtension::class);
        $twigStringFilter->addTag('twig.extension');

        $containerBuilder->addDefinitions([$twigStringFilter]);
>>>>>>> 252f6b33c... Use SonataTwig instead of CoreBundle:tests/Functional/AppKernel.php
```
It's just leaving this line `$loader->load($this->getProjectDir().'/config/services.yml');` and in `tests/App/config/services.yml` add:
```
Twig\Extensions\TextExtension:
        tags:
            - {name: twig.extension}
```

**Comment by franmomu** [comment]
@core23 are you planning on working on this? I don't mind creating another PR fixing the conflicts

**Comment by core23** [comment]
> @core23 are you planning on working on this? I don't mind creating another PR fixing the conflicts

Sorry, I don't have time at the moment. Feel free to finish this @franmomu

**Pull request closed without merging**
