### PR TITLE
Fix fatal error in strict mode: strlen() expects parameter 1 to be string, null given

### PR DESCRIPTION
**Pull request by aokhrimenko**
I am targeting this branch, because strict mode is enabled only in master.

## Changelog

```markdown
### Fixed
Fatal error in strict mode
```

## Subject
Fix a bug with strlen on null value:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: strlen() expects parameter 1 to be string, null given in /var/www/vendor/sonata-project/admin-bundle/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php:402
Stack trace:
#0 /var/www/vendor/sonata-project/admin-bundle/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php(402): strlen(NULL)
#1 /var/www/vendor/sonata-project/admin-bundle/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php(67): Sonata\AdminBundle\DependencyInjection\Compiler\AddDependencyCallsCompilerPass->replaceDefaultArguments(Array, Object(Symfony\Component\DependencyInjection\Definition), NULL)
#2 /var/www/vendor/symfony/dependency-injection/Compiler/Compiler.php(95): Sonata\AdminBundle\DependencyInjection\Compiler\AddDependencyCallsCompilerPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#3 /var/www/vendor/symfony/dependency-injection/ContainerBuilder.php(711): Symfony\Component\DependencyInj in /var/www/vendor/sonata-project/admin-bundle/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php on line 402

```

### CODE REVIEW

**Comment by greg0ire** [comment]
> I am targeting this branch, because strict mode is enabled only in master.

That's right, but let's try to have the branches diverge as little as possible, ok?

**Comment by aokhrimenko** [comment]
@greg0ire What should I do?

**Comment by greg0ire** [comment]
1. I'm going to retarget this
2. you do this: 
   - `git fetch --all --prune`
   - `git reset --hard e4a2ea2`
   - `git cherry-pick 8061c5f`
   - `git push --force`

**Comment by greg0ire** [comment]
Also, it looks like there is no email information linked to your commits, is that normal?

**Comment by aokhrimenko** [comment]
@greg0ire It's my very first PR :)
Made my email public.

**Comment by greg0ire** [comment]
Ah I noticed your branch is named `master`, so this is going to make things weird. Please create a new branch, and cherry-pick `8061c5f` on it. And you are going to need to create a new PR, sorry :P

**Comment by greg0ire** [comment]
Closing this, please do the following:
- `git checkout -b some_branch_name origin/3.x`
- `git cherry-pick 8061c5f`

and push that branch on your fork.

**Comment by aokhrimenko** [comment]
@greg0ire but origin/3.x doesn't have strict mode in that file. I'm a little bit confused

**Comment by greg0ire** [comment]
Yeah but it won't break it, and 3.x gets merged overnight into master. And our policy is to have as few differences between 3.x and master (precisely because it would make that merge harder and harder).

**Comment by aokhrimenko** [comment]
Got it, thanks

**Comment by greg0ire** [comment]
I'm on #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) if you need help

**Pull request closed without merging**
