### PR TITLE
Fix psalm

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Need https://github.com/phpstan/phpstan-symfony/pull/225

**Comment by jordisala1991** [comment]
Maybe you can use both psalm and phpstan phpdoc so we dont block until the other PR gets merged and released

**Comment by VincentLanglet** [comment]
> Maybe you can use both psalm and phpstan phpdoc so we dont block until the other PR gets merged and released

I prefer to update the baseline instead

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thanks

**Pull request merged**
