### PR TITLE
Update Admin.php

### PR DESCRIPTION
**Pull request by krewetka**
Fix for multiple admins for same entity/document and child admins in the same time

https://groups.google.com/forum/#!topic/sonata-devs/bziquOk3LYY

### CODE REVIEW

**Comment by core23** [comment]
@krewetka Please rebase

**Comment by OskarStark** [comment]
@core23 would you create a PR of this otherwise?
we can keep @krewetka 's commit for the credit

**Comment by core23** [comment]
@OskarStark No idea what was his intention for this. Don't know if it has already been fixed.

**Comment by core23** [comment]
ping @krewetka

**Comment by krewetka** [comment]
I'll try to do rebase this weekend.

These changes where made more than a year ago. I barely remember where I used it :)

**Comment by krewetka** [comment]
I checked today and it looks like the same thing was added to master in this commit https://github.com/sonata-project/SonataAdminBundle/commit/ee138c7de25f03c6bdd0fe73794df99f6a231fb9 (together with name caching). Conditions order is a bit different but looks like the #final efect is the same.

**Pull request closed without merging**
