### PR TITLE
 [Translator] Add param & return type hints to all files in the Translator dir

### PR DESCRIPTION
**Pull request by tambait**
## Subject

This is a follow up of #6404 to add param & return type hints.

## Changelog

```markdown
### Added
- Added parameter and return type hints to all files in the Translator dir

### CODE REVIEW

**Comment by tambait** [comment]
Hi,

- There was a phpdoc block for `LabelTranslatorStrategyInterface` which was removed by php-cs-fix after I added types for method arguments. Is this ok or phpdoc block should be returned? 

- I didn't put type hint method parameter for the `$resource` in `AdminExtractor` since it's not present in `ExtractorInterface` definition

- Initally I added return type hint for `extract` and `setPrefix` method but then removed them since they are not existing in `ExtractorInterface` definition

- There's a check failure/fatal error on `AdminExtractor.php#L121` about wrong type, but as far as I see 'ExtractorInterface' in 5.x has type `string` in `setPrefix` method (unlike 4.x)

Thanks.

**Comment by VincentLanglet** [comment]
> * There was a phpdoc block for `LabelTranslatorStrategyInterface` which was removed by php-cs-fix after I added types for method arguments. Is this ok or phpdoc block should be returned?

When phpdoc is redundant with types, the phpdoc should be omit indeed.

> * I didn't put type hint method parameter for the `$resource` in `AdminExtractor` since it's not present in `ExtractorInterface` definition
> * Initally I added return type hint for `extract` and `setPrefix` method but then removed them since they are not existing in `ExtractorInterface` definition

You can still add return type hint. It should be compatible

> * There's a check failure/fatal error on `AdminExtractor.php#L121` about wrong type, but as far as I see 'ExtractorInterface' in 5.x has type `string` in `setPrefix` method (unlike 4.x)

We're supporting both Symfony 4 and 5, so in this case you have to remove the `string` typehint.
You can add a comment
```
NEXT_MAJOR: Add string typehint when support for Symfony 4 is dropped
```
In order to help to know why there is no typehint ;)

> Thanks.

Thanks to you for your contribution

**Comment by tambait** [comment]
I modified the files, but I see errors/failures caused by adding type hints to method, for example
```
1) Sonata\AdminBundle\Tests\Admin\AdminTest::testFormAddPostSubmitEventForPreValidation
TypeError: Argument 1 passed to Mock_LabelTranslatorStrategyInterface_83ac1a1a::getLabel()
must be of the type string, null given, called in
/home/runner/work/SonataAdminBundle/SonataAdminBundle/src/Form/FormMapper.php on line 141
```

Will those be fixed by updating Test classes or I need to change something in the PR?

**Comment by VincentLanglet** [comment]
@tambait You need to update the test.

By default, a mocked method always returning null.

You may need to write something like
```
$this->service->method('getLabel')->willReturn('fakeLabel');
```

Is phpunit familiar to you ?

**Comment by tambait** [comment]
> You need to update the test.
> By default, a mocked method always returning null.
> You may need to write something like
> ```
> $this->service->method('getLabel')->willReturn('fakeLabel');
> ```
> Is phpunit familiar to you ?

I've used it to a degree but in simpler scenarios than this one. I tried to investigate the issue and from what I saw, when test is executed, at certain point, method [`add`](https://github.com/sonata-project/SonataAdminBundle/blob/master/src/Form/FormMapper.php#L65) from `FormMapper` class correctly receives string value for the `$name` argument, but later in code, `$name` gets value from the [`$fieldDescription->getName`](https://github.com/sonata-project/SonataAdminBundle/blob/master/src/Form/FormMapper.php#L129) method which returns null, and the variable is then passed to translators `getLabel` method. 

[FormMapper.php](https://github.com/sonata-project/SonataAdminBundle/blob/master/src/Form/FormMapper.php#L112)
```

$fieldDescription = $this->admin->getModelManager()->getNewFieldDescriptionInstance(
    $this->admin->getClass(),
    $name instanceof FormBuilderInterface ? $name->getName() : $name,
    $fieldDescriptionOptions
);
```
```
There was 1 error:

1) Sonata\AdminBundle\Tests\Admin\AdminTest::testFormAddPostSubmitEventForPreValidation
TypeError: Argument 1 passed to Mock_LabelTranslatorStrategyInterface_2c0b4bc3::getLabel()
must be of the type string, null given, called in /SonataAdminBundle/src/Form/FormMapper.php on line 141

/SonataAdminBundle/src/Form/FormMapper.php:141
/SonataAdminBundle/tests/Fixtures/Admin/ModelAdmin.php:52
/SonataAdminBundle/src/Admin/AbstractAdmin.php:1122
/SonataAdminBundle/tests/Admin/AdminTest.php:1492


```
```
There was 1 failure:

1) Sonata\AdminBundle\Tests\Admin\AdminTest::testCanAddInlineValidationOnlyForGenericMetadata
Failed asserting that exception of type "TypeError" matches expected exception "RuntimeException".
Message was: "Argument 1 passed to Mock_LabelTranslatorStrategyInterface_2c0b4bc3::getLabel()
must be of the type string, null given, called in /SonataAdminBundle/src/Form/FormMapper.php on line 141" at

/SonataAdminBundle/src/Form/FormMapper.php:141
/SonataAdminBundle/tests/Fixtures/Admin/ModelAdmin.php:52
/SonataAdminBundle/src/Admin/AbstractAdmin.php:1122
/SonataAdminBundle/tests/Admin/AdminTest.php:1543

```

**Comment by VincentLanglet** [comment]
Oh I thought the error was about the need to write
```
$labelTranslatorStrategy = $this->createMock(LabelTranslatorStrategyInterface::class);
$labelTranslatorStrategy->method('getLabel')->willReturn('foo');
```
But it happen before this.

There is the following code
```
$modelManager = $this->createMock(ModelManagerInterface::class);
$modelManager
    ->method('getNewFieldDescriptionInstance')
    ->willReturn(new FieldDescription());
$modelAdmin->setModelManager($modelManager);
```
You should try instead
```
$fieldDescription = new FieldDescription();
$fieldDescription->setName('FakeName');

$modelManager = $this->createMock(ModelManagerInterface::class);
$modelManager
    ->method('getNewFieldDescriptionInstance')
    ->willReturn($fieldDescription);
$modelAdmin->setModelManager($modelManager);
```

**Comment by tambait** [comment]
Great thanks. 

> Oh I thought the error was about the need to write
> ```
> $labelTranslatorStrategy = $this->createMock(LabelTranslatorStrategyInterface::class);
> $labelTranslatorStrategy->method('getLabel')->willReturn('foo');
> ```

I was initially trying to do that and later I wasn't sure what would be best way to go with fieldDescription, but looking at your solution, see I was overcomplicating / overthinking. :)

**Comment by VincentLanglet** [comment]
Closing in favor of https://github.com/sonata-project/SonataAdminBundle/pull/6487

**Pull request closed without merging**
