### PR TITLE
WIP: Default injected services

### PR DESCRIPTION
**Pull request by greg0ire**
- [x] writing the docs
- [ ] writing the tests
- [ ] writing the code

This is an RFC Some questions before I start :

1. What do you think about the configuration I documented ? I'm not sure it will be sufficient, because I think the strategy should only be applied on admins defined by the user. Maybe there should also be a configuration key whitelisting bundles that should be subject to this strategy ? @OskarStark @Soullivaneuh please advise.
1. What should happen when the users customizes the global label translator strategy, and specifies another strategy on a given admin ?
1. I'm basing this P.R. on the 2.3 branch, I think it can be fully B.C.

### CODE REVIEW

**Comment by rande** [comment]
Did you see this documentation : https://sonata-project.org/bundles/admin/master/doc/reference/translation.html#label-strategies ?

**Comment by greg0ire** [comment]
> Did you see this documentation : https://sonata-project.org/bundles/admin/master/doc/reference/translation.html#label-strategies ?

Oh my god no… how did I miss that ?

**Comment by rande** [comment]
I should add a search engine :)

**Comment by greg0ire** [comment]
> I should add a search engine :)

Yeah, and I should get some sleep :P

**Comment by greg0ire** [comment]
I'm going to merge both docs.

**Comment by OskarStark** [comment]
any news @greg0ire

**Comment by greg0ire** [comment]
I'm waiting for your input on item 1.

**Comment by Soullivaneuh** [comment]
First of all, are we talking about a new feature or a fix?

**Comment by OskarStark** [comment]
using an existing feature more easily by a global config option, right?

**Comment by greg0ire** [comment]
It's a new feature : being able to configure strategies globally. For the moment, you have to set them admin by admin, which is a bit painful.

I think the best would be if every bundle could have its own strategy : 

```
sonata_admin:
   label_translator_strategy:
      bundle1: some_strategy
      bundle2: some_other_strategy
```

**Comment by greg0ire** [comment]
> using an existing feature more easily by a global config option, right?

exactly, that would avoid a lot of repetition if one's admin.yml

**Comment by OskarStark** [comment]
> I think the best would be if every bundle could have its own strategy :

what about:

```yaml
sonata_admin:
   label_translator_strategy:
    global: some_strategy
    bundles:
        bundle1: some_strategy
        bundle2: some_other_strategy
```

**Comment by Soullivaneuh** [comment]
As new feature, it should be on master and not 2.3.

**Comment by greg0ire** [comment]
> As new feature, it should be on master and not 2.3.

Duly noted, I'll fix that

**Comment by greg0ire** [comment]
@OskarStark : not sure about global : it could apply to vendor bundles that did not specify anything, and break their translations

**Comment by greg0ire** [comment]
Maybe this would be better : 

```
sonata_admin:
   label_translator_strategy:
    global: some_strategy
    bundles:
        some_strategy: [bundle1, bundle2, bundle3]
        some_other_strategy: [bundle4, bundle5]
```

**Comment by greg0ire** [comment]
> @OskarStark : not sure about global : it could apply to vendor bundles that did not specify anything, and break their translations

Although global should be optional, so if it breaks anything, "just do not use it" seems sensible

**Comment by greg0ire** [comment]
Other question, what should `bundle1` exactly be ? A namespace prefix ? In which case someone could actually match several bundles with one prefix, likes `MyCompany` ?

**Comment by OskarStark** [comment]
> not sure about global : it could apply to vendor bundles that did not specify anything, and break their translations

you're right, global is not a great idea...

like this version of you, it looks wrong with ```bundles```:
```yaml
sonata_admin:
   label_translator_strategy:
       bundles:
           some_strategy: [bundle1, bundle2, bundle3]
           some_other_strategy: [bundle4, bundle5]
```

i think you mean something like this?
```yaml
sonata_admin:
   label_translator_strategy:
       strategies:
           some_strategy: [bundle1, bundle2, bundle3]
           some_other_strategy: [bundle4, bundle5]
```

**Comment by greg0ire** [comment]
Looks better indeed! What about the "bundle1" reference ? What would you actually use here ?

**Comment by rande** [comment]
I don't see the use case where this should be useful. It will be a pain to update the provided the translation for the new generated keys.

**Comment by OskarStark** [comment]
> What would you actually use here ?

```yaml
sonata_admin:
    label_translator_strategy:
        strategies:
            sonata.admin.label.strategy.native:
                - app.admin.foo
                - app.admin.bar
            sonata.admin.label.strategy.underscore:
                - app.admin.product
```

i would recommend to use the admin service id, because the strategies are already applied on the admin service configuration, what do you think?

**Comment by greg0ire** [comment]
> I don't see the use case where this should be useful. It will be a pain to update the provided the translation for the new generated keys.

It would not be configured globally by the bundle user. Instead, the bundle would merge their `sonata_admin` configuration with the user's configuration. Which means it should be mergeable. Which means we cannot really use the `strategies` key, @OskarStark, but stick with the bundles key.

**Comment by greg0ire** [comment]
> i would recommend to use the admin service id, because the strategies are already applied on the admin service configuration, what do you think?

I was thinking about something more general, like a bundle name or a namespace prefix, so that you do not have to specify every admin in your bundle (it is unlikely that you would mix strategies in a given bundle, but you should still be able to by not using this new feature and sticking with what already exists).

**Comment by rande** [comment]
The feature already exists: https://github.com/sonata-project/SonataAdminBundle/blob/master/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L225-L248

And it is documented: https://sonata-project.org/bundles/admin/master/doc/reference/advanced_configuration.html#service-configuration

:)

**Comment by greg0ire** [comment]
@rande : 

> When you create a new Admin service you can configure its dependencies, the services which are injected by default are:

You cannot change the defaults for all the admin in your bundle, can you ?

**Comment by greg0ire** [comment]
I think in the end it should look like that : 

```
/// config.yml
sonata_admin:
    label_translator_strategy:
        bundles:
            MyBundle: my_strategy_id
```

Then, in sonataUserBundle, you would prepend this config: 


```
# config.yml
sonata_admin:
    label_translator_strategy:
        bundles:
            SonataCoreBundle: whatever.strategy.is.used.in.the.core.bundle
```

**Comment by rande** [comment]
@greg0ire no, and I don't see the use case where you need to update all services. It is very sensible, and I guess it will be easier for someone you really want to do that to create a dedicated CompilerPass.

**Comment by rande** [comment]
if this should be implemented, it will be better to have:

```
sonata_admin:
     default_services:
           model_manager: the service id
           form_contractor: another service id
           label_translator_strategy: sonata.admin.label.strategy.native
```

**Comment by greg0ire** [comment]
@rande : here is how my admin.yml file looks at the moment :

```
    admin.library:
        class: SomeAdmin
        tags:
            -
                name: sonata.admin
                manager_type: orm
                label_translator_strategy: "sonata.admin.label.strategy.underscore"
    admin.admin_entity:
        class: SomeOtherADmin
        tags:
            -
                name: sonata.admin
                manager_type: orm
                label_translator_strategy: "sonata.admin.label.strategy.underscore"
    admin.prospect:
        class: YetAnotherAdmin
        tags:
            -
                name: sonata.admin
                manager_type: orm
                label_translator_strategy: "sonata.admin.label.strategy.underscore"
```

How can I avoid repeating the `label_translator_strategy` ? I'm using that on
every project, because I think it is far better that the native strategy, I'm
never going to use anything else in my bundles. Am I missing something ?

**Comment by greg0ire** [comment]
> if this should be implemented, it will be better to have…

Indeed, let's be more generic. But I think there should be an additional thing to specify : what should this defaults be limited to ? For instance, people probably do not want to change the strategy for, say, `SonataUserBundle`… so it should probably be :

```
sonata_admin:
    default_services:
        my_bundle:
            model_manager: the service id
            form_contractor: another service id
            label_translator_strategy: sonata.admin.label.strategy.native
```

That way, SonataUserBundle can also specify its config and get it merged with
the final user's config.

**Comment by rande** [comment]
@greg0ire you are also repeating the ``name``, and the ``manager_type``. IMHO, it is better to be explicit on what you want. There is no performance gain with your proposal. It just another vector of configuration complexity.

**Comment by greg0ire** [comment]
> you are also repeating the name, and the manager_type

I wouldn't if I could…

> There is no performance gain with your proposal.

That's not what I was looking for, I was looking for better DX

> It just another vector of configuration complexity. 

I get that, there are already many way to change the strategy, but it is not possible globally… too bad. But in the end it's your call, so I am closing.

**Comment by rande** [comment]
@greg0ire The feature can be implemented in a dedicated bundle, also I am not the only one to choose. I just raise my voice ;)

**Comment by greg0ire** [comment]
Ok, @OskarStark @Soullivaneuh , what do you think ? Useful or not ? Do not hesitate to say if not, I haven't coded anything yet, so, no worries :)

**Comment by OskarStark** [comment]
what about using the proposition by @rande 

```yaml
sonata_admin:
     default_services:
           model_manager: the service id
           form_contractor: another service id
           label_translator_strategy: sonata.admin.label.strategy.native
```

but IF the strategy is set directly on an admin, this one gets used?

same like the group for example:

```yaml
            sonata.admin.group.settings:
                label:           navigation.folder.settings
                label_catalogue: messages
                icon:            '<i class="fa fa-cog"></i>'
                items:
                    - setting.admin.portal_setting
```

```yaml
services:
    setting.admin.portal_setting:
        class: SettingBundle\Admin\PortalSettingAdmin
        arguments: [~, SettingBundle\Entity\PortalSetting, SettingBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Portal Setting List }
```

In this case ```group:admin``` is specified, but overwritten by the navigation configuration.

For the strategies i would like to use the reverse case. this already helps us to stay BC, because if its set directly on an admin, it works again

**Comment by greg0ire** [comment]
> but IF the strategy is set directly on an admin, this one gets used?

My point exactly, we are going to replace the defaults in the compiler pass

**Pull request closed without merging**
