### PR TITLE
[DO NOT MERGE] Merge 3.x

### PR DESCRIPTION
**Pull request by greg0ire**
Use `git reset` and `git push` instead. This is just to prove the tests are passing before pushing.

### CODE REVIEW

**Comment by greg0ire** [comment]
@Soullivaneuh follow the "command line instructions" link if you want to easily get my branch.

**Comment by greg0ire** [comment]
Wrong branch. Which does not matter since this will not get merged.

**Comment by Soullivaneuh** [comment]
I merged conflict myself.

Next time, do your CS nazi actions on 3.x! https://github.com/sonata-project/SonataAdminBundle/commit/3a87760c5c4070707df90303e6b83096720a0b0e

:trollface:

**Comment by greg0ire** [comment]
Right. I feel your pain

**Pull request closed without merging**
