### PR TITLE
Remove deprecation notices

### PR DESCRIPTION
**Pull request by greg0ire**
Backports many deprecation fixes from master

### CODE REVIEW

**Comment by OskarStark** [comment]
@greg0ire can i merge this?

**Comment by greg0ire** [comment]
Yes please. There are all the commit I found on master that fix deprecation notices.

**Comment by greg0ire** [comment]
Tagging 2.3.8 would be great just for that BTW : people would see far less deprecation notices.

**Comment by OskarStark** [comment]
to be honest i don't know how to do this here.

@core23 can you help?

**Comment by greg0ire** [comment]
IIRC, the plan was to have regular releases, and 2.3.{5.6.7} was following the plan but since… nothing.

**Pull request merged**
