### PR TITLE
make sure the test is running at the project level where JMSDiExtraBu…

### PR DESCRIPTION
**Pull request by rande**
I am targetting this branch, because it is the latest stable version.

## Changelog

```markdown
### Fixed
 - fix tests when they are started at the project level where JMSDiExtraBundle might not be available.
```

## Subject

fix tests when they are started at the project level where JMSDiExtraBundle might not be available.

### CODE REVIEW

**Comment by greg0ire** [comment]
LGTM. To bad there is no `--fail-on-skipped`, we risk the test not being run if the class is renamed or the dependency removed.

**Comment by OskarStark** [comment]
or `pedantic` ?

**Comment by core23** [comment]
Not sure if we need this check, because the bundle will always be loaded via composer at project level.

**Comment by greg0ire** [comment]
@rande needs thus to be released, so patch it is. @core23 : what if this is run from a project w/o the bundle? @rande : for each require dev in the bundle but not in the library, the project can fail, I didn't think of that when we argued about tests run from outside the bundle. This could be quite painful to maintain

**Comment by rande** [comment]
I can add the dependency in the sandbox, however it will not be used...

**Comment by greg0ire** [comment]
Add it as require dev?

**Comment by rande** [comment]
Yes; I can do that

**Comment by core23** [comment]
A project without the dependency won't run the tests. Test files will only be loaded on project level

**Pull request closed without merging**
