### PR TITLE
Fix wrong context on Select2 v4 field width calculation

### PR DESCRIPTION
**Pull request by alexndlm**
Fix select2 width calculation when using select2 4.

I am targetting this branch, because I am fix bug, and kept BC.

## Changelog
```markdown
### Fixed
- Fixed select2 width calculation when using select2 v4
```

## Subject
Fix select2 width calculation when using select2 4.

### CODE REVIEW

**Comment by greg0ire** [comment]
Please explain what the bug is and how your PR fixes it.

**Comment by jordisala1991** [comment]
Ping @alexndlm

**Comment by alexndlm** [comment]
When using select2 v4 argument passed to function Admin.get_select2_width is `jQuery(this)`.
`jQuery(this)` point to wrong context.

**Comment by alexndlm** [comment]
Done.

**Comment by jordisala1991** [comment]
We still need to know what is the bug you are fixing, would be nice to have some examples. Maybe a before and after screenshot? @alexndlm

**Comment by OskarStark** [comment]
> Maybe a before and after screenshot?

Screenshots would be great 👏

**Comment by alexndlm** [comment]
Before
select2 width before
After
select2 width after

**Comment by jordisala1991** [comment]
We need to make sure, this does not break with select2 < 4. Because we are still not supporting it (it is installed on SonataCoreBundle). Not sure how did you get that version, but must be your custom code.

I will try it tonight, if someone can try it also, would be nice.

**Comment by greg0ire** [comment]
2 changes… 3 commits, with cryptic messages… you can merge this, but if you do, please squash-merge, and provide a message that anyone can understand without looking at this web page.

**Comment by Soullivaneuh** [comment]
@alexndlm Are you sure about your fix? What about filters and edit fields rendering?

**Comment by Soullivaneuh** [comment]
Thank you @alexndlm.

**Comment by alexndlm** [comment]
Excellent

**Pull request merged**
