### PR TITLE
Fix phpstan

### PR DESCRIPTION
**Pull request by franmomu**

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]
Do you want to make a contribution to doctrine/common in order to add a template to this method ? :)

**Comment by franmomu** [comment]
> Do you want to make a contribution to doctrine/common in order to add a template to this method ? :)

I did, the problem is that is not really right: https://github.com/doctrine/common/pull/926

**Comment by VincentLanglet** [comment]
Maybe https://github.com/doctrine/common/pull/926#issuecomment-812471812 ?

**Comment by franmomu** [comment]
I'll give it a try 👍

**Pull request merged**
