### PR TITLE
add more config info to Lock Protection cookbook

### PR DESCRIPTION
**Pull request by mcwebb**
Follow up from https://github.com/sonata-project/SonataAdminBundle/pull/3170#issuecomment-149632675

### CODE REVIEW

**Comment by OskarStark** [comment]
is it important, that the fieldname is ``$version``, i would explicitly write this down.

**Comment by mcwebb** [comment]
I've clarified that the fieldname must be $version, and also added an XML config example.

**Comment by OskarStark** [comment]
Thank you very much @mcwebb :+1:

**Comment by mcwebb** [comment]
:+1:

**Pull request merged**
