### PR TITLE
Fix install doc

### PR DESCRIPTION
**Pull request by jvasseur**
Fix for #3412

The first commit moves the documentation of routes that need to be added in one place.
The second removes some duplication in the doc.

This may need a deeper look to see if some information need to be salvaged from the parts I removed (I don't have time to do it now).

### CODE REVIEW

**Comment by core23** [comment]
Please rebase

**Comment by jvasseur** [comment]
Rebased

**Comment by core23** [comment]
Please check travis @jvasseur

**Comment by core23** [comment]
ping @jvasseur

**Comment by jvasseur** [comment]
Fixed travis, sorry i waited so long to do it.

**Comment by greg0ire** [comment]
> This may need a deeper look to see if some information need to be salvaged from the parts I removed (I don't have time to do it now).

@jvasseur , could you give "the deeper look" ? We don't have that much times ourselves either. If you can't I'll do it, but it would be great if you did it yourself.

**Pull request closed without merging**
