### PR TITLE
Fix autocomplete search for field.subfield

### PR DESCRIPTION
**Pull request by netounet**
New PR to fix autocomplete search previously fixed in #3279
Last weeks was really fast and cannot take a look to my previous PR.
To avoid problem with rebase i just made a new fresh PR

### CODE REVIEW

**Comment by OskarStark** [comment]
thank you @netounet 

can you please provide a Test for this?

**Comment by netounet** [comment]
I would, but dont see how to test it. Just read the existing test, and for me it's on the dark side of the force :) The logic would be to test that the return list is filtered when a filtre type xxx.xxx is provided but i'm really dummy in test. @OskarStark  Any exemple or advice to do it ?

**Comment by OskarStark** [comment]
Not really an idea.

Maybe @Soullivaneuh can help

**Comment by core23** [comment]
Without a test case - no merge :-1:

**Comment by OskarStark** [comment]
@netounet maybe you can check how the test for autocomplete stuff works and adapt it?

**Comment by core23** [comment]
Any news @netounet ?

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
