### PR TITLE
Update show boolean field template icons

### PR DESCRIPTION
**Pull request by gnorby88**

### CODE REVIEW

**Comment by OskarStark** [comment]
fixes #3202 

thank you @gnorby88

**Comment by OskarStark** [comment]
can you please adjust the tests, which are failing in the travis build?

if you need help, ping me

**Comment by gnorby88** [comment]
Ok. But how? Is there any tut?

**Comment by Soullivaneuh** [comment]
@gnorby88 Just see Travis: https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/77679848#L492

You need to edit the according test to match new icons.

**Comment by OskarStark** [comment]
one more @gnorby88 

```
Sonata\AdminBundle\Tests\Twig\Extension\SonataAdminExtensionTest::testRenderViewElement with data set #67 ('<th>Data</th> <td><i class="f...o</td>', 'boolean', Sonata\AdminBundle\Exception\NoValueException Object (...), array())
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'<th>Data</th> <td><i class="fa fa-check-circle-o"></i>no</td>'
+'<th>Data</th> <td><i class="fa fa-ban"></i>no</td>'

/project/Tests/Twig/Extension/SonataAdminExtensionTest.php:482
```

**Comment by Soullivaneuh** [comment]
Please squash your commits (With `fixup` method to avoid extra useless comments).

**Comment by gnorby88** [comment]
Ok. But how? I tried git commit --fixup first_commit_number.. But nothing to commit, working directory clean. Sorry, but i am newbie in git :)

**Comment by qsomazzi** [comment]
@gnorby88 you can use this tutorial to lear how to squash : http://www.ekino.com/comment-squasher-efficacement-ses-commits-avec-git/

**Comment by OskarStark** [comment]
```git rebase -i HEAD~4```

then you should see 4 commits

leave the first as it is and then put an ```f``` (for fixup) in front of the others as described in the interactive editor on the CLI.

afterwards save

then push your branch as you did with the ```--force``` parameter.

**Comment by gnorby88** [comment]
It's ok? Thanks to all for help :)

**Comment by qsomazzi** [comment]
:+1:

**Comment by Soullivaneuh** [comment]
Thank you for your contribution @gnorby88.

**Comment by OskarStark** [comment]
thank you for your work!

2015-08-31 10:40 GMT+02:00 Sullivan SENECHAL <notifications@github.com>:

**Pull request merged**
