### PR TITLE
Use `while` statement instead of `do / while` at `CRUDController::assertObjectExists()`

### PR DESCRIPTION
**Pull request by phansys**
## Subject
Use `while` statement instead of `do / while` at `CRUDController::assertObjectExists()`.

I am targeting this branch, because this change respects BC.

See https://github.com/sonata-project/SonataAdminBundle/pull/6917#issuecomment-792095431.

## Changelog

```markdown
### Fixed
- Issue "Right side of && is always true" detected by PHPStan.
```

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Test are failing because of the change from 4.5.0 to 4.5.1 
https://github.com/sonata-project/SonataBlockBundle/compare/4.5.0...4.5.1

**Comment by core23** [comment]
Can you try to add a test that covers the problem?

**Review by core23 — APPROVED** [review]

**Comment by VincentLanglet** [comment]
> Can you try to add a test that covers the problem?

The problem solved by @phansys is just a phpstan error, there is no test to add IMHO.
But we have to solve the test failure.

**Comment by VincentLanglet** [comment]
I made https://github.com/sonata-project/SonataBlockBundle/pull/846 and I think a 4.5.2 will be needed

**Review by dmaicher — APPROVED** [review]

**Pull request merged**
