### PR TITLE
checkbox display problem fixed

### PR DESCRIPTION
**Pull request by iBasit**
#3600  issue fixed

### CODE REVIEW

**Comment by greg0ire** [comment]
Please rebase on the latest master, it should make the tests green.

**Comment by vincenttouzet** [comment]
I've tested and the translation domain is not used.

By adding the following block it works : 

```twig
{% block checkbox_radio_label %}
    {% if sonata_admin.admin %}
        {% set translation_domain = sonata_admin.field_description.translationDomain %}
    {% endif %}
    {# Do not display the label if widget is not defined in order to prevent double label rendering #}
    {% if widget is defined %}
        {% if required %}
            {% set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' required')|trim}) %}
        {% endif %}
        {% if parent_label_class is defined %}
            {% set label_attr = label_attr|merge({class: (label_attr.class|default('') ~ ' ' ~ parent_label_class)|trim}) %}
        {% endif %}
        {% if label is not sameas(false) and label is empty %}
            {% set label = name|humanize %}
        {% endif %}
        <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>
            {{- widget|raw -}}
            {{- label is not sameas(false) ? label|trans({}, translation_domain) -}}
        </label>
    {% endif %}
{% endblock checkbox_radio_label %}
```

**Comment by iBasit** [comment]
Following are my changes,  which works fine for me. 
```
{% block checkbox_widget -%}
    {% set parent_label_class = parent_label_class|default('') -%}
    {% if 'checkbox-inline' in parent_label_class %}
        {{- form_label(form, null, { widget: parent() }) -}}
    {% else -%}
        <div class="checkbox">
            {{- form_label(form, null, { widget: parent() }) -}}
        </div>
    {%- endif %}
{%- endblock checkbox_widget %}

{% block radio_widget -%}
    {%- set parent_label_class = parent_label_class|default('') -%}
    {% if 'radio-inline' in parent_label_class %}
        {{- form_label(form, null, { widget: parent() }) -}}
    {% else -%}
        <div class="radio">
            {{- form_label(form, null, { widget: parent() }) -}}
        </div>
    {%- endif %}
{%- endblock radio_widget %}

{% block checkbox_label -%}
    {{- block('checkbox_radio_label') -}}
{%- endblock checkbox_label %}

{% block radio_label -%}
    {{- block('checkbox_radio_label') -}}
{%- endblock radio_label %}
```

**Comment by greg0ire** [comment]
Please add tests to make sure it really works for everyone and prevent regressions. Here is an example of such a test : https://github.com/sonata-project/SonataAdminBundle/blob/master/Tests/Form/Widget/FormChoiceWidgetTest.php

**Comment by vincenttouzet** [comment]
I also have double label rendering when using 'sonata_type_model' with multiple and expanded to true.

Example with SonataUserBundle :
creer

**Comment by vincenttouzet** [comment]
If you replace the `choice_widget_expanded ` block with the following it fix the double label rendering

```twig
{% block choice_widget_expanded %}
{% spaceless %}
    {% set attr = attr|merge({'class': attr.class|default('') ~ ' list-unstyled'}) %}
    <ul {{ block('widget_container_attributes') }}>
    {% for child in form %}
        <li>
            {% set form_widget_content %}
                {{ form_widget(child, {'horizontal': false, 'horizontal_input_wrapper_class': ''}) }} {# {'horizontal': false, 'horizontal_input_wrapper_class': ''} needed to avoid MopaBootstrapBundle messing with the DOM #}
            {% endset %}
            {{ form_label(child, child.vars.label|default(null), { 'in_list_checkbox' : true, 'widget' : form_widget_content } ) }}
        </li>
    {% endfor %}
    </ul>
{% endspaceless %}
{% endblock choice_widget_expanded %}
```

**Comment by iBasit** [comment]
@vincenttouzet can you please create pull request with the fix. I won't be able to recreate pull request again.

**Comment by vincenttouzet** [comment]
I've updated my pull request : https://github.com/sonata-project/SonataAdminBundle/pull/3127

**Comment by greg0ire** [comment]
@iBasit : if you agree with #3127 , can you close this pull request?

**Comment by greg0ire** [comment]
ping @iBasit

**Comment by greg0ire** [comment]
@iBasit ? Are you there?

**Comment by iBasit** [comment]
@greg0ire Yes, sorry for delay response, closing this pull request

**Pull request closed without merging**
