### PR TITLE
We can use the autocomplete with only the LIST role

### PR DESCRIPTION
**Pull request by BenoitLeveque**
My Admin is only granted to display the list of my entities, i should be able to filter the list with the autocomplete filter the same way i can use the doctrine_orm_model filter

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Please rebase your PR for test.

**Comment by webdevilopers** [comment]
:+1:
Same problem here:
- https://github.com/sonata-project/SonataAdminBundle/pull/2523#issuecomment-118762083

**Comment by pulzarraider** [comment]
You should check if you are in the `filter` context. This ajax action is used for autocomplete filter and for autocomplete form type in create/edit operation, too.

In filter - granting for LIST should be checkd.
In create/edit - granting for CREATE/EDIT should be checkd.

**Comment by BenoitLeveque** [comment]
@Soullivaneuh i've finally updated my PR to follow @pulzarraider advice

**Comment by pulzarraider** [comment]
Thank you @BenoitLeveque

**Pull request merged**
