### PR TITLE
Revert "Make services shared"

### PR DESCRIPTION
**Pull request by jordisala1991**
Reverts sonata-project/SonataAdminBundle#4864

### CODE REVIEW

**Comment by jordisala1991** [comment]
I found a bug when using 3.x-dev: https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/513

Here I solved it by using this bundle reverting the last PR. I think we need to revert it all, and then find if there is a way to apply it again.

**Comment by greg0ire** [comment]
Please add a clear explanation as to why this is needed now that you know.

**Comment by greg0ire** [comment]
Cc @ossinkine

**Comment by ossinkine** [comment]
As I understand we should revert only `AddFilterTypeCompilerPass.php`. There is no issues with `AddDependencyCallsCompilerPass.php`, right?

**Comment by jordisala1991** [comment]
I need to add explanations on both reverts, but we need them both.

The problem is making this change affects on two things:

- People can get multiple filters with same type
- SonataDoctrinePHPCRAdminBundle starts failing again with the infinite loop problem

I am not sure if both issues can be solved and make those services shared again, but IMO until we figure out a way to do it, we should revert them

**Comment by greg0ire** [comment]
:+1: for revert, just... with explanations for the next devs

**Comment by jordisala1991** [comment]
I did a rework on the commit message, but I am not really sure on how to explain it better.

**Comment by greg0ire** [comment]
For the filters, it's probably because they are stateful, right? Filter settings are probably part of the state instead of passed to them at runtime.

**Comment by ossinkine** [comment]
@jordisala1991 Did you have any chance to figure out with shared admins issue? If no, could you share the reproducer for I trying to debug?

**Comment by jordisala1991** [comment]
The phpcr admin bundle is a good example. If you try to run travis with the change it does not work

**Comment by jvasseur** [comment]
I don't think admin services can be made shared: they contains a lot of state and can be instantiated multiple times in the same request (in case of parent/child relationships for example).

**Pull request merged**
