### PR TITLE
Custom Knp menu

### PR DESCRIPTION
**Pull request by Wharenn**
This PR allows usage of a custom Knp menu as a menu group:

    sonata_admin:
        dashboard:
            groups:
                my_group:
                    provider: 'MyBundle:MyMenuProvider:getMyMenu'

- [x] Code
- [x] Documentation
- [x] Tests

### CODE REVIEW

**Comment by Wharenn** [comment]
@rande, can you check this PR please ?

**Comment by rande** [comment]
Can you also add the logic to add the provider for an item ?


```
sonata_admin:
    dashboard:
        groups:
            my_group:
                provider: 'MyBundle:MyMenuProvider:getMyMenu'

            my_second_group:
                label:           sonata_content
                label_catalogue: SonataDemoBundle
                icon:            '<i class="fa fa-th"></i>'
                items:
                    - sonata.news.admin.comment
                    - sonata.news.admin.post
                    - sonata.media.admin.media
                    - {provider: 'MyBundle:MyMenuProvider:getMyMenu' }
                    - sonata.media.admin.gallery
                    - sonata.comment.admin.thread
```

**Comment by Wharenn** [comment]
I think we can do this in two parts :)

**Comment by plouc** [comment]
@Wharenn, can you please create an issue with the @rande request ?

**Pull request merged**
