### PR TITLE
admin value resolver accept generat AdminInterface type

### LINKED ISSUE #7846: AdminValueResolver don't check type properly
## Subject

When typing argument with the admin interface instead of the exact admin type the admin is not found.

## Code example

```PHP
class Admin implements \Sonata\AdminBundle\Admin\AdminInterface
{

}

class Action
{
  public function failingAction(\Sonata\AdminBundle\Admin\AdminInterface $admin)
  {
     // Will not found the admin parameter
  }

  public function workingAction(Admin $admin)
  {
    // Everything is ok
  }
}

```

## How to fix

This is because the is_subclass_of function use in AdminValueResolver does check if the class is the same as requested. Also the is_a function have a different behaviour base on a class string or an object, probably a bug in PHP, so it cannot be use of the first check.

```PHP
class Admin implements \Sonata\AdminBundle\Admin\AdminInterface
{

}

class Action
{
  public function failingAction(\Sonata\AdminBundle\Admin\AdminInterface $admin)
  {
  }

  public function workingAction(Admin $admin)
  {
  }
}

var_dump(is_a(ClassX::class, InterfaceY::class)); // false

var_dump(is_a(ClassX::class, ClassX::class)); // false

var_dump(is_a(new ClassX(), InterfaceY::class)); // true

var_dump(is_a(new ClassX(), ClassX::class)); // true

var_dump(is_subclass_of(ClassX::class, ClassX::class)); // false

var_dump(is_subclass_of(ClassX::class, InterfaceY::class)); // true
```

Recommendation would be the check if $type === AdminInterface::class or is_subclass_of.

### PR DESCRIPTION
**Pull request by mpoiriert**
## Subject

I am targeting this branch, because the bug is present in this branch.

Closes #7846.

## Changelog

```markdown

### Fixed
AdminValueResolver does support generic AdminInterface type.
```

### CODE REVIEW

**Comment by mpoiriert** [comment]
@VincentLanglet The PR is ready for #7846

**Comment by jordisala1991** [comment]
Do we have any docs for this feature?

**Comment by mpoiriert** [comment]
> Do we have any docs for this feature?

Yes there is in the Decouple from CRUDController but not specific to inject AdminInterface. I did add an example in the batch controller documentation.

I will add one to the documentation above.

**Comment by jordisala1991** [comment]
That would be great

**Comment by mpoiriert** [comment]
Done

**Review by VincentLanglet — APPROVED** [review]

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thanks @mpoiriert

**Pull request merged**
