### PR TITLE
Use ErrorElement from CoreBundle namespace

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
If this is indeed the good goal, we'll have to change use statement of a huge classes number. Did you plan it?

**Comment by rande** [comment]
@Soullivaneuh seems I commit a file for this PR: https://github.com/sonata-project/SonataAdminBundle/pull/2792

**Comment by Soullivaneuh** [comment]
Oops, wrong branch? :)

**Comment by Soullivaneuh** [comment]
@rande I also have to change namespace on several classes to get it working.

Can I make another PR or should I wait your work finished?

**Comment by rande** [comment]
@Soullivaneuh this should be fixed for the Admin class. did I miss others classes ?

**Comment by xaben** [comment]
@rande Exception is back...

[Symfony\Component\Debug\Exception\FatalErrorException]                                                                     
  Compile Error: Declaration of Sonata\AdminBundle\Admin\Admin::validate() must be compatible with Sonata\AdminBundle\Admin\  
  AdminInterface::validate(Sonata\CoreBundle\Validator\ErrorElement $errorElement, $object)

**Comment by Soullivaneuh** [comment]
@rande  Seems not:

```sh
$ app/console server:run localhost:9090
PHP Fatal error:  Declaration of Sonata\AdminBundle\Block\AdminListBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\AdminBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in /home/sullivan/projects/fork/sonata-sandbox/vendor/sonata-project/admin-bundle/Block/AdminListBlockService.php on line 105
PHP Stack trace:
PHP   1. {main}() /home/sullivan/projects/fork/sonata-sandbox/app/console:0
PHP   2. Symfony\Component\Console\Application->run() /home/sullivan/projects/fork/sonata-sandbox/app/console:34
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/sullivan/projects/fork/sonata-sandbox/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\HttpKernel\Kernel->boot() /home/sullivan/projects/fork/sonata-sandbox/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:70
PHP   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() /home/sullivan/projects/fork/sonata-sandbox/app/bootstrap.php.cache:2344
PHP   6. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /home/sullivan/projects/fork/sonata-sandbox/app/bootstrap.php.cache:2565
PHP   7. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /home/sullivan/projects/fork/sonata-sandbox/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:614
PHP   8. JMS\AopBundle\DependencyInjection\Compiler\PointcutMatchingPass->process() /home/sullivan/projects/fork/sonata-sandbox/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:117
PHP   9. JMS\AopBundle\DependencyInjection\Compiler\PointcutMatchingPass->processDefinition() /home/sullivan/projects/fork/sonata-sandbox/vendor/jms/aop-bundle/JMS/AopBundle/DependencyInjection/Compiler/PointcutMatchingPass.php:64
PHP  10. class_exists() /home/sullivan/projects/fork/sonata-sandbox/vendor/jms/aop-bundle/JMS/AopBundle/DependencyInjection/Compiler/PointcutMatchingPass.php:110
PHP  11. spl_autoload_call() /home/sullivan/projects/fork/sonata-sandbox/vendor/jms/aop-bundle/JMS/AopBundle/DependencyInjection/Compiler/PointcutMatchingPass.php:110
PHP  12. Symfony\Component\Debug\DebugClassLoader->loadClass() /home/sullivan/projects/fork/sonata-sandbox/vendor/jms/aop-bundle/JMS/AopBundle/DependencyInjection/Compiler/PointcutMatchingPass.php:0
```

**Comment by rande** [comment]
@Soullivaneuh my current favorite gist: https://gist.github.com/rande/9c0cfbd751d3e64b893f

**Comment by Soullivaneuh** [comment]
I understand the risk @rande it's just to continue on dev! ;)

BTW, sonata-seo won't upgrade with your current composer.json.

```
$ composer info -i | grep seo
sonata-project/seo-bundle                        1.1.9               Symfony SonataSeoBundle
```

Change version to dev-master should do the trick, thanks!

**Pull request merged**
