### PR TITLE
Check field_description existence in ModelAutocompleteType form field

### LINKED ISSUE #5328: After upgrade 3.41 -> 3.42: Impossible to access an attribute ("associationadmin") on a null variable
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.41.0 3.42.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.13.0 3.13.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.12.0 3.12.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0  2.4.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.2  1.1.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.6.3  3.6.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.9.1  1.9.1  Lightweight Exporter library
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/asset                v4.2.0  v4.2.0  Symfony Asset Component
symfony/browser-kit          v4.2.0  v4.2.0  Symfony BrowserKit Component
symfony/cache                v4.2.0  v4.2.0  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config               v4.2.0  v4.2.0  Symfony Config Component
symfony/console              v4.2.0  v4.2.0  Symfony Console Component
symfony/contracts            v1.0.1  v1.0.1  A set of abstractions extracted out of the Symfony components
symfony/css-selector         v4.2.0  v4.2.0  Symfony CssSelector Component
symfony/debug                v4.2.0  v4.2.0  Symfony Debug Component
symfony/debug-bundle         v4.2.0  v4.2.0  Symfony DebugBundle
symfony/debug-pack           v1.0.6  v1.0.6  A debug pack for Symfony projects
symfony/dependency-injection v4.2.0  v4.2.0  Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.2.0  v4.2.0  Symfony Doctrine Bridge
symfony/dom-crawler          v4.2.0  v4.2.0  Symfony DomCrawler Component
symfony/dotenv               v4.2.0  v4.2.0  Registers environment variables from a .env file
symfony/event-dispatcher     v4.2.0  v4.2.0  Symfony EventDispatcher Component
symfony/expression-language  v4.2.0  v4.2.0  Symfony ExpressionLanguage Component
symfony/filesystem           v4.2.0  v4.2.0  Symfony Filesystem Component
symfony/finder               v4.2.0  v4.2.0  Symfony Finder Component
symfony/flex                 v1.1.8  v1.1.8  Composer plugin for Symfony
symfony/form                 v4.2.0  v4.2.0  Symfony Form Component
symfony/framework-bundle     v4.2.0  v4.2.0  Symfony FrameworkBundle
symfony/http-foundation      v4.2.0  v4.2.0  Symfony HttpFoundation Component
symfony/http-kernel          v4.2.0  v4.2.0  Symfony HttpKernel Component
symfony/inflector            v4.2.0  v4.2.0  Symfony Inflector Component
symfony/intl                 v4.2.0  v4.2.0  A PHP replacement layer for the C intl extension that includes additional data from the...
symfony/maker-bundle         v1.9.0  v1.9.0  Symfony Maker helps you create empty commands, controllers, form classes, tests and mor...
symfony/monolog-bridge       v4.2.0  v4.2.0  Symfony Monolog Bridge
symfony/monolog-bundle       v3.3.1  v3.3.1  Symfony MonologBundle
symfony/options-resolver     v4.2.0  v4.2.0  Symfony OptionsResolver Component
symfony/orm-pack             v1.0.5  v1.0.5  A pack for the Doctrine ORM
symfony/panther              v0.2.0  v0.2.0  A browser testing and web scraping library for PHP and Symfony.
symfony/phpunit-bridge       v4.2.0  v4.2.0  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu    v1.10.0 v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.10.0 v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72       v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process              v4.2.0  v4.2.0  Symfony Process Component
symfony/profiler-pack        v1.0.3  v1.0.3  A pack for the Symfony web profiler
symfony/property-access      v4.2.0  v4.2.0  Symfony PropertyAccess Component
symfony/property-info        v4.2.0  v4.2.0  Symfony Property Info Component
symfony/routing              v4.2.0  v4.2.0  Symfony Routing Component
symfony/security-acl         v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.2.0  v4.2.0  Symfony SecurityBundle
symfony/security-core        v4.2.0  v4.2.0  Symfony Security Component - Core Library
symfony/security-csrf        v4.2.0  v4.2.0  Symfony Security Component - CSRF Library
symfony/security-guard       v4.2.0  v4.2.0  Symfony Security Component - Guard
symfony/security-http        v4.2.0  v4.2.0  Symfony Security Component - HTTP Integration
symfony/serializer           v4.2.0  v4.2.0  Symfony Serializer Component
symfony/serializer-pack      v1.0.1  v1.0.1  A pack for the Symfony serializer
symfony/stopwatch            v4.2.0  v4.2.0  Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.4  v3.2.4  Symfony SwiftmailerBundle
symfony/templating           v4.2.0  v4.2.0  Symfony Templating Component
symfony/test-pack            v1.0.4  v1.0.4  A pack for functional and end-to-end testing within a Symfony app
symfony/translation          v4.2.0  v4.2.0  Symfony Translation Component
symfony/twig-bridge          v4.2.0  v4.2.0  Symfony Twig Bridge
symfony/twig-bundle          v4.2.0  v4.2.0  Symfony TwigBundle
symfony/validator            v4.2.0  v4.2.0  Symfony Validator Component
symfony/var-dumper           v4.2.0  v4.2.0  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter         v4.2.0  v4.2.0  A blend of var_export() + serialize() to turn any serializable data structure to plain ...
symfony/web-link             v4.2.0  v4.2.0  Symfony WebLink Component
symfony/web-profiler-bundle  v4.2.0  v4.2.0  Symfony WebProfilerBundle
symfony/web-server-bundle    v4.2.0  v4.2.0  Symfony WebServerBundle
symfony/yaml                 v4.2.0  v4.2.0  Symfony Yaml Component```

#### PHP version

```
$ php -v
```
PHP 7.2.12 (cli) (built: Nov 16 2018 04:05:32) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.12, Copyright (c) 1999-2018, by Zend Technologies```
```

## Subject

"Impossible to access an attribute ("associationadmin") on a null variable" error on **showing list page with datagrid filter**.

An idea to the issue is located: https://github.com/sonata-project/SonataAdminBundle/compare/3.41.0...3.42.0#diff-9596174093e5de44115aaacafe7d4d77

## Steps to reproduce
In example
```
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('organization', ModelAutocompleteFilter::class, [], null, [
                'property' => 'name',
                'to_string_callback' => function (OrganizationInterface $entity) {
                    return $entity->getName();
                },
            ])
        ;
    }
```

## Expected results
A list page with 200 return http code. :)

## Actual results
HTTP Status 500

Best regards.

### PR DESCRIPTION
**Pull request by psyray**
## Subject

I am targeting this branch, because it's the main brach affected bu the bug.

Closes #5328 

## Changelog

```markdown
### Fixed
Fix crash on listing pages that have a datagrid filter

```

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Confirmed on Slack that this fixes the issue

**Comment by greg0ire** [comment]
Please write a changelog directed at end users. Keep in mind that they probably do not care what file or class you changed, but what features you provided / what bugs you fixed. Try to answer the question "What benefit do I get from upgrading?"
More on http://keepachangelog.com

**Comment by psyray** [comment]
@greg0ire  Can't be more clear than fix bug #5328

**Comment by greg0ire** [comment]
Are you kidding?

**Comment by psyray** [comment]
Nope
What do you want from me ?
This PR is a bugfix, so to answer your question "What benefit do I get from upgrading?"
The benefit is it fix the #5328 bug

**Comment by psyray** [comment]
You want me to add it in the title of the PR ?

**Comment by greg0ire** [comment]
There should be no mention of an issue number. Just a small description of the actual issue *end*-users will be facing. So, after reading #5328, I would say "fix crash on listing pages that have a datagrid filter". Isn't that way clearer?

**Comment by greg0ire** [comment]
Not the title, no, the changelog, it will appear here: https://github.com/sonata-project/SonataAdminBundle/releases

**Comment by greg0ire** [comment]
So please keep it reasonably small and avoid references to other pages, people don't want to click around they just want to know what will happen when they upgrade.

**Comment by greg0ire** [comment]
Thanks!

**Comment by psyray** [comment]
Don't know that the changelog will appear in the release page.

**Comment by greg0ire** [comment]
And you're probably not the only one. Let me try to improve https://github.com/sonata-project/dev-kit/blob/master/project/.github/PULL_REQUEST_TEMPLATE.md

**Comment by psyray** [comment]
:+1:

**Comment by greg0ire** [comment]
I think I will make a release just for that one, seems like a pretty big issue…

**Comment by greg0ire** [comment]
https://github.com/sonata-project/SonataAdminBundle/pull/5332

**Pull request merged**
