### PR TITLE
Add test against lowest dependencies

### PR DESCRIPTION
**Pull request by WouterJ**
Added a job to test the lower boundary of the specified version ranges. This will probably cause errors.

### CODE REVIEW

**Comment by WouterJ** [comment]
I can do 2 things now:

* Bump `doctrine/common` version requirement from `2.3` to`2.4`
* Add a little if statement to allow both 2.3 and 2.4

What do you want me to do?

**Comment by rande** [comment]
@WouterJ the build failed due to a missing class: ``Class 'Doctrine\Common\Inflector\Inflector'``, I guess the composer.json need to be adjusted

**Comment by WouterJ** [comment]
@rande that's exactly where I was talking about. The class was named `Doctrine\Common\Util\Inflector` in 2.3 and `Doctrine\Common\Inflector\Inflector` in >=2.4. So we could either bump the version or add a little if statement to use the correct class (as both have the same signature). What's your preferred choice?

**Comment by rande** [comment]
Hu, sorry I didn't see/read your comment :/ just bump the requirement to 2.4 as 2.3 is not supported as it.

**Comment by WouterJ** [comment]
I'm happy to tell you that all deps are correct now :)

**Comment by rande** [comment]
It's was not that bad ;)

**Pull request merged**
