### PR TITLE
Remove `setRequest` method call from menu builder definition

### PR DESCRIPTION
**Pull request by afurculita**
This solves https://github.com/sonata-project/SonataAdminBundle/issues/3712

### CODE REVIEW

**Comment by rmzamora** [comment]
This solved the error but introduce a new one for me. "An exception has been thrown during the rendering of a template ("The menu "sonata_admin_sidebar" exists, but is not a valid menu item object. Check where you created the menu to be sure it returns an ItemInterface object.")". Any solutions?

**Comment by iBasit** [comment]
+1 - waiting for this to be merged.

**Comment by greg0ire** [comment]
@afurculita @iBasit : what about @rmzamora 's problem ? @rmzamora : do you get this on every page ?

**Comment by yurii-mysak** [comment]
+1

**Comment by greg0ire** [comment]
@yurii-mysak @iBasit : there are :+1: buttons now, you know?

**Comment by greg0ire** [comment]
@rmzamora : I can't see how this PR would introduce your problem. Maybe the previous PR introduced it?

**Comment by OskarStark** [comment]
@greg0ire i think we can merge this, what do you think?

**Comment by greg0ire** [comment]
I think so too, as I said. @rmzamora 's problem, comes probably from @afurculita 's previous PR. @afurculita @rmzamora , can you talk together to get to the bottom of this please?

**Comment by core23** [comment]
:-1: There was no stable release with this

**Comment by greg0ire** [comment]
I don't understand. Once this is released, we will have to fix it, won't we? So why not fix it now?

**Comment by core23** [comment]
No, we don't. Using the latest **DEV**-master version is about taking the risk, that some code might change while developing. This part of code was never in a tag or non-dev-only release.

**Comment by core23** [comment]
Sorry, looked at the wrong ticket. Everything okax :+1:  ;)

**Comment by greg0ire** [comment]
Ok :) Please merge then :)

**Pull request merged**
