### PR TITLE
Fix possible null error in search

### PR DESCRIPTION
**Pull request by core23**
## Subject

I am targeting this branch, because this is a patch.

## Changelog

```markdown
### Fixed
- Fix possible null error in search
```

### CODE REVIEW

**Review by VincentLanglet — COMMENTED** [review]
It's not clear where there is an issue with the fact query can be null in the template https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/Core/search.html.twig

**Comment by core23** [comment]
It is an issue, I got several exception in my projects.

In the template we only check if the `query` variable is defined and not false. A null value is a defined value so the blocks are rendered.

**Comment by VincentLanglet** [comment]
> It is an issue, I got several exception in my projects.

What is the exception you get ?

The block result doesn't seems to use the query variable
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/Block/block_search_result.html.twig

> In the template we only check if the `query` variable is defined and not false. A null value is a defined value so the blocks are rendered.

`''` value will also be defined so block will be rendered in the same way.

Also, it's kinda weird to have this defined and not false check, since we use `query` in the translation too.
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/Core/search.html.twig#L14

it was made in https://github.com/sonata-project/SonataAdminBundle/pull/1855
Shouldn't we just update the template to `if query is not null` ?

**Comment by VincentLanglet** [comment]
Btw if you rebase, I fix the phpstan/rector build

**Comment by core23** [comment]
Done

**Comment by VincentLanglet** [comment]
> > It is an issue, I got several exception in my projects.
> 
> What is the exception you get ?
> 
> The block result doesn't seems to use the query variable [`4.x`/src/Resources/views/Block/block_search_result.html.twig](https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/Block/block_search_result.html.twig?rgh-link-date=2024-01-09T19%3A19%3A22Z)
> 
> > In the template we only check if the `query` variable is defined and not false. A null value is a defined value so the blocks are rendered.
> 
> `''` value will also be defined so block will be rendered in the same way.
> 
> Also, it's kinda weird to have this defined and not false check, since we use `query` in the translation too. [`4.x`/src/Resources/views/Core/search.html.twig#L14](https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/Core/search.html.twig?rgh-link-date=2024-01-09T19%3A19%3A22Z#L14)
> 
> it was made in #1855 Shouldn't we just update the template to `if query is not null` ?

I appreciate you re-request my review but I have a lot of question unanswered...

**Comment by core23** [comment]
> > It is an issue, I got several exception in my projects.
> 
> What is the exception you get ?

I receive a `TypeError`, as the null value is passed from the template to the **SearchHandler**:
```
/XXX/vendor/sonata-project/admin-bundle/src/Search/SearchHandler.php:38
/XXX/vendor/sonata-project/admin-bundle/src/Block/AdminSearchBlockService.php:68
/XXX/vendor/sonata-project/block-bundle/src/Block/BlockRenderer.php:46
/XXX/vendor/sonata-project/block-bundle/src/Templating/Helper/BlockHelper.php:162
/XXX/var/cache/prod/twig/98/98cd481aa2f0c78834272cc52e85c07d.php:105
```

> The block result doesn't seems to use the query variable https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/Block/block_search_result.html.twig
> 
> > In the template we only check if the `query` variable is defined and not false. A null value is a defined value so the blocks are rendered.
> 
> `''` value will also be defined so block will be rendered in the same way.
> 
> Also, it's kinda weird to have this defined and not false check, since we use `query` in the translation too. https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/Core/search.html.twig#L14
> 
> it was made in #1855 Shouldn't we just update the template to `if query is not null` ?

To be safe we could fix it in the template as well, but this won't help if you are using a custom template. The root cause is the block, not the template.

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks

Do you have the rights to make a release ? Or I will do it next week

**Pull request merged**
