### PR TITLE
Make the table in edition forms responsive

### PR DESCRIPTION
**Pull request by kuldipem**
On small devices, this class makes a scrollbar appear so that tables can be scrolled independently from the whole page.
See http://jasonbradley.me/bootstrap-responsive-tables/

### CODE REVIEW

**Comment by greg0ire** [comment]
The commit message should read:

```
Make the table in edition forms responsive

On small devices, this class makes a scrollbar appear so that tables can be scrolled independently from the whole page.
See http://jasonbradley.me/bootstrap-responsive-tables/
```

**Comment by core23** [comment]
Ping @kuldipem

**Comment by kuldipem** [comment]
hi @core23

**Comment by core23** [comment]
Can you please have a look at the comments... @kuldipem 

This title doesn't say anything

**Comment by kuldipem** [comment]
I have updated  the title

**Comment by core23** [comment]
... and the commit message please...

**Comment by kuldipem** [comment]
updated @core23

**Comment by greg0ire** [comment]
Looks like you did not change the commit message. Do you know how to do that?

**Comment by kuldipem** [comment]
I don't know how to change commit message. @greg0ire

**Comment by greg0ire** [comment]
Use `git commit --amend`, change the message, then save and exit, and the use `git push --force`.

**Comment by kuldipem** [comment]
In favor of PR #3603 closing this PR

**Pull request closed without merging**
