### PR TITLE
[doc] Fix documentation for `configureActionButtons()` method

### PR DESCRIPTION
**Pull request by phansys**
I am targetting this branch, because the method signature matches the one present in `master`.

Changelog

```markdown
### Fixed
- Update method signature for `configureActionButtons()` at `advanced_configuration.rst`
```

### CODE REVIEW

**Comment by phansys** [comment]
Hi @greg0ire. Sorry for the inconvenience, I've created the PR via API, so I didn't noticed the PR template. Fixed.

**Comment by greg0ire** [comment]
> I've created the PR via API

What does this mean? Honest question, many users are ignoring the template, it would be great to know why.

**Comment by phansys** [comment]
I've used a local tool that uses the GitHub API in order to perform the PR creation, not the web UI.

**Comment by greg0ire** [comment]
Ooooh I see! Interesting! Maybe some other contributors are using clients like the windows client for github, and it misses PR templates? I was thinking most of them were just lazy, but this could be the explanation!

**Comment by phansys** [comment]
Yes, this method doesn't exist in `2.x`.

**Comment by greg0ire** [comment]
Please rebase on 55a97ad3ad6ec19046be079e1fb6cda978d7a2e3, it should fix the build.

**Comment by phansys** [comment]
There were 71 commits between @55a97ad and @06296ef088d609069c324f67cf2372a44318705a, so I've noticed that the current fix isn't necessary at `3.x`: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/doc/reference/advanced_configuration.rst#actions-menu. Should I rebase evenly when the fix isn't required at `3.x`? Or should I close the PR?
The issue here is that [Symfony doc](http://symfony.com/doc/master/bundles/SonataAdminBundle/reference/advanced_configuration.html#actions-menu) is exposing the `3.x` branch as an alias of `master`, while that isn't true.

**Comment by greg0ire** [comment]
Woops sorry, I forgot you were on master. Not sure the fix in  55a97ad was backported here

**Comment by greg0ire** [comment]
Looks like it's ok now, you can rebase on master.

**Comment by OskarStark** [comment]
> Yes, this method doesn't exist in 2.x.

Ok, but what about `3.x`did you guys check that? Just asking to not overlook sth.

Thank you for your contribution @phansys 👍

**Comment by greg0ire** [comment]
Oh I didn't see you wrote `2.x` instead of `3.x`. What about that branch?

**Comment by greg0ire** [comment]
Please rebase on the latest 3.x, it should fix the build.

**Comment by greg0ire** [comment]
ping @phansys

**Comment by phansys** [comment]
As I mentioned before, the issue isn't at this repo, but in Symfony docs exposing the exposing the `3.x` branch as an alias of `master`, while that isn't true (the have different codes so the issue doesn't exist at all).

Thank you.

**Pull request closed without merging**
