### PR TITLE
allow user to define html class on autocomplete field

### PR DESCRIPTION
**Pull request by pantelm**
This PR add attr.class to the input fields in autocomplete so we can trigger action when the fields change based on the html class.

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you please add some tests and check travis?

Thank you :+1:

**Comment by core23** [comment]
Please add some test @pantelm

**Comment by pantelm** [comment]
I'll do asap

**Comment by pantelm** [comment]
I have some trouble on how to write the test. Some can help me?

**Comment by core23** [comment]
Maybe @greg0ire can help?

**Comment by greg0ire** [comment]
I must go, but maybe have a look at https://github.com/sonata-project/SonataAdminBundle/blob/master/Tests/Form/Widget/FormSonataFilterChoiceWidgetTest.php

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
