### PR TITLE
Add missing method in AbstractAdminExtension

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Changelog

```markdown
### Fixed
- Add missing `AbstractAdminExtension::configurePersistentParameters()`
```

### CODE REVIEW

**Review by phansys — COMMENTED** [review]
Isn't this a patch? If this change is fixing something, I think we should use "Fixed" instead of "Added" in the changelog.

**Review by phansys — APPROVED** [review]
It would be nice to have a test covering this fix.

**Comment by VincentLanglet** [comment]
> It would be nice to have a test covering this fix.

There is no real need here, it's an abstract class implementing an interface in the simplest way.
There is currently no AdminExtensionTest.
The test is kinda self-made in master ; because the LockExtension extends this abstract class and there is a php error if this method is not implemented.

**Comment by VincentLanglet** [comment]
I'll merge this since i'll do a release.

**Comment by franmomu** [comment]
Isn't this BC break?

Apparently there was a release with:

https://github.com/sonata-project/SonataAdminBundle/blob/3746236682cf6338ffc1ff598353155e1ec0d3a1/src/Admin/AbstractAdmin.php#L2139-L2162

I guess someone who was extending `AbstractAdminExtension` and overriding `getPersistentParameters`, after this, its `TheirExtension::getPersistentParameters` won't be called anymore.

**Comment by VincentLanglet** [comment]
I made a revert https://github.com/sonata-project/SonataAdminBundle/pull/6899 @franmomu

**Pull request merged**
