### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Hi, if we want to add this, it should be added here: https://github.com/sonata-project/dev-kit/tree/master/templates/project/.github/workflows

This `dev-kit` tool will then dispatch this files to every sonata projects.

cc @jordisala1991 WDYT about this ?

**Comment by jordisala1991** [comment]
Hum, for this kind of thing, I would prefer to trigger those updates on dev-kit itself, and then dev-kit is in charge to propagate to the other repositories.

**Comment by VincentLanglet** [comment]
> I would prefer to trigger those updates on dev-kit itself

You mean the dependencies updates ? All the project doesn't have the same.

I was wondering if we would have a lot of benefit from depandabot since some dependencies bump could introduce BC-break/bug ; we had a lot with the JS dependencies for instance.

**Comment by jordisala1991** [comment]
This Pr only updates deps for github action versions.

**Comment by VincentLanglet** [comment]
Oh i see

**Comment by VincentLanglet** [comment]
We already have this here: https://github.com/sonata-project/dev-kit/blob/master/.github/dependabot.yml#L20-L27

But I don't understand how it will be propagated to other repositories @jordisala1991 ?

**Comment by jordisala1991** [comment]
It wont, we would need to track those dep updates and propagate manually.

**Comment by VincentLanglet** [comment]
> It wont, we would need to track those dep updates and propagate manually.

One issue we have is the fact that sonata projects have more workflows (https://github.com/sonata-project/SonataAdminBundle/tree/4.x/.github/workflows) than the dev-kit one (https://github.com/sonata-project/dev-kit/tree/master/.github/workflows). So we might not be aware about the update.

Having such a file in all the sonata projects would give PR like
https://github.com/sonata-project/dev-kit/commit/eff05079ce162de22cc41e03d45ff319a7360eac
which might help us to be aware of the update. But this won't be perfect either
- PR will be created on every repos
- If it's merged automatically, our dev-kit dispatch will override the change every time.

Anyway. If the PR should be done somewhere, it's not here but on the dispatched files from the dev-kit.

**Pull request closed without merging**
