### PR TITLE
Multiple not working for AutocompleteType on master branche

### LINKED ISSUE #7248: Multiple not working for AutocompleteType on master branche
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              dev-master b3ee6cc dev-master b3ee6cc The missing Symfony Admin Generator
sonata-project/block-bundle              4.6.0              4.6.0              Symfony SonataBlockBundle
sonata-project/cache                     2.1.1              2.1.1              Cache library
sonata-project/doctrine-extensions       1.12.0             1.12.0             Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle dev-master de57db5 dev-master de57db5 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.6.2              2.6.2              Lightweight Exporter library
sonata-project/form-extensions           1.9.0              1.9.0              Symfony form extensions
sonata-project/twig-extensions           1.6.0              1.6.0              Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/amqp-messenger             v5.3.0  v5.3.0  Symfony AMQP extension Messenger Bridge
symfony/apache-pack                v1.0.1  v1.0.1  A pack for Apache support in Symfony
symfony/asset                      v5.3.0  v5.3.0  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/cache                      v5.3.0  v5.3.0  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.4.0  v2.4.0  Generic abstractions related to caching
symfony/config                     v5.3.0  v5.3.0  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v5.3.0  v5.3.0  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v5.3.0  v5.3.0  Converts CSS selectors to XPath expressions
symfony/debug-bundle               v5.3.0  v5.3.0  Provides a tight integration of the Symfony Debug component into the Symfony full-stack framework
symfony/debug-pack                 v1.0.9  v1.0.9  A debug pack for Symfony projects
symfony/dependency-injection       v5.3.0  v5.3.0  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v2.4.0  v2.4.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.3.1  v5.3.1  Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger         v5.3.0  v5.3.0  Symfony Doctrine Messenger Bridge
symfony/dom-crawler                v5.3.0  v5.3.0  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v5.3.0  v5.3.0  Registers environment variables from a .env file
symfony/error-handler              v5.3.0  v5.3.0  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.3.0  v5.3.0  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v2.4.0  v2.4.0  Generic abstractions related to dispatching event
symfony/expression-language        v5.3.0  v5.3.0  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.3.0  v5.3.0  Provides basic utilities for the filesystem
symfony/finder                     v5.3.0  v5.3.0  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.13.3 v1.13.3 Composer plugin for Symfony
symfony/form                       v5.3.0  v5.3.0  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v5.3.0  v5.3.0  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v5.3.0  v5.3.0  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.4.0  v2.4.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.3.1  v5.3.1  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.3.1  v5.3.1  Provides a structured process for converting a Request into a Response
symfony/intl                       v5.3.0  v5.3.0  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/lock                       v5.3.1  v5.3.1  Creates and manages locks, a mechanism to provide exclusive access to a shared resource
symfony/mailer                     v5.3.0  v5.3.0  Helps sending emails
symfony/maker-bundle               v1.31.1 v1.31.1 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                  v5.3.0  v5.3.0  Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                       v5.3.0  v5.3.0  Allows manipulating MIME messages
symfony/monolog-bridge             v5.3.0  v5.3.0  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.7.0  v3.7.0  Symfony MonologBundle
symfony/options-resolver           v5.3.0  v5.3.0  Provides an improved replacement for the array_replace PHP function
symfony/orm-pack                   v2.1.0  v2.1.0  A pack for the Doctrine ORM
symfony/password-hasher            v5.3.0  v5.3.0  Provides password hashing utilities
symfony/phpunit-bridge             v5.3.0  v5.3.0  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-ctype             v1.23.0 v1.23.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.23.0 v1.23.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.23.0 v1.23.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.23.0 v1.23.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.23.0 v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.23.0 v1.23.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                    v5.3.0  v5.3.0  Executes commands in sub-processes
symfony/profiler-pack              v1.0.5  v1.0.5  A pack for the Symfony web profiler
symfony/property-access            v5.3.0  v5.3.0  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v5.3.1  v5.3.1  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v5.3.0  v5.3.0  Provides integration for ProxyManager with various Symfony components
symfony/psr-http-message-bridge    v2.1.0  v2.1.0  PSR HTTP message bridge
symfony/redis-messenger            v5.3.0  v5.3.0  Symfony Redis extension Messenger Bridge
symfony/routing                    v5.3.0  v5.3.0  Maps an HTTP request to a set of configuration variables
symfony/runtime                    v5.3.0  v5.3.0  Enables decoupling PHP applications from global state
symfony/security-acl               v3.1.2  v3.1.2  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v5.3.0  v5.3.0  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v5.3.1  v5.3.1  Symfony Security Component - Core Library
symfony/security-csrf              v5.3.0  v5.3.0  Symfony Security Component - CSRF Library
symfony/security-guard             v5.3.0  v5.3.0  Symfony Security Component - Guard
symfony/security-http              v5.3.1  v5.3.1  Symfony Security Component - HTTP Integration
symfony/serializer                 v5.3.1  v5.3.1  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/serializer-pack            v1.0.4  v1.0.4  A pack for the Symfony serializer
symfony/service-contracts          v2.4.0  v2.4.0  Generic abstractions related to writing services
symfony/stopwatch                  v5.3.0  v5.3.0  Provides a way to profile code
symfony/string                     v5.3.0  v5.3.0  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/templating                 v5.3.0  v5.3.0  Provides all the tools needed to build any kind of template system
symfony/translation                v5.3.0  v5.3.0  Provides tools to internationalize your application
symfony/translation-contracts      v2.4.0  v2.4.0  Generic abstractions related to translation
symfony/twig-bridge                v5.3.0  v5.3.0  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v5.3.0  v5.3.0  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v5.3.1  v5.3.1  Provides tools to validate values
symfony/var-dumper                 v5.3.0  v5.3.0  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.3.0  v5.3.0  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                   v5.3.0  v5.3.0  Manages links between resources
symfony/web-profiler-bundle        v5.3.0  v5.3.0  Provides a development tool that gives detailed information about the execution of any request
symfony/yaml                       v5.3.0  v5.3.0  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 8.0.5 (cli) (built: May  3 2021 11:30:57) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.5, Copyright (c), by Zend Technologies
```

## Steps to reproduce

```
->add('projects', ModelAutocompleteType::class, [
    'multiple' => true,
    'property' => [
        'name',
        'type',
        'code',
    ],
    'required' => true,
])
```

When you have multiple values, you can add new items one by one, and save the entity. The values are saved, but when you edit the entity again, you only see the first value. Other values are in the hidden fields, so there are not gone when you save the entity again. But you can't see them and you can't remove them.

## Expected results

You have to see the values

## Actual results

You only see the first value

### PR DESCRIPTION
**Pull request by willemverspyck**
## Subject

I am targeting this branch, because it's BC.

Closes #7248.

## Changelog

```markdown
### Fixed
- "multiple" option of AutocompleteType
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Do you know if this bug is on the 3.x branch too ?
If so, it could be nice to apply the bugfix to 3.x instead.

**Comment by willemverspyck** [comment]
No, this bug was not in 3.x branch, because it started after trying the master branche. Not sure if the unused code can also be removed in 3.x branch.

**Comment by VincentLanglet** [comment]
> No, this bug was not in 3.x branch, because it started after trying the master branche. Not sure if the unused code can also be removed in 3.x branch.

I think we bumped the version on Select2 on master, so it should be related to this then. Thanks

**Review by VincentLanglet — APPROVED** [review]

**Comment by dmaicher** [comment]
I can confirm the issue when using 4.0.0-alpha-2.

However when I apply this fix then all the autocomplete ajax requests fail for me with

```
 "Argument 1 passed to Sonata\\AdminBundle\\Admin\\Pool::getInstance() must be of the type string, null given, called in /myproject/symfony/vendor/sonata-project/admin-bundle/src/Action/RetrieveAutocompleteItemsAction.php on line 46", class: "TypeError"

**Review by dmaicher — APPROVED** [review]
I can confirm the issue on master/alpha-2

I tested your fix and it works fine for me :+1:

**Comment by VincentLanglet** [comment]
Thanks !

**Comment by willemverspyck** [comment]
Thanks @VincentLanglet & @dmaicher. Is there already an estimate release date for the first beta (or final) of version 4? I saw the milestone for version 4 is already at 95%.

**Comment by VincentLanglet** [comment]
> Thanks @VincentLanglet & @dmaicher. Is there already an estimate release date for the first beta (or final) of version 4? I saw the milestone for version 4 is already at 95%.

When the milestone will be done we'll release a RC.
But there is no due date, it all about time taken by contributors and maintainers.

**Pull request merged**
