### PR TITLE
Use new namespaces

### PR DESCRIPTION
**Pull request by greg0ire**
## Subject
I am targeting this branch, because this is BC.

## Changelog

```markdown
### Fixed
- some deprecations about the new namespaces have been fixed
```

### CODE REVIEW

**Comment by core23** [comment]
You need to update the `composer.json`

**Comment by dmaicher** [comment]
Note that technically this was a BC break.

I have overwritten the `AbstractAdmin::validate` method and now get some nice errors like

```
Fatal error: Declaration of MyAdmin::validate(Sonata\CoreBundle\Validator\ErrorElement $errorElement, $account): void must be compatible with Sonata\AdminBundle\Admin\AbstractAdmin::validate(Sonata\Form\Validator\ErrorElement $errorElement, $object)

**Comment by greg0ire** [comment]
Could you please `var_dump()` that line, see if there might be some typo/autoloading issue?

**Comment by greg0ire** [comment]
Ah I know, that's not enough indeed I'm a friend. The line is correct, but is never executed in your case :(

**Comment by dmaicher** [comment]
Indeed it never gets there.

**Comment by greg0ire** [comment]
:thinking: the solution would be to copy the line at the bottom of `AbstractAdmin.php`

**Comment by dmaicher** [comment]
> thinking the solution would be to copy the line at the bottom of `AbstractAdmin.php`

Indeed that worked :wink:

**Pull request merged**
