### PR TITLE
Allow return null in AdminInterface::getNewInstance

### LINKED ISSUE #5679: Support entities with constructor arguments
## Feature Request

It's hard work and a little hacky to work with entities with constructor arguments. We have a number of entities with immutable values which we pass in constructors. In these cases, we override `getNewInstance()` in our admin class as follows:

```php
    public function getNewInstance()
    {
        return null;
    }
```

With some other work like a callback for the form's `empty_data` option, this works.

With the latest release, `getNewInstance()` is correctly documented as returning an `object`, which is causing our static analysis to flag our workaround as a problem.

If there are better recommended way to handle this, or is it on the roadmap to be implemented?

### PR DESCRIPTION
**Pull request by franmomu**
## Subject

As commented in https://github.com/sonata-project/SonataAdminBundle/issues/5679, if you have entities/models with constructor arguments you have to override the method `getNewInstance` to return `null`. 

Enforcing to return an object will mean that we have to return "empty" objects since we cannot pass any argument. 

IMO we shouldn't tell users how they should construct their entities/models, maybe there is another way to do this, but the only one I know now is overriding `getNewInstance` and returning null (and use a custom data mapper).

Here is an example: https://github.com/franmomu/sonata_example_constructor

I am targeting this branch, because this is BC.

Closes #5679

## Changelog

```markdown
### Changed
- Allow `AdminInterface::getNewInstance` to return `null`
```

### CODE REVIEW

**Comment by franmomu** [comment]
I don't see the impact, `setSubject` and `getSubject` allow `null` values.

The example is pretty easy, if you have a model like:
```php
final class Foo
{
    private $id;

    private $name;

    public function __construct(string $id, string $name)
    {
        $this->id = $id;
        $this->name = $name;
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }
}
```
and create an admin to handle it, that's it.

**Comment by VincentLanglet** [comment]
> The example is pretty easy (as explained in #5679), if you have a model like:
> 
> ...
> 
> and create an admin to handle it, that's it.

That still does explain the issue.
I just created a FooAdmin with your Foo entity. And I can create an entity without any problem or error message.

**Comment by franmomu** [comment]
> > The example is pretty easy (as explained in #5679), if you have a model like:
> > ...
> > and create an admin to handle it, that's it.
> 
> That still does not explain the issue. I just created a FooAdmin with your Foo entity. And I can create an entity without any problem or error message.

That's weird, try this maybe https://github.com/franmomu/sonata_example_constructor

**Comment by VincentLanglet** [comment]
> That's weird, try this maybe https://github.com/franmomu/sonata_example_constructor

I have some exceptions in this example.
 
Since the constructor is not called, the getter should allow to return a nullable value.
If I update
```
public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function getScore(): ?float
    {
        return $this->score;
    }
```
I can display the create page now.

But then when I submit the form, I get an error because you didn't create the setters.
Why would you allow to edit the field without a setter ?

This example seems purely theoretical and not real-life usable.

The only improvement I could see here, is to call the constructor in the getNewInstance. But the question would be "with which value ?". But anyway, I don't see how you expect this to work without setter if you allow the user to chose a value. So can you give me more context ?
- How you used it ?
- How you expected it to work ?
- How you made it work ?

**Comment by VincentLanglet** [comment]
I may understand your issue @franmomu, and I think that
- https://sonata-project.org/bundles/admin/3-x/doc/cookbook/recipe_data_mapper.html
- https://github.com/sensiolabs-de/rich-model-forms-bundle
Are better solutions than allowing a null subject.

**Comment by franmomu** [comment]
This are real-life examples, I have some entities like this (then I have a method or two for update some fields), it's normal to want to construct your entities in a valid state. 

I don't think people should change their entities to return nullable values (or change anything to make it work), it's part of each ones domain. 

> Edit, I just tested dataMapper. It works really well.
> See VincentLanglet/sonata_example_constructor@0969879#diff-84489526b81bc66973068d2776fe782c

It works because you allowed to return nullable values. The example was meant to only show how to construct, the full example would be with this https://github.com/franmomu/sonata_example_constructor/commit/4c6909e46fc3134a9bc483d2300cc81a1ff15ad9 and for that you need to override the `getNewInstance` to return `null`.

Here another issue about the same thing: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/200

> But using https://github.com/sensiolabs-de/rich-model-forms-bundle could be another solution.

I haven't tried it yet, but looks like it only solves the problem with the mapper.

**Comment by VincentLanglet** [comment]
> I don't think people should change their entities to return nullable values (or change anything to make it work), it's part of each ones domain.
> 
> > Edit, I just tested dataMapper. It works really well.
> > See [VincentLanglet/sonata_example_constructor@0969879](https://github.com/VincentLanglet/sonata_example_constructor/commit/0969879)#diff-84489526b81bc66973068d2776fe782c
> 
> It works because you allowed to return nullable values.

I think it's a tricky question.

If you only set the default value in the constructor, is it a good idea to use non-nullable typehint, since a php class can be instantiated without calling the constructor... ?

Anyway, it still works without allowing nullable score and name: 
See this new commit: https://github.com/VincentLanglet/sonata_example_constructor/commit/0cf5e10a524da24ee27448ff4f1ad839ce398f9e

**Comment by franmomu** [comment]
> If you only set the default value in the constructor, is it a good idea to use non-nullable typehint, since a php class can be instantiated without calling the constructor... ?

In this case for example, if I have a mandatory `name` or `score`, why would I use nullable typehints?

> Anyway, it still works without allowing nullable score and name:
> See this new commit: [VincentLanglet/sonata_example_constructor@0cf5e10](https://github.com/VincentLanglet/sonata_example_constructor/commit/0cf5e10a524da24ee27448ff4f1ad839ce398f9e)

Well, I keep seeing changes in [the Entity](https://github.com/VincentLanglet/sonata_example_constructor/commit/0cf5e10a524da24ee27448ff4f1ad839ce398f9e#diff-cb10a91ae0130aa6e9f2533a5f3bce83), you changed the `getId(): int` to `getId(): ?int`.

**Comment by VincentLanglet** [comment]
> > If you only set the default value in the constructor, is it a good idea to use non-nullable typehint, since a php class can be instantiated without calling the constructor... ?
> 
> In this case for example, if I have a mandatory `name` or `score`, why would I use nullable typehints?

It's not because it's mandatory that you have to use non-nullable type-hint. 
Typehint should represent the reality in php: is it possible to receive a null value ?

Since you can when you bypass the constructor, it could make more sens to use nullable typehint.
If a function receive an Example entity, can this function be sure the name is set ? Seems like no.

> > Anyway, it still works without allowing nullable score and name:
> > See this new commit: [VincentLanglet/sonata_example_constructor@0cf5e10](https://github.com/VincentLanglet/sonata_example_constructor/commit/0cf5e10a524da24ee27448ff4f1ad839ce398f9e)
> 
> Well, I keep seeing changes in [the Entity](https://github.com/VincentLanglet/sonata_example_constructor/commit/0cf5e10a524da24ee27448ff4f1ad839ce398f9e#diff-cb10a91ae0130aa6e9f2533a5f3bce83), you changed the `getId(): int` to `getId(): ?int`.

I'm used to work with entity with auto-generated id.
But you have another solution without touching the entity here: https://github.com/VincentLanglet/sonata_example_constructor/commit/a83970fb8ecf85f4bd82b5318c6386385836fedc

**Comment by franmomu** [comment]
> It's not because it's mandatory that you have to use non-nullable type-hint.
> Typehint should represent the reality in php: is it possible to receive a null value ?
> 
> Since you can when you bypass the constructor, it could make more sens to use nullable typehint.

So every attribute from a class should be nullable? It makes no sense to me.

> If a function receive an Example entity, can this function be sure the name is set ? Seems like no.

Yes, using php 7.4, I declare my attributes with type and not allowing nullable values because I set the mandatory parameters in the constructor.

> But you have another solution without touching the entity here: VincentLanglet/sonata_example_constructor@a83970f

I try to use stateless services.

**Comment by VincentLanglet** [comment]
> > It's not because it's mandatory that you have to use non-nullable type-hint.
> > Typehint should represent the reality in php: is it possible to receive a null value ?
> > Since you can when you bypass the constructor, it could make more sens to use nullable typehint.
> 
> So every attribute from a class should be nullable? It makes no sense to me.

Every attribute without default value should be nullable yes.

You can see in the symfony demo https://github.com/symfony/demo/blob/master/src/Entity/Tag.php that `name` is mandatory, but `getName` return `?string`.

Because if I do `(new Tag())->getName()`, it get `null`.

> > If a function receive an Example entity, can this function be sure the name is set ? Seems like no.
> 
> Yes, using php 7.4, I declare my attributes with type and not allowing nullable values because I set the mandatory parameters in the constructor.

I was talking in a general way. If there is a default value, of couse it won't be `null`.
 
> > But you have another solution without touching the entity here: [VincentLanglet/sonata_example_constructor@a83970f](https://github.com/VincentLanglet/sonata_example_constructor/commit/a83970f)
> 
> I try to use stateless services.

It's certainly improvable. It was just to show you that was possible without a `null` value for `getNewInstance`. Plus, it's the documented way.

You even can write:
```
getName() {
    return (string) $this->name;
}
```

Anyway, a nullable value for `getNewInstance` is far to be a good solution.

In `AppendFormFieldElementAction`, there is the following code
```
$subject = $admin->getObject($objectId);
if ($objectId && !$subject) {
     throw new NotFoundHttpException(sprintf('Could not find subject for id "%s"', $objectId));
}

if (!$subject) {
    $subject = $admin->getNewInstance();
}

$admin->setSubject($subject);

list(, $form) = $this->helper->appendFormFieldElement($admin, $subject, $elementId);
```
If `$admin->getNewInstance()` return `null`, `appendFormFieldElement` method would be called with `null` as second argument which lead to multiple error.

In the same way `RetrieveAutocompleteItemsAction` and `RetrieveFormFieldElementAction` are setting the `$subject` of the admin by calling `getNewInstance()` and seems to rely on a not-nullable subject.

The `addNewInstance` method of the adminHelper would break too. And there is others methods using the `getNewInstance`.

If the `null` value would be allowed, it should be with a test for each of these methods with the `null` value. But I still consider there is no reason to add this hack (which has bad impact for project with static analysis) when there is a working and documented solution.

**Comment by franmomu** [comment]
> Every attribute without default value should be nullable yes.
> 
> You can see in the symfony demo https://github.com/symfony/demo/blob/master/src/Entity/Tag.php that name is mandatory, but getName return ?string.
> 
> Because if I do (new Tag())->getName(), it get null.

😕 Of course... because it doesn't have a constructor setting the name...

Anyway I got tired, so I'm losing interest, I'll try to find another way.

**Pull request closed without merging**
