### PR TITLE
Fix - Unknown "sonata_admin" filter error.

### PR DESCRIPTION
**Pull request by ggabrovski**
## Subject

Fix `Unknown "sonata_admin" filter` error in 4.2.0

I am targeting this branch, because this is a bug fix.

## Changelog

```markdown
### Fixed
- Unknown "sonata_admin" filter
```

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks, I made the backport to 3.x
https://github.com/sonata-project/SonataAdminBundle/pull/7574

I'll release the fix after the merge

**Comment by VincentLanglet** [comment]
This will be included in https://github.com/sonata-project/SonataAdminBundle/pull/7576

**Comment by ggabrovski** [comment]
Greats, thank you.

**Comment by VincentLanglet** [comment]
4.2.1 should solve the issue

**Pull request closed without merging**
