### PR TITLE
Fix autocomplete search for field.subfield

### PR DESCRIPTION
**Pull request by netounet**
Search does not work for sub field as setValue does not convert the field name with __ as separor instead of .

### CODE REVIEW

**Comment by OskarStark** [comment]
please fix the errors from travis and the CS

thank you

**Comment by netounet** [comment]
Ok that's done

**Comment by OskarStark** [comment]
travis looks good, can you please squash your commits?

and can you please provide an example, so that we can try this by our own?

@Soullivaneuh can you please review this

**Comment by OskarStark** [comment]
@netounet is your case tested via ```HelperCOntrollerTest.php```?
https://github.com/sonata-project/SonataAdminBundle/blob/1e3dc54160b0df73ec0d7b5f1d66cc48f06a782c/Tests/Controller/HelperControllerTest.php

if not, can you please add a test for this case?

**Comment by netounet** [comment]
@OskarStark for test no and I don't see how to test it . . . :)
For the scenario : in target admin i had a filter name "user.lastname" that filter my list on field lastname of user many2one relation of my entity. For some obscure reason in the filtering process the subentities filters are converter from xxx.xxx format to xxx_xxx format.

**Comment by netounet** [comment]
@OskarStark  For squash it seems i missed something :) can you give me the right way to do this ?

**Comment by OskarStark** [comment]
1. checkout your forked repo
2. git add remote upstream git@github.com:sonata-project/SonataAdminBundle.git
3. git fetch upstream
4. git checkout patch
5. git rebase upstream/master

no it is rebase, to suash
6. git rebase -I HEAD~4
7. change ```pick``` with ```f````, but leave the first commit as it is
8. git push origin patch-7 --force

oskar

**Comment by Soullivaneuh** [comment]
I can't see what you're trying to fix.

Can you please provide a concrete use case?

BTW, as a bug fix, related tests should be provided.

**Comment by EmmanuelVella** [comment]
I confirm the issue. When stored in the datagrid, the dots in the filter name are replaced with double undescore (see https://github.com/sonata-project/SonataAdminBundle/blob/master/Filter/Filter.php#L49)

@netouned You should do this instead : `$datagrid->setValue($filter->getFormName(), null, $searchText);`

**Comment by netounet** [comment]
@EmmanuelVella yes good notice just change it
@OskarStark Hum not sure that i did the correct think, dont understand why others commits appear here

**Comment by OskarStark** [comment]
you have to rebase again please, we added some commits in the meantime

**Pull request closed without merging**
