### PR TITLE
Using form type names instead of FQCN to significantly reduce the change of getting an error while visiting the admin panel

### PR DESCRIPTION
**Pull request by WouterJ**
Revert #3709

Now I have to figure out why things don't work nice with the CMF on Symfony 3...

### CODE REVIEW

**Comment by greg0ire** [comment]
Please read and apply : https://github.com/sonata-project/dev-kit/blob/master/doc/CONTRIBUTING.md#the-commit-message

This following part applies to #3709 : 

> Also, when you specify what you did avoid commit message subjects with "Fix bug in such and such feature". Saying you are fixing something implies the previous implementation was wrong and yours is right, which might not be even true. Instead, state unquestionable technical facts about your changes, not opinions. Then, in the commit description, explain why you did that and how it fixes something.

**Comment by greg0ire** [comment]
What about the CMF, what's wrong ?

**Comment by Soullivaneuh** [comment]
@WouterJ So, stop me if I'm wrong, but this is indeed what I was thinking. This method is part of `FormBuilderInterface` from Symfony and does not support FQCN for SF <2.7, right.

In this case, could we have conditional value to have support for both old and new way to do (e.g. 3.0)?

**Comment by WouterJ** [comment]
> In this case, could we have conditional value to have support for both old and new way to do (e.g. 3.0)?

Did you look at the code I linked in the previous PR? It does this...

**Comment by Soullivaneuh** [comment]
> Did you look at the code I linked in the previous PR? It does this...

Yes I did and I even participated to the comments.

You said that this is supported by all SF version even 2.3 but it does not look like.

Or I didn't understand the real problem. Which exact error did you get since this PR?

**Comment by WouterJ** [comment]
Sorry if I was unclear, I meant these links (I know you participated in my previous PR): 
 * https://sonata-project.org/bundles/core/master/doc/reference/form_types.html#symfony3-supports
 * https://github.com/sonata-project/SonataCoreBundle/blob/master/Form/FormHelper.php
 * https://github.com/sonata-project/SonataCoreBundle/blob/master/Form/Extension/DependencyInjectionExtension.php

**Comment by Soullivaneuh** [comment]
Oh ok. I'm sorry but I'm confused with this old PR and this new one. If I understand clearly, this:

```php
$this->formBuilder->add('_sort_by', 'Symfony\Component\Form\Extension\Core\Type\HiddenType');
```

Will not work on older SF releases. And this:

```php
$this->formBuilder->add('_sort_by', 'hidden');
```

Should work with all 2.x and 3.x SF version, that's it?

cc @rande

**Comment by WouterJ** [comment]
> Should work with all 2.x and 3.x SF version, that's it?

Yes. I submitted my previous PR because I got some errors in Symfony 3 which I thought were caused by not using FQCN (I thought the FormHelper worked the other way around, which may be more logical in order to make removing <2.8 BC layer as easy as possible).

I just reran the CMF tests after applying these changes locally and they still pass, so the failures some weeks ago were caused by some other bug (that has been fixed now, if I'm allowed to use that word in this context).

**Comment by Soullivaneuh** [comment]
Ok @WouterJ thanks for the clarification and your work.

**Comment by greg0ire** [comment]
Nice job on the new commit message, thanks!

**Pull request merged**
