### PR TITLE
Detailed deprecation messages

### PR DESCRIPTION
**Pull request by OskarStark**
I am targetting this branch, because there is no BC break

Fixes #4106

## Subject

Be more clear when they will be removed!

### CODE REVIEW

**Comment by greg0ire** [comment]
LGTM

**Comment by OskarStark** [comment]
rebased after #4106 was merged

**Comment by OskarStark** [comment]
@greg0ire can you please merge this?

**Comment by core23** [comment]
Thank you @OskarStark

**Pull request merged**
