### PR TITLE
Update sonata_type_model_autocomplete.html.twig

### PR DESCRIPTION
**Pull request by austinh**
Fix Bug with subclass inheritance and model_type_autocomplete

Reference issue #3428

### CODE REVIEW

**Comment by OskarStark** [comment]
Thank you for your contribution :+1: 

can you please add a test case for your enhancement/bugfix?

**Comment by ruscon** [comment]
@OskarStark can you add this fix in stable version ?

**Comment by pulzarraider** [comment]
Please also change the commit text. `Update sonata_type_model_autocomplete.html.twig` doesn't say why the file was modified and what it fixes.

**Comment by OskarStark** [comment]
@ruscon you mean ``2.3`` does this commit fixes your problem?

**Comment by ruscon** [comment]
@OskarStark, yep

**Comment by OskarStark** [comment]
@Soullivaneuh can you then merge this PR an cherry pick the commit to the 2.3?

**Comment by phofmann-trust** [comment]
I also hit this bug. Would be great if this could be merged.

**Comment by OskarStark** [comment]
Merged it, but having problems to cherry pick this commit

@core23 can you help?

**Comment by andreicio** [comment]
I have a question about this fix: how does it work for edit pages?

From what I understand, this fix uses the subclass request parameter to determine the appropriate subclass to use for the autocomplete ajax callback. This works well in the add page, where the subclass is set in the url, but not so well (in my case) for the edit page. Both cases can be fixed, though, by adding the subclass to the 'req_params' key of the options array. The code I used is this:

`$subject = $this->getSubject();
$subclasses = $this->getSubClasses();
$activeSubclass = get_class($subject);
$subclass = array_search($activeSubclass, $subclasses);

$formMapper->add(
    'country',
    'sonata_type_model_autocomplete',
    [
        'label'    => 'Country',
        'property' => 'name',
        'req_params' => ['subclass' => $subclass],
    ]
);`

So, what am I missing?

**Comment by MARK-BAIN** [comment]
@andreicio I'm using your code and it works just fine. Passing subclass via req_params solves the issue

**Pull request merged**
