### PR TITLE
Make the table in edition forms responsive

### PR DESCRIPTION
**Pull request by kuldipem**
On small devices, this class makes a scrollbar appear so that tables can be scrolled independently from the whole page.
See http://jasonbradley.me/bootstrap-responsive-tables/

### CODE REVIEW

**Comment by OskarStark** [comment]
could you add some screenshots?

**Comment by ju1ius** [comment]
@kuldipem, @OskarStark By looking at the [corresponding bootstrap source](https://github.com/twbs/bootstrap/blob/master/less/tables.less#L171), I don't see how your change can work...
The `.table-responsive` class is supposed to be applied to a table's direct parent element, not to any  random ancestor.

**Comment by Soullivaneuh** [comment]
Agree with @ju1ius.

@kuldipem Could you please fix you class placement?

**Comment by Soullivaneuh** [comment]
According to the new [Sonata version management](https://github.com/sonata-project/SonataAdminBundle/issues/3053) and next major [release plan](https://github.com/sonata-project/SonataAdminBundle/issues/3731), this project has been refactored regarding branching and versioning.

If you see this message, your PR concerns a patch or a minor release and is not targeting the right branch.

So I'm closing this one, but don't see it as a refusal. If you think your work is still relevant and want to continue, feel free to reopen it on the right branch (e.g. the default one).

Regards.

**Pull request closed without merging**
