### PR TITLE
Avoid error when a wrong code is provided

### PR DESCRIPTION
**Pull request by VincentLanglet**
Fix BC.

No changelog needed since the version is not released.

### CODE REVIEW

**Comment by OskarStark** [comment]
PHPStan is failing 🤔

**Comment by VincentLanglet** [comment]
> PHPStan is failing 🤔

I opened https://github.com/phpstan/phpstan-symfony/pull/132

**Comment by OskarStark** [comment]
Great work

**Comment by VincentLanglet** [comment]
Fixed @OskarStark

**Pull request merged**
