### PR TITLE
Add form sticky elements

### PR DESCRIPTION
**Pull request by qsomazzi**
The goal of this feature is to provider a sticky Header and footer to optimize navigation inside long forms.

While you scroll down the page, the header will stick to the top, so you can always see wich content you are currently editing.

When you reach the bottom of the form, the footer de-stick itself to get to his original place.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Could you please explain a little bit this feature? Some screenshots and concrete case applications would be great. Thanks.

**Comment by qsomazzi** [comment]
@Soullivaneuh added to the PR description, would you like me to add it somewhere inside the doc ?

**Comment by Soullivaneuh** [comment]
Ok. Is that an option?

Sticky footer / header could not be done with css? Also AdminLTE could maybe provide some tricks about it...

**Comment by qsomazzi** [comment]
I could make it an option right.

It's part done with CSS to make it stuck, but the detection of scroll must be done in javascript.
And I haven't find anything for it inside AdminLTE, but I didn't break the design with this feature, it just make the block fixed.

**Comment by qsomazzi** [comment]
@Soullivaneuh I've make it Optional but enable by default

**Comment by Soullivaneuh** [comment]
I just checkout your fork on my project, no sticky header/footer at all.

Am I missing something?

**Comment by qsomazzi** [comment]
Did you add 
`- bundles/sonataadmin/vendor/waypoints/lib/jquery.waypoints.min.js`
`- bundles/sonataadmin/vendor/waypoints/lib/shortcuts/sticky.min.js`
in your sonata_admin assets conf (if you override it) ?

**Comment by OskarStark** [comment]
would add this as default because of the javascripts

**Comment by OskarStark** [comment]
awesome work @qsomazzi 

thank you!

**Comment by Soullivaneuh** [comment]
@rande Why merge now? I would review it a little bit before that.

**Comment by rande** [comment]
@Soullivaneuh what are you missing from this PR ?

**Comment by Soullivaneuh** [comment]
Nothing for now. Just want to test it on projects before validate. :+1:

**Comment by Soullivaneuh** [comment]
@qsomazzi There is some issue on show template.

Actions dropdown disappear on scroll and sometime the bar stay sticky when you scroll back.

This is also why it's better to have multiple user testing before implement this kind of feature. :-P

**Comment by qsomazzi** [comment]
I'm looking to at this moment

**Comment by qsomazzi** [comment]
@Soullivaneuh Fix here : https://github.com/sonata-project/SonataAdminBundle/pull/3196

**Pull request merged**
