### PR TITLE
Add generic to Mapper and Event

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

Backport of https://github.com/sonata-project/SonataAdminBundle/pull/7278

## Changelog

```markdown
### Added
- Add generic to MapperInterface and all extending classes.
- Added generic to ConfigureEvent and PersistenceEvent.
```

### CODE REVIEW

**Review by phansys — APPROVED** [review]

**Comment by VincentLanglet** [comment]
I'd like the confirmation of @jordisala1991 that https://github.com/sonata-project/SonataAdminBundle/pull/7278 is solving his issue on the MediaBundle

**Comment by jordisala1991** [comment]
Let me check

**Comment by jordisala1991** [comment]
Oh...

With this patch (for master branch) , now I get this other error:

```
ERROR: InvalidArgument - src/Admin/BaseMediaAdmin.php:169:38 - Argument 1 of Sonata\MediaBundle\Provider\MediaProviderInterface::buildEditForm expects Sonata\AdminBundle\Form\FormMapper<object>, Sonata\AdminBundle\Form\FormMapper<Sonata\MediaBundle\Model\MediaInterface> provided (see https://psalm.dev/004)
            $provider->buildEditForm($form);


ERROR: InvalidArgument - src/Admin/BaseMediaAdmin.php:171:40 - Argument 1 of Sonata\MediaBundle\Provider\MediaProviderInterface::buildCreateForm expects Sonata\AdminBundle\Form\FormMapper<object>, Sonata\AdminBundle\Form\FormMapper<Sonata\MediaBundle\Model\MediaInterface> provided (see https://psalm.dev/004)
            $provider->buildCreateForm($form);

```

**Comment by jordisala1991** [comment]
But I think I've got it, I have to add this:

```

    /**
     * build the related create form.
     *
     * @phpstan-param FormMapper<MediaInterface> $form
     */
    public function buildCreateForm(FormMapper $form);

    /**
     * build the related create form.
     *
     * @phpstan-param FormMapper<MediaInterface> $form
     */
    public function buildEditForm(FormMapper $form);
```

To the mediaProviderInterface

**Review by jordisala1991 — APPROVED** [review]

**Pull request merged**
