### PR TITLE
Manual Merge

### PR DESCRIPTION
**Pull request by kunicmarko20**
Just approve, merge, do not.

### CODE REVIEW

**Comment by jordisala1991** [comment]
Well flintCI :P

**Comment by kunicmarko20** [comment]
fixed :smile:

**Comment by greg0ire** [comment]
Travis seems to have serious issues… cannot fetch log

**Comment by kunicmarko20** [comment]
Works now, but I broke  a return type

**Comment by greg0ire** [comment]
wtf

**Comment by kunicmarko20** [comment]
They are probably fixing something, I can't see log now.

**Comment by kunicmarko20** [comment]
fixed :tada:

**Pull request merged**
