### PR TITLE
Bugfix TypeError: data.config is not a function in Admin.js

### LINKED ISSUE #5249: Admin.get_config is not a function
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.40.0 3.40.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.11.2 3.11.2 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.6.2  3.6.2  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.9.1  1.9.1  Lightweight Exporter library
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
Restricting packages listed in "symfony/symfony" to "4.1.*"
symfony/apache-pack          v1.0.1 v1.0.1 A pack for Apache support in Symfony
symfony/asset                v4.1.6 v4.1.6 Symfony Asset Component
symfony/browser-kit          v4.1.6 v4.1.6 Symfony BrowserKit Component
symfony/cache                v4.1.6 v4.1.6 Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config               v4.1.6 v4.1.6 Symfony Config Component
symfony/console              v4.1.6 v4.1.6 Symfony Console Component
symfony/css-selector         v4.1.6 v4.1.6 Symfony CssSelector Component
symfony/debug                v4.1.6 v4.1.6 Symfony Debug Component
symfony/debug-bundle         v4.1.6 v4.1.6 Symfony DebugBundle
symfony/debug-pack           v1.0.6 v1.0.6 A debug pack for Symfony projects
symfony/dependency-injection v4.1.6 v4.1.6 Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.1.6 v4.1.6 Symfony Doctrine Bridge
symfony/dom-crawler          v4.1.6 v4.1.6 Symfony DomCrawler Component
symfony/dotenv               v4.1.6 v4.1.6 Registers environment variables from a .env file
symfony/event-dispatcher     v4.1.6 v4.1.6 Symfony EventDispatcher Component
symfony/expression-language  v4.1.6 v4.1.6 Symfony ExpressionLanguage Component
symfony/filesystem           v4.1.6 v4.1.6 Symfony Filesystem Component
symfony/finder               v4.1.6 v4.1.6 Symfony Finder Component
symfony/flex                 v1.1.1 v1.1.1 Composer plugin for Symfony
symfony/form                 v4.1.6 v4.1.6 Symfony Form Component
symfony/framework-bundle     v4.1.6 v4.1.6 Symfony FrameworkBundle
symfony/http-foundation      v4.1.6 v4.1.6 Symfony HttpFoundation Component
symfony/http-kernel          v4.1.6 v4.1.6 Symfony HttpKernel Component
symfony/inflector            v4.1.6 v4.1.6 Symfony Inflector Component
symfony/intl                 v4.1.6 v4.1.6 A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle         v1.7.0 v1.7.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/monolog-bridge       v4.1.6 v4.1.6 Symfony Monolog Bridge
symfony/monolog-bundle       v3.3.0 v3.3.0 Symfony MonologBundle
symfony/options-resolver     v4.1.6 v4.1.6 Symfony OptionsResolver Component
symfony/orm-pack             v1.0.5 v1.0.5 A pack for the Doctrine ORM
symfony/panther              v0.2.0 v0.2.0 A browser testing and web scraping library for PHP and Symfony.
symfony/phpunit-bridge       v4.1.6 v4.1.6 Symfony PHPUnit Bridge
symfony/polyfill-intl-icu    v1.9.0 v1.9.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.9.0 v1.9.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72       v1.9.0 v1.9.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process              v4.1.6 v4.1.6 Symfony Process Component
symfony/profiler-pack        v1.0.3 v1.0.3 A pack for the Symfony web profiler
symfony/property-access      v4.1.6 v4.1.6 Symfony PropertyAccess Component
symfony/property-info        v4.1.6 v4.1.6 Symfony Property Info Component
symfony/routing              v4.1.6 v4.1.6 Symfony Routing Component
symfony/security             v4.1.6 v4.1.6 Symfony Security Component
symfony/security-acl         v3.0.1 v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.1.6 v4.1.6 Symfony SecurityBundle
symfony/serializer           v4.1.6 v4.1.6 Symfony Serializer Component
symfony/serializer-pack      v1.0.1 v1.0.1 A pack for the Symfony serializer
symfony/stopwatch            v4.1.6 v4.1.6 Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.3 v3.2.3 Symfony SwiftmailerBundle
symfony/templating           v4.1.6 v4.1.6 Symfony Templating Component
symfony/test-pack            v1.0.4 v1.0.4 A pack for functional and end-to-end testing within a Symfony app
symfony/thanks               v1.1.0 v1.1.0 Give thanks (in the form of a GitHub ⭐) to your fellow PHP package maintainers (not limited to Symfony components)!
symfony/translation          v4.1.6 v4.1.6 Symfony Translation Component
symfony/twig-bridge          v4.1.6 v4.1.6 Symfony Twig Bridge
symfony/twig-bundle          v4.1.6 v4.1.6 Symfony TwigBundle
symfony/validator            v4.1.6 v4.1.6 Symfony Validator Component
symfony/var-dumper           v4.1.6 v4.1.6 Symfony mechanism for exploring and dumping PHP variables
symfony/web-link             v4.1.6 v4.1.6 Symfony WebLink Component
symfony/web-profiler-bundle  v4.1.6 v4.1.6 Symfony WebProfilerBundle
symfony/web-server-bundle    v4.1.6 v4.1.6 Symfony WebServerBundle
symfony/yaml                 v4.1.6 v4.1.6 Symfony Yaml Component
```

#### PHP version

```
$ php -v
PHP 7.2.10-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct  1 2018 11:45:50) ( NTS )
```

## Steps to reproduce
- Install app, run adminsitration, open console debugger (F12 in Chrome) and see error.

## Expected results
- no errors in console log

## Actual results
Uncaught TypeError: Admin.get_config is not a function
    at HTMLInputElement.<anonymous> (list:1278)
    at HTMLInputElement.dispatch (jquery.js:4435)
    at HTMLInputElement.r.handle (jquery.js:4121)

### PR DESCRIPTION
**Pull request by rapemer**
Closes #5249 

## Changelog
```markdown
### Fixed
- Minor bug in JavaScripts (Admin.js)
```

### CODE REVIEW

**Comment by greg0ire** [comment]
Please associate your fousky.cz email address with your Github account, or change the email in your commits to an address already associated with it.

**Comment by greg0ire** [comment]
Thanks @rapemer !

**Comment by rapemer** [comment]
@moon-watcher are you extending standard_layout.html.twig? If yes, check diff between original and your extended version -> between version 3.39.0 and 3.40.0 there was major changes in "standard_layout.html.twig"

**Comment by moon-watcher** [comment]
That worked great! Thanks, man

**Comment by psyray** [comment]
Login page of [overrided sonata user bundle](https://github.com/sonata-project/SonataUserBundle/blob/391dc8d101250f98787e709d4ccd7f6887829840/src/Resources/views/Admin/Security/login.html.twig#L23) does not reflect this changes so it is badly formatted (no icheck..) and error in console (see capture below).
I will open an issue in this bundle
image

**Pull request merged**
