### PR TITLE
Spell "deprecation" properly

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Why is this missing on master branch, it was added ages ago...

**Comment by greg0ire** [comment]
> Why is this missing on master branch

what does "this" refer to?

**Comment by greg0ire** [comment]
As you can see, it is partly present:

```
rg epreaction 
tests/Twig/Extension/SonataAdminExtensionTest.php
254:     * @expectedDepreaction The Sonata\AdminBundle\Admin\AbstractAdmin::getTemplate method is deprecated (since 3.34, will be dropped in 4.0. Use TemplateRegistry services instead).
```

but note that deprecations should ultimately disappear from master, so maybe one out of the 2 has already been removed?

**Comment by kunicmarko20** [comment]
`expectedDeprecation` check my PR: https://github.com/sonata-project/SonataAdminBundle/pull/5097/files#diff-47b1548a4d062a7a56630ceb30fc1bbc

travis is failing because of that

**Comment by greg0ire** [comment]
If it fails, then it means there is no deprecation, and if there is no deprecation it might mean the corresponding code has already been removed?

**Pull request merged**
