### PR TITLE
Make support symfony 2.8 on 2.3 branch

### PR DESCRIPTION
**Pull request by Th3Mouk**
@OskarStark PR for https://github.com/sonata-project/SonataAdminBundle/issues/3438 pretty annoying

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
2.3 version will not works with SF 2.8 AFAIK.

We are working to make it comptible but on 2.4 only.

cc @rande.

**Comment by pulzarraider** [comment]
I agree with @Soullivaneuh.

**Comment by ruscon** [comment]
Waiting 2.4

**Comment by OskarStark** [comment]
so can we close this issue?

**Pull request closed without merging**
