### PR TITLE
Fix mosaic list items

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Fixed
- Fix mosaic list item height
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
Before:
Captura de pantalla 2021-09-03 a las 11 02 43

After:
Captura de pantalla 2021-09-03 a las 11 02 12

**Comment by core23** [comment]
Should we limit the height? What if you have images with different formats, e.g. 1:4 and 4:1?

**Comment by VincentLanglet** [comment]
> Should we limit the height? What if you have images with different formats, e.g. 1:4 and 4:1?

I agree.
You change `col-sm-3` to `col-md-2` and removed the height limit, we should try with other size and be sure we support them.

**Comment by jordisala1991** [comment]
Yep I am trying another approach. None of them are perfect, but they will be better than we have now. I will ping once I have it ready.

**Comment by jordisala1991** [comment]
I think I won't have time for this one, closing for now.

**Pull request closed without merging**
