### PR TITLE
Remove wells from form actions bar

### PR DESCRIPTION
**Pull request by davidromani**
I think that here we can remove well & well-small CSS classes to clean up form acions bar.

captura de pantalla 2015-09-09 a les 16 50 26

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
I'm not sure of what I prefer.

@rande what do you think?

@davidromani Did you test sticky scroll reaction?

**Comment by Soullivaneuh** [comment]
Ping @qsomazzi too.

**Comment by qsomazzi** [comment]
I'm afraid that without wells it's going to be weird when buttons will be in front of other inputs

**Comment by Soullivaneuh** [comment]
Yeah, this is what I was thinking too...

**Comment by davidromani** [comment]
@Soullivaneuh works well on tiny screens. Keep in mind that wells will be removed in BS4 too.

**Comment by davidromani** [comment]
Sorry, I've just discovered sticky form actions bottom bar. You are right @Soullivaneuh, it doesn't works well.

**Pull request closed without merging**
