### PR TITLE
Moved public methods to AdminInterface

### PR DESCRIPTION
**Pull request by core23**
### Changelog

```markdown
### Added
- Add the `getExportFields` method to the AdminInterface
- Add the `setTemplates` method to the AdminInterface
- Add the `setTemplate` method to the AdminInterface
- Add the `getTemplates` method to the AdminInterface
- Add the `getClassnameLabel` method to the AdminInterface
- Add the `getPersistentParameter` method to the AdminInterface
- Add the `preValidate` method to the AdminInterface
- Add the `getSubClasses` method to the AdminInterface
- Add the `addSubClass` method to the AdminInterface
- Add the `getDashboardActions` method to the AdminInterface
- Add the `getActionButtons` method to the AdminInterface
```

### Subject

Added some public methods of `Admin` to the `AdminInterface`.

### To do

- [X] Add an upgrade note

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Maybe can we take profit to add a comment on the phpdoc?

Because reading this like this, I don't really see the usage of this method...

**Comment by core23** [comment]
I would like to add some more methods (`getClasslabel`, `getClass`, ...) to the `AdminInterface`. Should I create one PR for each methods or one PR for all? @Soullivaneuh

**Comment by Soullivaneuh** [comment]
@core23 I thinkg for this case you can do it on one PR with one commit per added method. :+1:

**Comment by Soullivaneuh** [comment]
@greg0ire Could I have a review from you please?

**Comment by Soullivaneuh** [comment]
@core23 Please dispatch this commit modifications: https://github.com/sonata-project/SonataAdminBundle/pull/3857/commits/eaf0ebcc632677b05e6ed9861fc0391e62b923ef

On the related commits.

**Comment by greg0ire** [comment]
I'm on a train but I will try;)

**Comment by greg0ire** [comment]
LGTM, altough this is a huge ISP violation, but not your fault

**Comment by core23** [comment]
Fixed @Soullivaneuh

**Comment by Soullivaneuh** [comment]
Thanks a lot @core23!

**Pull request merged**
