### PR TITLE
Fix for not showing placeholder when using Select2 with ChoiceType

### LINKED ISSUE #7305: Placeholder text not displayed with select2
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              dev-master 9bbdf97 dev-master 9bbdf97 The missing Symfony Admin Generator
sonata-project/block-bundle              4.6.0              4.6.0              Symfony SonataBlockBundle
sonata-project/cache                     2.1.1              2.1.1              Cache library
sonata-project/datagrid-bundle           3.3.0              3.3.0              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.13.0             1.13.0             Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle dev-master df32d93 dev-master df32d93 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.7.0              2.7.0              Lightweight Exporter library
sonata-project/form-extensions           1.9.0              1.9.0              Symfony form extensions
sonata-project/media-bundle              dev-master 1d467fe dev-master 1d467fe Symfony SonataMediaBundle
sonata-project/twig-extensions           1.6.0              1.6.0              Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/amqp-messenger             v5.3.2  v5.3.2  Symfony AMQP extension Messenger Bridge
symfony/asset                      v5.3.2  v5.3.2  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                v5.3.0  v5.3.0  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/cache                      v5.3.3  v5.3.3  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.4.0  v2.4.0  Generic abstractions related to caching
symfony/config                     v5.3.3  v5.3.3  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v5.3.2  v5.3.2  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v5.3.0  v5.3.0  Converts CSS selectors to XPath expressions
symfony/debug-bundle               v5.3.0  v5.3.0  Provides a tight integration of the Symfony Debug component into the Symfony full-stack framework
symfony/dependency-injection       v5.3.3  v5.3.3  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v2.4.0  v2.4.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.3.3  v5.3.3  Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger         v5.3.2  v5.3.2  Symfony Doctrine Messenger Bridge
symfony/dom-crawler                v5.3.0  v5.3.0  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v5.3.0  v5.3.0  Registers environment variables from a .env file
symfony/error-handler              v5.3.3  v5.3.3  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.3.0  v5.3.0  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v2.4.0  v2.4.0  Generic abstractions related to dispatching event
symfony/expression-language        v5.3.0  v5.3.0  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.3.3  v5.3.3  Provides basic utilities for the filesystem
symfony/finder                     v5.3.0  v5.3.0  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.13.3 v1.13.3 Composer plugin for Symfony
symfony/form                       v5.3.3  v5.3.3  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v5.3.3  v5.3.3  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v5.3.3  v5.3.3  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.4.0  v2.4.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.3.3  v5.3.3  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.3.3  v5.3.3  Provides a structured process for converting a Request into a Response
symfony/intl                       v5.3.0  v5.3.0  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                     v5.3.3  v5.3.3  Helps sending emails
symfony/maker-bundle               v1.33.0 v1.33.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                  v5.3.3  v5.3.3  Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                       v5.3.2  v5.3.2  Allows manipulating MIME messages
symfony/monolog-bridge             v5.3.3  v5.3.3  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.7.0  v3.7.0  Symfony MonologBundle
symfony/options-resolver           v5.3.0  v5.3.0  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v5.3.3  v5.3.3  Provides password hashing utilities
symfony/phpunit-bridge             v5.3.3  v5.3.3  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-ctype             v1.23.0 v1.23.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.23.0 v1.23.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.23.0 v1.23.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.23.0 v1.23.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.23.0 v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.23.0 v1.23.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                    v5.3.2  v5.3.2  Executes commands in sub-processes
symfony/property-access            v5.3.0  v5.3.0  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v5.3.1  v5.3.1  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v5.3.0  v5.3.0  Provides integration for ProxyManager with various Symfony components
symfony/redis-messenger            v5.3.2  v5.3.2  Symfony Redis extension Messenger Bridge
symfony/routing                    v5.3.0  v5.3.0  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.1.2  v3.1.2  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v5.3.3  v5.3.3  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v5.3.3  v5.3.3  Symfony Security Component - Core Library
symfony/security-csrf              v5.3.3  v5.3.3  Symfony Security Component - CSRF Library
symfony/security-guard             v5.3.0  v5.3.0  Symfony Security Component - Guard
symfony/security-http              v5.3.3  v5.3.3  Symfony Security Component - HTTP Integration
symfony/serializer                 v5.3.2  v5.3.2  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts          v2.4.0  v2.4.0  Generic abstractions related to writing services
symfony/stopwatch                  v5.3.0  v5.3.0  Provides a way to profile code
symfony/string                     v5.3.3  v5.3.3  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                v5.3.3  v5.3.3  Provides tools to internationalize your application
symfony/translation-contracts      v2.4.0  v2.4.0  Generic abstractions related to translation
symfony/twig-bridge                v5.3.3  v5.3.3  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v5.3.3  v5.3.3  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v5.3.3  v5.3.3  Provides tools to validate values
symfony/var-dumper                 v5.3.3  v5.3.3  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.3.3  v5.3.3  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                   v5.3.3  v5.3.3  Manages links between resources
symfony/web-profiler-bundle        v5.3.2  v5.3.2  Provides a development tool that gives detailed information about the execution of any request
symfony/yaml                       v5.3.3  v5.3.3  Loads and dumps YAML files

```

</p>
</details>

#### PHP version

```
$ php -v
PHP 8.0.7 (cli) (built: Jun  4 2021 21:26:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.7, Copyright (c), by Zend Technologies

```

## Subject
When using a simple ChoiceType with a placeholder in an edit view, the field is not rendered with the placeholder in select2

## Steps to reproduce

Add a field in the edit view

```php
$formMapper
    ->add('duration', ChoiceType::class, [
        'label' => 'duration',
        'choices' => [
            '10s' => 10000,
            '20s' => 20000,
            '30s' => 30000,
        ],
        'placeholder' => 'auto',
    ])
;
```

## Expected results
The `auto` placeholder is correctly rendered.
## Actual results

image

### PR DESCRIPTION
**Pull request by willemverspyck**
I am targeting this branch, because it's BC.

Closes #7305

## Changelog

```markdown
### Fixed
Fix for not showing placeholder when using Select2 with ChoiceType

```

Before:
Screenshot 2021-07-14 at 15 46 32

After with Select2:
Screenshot 2021-07-14 at 15 00 33

After without Select2 (disabled by config):
Screenshot 2021-07-14 at 15 00 13

### CODE REVIEW

**Comment by willemverspyck** [comment]
"Frontend / Webpack Encore" failed, but I'm not sure it's related to my changes.

**Comment by VincentLanglet** [comment]
Yes, you have to regenerate the assets. Will give you the command when i'll find a computer

**Comment by VincentLanglet** [comment]
I think you have to run `.bin/encore production`

**Comment by VincentLanglet** [comment]
I'm not familiar with the asset, maybe @jordisala1991 can help

**Comment by willemverspyck** [comment]
I've run your command and regenerated the assets, but I still get the error.

**Comment by VincentLanglet** [comment]
According to
https://github.com/sonata-project/SonataAdminBundle/pull/7193#issuecomment-847544404

```
yarn install --frozen-lockfile
yarn encore production
```
should be the way to fix this build...

I suppose you're node modules are not up to date with the lock file, because it's weird that the css builds were changed since you didn't touch any css files.

**Comment by VincentLanglet** [comment]
I succeed to get a green build @willemverspyck.

Closing in favor of https://github.com/sonata-project/SonataAdminBundle/pull/7330

**Comment by willemverspyck** [comment]
Thanks @VincentLanglet 👍

I had the latest node modules, but I used NPM to generate the assets. Maybe that makes the difference in CSS files.

**Pull request closed without merging**
