### PR TITLE
drop support for Symfony < 4.3

### PR DESCRIPTION
**Pull request by dmaicher**
See https://github.com/sonata-project/SonataAdminBundle/pull/5842

## Changelog

```markdown
### Removed
- removed support for Symfony < 4.3
- removed some outdated legacy code that is not needed anymore
```

### CODE REVIEW

**Comment by dmaicher** [comment]
Seems not so straightforward :smile: :see_no_evil: 

```
jms/di-extra-bundle 1.9.2 requires symfony/dependency-injection ~2.3|~3.0

**Comment by dmaicher** [comment]
@greg0ire @core23 should I only bump the requirement for `symfony/event-dispatcher` for now? Bumping all of them seems to require dropping some jms-di-extra features.

**Comment by greg0ire** [comment]
@dmaicher I'm already working on that, I thought you saw that in my comments:  #5843

**Comment by dmaicher** [comment]
:+1: sorry I misunderstood :smile:

**Pull request closed without merging**
