### PR TITLE
Enables 'editable' option on choice fields

### PR DESCRIPTION
**Pull request by silvioq**
The 'editable' option on choice fields works as boolean fields

### CODE REVIEW

**Comment by webdevilopers** [comment]
:+1:

**Comment by OskarStark** [comment]
@Soullivaneuh can you please restart the travis job, the error is not related to this PR

@silvioq :+1:  i like your PR

**Comment by Soullivaneuh** [comment]
PR need to be rebased.

**Comment by silvioq** [comment]
Hi @Soullivaneuh I removed the original fork because it duplicated #2484. If you prefer this solution, I will prepare a new PR.

**Pull request closed without merging**
