### PR TITLE
Current implementation does not keep order of items

### PR DESCRIPTION
**Pull request by mieszko4**

### CODE REVIEW

**Comment by OskarStark** [comment]
@mieszko4  what is the current status of this PR?

@pulzarraider tests were added, travis seems to be fine.

@rande shall we merge this PR then?

**Comment by core23** [comment]
Ping @mieszko4

**Comment by mieszko4** [comment]
I'm sorry but I've been totally out of Sonata so I cannot confirm the status of this pr as it was meant for some specific case.

The case was sending through form parameters list of ids of objects reordered by a front-end drag-n-drop component. The problem was that order at which the server received the ids was not persisted and this pr was fixing it.

I guess you can skip merging and close this pr. Your call :)

**Comment by OskarStark** [comment]
@greg0ire what do you think?

**Comment by greg0ire** [comment]
I would close this. If the bug still exist, people can still search and find this PR and resurrect it.

**Comment by OskarStark** [comment]
👍

**Pull request closed without merging**
