### PR TITLE
make the code samples syntactically correct

### PR DESCRIPTION
**Pull request by greg0ire**
see https://github.com/sphinx-doc/sphinx/issues/2264
Should fix the build.

Conflicts:
	Resources/doc/cookbook/recipe_sortable_listing.rst
	Resources/doc/reference/architecture.rst
	Resources/doc/reference/getting_started.rst

### CODE REVIEW

**Comment by Koc** [comment]
@greg0ire problem is wider. Unit tests are also broken. Covered by #3561

**Comment by greg0ire** [comment]
Oh, I see. Closing then.

**Comment by OskarStark** [comment]
but the current changes in this PR are not "wrong" IMO

**Comment by greg0ire** [comment]
@Koc says he's "covering it" in #3561

**Comment by OskarStark** [comment]
didn't get that, sorry guys!

**Pull request closed without merging**
