### PR TITLE
Remove oppressive language

### LINKED ISSUE #6185: Remove oppressive words from code
## Feature Request

We should avoid terms like *blacklist*, *whitliste*, *master*, *slave*, ... and use more tech-related words like *blocklist*, *prmary*, *secondary*,...

In this repo, we use the term *whitelist* which could be replaced with *allowlist*:
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/docs/reference/routing.rst#removing-all-routes-except-named-ones

### PR DESCRIPTION
**Pull request by jaikdean**
## Subject

This removes oppressive language from the code.

There is a default permission of `MASTER` which may want to be considered for changing, but this would be a BC break and may be something people are comfortable keeping given the context it is used in.

I am targeting this branch, because the change is back-compatible.

Closes #6185.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
> There is a default permission of `MASTER` which may want to be considered for changing, but this would be a BC break and may be something people are comfortable keeping given the context it is used in.

Where is it used ? We can provide a BC-path or change it in the next release.

**Comment by jordisala1991** [comment]
Thank you @jaikdean

**Comment by VincentLanglet** [comment]
Is it the only oppressive word of the project and we really can close #6185 ?

**Comment by jaikdean** [comment]
> Is it the only oppressive word of the project and we really can close #6185 ?

I searched the code for `white`, `black`, `master` and `slave`. Aside from the `MASTER` permission and colours in CSS and JS files, this was all I found.

**Comment by VincentLanglet** [comment]
Yes, I made the same research and didn't find anything except `MASTER`.

Theorically, it could be changed. But since it's related to
```
Symfony\Component\Security\Acl\Permission\MaskBuilder::MASK_MASTER
```
I'm not sure it's a good idea to rename this before Symfony.

**Pull request merged**
