### PR TITLE
support ru-RU locale for MomentJS

### PR DESCRIPTION
**Pull request by OskarStark**
## Subject

I am targeting this branch, because {reason}.

Closes https://github.com/sonata-project/SonataCoreBundle/pull/575

## Changelog

```markdown
### Added
- support for `ru-RU` locale for MomentJS

```

### CODE REVIEW

**Comment by OskarStark** [comment]
> The travis build is failing.

thanks @greg0ire I fixed it

**Comment by OskarStark** [comment]
Yeah I know, don’t know what’s the problem here 🤔

**Comment by kunicmarko20** [comment]
you inversed the keys in tests, maybe that?

**Comment by OskarStark** [comment]
Not sure why it fails, just wanted to care of the old PR, closing for now, because I don't need it and don't want to invest time though...

**Pull request closed without merging**
