### PR TITLE
Allow Twig 2 and use caret operator

### PR DESCRIPTION
**Pull request by WouterJ**

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Why necessarily carets?

**Comment by WouterJ** [comment]
@Soullivaneuh for 2 reasons:

 * It's the improved version of the tilde. It can do everything that the tilde can with extra things
 * Consistency. The current composer.json contained all variants (`~2.3`, `^2.3.8`, `~2.3,>=2.3.3`, `>=2.0,<3.0.0`).

**Comment by Soullivaneuh** [comment]
Yeah it can do everything but `~2.3` and `^2.3` is the same AFAIK. So why changing this right now?

**Comment by core23** [comment]
Can you explain the benefit @WouterJ 
I am with @Soullivaneuh. It is the same

**Comment by core23** [comment]
Are you still working on this? Please rebase or close this PR @WouterJ

**Pull request closed without merging**
