### PR TITLE
Changed tab styles to use the grid

### PR DESCRIPTION
**Pull request by WouterJ**
With this PR, it will be possible to use grids in the groups.

### CODE REVIEW

**Comment by WouterJ** [comment]
@pulzarraider I think it's a bug fix. In 2.3, support for tabs were added and because the implementation wasn't 100% correct, the support for grids in tabs was temporary removed and added as a fixme (see removed comment). This PR readds it by adding some small things.

**Comment by WouterJ** [comment]
Sorry to bump again, but we need this for the CMF (see referenced CMF PRs). So I would be very happy if a decision can be made quickly about the branch of this PR (and a new minor release can be tagged soon after it).

**Comment by dbu** [comment]
see https://github.com/symfony-cmf/SimpleCmsBundle/pull/131 for example. it would allow to write admins that work with tabs and groups that work on both sonata admin 2.3 and 2.4 which would be a very good thing. i am +1 on this one.

**Comment by pulzarraider** [comment]
Thank you @WouterJ

**Comment by lsmith77** [comment]
has this been released yet?

**Comment by lsmith77** [comment]
I guess not .. will be in 2.3.2 I guess?

**Comment by pulzarraider** [comment]
@lsmith77 yes, this will be in 2.3.2.

**Pull request merged**
