### PR TITLE
Add generics to ModelManagerInterface

### PR DESCRIPTION
**Pull request by franmomu**
## Subject

This should fix https://github.com/sonata-project/SonataAdminBundle/pull/6713#issuecomment-748465250, I think the problem was that given:

```php
/**
 * @phpstan-return T
 */
public function getNewInstance()
{
    $object = $this->getModelManager()->getModelInstance($this->getClass());

    $this->appendParentObject($object);

    foreach ($this->getExtensions() as $extension) {
        $extension->alterNewInstance($this, $object);
    }

    return $object;
}
```
This line 
```php
$object = $this->getModelManager()->getModelInstance($this->getClass());
```

was not returning the same `T`. Now with:
```php
/**
 * @phpstan-return ModelManagerInterface<T>
 */
public function getModelManager()
```

should be fine.

I am targeting this branch, because these changes are BC.

## Changelog

```markdown
### Added
- Add generics to `ModelManagerInterface`.
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
I have some trouble to understand how the issue (https://github.com/sonata-project/SonataAdminBundle/pull/6713#issuecomment-748465250) would come from the ModelManager since commenting the line `$this->appendParentObject($object);` was fixing the issue. (And it works well on 3.x)

I'm not sure those generics should be added. We generally use one ModelManager for every admin, and we're passing the class to most of the methods, so the modelManager shouldn't be related to one class `T`.

**Review by VincentLanglet — CHANGES_REQUESTED** [review]
https://github.com/sonata-project/SonataAdminBundle/pull/6713 is solved.

And I don't think the modelManager should be restricted to one class, since every class-specific methods are taking a param `$class`.

**Review by VincentLanglet — APPROVED** [review]

**Review by VincentLanglet — CHANGES_REQUESTED** [review]
I don't think it will work
https://phpstan.org/r/c9e2bf6d-3426-4a3f-8a96-cf96b8e98719

**Comment by franmomu** [comment]
> I don't think it will work
> https://phpstan.org/r/c9e2bf6d-3426-4a3f-8a96-cf96b8e98719

it depends, if the ModelManager it is for `Foo`, should be `ModelManagerInterface<Foo>`, if it is used for more, then should not use `<object>`, be generic and the property should have: `/** @var ModelManager<Foo> */`

**Comment by VincentLanglet** [comment]
> > I don't think it will work
> > https://phpstan.org/r/c9e2bf6d-3426-4a3f-8a96-cf96b8e98719
> 
> if it is used for more, then should not use `<object>`, be generic and the property should have: `/** @var ModelManager<Foo> */`

I don't see any benefit in this case.
Method with a `class-string` as parameter are already using a template.

The issue you were trying to solve is solved, it shows that 
```
$object = $this->getModelManager()->getModelInstance($this->getClass());
```
works well without the generic.

By adding a generic to ModelManager, you will forbid this code
```
/**
 * @phpstan-implements AdminInterface<Foo>
 */
class FooAdmin {

    public function something()
    {
        $object = $this->getModelManager()->getModelInstance(Bar::class);
    }
}
```
But this code is valid. The ModelManager is not restricted to the class of the subject.

**Pull request closed without merging**
