### PR TITLE
[FIX] Model Type compatibility for 2.7+

### PR DESCRIPTION
**Pull request by Th3Mouk**
Hot fix, I need a 2.3.8 tag please

### CODE REVIEW

**Comment by meshenka** [comment]
i did a similar request and PR here https://github.com/sonata-project/SonataAdminBundle/pull/3530 
CI does not pass also. No idea why

cheers

**Comment by OskarStark** [comment]
@meshenka i would like to use the PR of @Th3Mouk, it looks cleaner and easier to understand.
Is this ok for you?

@core23 @webdevilopers @rande can you verify this PR please? thank you

**Comment by OskarStark** [comment]
and btw, i don't know why Travis is failing oO

**Comment by OskarStark** [comment]
ah, i missed that you backport the code from dev master... hmm, shall we keep this or the IMO more simple commit of @Th3Mouk :confused:

**Comment by meshenka** [comment]
i did try this PR on my project exception is gone but the model choices choices is empty, on create and update existing non empty collection. So i am not able to pick'n choose one of the existing Entity for my collection.

My use case is a simple Group 1 --> * Users (with a GroupAdmin)


i run Symfony 2.7.8 + SonataAdmin 2.3.7

**Comment by Th3Mouk** [comment]
@meshenka oooh sorry, i've tested it on the PageAdmin.php field in the CMS part and looks good. I've no idea why your field is empty, cause it's a default option that be already already null before.
IMO this change can't BC

**Comment by OskarStark** [comment]
but your code works @Th3Mouk 

@meshenka can you please verify the code in your case?

**Comment by meshenka** [comment]
I double check
  * sf 2.7.7 + this PR = accounts aren't prefill
  * sf 2.7.7 without this PR = accounts are prefilled
  * sf 2.7.8 + this PR = accounts aren't prefill
  * sf 2.7.8 without this PR = i got the infamous exception

my Admin looks like this, pretty straight forward
```php
//GroupAdmin.php
       // Fields to be shown on create/edit forms
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->with('General')
                ->add('name')
            ->end()
            ->with('Users')
                ->add('accounts', 'sonata_type_model', array(
                    'btn_add' => false,
                    'required' => false,
                    //'expanded' => true,
                    'by_reference' => false,
                    'multiple' => true,
                    'property' => 'fullname',
                ))
            ->end()
        ;
    }
```
@Th3Mouk did you test my PR? #3530

@OskarStark i agree @Th3Mouk code looks fine but the issue is in Sonata\AdminBundle\Form\ChoiceList\ModelChoiceList

See this part of the code https://github.com/sonata-project/SonataAdminBundle/blob/2.3/Form/ChoiceList/ModelChoiceList.php#L123
```php
       if (is_array($choices)) {
            $entities = $choices;
        } elseif ($this->query) {
            $entities = $this->modelManager->executeQuery($this->query);
        } else {
            $entities = $this->modelManager->findBy($this->class);
        }
```

So now if i let default choices $choices is an array and line https://github.com/sonata-project/SonataAdminBundle/blob/2.3/Form/ChoiceList/ModelChoiceList.php#L128 won't be runned then behavior change :(

**Comment by Th3Mouk** [comment]
@meshenka @OskarStark what do you think of this correction on `ModelChoiceList.php` ?

**Comment by OskarStark** [comment]
@meshenka can you test the new code of @Th3Mouk with your test matrix again?

**Comment by meshenka** [comment]
* sf 2.7.7 + this PR = accounts are prefilled
  * sf 2.7.8 + this PR = accounts are prefilled
  * sf 2.7.9 + this PR = accounts are prefilled

All good to me :+1:

**Comment by Th3Mouk** [comment]
@OskarStark ooh yeah :beers: :sunglasses:

**Comment by OskarStark** [comment]
hmm, travis fails :(

**Comment by meshenka** [comment]
It becomes tricky AFIK there are 5 failling unit tests on ModelType, looks to be related to the change in sf 2.7.8... will be hard to have Unit tests that works with sf 2.7.7 and 2.7.8

**Comment by rande** [comment]
We can add a condition to work on sf >=2.7.8

**Comment by meshenka** [comment]
The test line that crash is
        $options = $optionResolver->resolve(array('model_manager' => $modelManager, 'choices' => array()));

**Comment by meshenka** [comment]
The line that crash in the code is 
        $options = $optionResolver->resolve(array('model_manager' => $modelManager, 'choices' => array()));

in all tests :(

**Comment by meshenka** [comment]
@rande @OskarStark i think my PR https://github.com/sonata-project/SonataAdminBundle/pull/3530 on the same matter is superior
  * It is a backport from 2.4
  * It does not depend on the presence of some weird legacy class
  * unit tests passes

just need this PR merged ASAP

**Comment by OskarStark** [comment]
@rande can you please handle this PR?

**Comment by rande** [comment]
Test are red...

**Comment by core23** [comment]
Can you please rebase @Th3Mouk Travis should be fixed

**Comment by Th3Mouk** [comment]
@meshenka @OskarStark @rande @core23 the update on the symfony 2.7.9 version had resolved the problem. Do you think this PR is still relevant ?

**Comment by core23** [comment]
Then we should update the composer settings @Th3Mouk

**Comment by OskarStark** [comment]
@Th3Mouk can you anyway rebase to get the latest travis conf? :+1:

**Pull request closed without merging**
