### PR TITLE
Allow use master with Sonata v3 bundles

### PR DESCRIPTION
**Pull request by wbloszyk**
## Subject

Remove some return type hints to allow use this branch with Sonata3. This change should be revert in Sonata5.

I am targeting this branch, because {reason}.

Closes #{put_issue_number_here}.

## Changelog

```markdown
### Added
- Added some `Class::newMethod()` to do great stuff.

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
I think removing typehints is not a great idea. If there are bundles that can be compatibles with v3 and v4 it is ok, but having to remove this typehints means that on v5 we will have same problems.

If I have to chose between having improvements vs holding back because we have to be compatible with everything I chose having improvements.

**Comment by wbloszyk** [comment]
@jordisala1991 Lets say we have `AbstractAdmin` and `ImageAdmin` without return type hints (It is sonata v3). We can't add return type hints to `AbstractAdmin` becouse this will throw Error but we can add it to `ImageAdmin` and then to `AbstractAdmin`. Simmilar can be sonata v4 - add return type hints where admin/block is in dependencies and revert type hints from this PR in admin v5

**Comment by VincentLanglet** [comment]
> @jordisala1991 Lets say we have `AbstractAdmin` and `ImageAdmin` without return type hints (It is sonata v3). We can't add return type hints to `AbstractAdmin` becouse this will throw Error but we can add it to `ImageAdmin` and then to `AbstractAdmin`. Simmilar can be sonata v4 - add return type hints where admin/block is in dependencies and revert type hints from this PR in admin v5

That doesn't solve everything. There are also param typehint. You can't add them to ImageAdmin.

And you can add return typehint to your ImageAdmin with SonataAdmin v3, you don't have to wait for SonataAdmin v4 to do so.

**Comment by wbloszyk** [comment]
> > @jordisala1991 Lets say we have `AbstractAdmin` and `ImageAdmin` without return type hints (It is sonata v3). We can't add return type hints to `AbstractAdmin` becouse this will throw Error but we can add it to `ImageAdmin` and then to `AbstractAdmin`. Simmilar can be sonata v4 - add return type hints where admin/block is in dependencies and revert type hints from this PR in admin v5
> 
> That doesn't solve everything. There are also param typehint. You can't add them to ImageAdmin.
> 
> And you can add return typehint to your ImageAdmin with SonataAdmin v3, you don't have to wait for SonataAdmin v4 to do so.

Technicly agrre, but what if `ImageAdmin` is from SonataMediaBundle and someone extends this Admin? This will be BC-break

**Comment by jordisala1991** [comment]
But then you are changing versions from v3 to v4. When we added those typehints we knew it causes BC breaks, but not having them is like using php 5.

**Comment by VincentLanglet** [comment]
> Technicly agrre, but what if `ImageAdmin` is from SonataMediaBundle and someone extends this Admin? This will be BC-break

Then we can make a (major or beta) release of SonataMediaBundle with return typehint and a major release with support of Sonata v4. There is no need for delaying typehint in SonataAdmin.

**Comment by wbloszyk** [comment]
:thinking: 

:confused: 

https://github.com/sonata-project/dev-kit/issues/780#issuecomment-657525810

**Comment by VincentLanglet** [comment]
You can have a SonataMediaBundle v4 with return typehint. And a SonataMediaBundle v5 with Sonata v4 support.
It's a SonataMediaBundle problem, not a SonataAdmin one.

**Comment by wbloszyk** [comment]
:thinking: 

We can't use Admin/BlockBundle v4 with sonata v3 bundles but we can use sonata v4 with Admin/BlockBundle v3.

:thinking: 

For example in sandbox bundle like meda, news, page .... must be upgrade first, then admin and block bundle. 
If someone use only admin then upgrade is ready.

It mean we can upgrade one by one bundle and keep return type hints?

Do I understand it correct? @VincentLanglet

**Comment by VincentLanglet** [comment]
> We can't use Admin/BlockBundle v4 with sonata v3 bundles but we can use sonata v4 with Admin/BlockBundle v3.
>
> For example in sandbox bundle like meda, news, page .... must be upgrade first, then admin and block bundle.
> If someone use only admin then upgrade is ready.
> 
> It mean we can upgrade one by one bundle and keep return type hints?
> 
> Do I understand it correct? @VincentLanglet

Yes

This way, our release path could be
- SonataAdmin v4.
- Then SonataDoctrineORMAdmin with support of SonataAdmin v4.

If someone only use these bundle, he can upgrade easily by adding the typehint.
This will allow to support Symfony 5 and Twig 3 for every developer which use only these package.

Then we can release let's say MediaBundle with support of SonataAdmin v4.
What you said is bumping MediaBundle + AdminBundle are too much.
I'm not sure about it, but if so, we can make smaller steps for MediaBundle like,
- MediaBundle v4 add every possible return type
- MediaBundle v5 add SonataAdmin v4 support

Or doing this upgrade-path with something like beta-release:
- MediaBundle v4-beta-1 with some BC-break.
- MediaBundle v4-beta-2 with some others...
- MediaBundle v4-last-beta with AdminBundle support.
All of these beta are meant to work, they're just created to give smaller step.

When Bundle A depends on Bundle B, the bundle B shouldn't care about how A is implemented.

Since SonataAdmin depends on SonataBlockBundle, we could try to support both SonataBlockBundle v3 and SonataBlockBundle v4 on Sonata v4 to make the update easier. But we should avoid to move backward on SonataBlockBundle in order to please SonataAdmin.

Don't know if my point of view is clear 😅

**Comment by wbloszyk** [comment]
It is clear. I want avoid release like BlockBundle v4 where it is not upgrade in other bundles dependencies. 

BTW
More time I spending on sandbox contributing. I will focus on this. Can you focus on AdminBundle release? @VincentLanglet

**Comment by VincentLanglet** [comment]
> Can you focus on AdminBundle release? @VincentLanglet

I never say no to help, but I'm already trying to.

My first step is to be able to use both SonataAdmin dev-master and SonataDoctrineORMAdmin dev-master
Then I'll work on `NEXT_MAJOR` and typehint. There is a lot...

**Pull request closed without merging**
