### PR TITLE
Execute php-cs-fixer

### PR DESCRIPTION
**Pull request by ruslan-naryzhnyi**
I am targetting this branch, to execute php-cs-fixer
## Changelog

``` markdown

### Fixed
```

### CODE REVIEW

**Comment by greg0ire** [comment]
How and why did you run phpcs-fixer?

**Comment by ruslan-naryzhnyi** [comment]
In my local machine `php vendor\friendsofphp\php-cs-fixer\php-cs-fixer fix Tests\`
Just checked that the style matches

**Comment by greg0ire** [comment]
This is supposed to be checked automatically, but what you're showing us means it does not work for the `Tests` directory… I think [this file](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/.styleci.yml) needs to be fixed somehow.

**Comment by ruslan-naryzhnyi** [comment]
Should I close the PR?

**Comment by greg0ire** [comment]
Not necessarily, you can fix the `.travis.yml`, and then use `git push --force`.

**Comment by ruslan-naryzhnyi** [comment]
`.travis.yml` or  `.styleci.yml` ?

**Comment by greg0ire** [comment]
The latter one, sorry.

**Comment by core23** [comment]
Ping @ruslan-naryzhnyi

**Comment by ruslan-naryzhnyi** [comment]
@core23 what should I do next?

**Comment by core23** [comment]
First of all you should clean this PR, there are some merge commits in it

**Comment by greg0ire** [comment]
> First of all you should clean this PR, there are some merge commits in it

Yeah, and 0 commits are yours… and there are 113 commits… looks weird.

**Pull request closed without merging**
