### PR TITLE
Added to doku

### PR DESCRIPTION
**Pull request by florianlenz**
In the doku we create a BlogPost class -> https://sonata-project.org/bundles/admin/2-3/doc/getting_started/creating_an_admin.html Later if you try to safe a blog post you will get a error because doctrine can't save null to a boolean. I added it to the Doku

### CODE REVIEW

**Comment by core23** [comment]
Please rebase and change commit and PR title

**Comment by OskarStark** [comment]
hey @core23 as this is a colleague of mine, i takeover this PR and discuss this directly to him ;-)

**Comment by greg0ire** [comment]
Hallo! Kein deutsch bitte! Please replace "Doku" with "docs". Thanks for your contribution.

**Comment by greg0ire** [comment]
ping @florianlenz

**Pull request merged**
