### PR TITLE
Use "knplabs/knp-menu-bundle:3.0"

### PR DESCRIPTION
**Pull request by phansys**
## Subject
Use "knplabs/knp-menu-bundle:3.0".

I am targeting this branch, because this change breaks BC.

Closes #5947.

## Changelog

```markdown
### Changed
- Bump "knplabs/knp-menu-bundle" to ^3.0.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
If we support knplabs/knp-menu-bundle:3 only in master it means we won't be able to support Symfony 5 and Twig 3 in SonataAdmin 3.x.
Can't we do something about it ?

Cf: https://github.com/KnpLabs/KnpMenu/releases/tag/v3.1.0
https://github.com/KnpLabs/KnpMenuBundle/blob/v2.3.0/composer.json

**Comment by core23** [comment]
IMHO we can do this on the stable branch, because this are only signature changes for the menu bundle.

If your application supports menu bundle 3, you should already use the new signatures. If your application does not support menu bundle thew new admin bundle version (which requires menu bundle 3) should not be resolved by composer.

**Comment by VincentLanglet** [comment]
> If your application supports menu bundle 3, you should already use the new signatures. If your application does not support menu bundle 3, the new admin bundle version (which requires menu bundle 3) should not be resolved by composer.

We can't indeed support both 2.x and 3.x version, but dropping the support of 2.x version and using 3.x version is not considered as a BC-break.
https://github.com/sonata-project/SonataAdminBundle/issues/5788#issuecomment-595420541

@phansys Can you make this PR on 3.x instead (without adding final keyword) ? :)

**Comment by phansys** [comment]
Will we consider as backward compatible changes on public method signatures which are not final?
```patch
-    public function get($name, array $options = [])
+    public function get(string $name, array $options = []): ItemInterface
```

**Comment by greg0ire** [comment]
Ugh… we're a bit stuck aren't we? I think we should keep this on master, do all other BC-incompatible changes that allow us to provide compatibility with Symfony 5, and release a new major. We keep waiting for more things to become ready.

@phansys , can you please check what's wrong with Travis?

**Comment by phansys** [comment]
>@phansys , can you please check what's wrong with Travis?

Travis is failing because the issues already present in `master`.
I've created #5949 in order to fix them.

**Comment by greg0ire** [comment]
The `prefer-lowest` build fails, you probably need to bump some dependency.

**Comment by franmomu** [comment]
Looks like it was a bug that [was fixed](https://github.com/KnpLabs/KnpMenu/pull/312) [in 3.0.1](https://github.com/KnpLabs/KnpMenu/commits/v3.0.1). But I'd use `^3.1` since it has support for Symfony 5 and Twig 3.

**Comment by phansys** [comment]
Bumped "knplabs/knp-menu" to ^3.1.

**Comment by greg0ire** [comment]
Thanks @franmomu !

**Comment by franmomu** [comment]
Well thanks @phansys ! 😬

**Comment by greg0ire** [comment]
Uuuuh yeah thanks @phansys :sweat_smile: I'm doing lots of reviewing and getting confused :P

**Pull request merged**
