### PR TITLE
[WIP] Fix tests for 2.3

### PR DESCRIPTION
**Pull request by Koc**
waiting for travis build...

### CODE REVIEW

**Comment by Koc** [comment]
Can anybody say me why symfony/security installed at version 3.0.1?

**Comment by Koc** [comment]
@OskarStark @rande @core23 Finally it green!

**Comment by OskarStark** [comment]
@Koc to be honest i don't know why, but thank you for the fix :+1:

**Comment by OskarStark** [comment]
damn, forget to change the title.... :disappointed:

**Pull request merged**
