### PR TITLE
Filters must respect `createQuery()` clauses

### LINKED ISSUE #3368: Global search ads wrong condition to custom query
My `CompanyAdmin` uses the `createQuery` method:

``` php
    public function createQuery($context = 'list')
    {
        $query = parent::createQuery($context);

        $query->addSelect(
                'PARTIAL ' . $query->getRootAlias() . '.{id, name, phone, fax, postcode, street, city, country}',
                'PARTIAL b.{id, name}'
            )
            ->join($query->getRootAlias() . '.branches', 'b')
        ;

        $query->where($query->getRootAlias() . '.id = 1');

        return $query;
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('name', null, array(
                'show_filter' => true,
                'global_search' => true
            ))
        ;
    }
```

The `where` condition is not added with an `AND` operator but an `OR`:

``` sql


SELECT 
  DISTINCT c0_.id AS id_0 
FROM 
  companies c0_ 
  INNER JOIN branches b1_ ON c0_.id = b1_.company_id 
WHERE 
  c0_.id = 1 
  OR c0_.name LIKE ? 
LIMIT 
  10 OFFSET 0
```

This only happens when using the `createQuery`  method and seems to be a problem of the global search adding it.

Without that method it is generated correctly:

``` sql


SELECT 
  DISTINCT c0_.id AS id_0 
FROM 
  companies c0_ 
WHERE 
  c0_.name LIKE ? 
LIMIT 
  10 OFFSET 0
```

### LINKED ISSUE #5569: CreateQuery and searchAction have conflict
#### Sonata packages

```
sonata-project/admin-bundle              3.40.3 3.49.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.15.0 3.15.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.17.0 3.17.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  2.5.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.3.0  1.3.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.6.3  3.9.0  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.11.1 1.11.1 Lightweight Exporter library
```

#### Symfony packages

```
symfony/monolog-bundle     v3.1.2  v3.3.1  Symfony MonologBundle
symfony/phpunit-bridge     v4.2.9  v4.3.0  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.2.0  v1.11.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.11.0 v1.11.0 Symfony polyfill for ctype functions
symfony/polyfill-iconv     v1.11.0 v1.11.0 Symfony polyfill for the Iconv extension
symfony/polyfill-intl-icu  v1.11.0 v1.11.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn  v1.11.0 v1.11.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring  v1.11.0 v1.11.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72     v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util      v1.11.0 v1.11.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.2  v3.0.2  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v3.2.6  v3.2.7  Symfony SwiftmailerBundle
symfony/symfony            v3.4.28 v4.3.0  The Symfony PHP framework
```

#### PHP version

```
PHP 7.2.17-1+0~20190412071344.20+stretch~1.gbp23a36d (cli) (built: Apr 12 2019 07:13:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.17-1+0~20190412071344.20+stretch~1.gbp23a36d, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

## Subject

I use the `createQuery` function to limiting entities in the list ([here](https://symfony.com/doc/3.x/bundles/SonataAdminBundle/reference/action_list.html#customizing-the-query-used-to-generate-the-list)). I recently used the sonata search bar and I was expected the `createQuery` used in the search to filter the possible results found. But the way the `createQuery` just makes the search bar useless. Instead of looking for my research and then filtering with the `createQuery`, the search action is looking for all entities matching with my research OR the `createQuery`, so it returns all the entities I can see in the list...

## Steps to reproduce

1) Create an Admin without `createQuery`
2) Use the search bar and search for fooBarThingDoesntExist
3) Get no result
4) Add this is the `createQuery`
```
    public function createQuery($context = 'list')
    {
        $query = parent::createQuery($context);

        $o = $query->getRootAliases()[0];
        $query->andWhere("$o.id IS NOT NULL");

        return $query;
    }
```
5) Use the search bar and search for fooBarThingDoesntExist
6) Get a lot of result

## Expected results

The request used in the search action should be
```
SELECT 
  count(DISTINCT a0_.id) AS sclr_0 
FROM 
  asv_client a0_ 
WHERE 
  (
    a0_.id IS NOT NULL 
    AND (
        a0_.firstname LIKE ?
        OR a0_.usagename LIKE ?
    )
  ) 
  AND a0_.type IN ('client') 
LIMIT 
  25
```

## Actual results

In fact the request is the following, so the search return all possible result in the list...
```
SELECT 
  count(DISTINCT a0_.id) AS sclr_0 
FROM 
  asv_client a0_ 
WHERE 
  (
    a0_.id IS NOT NULL 
    OR a0_.firstname LIKE ?
    OR a0_.usagename LIKE ?
  ) 
  AND a0_.type IN ('client') 
LIMIT 
  25
```

### PR DESCRIPTION
**Pull request by phansys**
## Subject

Filters must respect `createQuery()` clauses.

I am targeting this branch, because these changes are BC.

Closes #3368.
Closes #5569.

## Changelog

```markdown
### Fixed
- Admin query clauses provided by `createQuery()` method are not being respected while performing search, which uses "OR" as filter condition.
```
    
## To do
    
- [ ] Add tests;
- [ ] Wait for sonata-project/SonataDoctrineORMAdminBundle#925.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@phansys Hi ! I'd love to see this fix merged. Do you need some help ?

**Comment by phansys** [comment]
It's ok for me if you want to continue with this issue. I was not able to give more time for this after the creation of this PR.

**Comment by VincentLanglet** [comment]
The way sonata filters work is totally new for me, so it'll be hard but I can give a try.

So If I understand, I should start with this pr : https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/925

Nothing to do about this two ORM bundle ?
https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/tree/2.x/src/Filter
https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/tree/3.x/src/Filter

**Comment by phansys** [comment]
No problem.
Yes, those packages must be updated for sure. Hopefully I can find some time this week. I'll try to keep my comments up to date regarding the progress.

**Comment by VincentLanglet** [comment]
I was thinking... Maybe we can do something like this
```php
$whereClause = $this->query->getQueryParts('where');
$this->query->resetQueryParts('where');

if (isset($this->values['_sort_by'])) {
            if (!$this->values['_sort_by'] instanceof FieldDescriptionInterface) {
                throw new UnexpectedTypeException($this->values['_sort_by'], FieldDescriptionInterface::class);
            }

            if ($this->values['_sort_by']->isSortable()) {
                $this->query->setSortBy($this->values['_sort_by']->getSortParentAssociationMapping(), $this->values['_sort_by']->getSortFieldMapping());
                $this->query->setSortOrder(isset($this->values['_sort_order']) ? $this->values['_sort_order'] : null);
            }
        }

$filterWhereClause = $this->query->getQueryParts('where');
$this->query->where('('.$whereClause.') AND ('.$filterWhereClause.')')
```

What do you think ?

**Comment by phansys** [comment]
Excellent!
It seems much more feasible than what I have proposed. I'm not a fan of resetting query parts, but in this case I guess this is our better option :+1: 
Could you please create a PR with these changes?
Thank you.

**Comment by VincentLanglet** [comment]
@phansys Sure, I'll be happy to create the PR. But I thought again and my example works only with DoctrineORMAdminBundle `QueryBuilder`.

As far I know, there is 3 different storage bundle.

DoctrineORM:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Datagrid/ProxyQuery.php
Which use this `QueryBuilder`
https://github.com/doctrine/orm/blob/master/lib/Doctrine/ORM/QueryBuilder.php
With functions `getDQLPart` and `resetDQLPart`

DoctrinePhpcr
https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/2.x/src/Datagrid/ProxyQuery.php
Which use this `QueryBuilder`
https://github.com/doctrine/phpcr-odm/blob/master/lib/Doctrine/ODM/PHPCR/Query/Builder/QueryBuilder.php
There is maybe something to do with functions 'getChildrenOfType' and 'removeChildrenOfType'

DoctrineMongoDB
https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/3.x/src/Datagrid/ProxyQuery.php
Which use this `QueryBuilder`
https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Query/Builder.php

So with my solution, I have to 
- Modify the 3 ProxyQuery and expose something like getWhereClause and resetWhereClause.
- Implement theses functions with the 3 QueryBuilder.
- Modify the ProxyQueryInterface.
- And then, adding my fix in the Datagrid.
Can you confirm this ?

**Comment by phansys** [comment]
I'm not familiar with the the other model managers than the ORM, but based on your proposal, I was guessing they should respect the contract from `ProxyQueryInterface`.
If the required changes are similar to what I have drafted in this PR, I ask you to wait, since these are no minimal and there is some concerns that we must to validate before changing the current API.

**Comment by VincentLanglet** [comment]
You wanted to modify `FilterInterface`, my proposal is different since it let untouched the filters. I think this will lead to less changements but it seems to still need to modify an interface, the `ProxyQueryInterface`. I'm not familiar at all with other model managers than the ORM but I discovered they do not expose the same functions to get/reset the where clause.

I'll sure wait for the validation of the `Interface` change.
Maybe @greg0ire you can help us ? I saw you approved https://github.com/sonata-project/SonataAdminBundle/pull/4471

**Comment by greg0ire** [comment]
It's been 2 years and I can't say I followed this topic. Bear in mind that modifying an interface is a BC-break, but that creating new interfaces isn't, and that classes may implement several interfaces. Also interfaces may extend other interfaces. I hope this can help you make your changes in a BC way.

**Pull request closed without merging**
