### PR TITLE
Changed deprecated 'field' type to 'form' in FormTypeFieldExtension

### PR DESCRIPTION
**Pull request by pulzarraider**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3266
| License       | MIT

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Where is the deprecation notice on Symfony docs?

**Comment by pulzarraider** [comment]
https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.1.md#bc-breaks-in-form-types-and-options

**Comment by petforsberg** [comment]
Please accept PR asap, thx.

**Comment by Soullivaneuh** [comment]
:+1:

**Comment by WouterJ** [comment]
Can you please release a new 2.3 patch release to fix this error? This is breaking all CMF builds now.

**Comment by javiereguiluz** [comment]
Has this fix been published in a new SonataAdmin version? I'm still getting this annoying error:

sonata_error

**Comment by WouterJ** [comment]
@javiereguiluz use 2.3 unstable to get rid of the error

**Comment by petforsberg** [comment]
Or simply try to change it in your Sonata Admin vendors sources temporary, if you don't want to download unstable one.

**Comment by WouterJ** [comment]
Please, can someone release 2.3.7? 2.3.6 is 6 months ago and there are enough changes already (if this error breaking applications isn't important enough for a new release): https://github.com/sonata-project/SonataAdminBundle/compare/2.3.6...2.3

**Comment by OskarStark** [comment]
Ping @rande

**Comment by pulzarraider** [comment]
I have tagged the 2.3 branch with `2.3.7`.  cc @sonata-project/contributors

**Comment by rande** [comment]
@pulzarraider thanks

**Pull request merged**
