### PR TITLE
Improve error message for non existent admin declaration

### LINKED ISSUE #7969: AdminSearchCompilerPass::validateAdminClass does not check for class existence.
### Environment

Ubuntu 22.04 Jammy Jellyfish

#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
Direct dependencies required in composer.json:
sonata-project/admin-bundle                  4.20.0 4.20.0 The missing Symfony Admin Generator
sonata-project/doctrine-mongodb-admin-bundle 4.6.0  4.6.0  Symfony Sonata / Integrate Doctrine MongoDB ODM into the SonataAdminBundle
sonata-project/user-bundle                   5.4.0  5.4.0  Symfony SonataUserBundle

Transitive dependencies not required in composer.json:
sonata-project/block-bundle                  4.19.0 4.19.0 Symfony SonataBlockBundle
sonata-project/cache                         2.2.0  2.2.0  Cache library
Package sonata-project/cache is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/doctrine-extensions           2.0.1  2.0.1  Doctrine2 behavioral extensions
sonata-project/exporter                      3.0.0  3.0.0  Lightweight Exporter library
sonata-project/form-extensions               1.18.0 1.18.0 Symfony form extensions
sonata-project/twig-extensions               2.0.0  2.0.0  Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
Direct dependencies required in composer.json:
symfony/asset                      v6.1.5  v6.1.5  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                v6.1.3  v6.1.3  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/console                    v6.1.7  v6.1.7  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v6.1.3  v6.1.3  Converts CSS selectors to XPath expressions
symfony/debug-bundle               v6.1.3  v6.1.3  Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge into the Symfony full-stack framework
symfony/doctrine-messenger         v6.1.4  v6.1.4  Symfony Doctrine Messenger Bridge
symfony/dotenv                     v6.1.0  v6.1.0  Registers environment variables from a .env file
symfony/expression-language        v6.1.6  v6.1.6  Provides an engine that can compile and evaluate expressions
symfony/flex                       v2.2.3  v2.2.3  Composer plugin for Symfony
symfony/form                       v6.1.7  v6.1.7  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v6.1.7  v6.1.7  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v6.1.7  v6.1.7  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/intl                       v6.1.7  v6.1.7  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                     v6.1.7  v6.1.7  Helps sending emails
symfony/maker-bundle               v1.47.0 v1.47.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mercure-bundle             v0.3.5  v0.3.5  Symfony MercureBundle
symfony/mime                       v6.1.7  v6.1.7  Allows manipulating MIME messages
symfony/monolog-bundle             v3.8.0  v3.8.0  Symfony MonologBundle
symfony/notifier                   v6.1.0  v6.1.0  Sends notifications via one or more channels (email, SMS, ...)
symfony/phpunit-bridge             v6.1.6  v6.1.6  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/process                    v6.1.3  v6.1.3  Executes commands in sub-processes
symfony/property-access            v6.1.7  v6.1.7  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v6.1.7  v6.1.7  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v6.1.0  v6.1.0  Provides integration for ProxyManager with various Symfony components
symfony/runtime                    v6.1.3  v6.1.3  Enables decoupling PHP applications from global state
symfony/security-bundle            v6.1.3  v6.1.3  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/serializer                 v6.1.6  v6.1.6  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/stopwatch                  v6.1.5  v6.1.5  Provides a way to profile code
symfony/string                     v6.1.7  v6.1.7  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                v6.1.6  v6.1.6  Provides tools to internationalize your application
symfony/twig-bundle                v6.1.1  v6.1.1  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v6.1.7  v6.1.7  Provides tools to validate values
symfony/web-link                   v6.1.0  v6.1.0  Manages links between resources
symfony/web-profiler-bundle        v6.1.6  v6.1.6  Provides a development tool that gives detailed information about the execution of any request
symfony/yaml                       v6.1.6  v6.1.6  Loads and dumps YAML files

Transitive dependencies not required in composer.json:
symfony/cache                      v6.1.7  v6.1.7  Provides extended PSR-6, PSR-16 (and tags) implementations
symfony/cache-contracts            v3.1.1  v3.1.1  Generic abstractions related to caching
symfony/config                     v6.1.3  v6.1.3  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/dependency-injection       v6.1.5  v6.1.5  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v3.1.1  v3.1.1  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v6.1.7  v6.1.7  Provides integration for Doctrine with various Symfony components
symfony/dom-crawler                v6.1.7  v6.1.7  Eases DOM navigation for HTML and XML documents
symfony/error-handler              v6.1.7  v6.1.7  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v6.1.0  v6.1.0  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v3.1.1  v3.1.1  Generic abstractions related to dispatching event
symfony/filesystem                 v6.1.5  v6.1.5  Provides basic utilities for the filesystem
symfony/finder                     v6.1.3  v6.1.3  Finds files and directories via an intuitive fluent interface
symfony/http-client-contracts      v3.1.1  v3.1.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v6.1.7  v6.1.7  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v6.1.7  v6.1.7  Provides a structured process for converting a Request into a Response
symfony/mercure                    v0.6.1  v0.6.1  Symfony Mercure Component
symfony/messenger                  v6.1.6  v6.1.6  Helps applications send and receive messages to/from other applications or via message queues
symfony/monolog-bridge             v6.1.2  v6.1.2  Provides integration for Monolog with various Symfony components
symfony/options-resolver           v6.1.0  v6.1.0  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v6.1.3  v6.1.3  Provides password hashing utilities
symfony/polyfill-intl-grapheme     v1.26.0 v1.26.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.26.0 v1.26.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.26.0 v1.26.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.26.0 v1.26.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.26.0 v1.26.0 Symfony polyfill for the Mbstring extension
symfony/routing                    v6.1.7  v6.1.7  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.3.2  v3.3.2  Symfony Security Component - ACL (Access Control List)
symfony/security-core              v6.1.7  v6.1.7  Symfony Security Component - Core Library
symfony/security-csrf              v6.1.0  v6.1.0  Symfony Security Component - CSRF Library
symfony/security-http              v6.1.7  v6.1.7  Symfony Security Component - HTTP Integration
symfony/service-contracts          v3.1.1  v3.1.1  Generic abstractions related to writing services
symfony/translation-contracts      v3.1.1  v3.1.1  Generic abstractions related to translation
symfony/twig-bridge                v6.1.7  v6.1.7  Provides integration for Twig with various Symfony components
symfony/var-dumper                 v6.1.6  v6.1.6  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v6.1.3  v6.1.3  Allows exporting any serializable PHP data structure to plain PHP code
```

</p>
</details>

#### PHP version

```
$ php -v
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2-1ubuntu2.6, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
```

## Subject

When the admin class configured in `services.yaml` does not exists (for example, miss typed), SonataAdmin display a miss-leading error message.

The issue is in `AdminSearchCompilerPass::validateAdminClass` method that is missing a check for class existence.

## Steps to reproduce

Create a bogous admin declaration in `services.yaml`, linked to an existing Document (or Entity ?):

```yaml
    admin.SomeAdmin:
        class: App\Admin\BogousAdmin
        tags:
            -
                name: sonata.admin
                model_class: App\Document\ExistingDocument
                manager_type: doctrine_mongodb
                label: 'Bogous admin'
```

## Expected results

```log
Service 'admin.SomeAdmin' class 'App\Admin\bogousAdmin' does not exists.
```

## Actual results

```log
Service 'admin.SomeAdmin' must implement `Sonata\AdminBundle\Admin\AdminInterface`.
```

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

Closes #7969.

## Changelog

```markdown
### Fixed
- Improve message when the admin class declared on the container does not exist.
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
I think this should improve error message @landure 

@VincentLanglet I think the whole checker for admin validation should be removed. On the actual search handler things are already typed as AdminInterface.

**Comment by VincentLanglet** [comment]
I dont know about the removal. I think the purpose of this checker was to avoid people adding the admin tag to something which is not an AdminInterface.

Maybe we should test this behavior

**Comment by phansys** [comment]
>I dont know about the removal. I think the purpose of this checker was to avoid people adding the admin tag to something which is not an AdminInterface.

Indeed, that was the intention in #6609.

>Maybe we should test this behavior

I agree.

**Comment by jordisala1991** [comment]
AdminSearchCompilerPass doesnt sound like a validator of what thing is getting the admin tag to me.

Maybe what is needed is another compiler pass to check that?

Edit: Also I dont even know that any symfony own tag like 'twig.extension' does a validation like that, do you have any example?

**Comment by jordisala1991** [comment]
Generated by gpt-4:

```php
// src/DependencyInjection/Compiler/CheckSonataAdminTaggedServicesPass.php

/*
 * This file is part of the Sonata Project package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sonata\AdminBundle\DependencyInjection\Compiler;

use Sonata\AdminBundle\Admin\AdminInterface;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Exception\InvalidArgumentException;

class CheckSonataAdminTaggedServicesPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container): void
    {
        foreach ($container->findTaggedServiceIds(AdminInterface::ADMIN_TAG) as $id => $tags) {
            $definition = $container->getDefinition($id);
            $class = match (true) {
                str_starts_with($definition->getClass(), '%') && str_ends_with($definition->getClass(), '%') => $container->getParameter(trim($definition->getClass(), '%')),
                default => $definition->getClass(),
            };

            if (!class_exists($class)) {
                throw new InvalidArgumentException(sprintf('Class "%s" for service "%s" does not exist.', $class, $id));
            }

            if (!is_subclass_of($class, AdminInterface::class)) {
                throw new InvalidArgumentException(sprintf('Service "%s" must implement the interface "%s" to use the "%s" tag.', $id, AdminInterface::class, AdminInterface::ADMIN_TAG));
            }
        }
    }
}
```

Wdyt about adding an extra compiler pass with tests specific to this behavior?

IMO it is not super needed, since symfony itself does not have a way to enforce this and does not do it for its own tags, but if we want to do it, I would definitely go with doing it in another class, since it is not related with global search in any way.

**Comment by VincentLanglet** [comment]
If symfony does not any validation in his code, im ok removing our

**Comment by jordisala1991** [comment]
Then, do you agree with this pr?

**Review by VincentLanglet — APPROVED** [review]

**Pull request merged**
