### PR TITLE
Replace extension logic with dispatcher

### LINKED ISSUE #5494: Use events instead of class methods
## Feature Request

Today we have many extensions points in our classes, e.g. `CRUDController::preEdit` or `AbstractAdmin::preValidate`. This is really bad. My idea is to replace all this classes with well defined events (e.g `Event\PreValidateObject` or `PreEditObject`), so it is easier to add custom code without using class inheritance to the max.

cc @sonata-project/contributors

### PR DESCRIPTION
**Pull request by core23**
I am targeting this branch, because this is BC

Closes #5494 

## Changelog

```markdown
### Added
- Admin specific `ExtensionEmitter` that will be used to dispatch extension events
- Admin specific `ExtensionNotifier` and `ExtensionProcessor` that will handle events
- Admin specific `ExtensionProvider` that will provide extensions
- Single-method Event Objects per Extension Interface

### Changed
- Separated `Sonata\AdminBundle\Admin\AdminExtensionInterface` into single-method
interfaces, they can be found under the `Sonata\AdminBundle\Admin\Extension` namespace

### Deprecated
- `Sonata\AdminBundle\Admin\AdminExtensionInterface`
- `Sonata\AdminBundle\Admin\AbstractAdminExtension`
- `Sonata\AdminBundle\Admin\AbstractAdmin::addExtension`
```

## To do
    
- [x] Update the tests
- [x] Update the changelog
- [x] Add an upgrade note
- [ ]  Test cherry picking #5199

## Subject

Built on top of #5164, this adds PSR14 compliant (hopefully it won't change much until it is approved) dispatcher for our extension instead of current logic, this will transform:

```php
    public function update($object)
    {
        $this->preUpdate($object);
        foreach ($this->extensions as $extension) {
            $extension->preUpdate($this, $object);
        }
        
        //...

        $this->postUpdate($object);
        foreach ($this->extensions as $extension) {
            $extension->postUpdate($this, $object);
        }
        return $object;
    }
```

into:

```php
public function update($object)
    {
        $this->preUpdate($object);
        $this->extensionEmitter->dispatch(new PreUpdateMessage($this, $object));

        //...

         $this->postUpdate($object);
         $this->extensionEmitter->dispatch(new PostUpdateMessage($this, $object));

         return $object;
    }
```

### CODE REVIEW

**Comment by kunicmarko20** [comment]
Since my PR that PSR changed (eg. Task and TaskInterface were dropped), and is still not finished, + a lot of people reported problems with PSR. The idea was nice but not sure we should conform to the PSR, especially since it is still unstable.

**Comment by core23** [comment]
> Since my PR that PSR changed (eg. Task and TaskInterface were dropped), and is still not finished, + a lot of people reported problems with PSR. The idea was nice but not sure we should conform to the PSR, especially since it is still unstable.

What do you mean with "PSR"?

From a code perspectiv, your code looks good and should work. I'll try to finish this next weekend.

**Comment by kunicmarko20** [comment]
@greg0ire and me were working on a dispatcher implementation based on psr14, but at that time it wasn't stable. If that isn't important anymore some stuff can be simplified here

**Comment by kunicmarko20** [comment]
https://github.com/sonata-project/SonataAdminBundle/commit/4d0dbdd030c401053ff8ef4364c1b5b0128ef44a this is a better revision if you ask me, I would rather have `__invoke` make users have a class per extension and drop the method map. wdyt?

WDYT about TaskInterface vs MessageInterface? eg task interface and processor means there will be a return, I see how it could be useful but I think maybe it is redundant to separate it and just always return the object, that way we could drop additional code.

Also, I can finalize this once we agree if you want.

cc @sonata-project/contributors

**Comment by core23** [comment]
Don't have the time to finish this. Maybe someone else will do

**Pull request closed without merging**
